<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Crosfhocail Ghaeilge - Irish Crossword : Irish crossword</title><link>http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx</link><description>Tags: Irish crossword</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Irish Crossword Puzzle 52 - Crosfhocal Ghaeilge 52</title><link>http://talkirish.com/blogs/crosswords/archive/2011/02/14/irish-crossword-puzzle-52-crosfhocal-ghaeilge-52.aspx</link><pubDate>Mon, 14 Feb 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4685</guid><dc:creator>michelle</dc:creator><slash:comments>1</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4685</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/02/14/irish-crossword-puzzle-52-crosfhocal-ghaeilge-52.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4685" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.85/crossword52.doc" length="108544" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 51 - Crosfhocal Ghaeilge 51</title><link>http://talkirish.com/blogs/crosswords/archive/2011/02/07/irish-crossword-puzzle-51-crosfhocal-ghaeilge-51.aspx</link><pubDate>Mon, 07 Feb 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4684</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4684</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/02/07/irish-crossword-puzzle-51-crosfhocal-ghaeilge-51.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4684" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.84/crossword51.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 50 - Crosfhocal Ghaeilge 50</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/31/irish-crossword-puzzle-50-crosfhocal-ghaeilge-50.aspx</link><pubDate>Mon, 31 Jan 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4683</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4683</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/01/31/irish-crossword-puzzle-50-crosfhocal-ghaeilge-50.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4683" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.83/crossword50.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 49 - Crosfhocal Ghaeilge 49</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/24/irish-crossword-puzzle-49-crosfhocal-ghaeilge-49.aspx</link><pubDate>Mon, 24 Jan 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4682</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4682</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/01/24/irish-crossword-puzzle-49-crosfhocal-ghaeilge-49.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4682" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.82/crossword49.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 48 - Crosfhocal Ghaeilge 48</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/17/irish-crossword-puzzle-48-crosfhocal-ghaeilge-48.aspx</link><pubDate>Mon, 17 Jan 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4681</guid><dc:creator>michelle</dc:creator><slash:comments>1</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4681</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/01/17/irish-crossword-puzzle-48-crosfhocal-ghaeilge-48.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4681" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.81/crossword48.doc" length="110592" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 47 - Crosfhocal Ghaeilge 47</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/10/irish-crossword-puzzle-47-crosfhocal-ghaeilge-47.aspx</link><pubDate>Mon, 10 Jan 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4680</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4680</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/01/10/irish-crossword-puzzle-47-crosfhocal-ghaeilge-47.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4680" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.80/crossword47.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 46 - Crosfhocal Ghaeilge 46</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/03/irish-crossword-puzzle-46-crosfhocal-ghaeilge-46.aspx</link><pubDate>Mon, 03 Jan 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4679</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4679</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2011/01/03/irish-crossword-puzzle-46-crosfhocal-ghaeilge-46.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4679" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.79/crossword46.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 45 - Crosfhocal Ghaeilge 45</title><link>http://talkirish.com/blogs/crosswords/archive/2010/12/27/irish-crossword-puzzle-45-crosfhocal-ghaeilge-45.aspx</link><pubDate>Mon, 27 Dec 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4678</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4678</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/12/27/irish-crossword-puzzle-45-crosfhocal-ghaeilge-45.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4678" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.78/crossword45.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 44 - Crosfhocal Ghaeilge 44</title><link>http://talkirish.com/blogs/crosswords/archive/2010/12/20/irish-crossword-puzzle-44-crosfhocal-ghaeilge-44.aspx</link><pubDate>Mon, 20 Dec 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4677</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4677</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/12/20/irish-crossword-puzzle-44-crosfhocal-ghaeilge-44.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4677" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.77/crossword44.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 43 - Crosfhocal Ghaeilge 43</title><link>http://talkirish.com/blogs/crosswords/archive/2010/12/13/irish-crossword-puzzle-43-crosfhocal-ghaeilge-43.aspx</link><pubDate>Mon, 13 Dec 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4676</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4676</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/12/13/irish-crossword-puzzle-43-crosfhocal-ghaeilge-43.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4676" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.76/crossword43.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 42 - Crosfhocal Ghaeilge 42</title><link>http://talkirish.com/blogs/crosswords/archive/2010/12/06/irish-crossword-puzzle-42-crosfhocal-ghaeilge-42.aspx</link><pubDate>Mon, 06 Dec 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4675</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4675</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/12/06/irish-crossword-puzzle-42-crosfhocal-ghaeilge-42.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4675" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.75/crossword42.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 41 - Crosfhocal Ghaeilge 41</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/29/irish-crossword-puzzle-41-crosfhocal-ghaeilge-41.aspx</link><pubDate>Mon, 29 Nov 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4674</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4674</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/11/29/irish-crossword-puzzle-41-crosfhocal-ghaeilge-41.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4674" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.74/crossword41.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 40 - Crosfhocal Ghaeilge 40</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/22/irish-crossword-puzzle-40-crosfhocal-ghaeilge-40.aspx</link><pubDate>Mon, 22 Nov 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4673</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4673</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/11/22/irish-crossword-puzzle-40-crosfhocal-ghaeilge-40.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4673" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.73/crossword40.doc" length="109056" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 39 - Crosfhocal Ghaeilge 39</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/15/irish-crossword-puzzle-39-crosfhocal-ghaeilge-39.aspx</link><pubDate>Mon, 15 Nov 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4672</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4672</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/11/15/irish-crossword-puzzle-39-crosfhocal-ghaeilge-39.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4672" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.72/crossword39.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item><item><title>Irish Crossword Puzzle 38 - Crosfhocal Ghaeilge 38</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/08/irish-crossword-puzzle-38-crosfhocal-ghaeilge-38.aspx</link><pubDate>Mon, 08 Nov 2010 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4671</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/crosswords/rsscomments.aspx?PostID=4671</wfw:commentRss><comments>http://talkirish.com/blogs/crosswords/archive/2010/11/08/irish-crossword-puzzle-38-crosfhocal-ghaeilge-38.aspx#comments</comments><description>&lt;div style="float:left;"&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/crosswords/crossword_5F00_blog.png" alt="" /&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Gach seachtain, post&amp;aacute;iltear Crosfhocal nua i nGaeilge anseo ar &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
Baintear &amp;uacute;s&amp;aacute;id as na focail &amp;oacute; Focal an Lae sna crosfhocail agus mar sin de, is f&amp;eacute;idir leat an m&amp;eacute;id a d&amp;rsquo;fhoghlaim t&amp;uacute; anseo a th&amp;aacute;st&amp;aacute;il.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;
&amp;Iacute;osl&amp;oacute;d&amp;aacute;il an .doc anseo. Agus c&amp;eacute; go bhfuil cead ag c&amp;aacute;ch na crosfhocail seo a phriont&amp;aacute;il, a ch&amp;oacute;ipe&amp;aacute;il agus a dh&amp;aacute;ileadh saor in aisce, n&amp;aacute; d&amp;eacute;an dearmad &amp;aacute;r l&amp;oacute;g&amp;oacute; agus &amp;aacute;r sonra&amp;iacute; a choinne&amp;aacute;il ar an doicim&amp;eacute;ad, le daoine eile a chur ar an eolas faoi www.talkirish.com.
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Every week we post a new Irish Crossword Puzzle here on &lt;a href="http://talkirish.com/controlpanel/blogs/posteditor.aspx/www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt;.
The puzzles uses the vocabulary from our Focal an Lae, so you can test what you&amp;#39;ve learned here.
&lt;/p&gt;
&lt;p&gt;Download the .doc below. Remember, our crosswords are free to print, copy and redistribute - but please keep our logo and details on the document to help us spread the word about www.talkirish.com.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4671" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.46.71/crossword38.doc" length="109568" type="application/msword" /><category domain="http://talkirish.com/blogs/crosswords/archive/tags/Irish+crossword/default.aspx">Irish crossword</category></item></channel></rss>