<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Crosfhocail Ghaeilge - Irish Crossword - All Comments</title><link>http://talkirish.com/blogs/crosswords/default.aspx</link><description /><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Crossword Puzzle 48 - Crosfhocal Ghaeilge 48</title><link>http://talkirish.com/blogs/crosswords/archive/2011/01/17/irish-crossword-puzzle-48-crosfhocal-ghaeilge-48.aspx#16518</link><pubDate>Tue, 24 Oct 2017 06:01:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16518</guid><dc:creator>cuplafocal</dc:creator><description>&lt;p&gt;go hiontach. Buíochas&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16518" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 1 - Crosfhocal Ghaeilge 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/02/23/irish-crossword-puzzle-1-crosfhocal-ghaeilge-1.aspx#8143</link><pubDate>Wed, 13 Mar 2013 16:39:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8143</guid><dc:creator>CaoimhghinRobinson</dc:creator><description>&lt;p&gt;you gotta print them&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=8143" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 52 - Crosfhocal Ghaeilge 52</title><link>http://talkirish.com/blogs/crosswords/archive/2011/02/14/irish-crossword-puzzle-52-crosfhocal-ghaeilge-52.aspx#7556</link><pubDate>Mon, 02 Jul 2012 01:23:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7556</guid><dc:creator>darao</dc:creator><description>&lt;p&gt;go maith. &amp;nbsp; GRMA&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=7556" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 1 - Crosfhocal Ghaeilge 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/02/23/irish-crossword-puzzle-1-crosfhocal-ghaeilge-1.aspx#5941</link><pubDate>Thu, 22 Jul 2010 08:16:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5941</guid><dc:creator>Nessa Patricia</dc:creator><description>&lt;p&gt;Ní thigim.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5941" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 12 - Crosfhocal Ghaeilge 12</title><link>http://talkirish.com/blogs/crosswords/archive/2010/05/10/irish-crossword-puzzle-12-crosfhocal-ghaeilge-12.aspx#5826</link><pubDate>Sat, 05 Jun 2010 16:25:13 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5826</guid><dc:creator>maire nic an tsaoir</dc:creator><description>&lt;p&gt;Is iontach an ait e!!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5826" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 1 - Crosfhocal Ghaeilge 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/02/23/irish-crossword-puzzle-1-crosfhocal-ghaeilge-1.aspx#5421</link><pubDate>Fri, 14 May 2010 14:31:20 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5421</guid><dc:creator>drummuck</dc:creator><description>&lt;p&gt;grma&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5421" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 1 - Crosfhocal Ghaeilge 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/02/23/irish-crossword-puzzle-1-crosfhocal-ghaeilge-1.aspx#5404</link><pubDate>Sun, 09 May 2010 17:11:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5404</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Tá brón orm, Drummuck, it&amp;#39;s not very clear, but if you see the very last words in the blog post - attachment: crossword1.doc - you click the crossword1.doc link, and this should download the crossword to your desktop.&lt;/p&gt;
&lt;p&gt;Ádh mór ort,&lt;/p&gt;
&lt;p&gt;Michelle&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5404" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 1 - Crosfhocal Ghaeilge 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/02/23/irish-crossword-puzzle-1-crosfhocal-ghaeilge-1.aspx#5388</link><pubDate>Fri, 07 May 2010 13:57:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5388</guid><dc:creator>drummuck</dc:creator><description>&lt;p&gt;How can I acess the cross word puzzles/&lt;/p&gt;
&lt;p&gt;Nil a fhios agam ??????&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5388" width="1" height="1"&gt;</description></item><item><title>Twitter Trackbacks for                 Irish Crossword Puzzle 7 - Crosfhocal Ghaeilge 7 - Crosfhocail Ghaeilge - Irish Crossword - Talk Irish         [talkirish.com]        on Topsy.com</title><link>http://talkirish.com/blogs/crosswords/archive/2010/04/05/irish-crossword-puzzle-7-crosfhocal-ghaeilge-7.aspx#5056</link><pubDate>Fri, 09 Apr 2010 08:24:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5056</guid><dc:creator>Twitter Trackbacks for                 Irish Crossword Puzzle 7 - Crosfhocal Ghaeilge 7 - Crosfhocail Ghaeilge - Irish Crossword - Talk Irish         [talkirish.com]        on Topsy.com</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Twitter Trackbacks for &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Irish Crossword Puzzle 7 - Crosfhocal Ghaeilge 7 - Crosfhocail Ghaeilge - Irish Crossword - Talk Irish &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [talkirish.com] &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;on Topsy.com&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5056" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 7 - Crosfhocal Ghaeilge 7</title><link>http://talkirish.com/blogs/crosswords/archive/2010/04/05/irish-crossword-puzzle-7-crosfhocal-ghaeilge-7.aspx#5053</link><pubDate>Fri, 09 Apr 2010 07:22:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5053</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Ar fheabhas :)&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5053" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 7 - Crosfhocal Ghaeilge 7</title><link>http://talkirish.com/blogs/crosswords/archive/2010/04/05/irish-crossword-puzzle-7-crosfhocal-ghaeilge-7.aspx#5036</link><pubDate>Mon, 05 Apr 2010 14:50:06 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5036</guid><dc:creator>Maripat</dc:creator><description>&lt;p&gt;I love them! tthey help me spell better and remember&lt;/p&gt;
&lt;p&gt;GRMA&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5036" width="1" height="1"&gt;</description></item><item><title>re: Irish Crossword Puzzle 6 - Crosfhocal Ghaeilge 6</title><link>http://talkirish.com/blogs/crosswords/archive/2010/03/29/irish-crossword-puzzle-6-crosfhocal-ghaeilge-6.aspx#5029</link><pubDate>Thu, 01 Apr 2010 09:36:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5029</guid><dc:creator>Maripat</dc:creator><description>&lt;p&gt;Tá sé go maith! &amp;nbsp;Tá ptuigunn tú Ghaeilge, Is ag obair crosfhocal liom &amp;nbsp;ó mo co worker.&lt;/p&gt;
&lt;p&gt;It is very good! &amp;nbsp;&amp;quot;You understand Gaelic&amp;quot;, from my co worker with me working crossword puzzle.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5029" width="1" height="1"&gt;</description></item><item><title>re: Word Puzzles week 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/29/test-crossword.aspx#4311</link><pubDate>Tue, 08 Dec 2009 07:09:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4311</guid><dc:creator>creek</dc:creator><description>&lt;p&gt;HI Michelle&lt;/p&gt;
&lt;p&gt;I&amp;#39;m probably being a right eejit but I can&amp;#39;t find the clues for this crossword when I downloaded it. &lt;/p&gt;
&lt;p&gt;Cheers&lt;/p&gt;
&lt;p&gt;Creek&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4311" width="1" height="1"&gt;</description></item><item><title>re: Word Puzzles week 1</title><link>http://talkirish.com/blogs/crosswords/archive/2010/11/29/test-crossword.aspx#4288</link><pubDate>Tue, 01 Dec 2009 23:59:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4288</guid><dc:creator>Cianaigh</dc:creator><description>&lt;p&gt;How about being able to do crosswords online?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4288" width="1" height="1"&gt;</description></item></channel></rss>