<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Seanfhocal an lae - Irish Proverb A Day : seanfhocal, wisdom</title><link>http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/wisdom/default.aspx</link><description>Tags: seanfhocal, wisdom</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Irish Proverb 365 - Seanfhocail Ghaeilge 365</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-365-seanfhocail-ghaeilge-365.aspx</link><pubDate>Sun, 27 Feb 2011 17:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5798</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=5798</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-365-seanfhocail-ghaeilge-365.aspx#comments</comments><description>&lt;p&gt;&lt;strong&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;strong&gt;N&amp;iacute;l saoi gan locht n&amp;aacute; daoi gan tr&amp;eacute;ith. &lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Seo ciall an tseanfhocail:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;There is no wise man without a fault nor any fool without a good feature.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5798" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.57.98/Irish-Proverb-365.mp3" length="29045" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/default.aspx">seanfhocal</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+sayings/default.aspx">irish sayings</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverb/default.aspx">irish proverb</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/caution/default.aspx">caution</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/advice/default.aspx">advice</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/wisdom/default.aspx">wisdom</category></item><item><title>Irish Proverb 364 - Seanfhocail Ghaeilge 364</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-364-seanfhocail-ghaeilge-364.aspx</link><pubDate>Sun, 27 Feb 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5797</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=5797</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-364-seanfhocail-ghaeilge-364.aspx#comments</comments><description>&lt;p&gt;&lt;b&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;b&gt;N&amp;iacute;or chaill fear an mhisnigh riamh &amp;eacute;. &lt;br /&gt;&lt;/b&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Seo ciall an tseanfhocail:&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;The man of courage never lost it.&lt;/p&gt;
&lt;p&gt;&lt;b&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5797" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.57.97/Irish-Proverb-364.mp3" length="726519" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/default.aspx">seanfhocal</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+sayings/default.aspx">irish sayings</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverb/default.aspx">irish proverb</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/advice/default.aspx">advice</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/comfort/default.aspx">comfort</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/wisdom/default.aspx">wisdom</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/strength/default.aspx">strength</category></item></channel></rss>