<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Seanfhocal an lae - Irish Proverb A Day : seanfhocail</title><link>http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx</link><description>Tags: seanfhocail</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Irish Proverb 19 - Seanfhocail Ghaeilge 19</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/18/irish-proverb-19-seanfhocail-ghaeilge-19.aspx</link><pubDate>Fri, 18 Mar 2011 23:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4764</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=4764</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/18/irish-proverb-19-seanfhocail-ghaeilge-19.aspx#comments</comments><description>&lt;p&gt;&lt;strong&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;strong&gt;Ar mhaithe leis f&amp;eacute;in a bh&amp;iacute;onn an cat ag cr&amp;oacute;n&amp;aacute;n. &lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Seo ciall an tseanfhocail:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;The cat purrs to please itself.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4764" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.47.64/Irish-Proverb-019.mp3" length="47287" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category></item><item><title>Irish Proverb 18 - Seanfhocail Ghaeilge 18</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/18/irish-proverb-18-seanfhocail-ghaeilge-18.aspx</link><pubDate>Fri, 18 Mar 2011 22:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4763</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=4763</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/18/irish-proverb-18-seanfhocail-ghaeilge-18.aspx#comments</comments><description>&lt;p&gt;&lt;strong&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;strong&gt;An t-uan ag m&amp;uacute;ineadh m&amp;eacute;il&amp;iacute; d&amp;aacute; mh&amp;aacute;thair. &lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Seo ciall an tseanfhocail:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;The lamb teaching its mother how to bleat.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4763" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.47.63/Irish-Proverb-018.mp3" length="45412" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category></item><item><title>Irish Proverb 9 - Seanfhocail Ghaeilge 9</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/08/irish-proverb-9-seanfhocail-ghaeilge-9.aspx</link><pubDate>Tue, 08 Mar 2011 23:10:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4740</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=4740</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/03/08/irish-proverb-9-seanfhocail-ghaeilge-9.aspx#comments</comments><description>&lt;p&gt;&lt;strong&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;strong&gt;Aithn&amp;iacute;tear cara i gcruatan.&lt;/strong&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Seo ciall an tseanfhocail:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;It is in hardship that a friend is recognised.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4740" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.47.40/Irish-Proverb-009.mp3" length="737968" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category></item><item><title>Irish Proverb 365 - Seanfhocail Ghaeilge 365</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-365-seanfhocail-ghaeilge-365.aspx</link><pubDate>Sun, 27 Feb 2011 17:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5798</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=5798</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-365-seanfhocail-ghaeilge-365.aspx#comments</comments><description>&lt;p&gt;&lt;strong&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;strong&gt;N&amp;iacute;l saoi gan locht n&amp;aacute; daoi gan tr&amp;eacute;ith. &lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Seo ciall an tseanfhocail:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;There is no wise man without a fault nor any fool without a good feature.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5798" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.57.98/Irish-Proverb-365.mp3" length="29045" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/default.aspx">seanfhocal</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+sayings/default.aspx">irish sayings</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverb/default.aspx">irish proverb</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/caution/default.aspx">caution</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/advice/default.aspx">advice</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/wisdom/default.aspx">wisdom</category></item><item><title>Irish Proverb 364 - Seanfhocail Ghaeilge 364</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-364-seanfhocail-ghaeilge-364.aspx</link><pubDate>Sun, 27 Feb 2011 03:00:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5797</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=5797</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2011/02/27/irish-proverb-364-seanfhocail-ghaeilge-364.aspx#comments</comments><description>&lt;p&gt;&lt;b&gt;Is &amp;eacute; seo Seanfhocal an Lae:&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Today&amp;#39;s Proverb is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;&lt;b&gt;N&amp;iacute;or chaill fear an mhisnigh riamh &amp;eacute;. &lt;br /&gt;&lt;/b&gt;&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Seo ciall an tseanfhocail:&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;The translation or meaning is:&lt;/p&gt;
&lt;p style="padding-left:30px;"&gt;The man of courage never lost it.&lt;/p&gt;
&lt;p&gt;&lt;b&gt;An bhfuil a mhalairt de thuairim agat maidir le ciall an tseanfhocail seo, n&amp;oacute; ar mhaith leat an t-aistri&amp;uacute;ch&amp;aacute;n s&amp;rsquo;agatsa a roinnt linn? D&amp;eacute;an caint ar seo th&amp;iacute;os.&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Got a different idea on what this proverb means or want to share your own translation? Comment below.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5797" width="1" height="1"&gt;</description><enclosure url="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Components.PostAttachments/00.00.00.57.97/Irish-Proverb-364.mp3" length="726519" type="audio/mpg" /><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/default.aspx">seanfhocal</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+sayings/default.aspx">irish sayings</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverb/default.aspx">irish proverb</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/advice/default.aspx">advice</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/comfort/default.aspx">comfort</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/wisdom/default.aspx">wisdom</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/strength/default.aspx">strength</category></item><item><title>Irish Proverbs - Seanfhocail Ghaeilge</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2010/02/20/irish-proverbs-seanfhocail-ghaeilge.aspx</link><pubDate>Sat, 20 Feb 2010 09:41:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4590</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=4590</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2010/02/20/irish-proverbs-seanfhocail-ghaeilge.aspx#comments</comments><description>&lt;p&gt;Personally I love all aspects of folklore and tradition, and proverbs are no exception. They are both rooted in their own time and eternal, both parochial and international. Their specific form expresses the character of the peoples which produced them but their concerns are much the same in every country. They transmit the wisdom and humour of age and experience to the young. They are warnings, advice, jokes and observations. But they are also of great value to the learner of a language. 
&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;
Why are they so useful? Well, think of the words that are used in common proverbs. Because most proverbs are ways of expressing abstract concepts using concrete language, they very often make use of common and basic vocabulary &amp;ndash; animals, colours, food, geographical features. But they also contain a useful core of abstract vocabulary &amp;ndash; fear, hope, love, thrift, intelligence, speed, accuracy.
&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;
Think of the following proverb: T&amp;oacute;gfaidh dath dubh ach n&amp;iacute; th&amp;oacute;gfaidh dubh dath. It is an image derived from the world of dyeing. The learner will learn a lot from it: the Irish for take (t&amp;oacute;g), the future tense (t&amp;oacute;gfaidh), the negative of the future tense (n&amp;iacute; th&amp;oacute;gfaidh), the word for colour (dath) and the word for black (dubh). There is a music about this proverb, an elegance of expression. And there is also a warning and a wisdom about it. It is warning against jumping to conclusions about people or defaming them. A coloured cloth, it says, can be dyed black very easily, but a black cloth cannot be dyed any other colour. Once you have defamed someone, it is not so easy to restore their reputation. This is just one example of a great proverb, and there are hundreds to choose from in Irish! 
&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;
Now, some people might say that proverbs are clich&amp;eacute;s, and to a point this is true. But I would ask you to remember that a lot of humour depends on changing clich&amp;eacute;d forms of language to give them a new twist and this is an important way that languages have of revitalizing themselves. What about this one, which changes a few words: &amp;ndash; Is fearr cara sa Pharlaimint Eorpach n&amp;aacute; euro sa spar&amp;aacute;n (Better a friend in the European Parliament than a euro in the purse), which is based on Is fearr cara sa ch&amp;uacute;irt n&amp;aacute; punt sa spar&amp;aacute;n (better a friend in the court than a pound in the purse).  Or we can add a bit to an old proverb. For example, N&amp;iacute; dh&amp;eacute;anfadh an saol capall r&amp;aacute;sa d&amp;rsquo;asal (the whole world couldn&amp;rsquo;t make a race horse out of a donkey) is an old proverb, but you could add a second part &amp;ndash; ach is ioma&amp;iacute; capall r&amp;aacute;sa a ndearna an saol asal de! (But it&amp;rsquo;s many a racehorse the world made a donkey of!) I am sure you can think of better examples. Being creative is a vital part of language learning and no language should ever be treated as a museum exhibit.    
&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4590" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category></item><item><title>Coming Soon - New Irish Proverb a Day Service</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2010/02/10/coming-soon-new-irish-proverb-a-day-service.aspx</link><pubDate>Wed, 10 Feb 2010 02:30:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4207</guid><dc:creator>michelle</dc:creator><slash:comments>1</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/irishproverbaday/rsscomments.aspx?PostID=4207</wfw:commentRss><comments>http://talkirish.com/blogs/irishproverbaday/archive/2010/02/10/coming-soon-new-irish-proverb-a-day-service.aspx#comments</comments><description>&lt;p&gt;&lt;b&gt;We&amp;#39;re working hard to get our new SeanFhocal an Lae service ready for release. Soon you&amp;#39;ll be able to listen to and understand great sayings like:
&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;
B&amp;iacute;onn cluasa fada ar mhuca beaga.
&lt;/p&gt;
&lt;p&gt;Beatha teanga &amp;iacute; a labhairt. 
&lt;/p&gt;
&lt;p&gt;Is glas iad na cnoic i bhfad uainn.
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4207" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+proverbs/default.aspx">irish proverbs</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocal/default.aspx">seanfhocal</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/irish+sayings/default.aspx">irish sayings</category><category domain="http://talkirish.com/blogs/irishproverbaday/archive/tags/seanfhocail/default.aspx">seanfhocail</category></item></channel></rss>