<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Proverb 305 - Seanfhocail Ghaeilge 305</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2016/12/30/irish-proverb-305-seanfhocail-ghaeilge-305.aspx</link><description>Is &amp;eacute; seo Seanfhocal an Lae: Today&amp;#39;s Proverb is: Is on&amp;oacute;rai poll n&amp;aacute; paiste. (Please visit the site to view this media) Seo ciall an tseanfhocail: The translation or meaning is: A hole is more honourable than a patch. An bhfuil a</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Proverb 305 - Seanfhocail Ghaeilge 305</title><link>http://talkirish.com/blogs/irishproverbaday/archive/2016/12/30/irish-proverb-305-seanfhocail-ghaeilge-305.aspx#7998</link><pubDate>Tue, 15 Jan 2013 10:24:11 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7998</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;We had an email query regarding this proverb:&lt;/p&gt;
&lt;p&gt;&amp;quot;Shouldn&amp;#39;t the quotation be &amp;quot;Is onórai poll nois ná paiste&amp;quot;? &amp;nbsp;Or is &amp;quot;nois&amp;quot; understood from the context and the use of &amp;#39;ná&amp;#39;?&amp;quot;&lt;/p&gt;
&lt;p&gt;I think you are thinking of the word níos rather than nois. Níos is often used with comparative expressions, though not always. For example, you can say:&lt;/p&gt;
&lt;p&gt;Tá an leabhar seo níos fearr ná an leabhar sin. &lt;/p&gt;
&lt;p&gt;This book is better than that book.&lt;/p&gt;
&lt;p&gt;But you could also use &lt;/p&gt;
&lt;p&gt;Is fearr an leabhar seo ná an leabhar sin.&lt;/p&gt;
&lt;p&gt;The constructions with is are often used in proverbs - Is fearr glas ná amhras, for example. (Better a lock than doubt).&lt;/p&gt;
&lt;p&gt;So, in this particular case, you don&amp;#39;t need the níos. Hope this answers your question!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=7998" width="1" height="1"&gt;</description></item></channel></rss>