<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx</link><description>dearg red (Please visit the site to view this media) Example Sentence Cheannaigh s&amp;eacute; r&amp;oacute;sanna dearga di. He bought her red roses. (Please visit the site to view this media) Flashcards</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#5532</link><pubDate>Tue, 25 May 2010 16:35:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5532</guid><dc:creator>beanrua</dc:creator><description>&lt;p&gt;scríobh Michelle -Tá sé an baile beag &amp;nbsp; &amp;nbsp;It&amp;#39;s a small town &amp;nbsp;&lt;/p&gt;
&lt;p&gt;? It is the small town?&lt;/p&gt;
&lt;p&gt;Can you use - Is baile beag é&lt;/p&gt;
&lt;p&gt;Níl mé ach ag cleachtadh.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5532" width="1" height="1"&gt;</description></item><item><title>Twitter Trackbacks for                 Irish Word a Day - Dearg - Red - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#4559</link><pubDate>Sun, 07 Feb 2010 01:32:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4559</guid><dc:creator>Twitter Trackbacks for                 Irish Word a Day - Dearg - Red - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Twitter Trackbacks for &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Irish Word a Day - Dearg - Red - Focal an Lae - Irish Word a Day - Talk Irish &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [talkirish.com] &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;on Topsy.com&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4559" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#4535</link><pubDate>Wed, 03 Feb 2010 00:30:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4535</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Bhí car dearg ag mo bhean chéile, ach tá car bán aici anois.&lt;/p&gt;
&lt;p&gt;My wife had a red car, but now she has a white car.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4535" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1182</link><pubDate>Tue, 03 Feb 2009 12:34:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1182</guid><dc:creator>Frankie</dc:creator><description>&lt;p&gt;Awesome Gearóid, that seems pretty flash, I&amp;#39;d definitely like to use &amp;quot;úrnua&amp;quot;. Thanks. &lt;/p&gt;
&lt;p&gt;I&amp;#39;m feeling all proud of myself, starting to feel like I&amp;#39;m getting somewhere with my gaeilge.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1182" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1180</link><pubDate>Tue, 03 Feb 2009 06:49:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1180</guid><dc:creator>Gearoid</dc:creator><description>&lt;p&gt;Frankie&lt;/p&gt;
&lt;p&gt;&amp;#39;Tá rothar dearg nua agam&amp;#39; is correct&lt;/p&gt;
&lt;p&gt;You can also use &amp;#39;úr&amp;#39;&lt;/p&gt;
&lt;p&gt;&amp;#39;Tá rothar dearg úr agam.&amp;#39;&lt;/p&gt;
&lt;p&gt;úr means&amp;#39; fresh&amp;#39; or &amp;#39;new&amp;#39;&lt;/p&gt;
&lt;p&gt;You can put &amp;#39;úr&amp;#39; and &amp;#39;nua&amp;#39; together to make another word&lt;/p&gt;
&lt;p&gt;&amp;#39;úrnua&amp;#39; which means &amp;#39;brand-new&amp;#39;&lt;/p&gt;
&lt;p&gt;&amp;#39;Tá rothar dearg úrnua agam.&amp;#39; meaning &amp;#39;i have a brand-new red bike.&amp;#39; &amp;nbsp;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1180" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1177</link><pubDate>Mon, 02 Feb 2009 16:05:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1177</guid><dc:creator>Frankie</dc:creator><description>&lt;p&gt;Tá rothar dearg nua agam.&lt;/p&gt;
&lt;p&gt;An bhfuil sin ceart?&lt;/p&gt;
&lt;p&gt;I was wanting to say &amp;quot; I have a new red bike&amp;quot;.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1177" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1176</link><pubDate>Mon, 02 Feb 2009 14:35:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1176</guid><dc:creator>jaicmac</dc:creator><description>&lt;p&gt;Chaith sí gúna dearg ag a pósadh.&lt;/p&gt;
&lt;p&gt;(She wore a red dress at her wedding.)&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1176" width="1" height="1"&gt;</description></item><item><title>Irish Word a Day - Dearg - Red &amp;laquo; Join Martin</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1175</link><pubDate>Mon, 02 Feb 2009 07:58:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1175</guid><dc:creator>Irish Word a Day - Dearg - Red « Join Martin</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Irish Word a Day - Dearg - Red &amp;laquo; Join Martin&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1175" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Dearg - Red</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/02/irish-word-a-day-dearg-red.aspx#1174</link><pubDate>Mon, 02 Feb 2009 04:49:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1174</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Is as Caisleán na Deirge mé. Tá sé an baile beag.&lt;/p&gt;
&lt;p&gt;I&amp;#39;m from Castlederg. It&amp;#39;s a small town. &lt;/p&gt;
&lt;p&gt;Caisleán na Deirge = The Red Castle &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1174" width="1" height="1"&gt;</description></item></channel></rss>