<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Si&amp;#250;cra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx</link><description>si&amp;uacute;cra sugar (Please visit the site to view this media) With Article (Singular) an si&amp;uacute;cra the sugar (Please visit the site to view this media) Example Sentence An dt&amp;oacute;gfaidh t&amp;uacute; si&amp;uacute;cra sa tae? Will you take sugar in your</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#6439</link><pubDate>Mon, 24 Jan 2011 09:14:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6439</guid><dc:creator>seano</dc:creator><description>&lt;p&gt;Interesting question here. Dia&amp;#39;s Muire duit, a Mháire! It is true that you wouldn&amp;#39;t lenite s or t after sa but there is a special reason for this, the famous DeNTaLS rule. That is, where DNTLS come together in certain contexts, they don&amp;#39;t lenite. Hang on, I hear you say, there&amp;#39;s no n at the end of sa! True, but sa is short for insan, so it behaves as if there is an n there. So it&amp;#39;s don teangeolaí (for the linguist) or sa seomra, with no lenition. This rule also applies to comhfhocail, or combined words, like uimhirphláta (numberplate). When you have DNTLS coming together, as in bándearg, you don&amp;#39;t lenite. Some people believe that DNTLS applies to adjectives, and that you should say bean dubh instead of bean dhubh but the Standard says otherwise. As for ordinary lenition without the DNTLS, as in mo sheomra, a shiúcra, a theach, these are just lenited like any other word. Incidentally, I would tend to say &amp;quot;mo chuid tae&amp;quot; (my part of tea) or &amp;quot;mo chuid caife&amp;quot;. It just sounds better to me. Faberm, that&amp;#39;s not a bad attempt but personally I would say &amp;quot;Is fearr liom tae ná rud ar bith eile&amp;quot; or just &amp;quot;Is é an tae is fearr liom!&amp;quot; Slán go fóill!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6439" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#6437</link><pubDate>Fri, 21 Jan 2011 22:20:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6437</guid><dc:creator>mary Dugan</dc:creator><description>&lt;p&gt;My grammar book has &amp;quot;a seoladh ( her address) &amp;nbsp;and a sheoladh &amp;nbsp;(his address)&amp;quot;. &amp;nbsp; Is &amp;nbsp;the word &amp;quot; a &amp;quot;an exception to the rule of no lenition of s? &amp;nbsp;Also, Diia dhuit a Sheáin.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6437" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#5057</link><pubDate>Sat, 10 Apr 2010 06:48:56 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5057</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Is maith liom mo tae nios mo gach rud eile. (I like my tea more than anything else).&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5057" width="1" height="1"&gt;</description></item><item><title>Twitter Trackbacks for                 Irish Word a Day - Si??cra - Sugar - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#5017</link><pubDate>Tue, 30 Mar 2010 07:13:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5017</guid><dc:creator>Twitter Trackbacks for                 Irish Word a Day - Si??cra - Sugar - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Twitter Trackbacks for &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Irish Word a Day - Si??cra - Sugar - Focal an Lae - Irish Word a Day - Talk Irish &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [talkirish.com] &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;on Topsy.com&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5017" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#2244</link><pubDate>Sun, 19 Apr 2009 14:40:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2244</guid><dc:creator>Gearoid</dc:creator><description>&lt;p&gt;Hi There,&lt;/p&gt;
&lt;p&gt;Your friend is correct, &amp;#39;sa&amp;#39; does cause lenition to the noun that comes after it (where possible)&lt;/p&gt;
&lt;p&gt;&amp;#39;sa&amp;#39; wont cause any change to&lt;/p&gt;
&lt;p&gt;words beginning with&lt;/p&gt;
&lt;p&gt;d,t,s - &lt;/p&gt;
&lt;p&gt;others that can never be lenited are&lt;/p&gt;
&lt;p&gt;&amp;#39;sc,sm,sp,st&amp;#39;&lt;/p&gt;
&lt;p&gt;&amp;#39;h, l, n,,r&amp;#39;&lt;/p&gt;
&lt;p&gt;and&lt;/p&gt;
&lt;p&gt;vowels&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2244" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#2002</link><pubDate>Sun, 12 Apr 2009 20:21:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2002</guid><dc:creator>patpmcmahon@yahoo.com</dc:creator><description>&lt;p&gt;I have a grammar gook that says &amp;quot;sa&amp;quot; causes lenition. &amp;nbsp;So, the sentence should read&lt;/p&gt;
&lt;p&gt;An dtófaidh tú siúcra sa thae?&lt;/p&gt;
&lt;p&gt;And pronunciation should be adjusted accordingly.&lt;/p&gt;
&lt;p&gt;Yes? &amp;nbsp;No? Is the &amp;quot;t&amp;quot; &amp;quot;resisting&amp;quot; lenition???&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2002" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Siúcra - Sugar</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/30/irish-word-a-day-si-250-cra-sugar.aspx#1847</link><pubDate>Mon, 30 Mar 2009 19:38:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1847</guid><dc:creator>eman</dc:creator><description>&lt;p&gt;Ólaim tae agus caife gan siúcra&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1847" width="1" height="1"&gt;</description></item></channel></rss>