<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - L&amp;#225; an Altaithe - Thanksgiving Day</title><link>http://talkirish.com/blogs/wordaday/archive/2016/11/26/irish-word-a-day-l-225-an-altaithe-thanksgiving-day.aspx</link><description>L&amp;aacute; an Altaithe Thanksgiving Day (Please visit the site to view this media) Example Sentence Tar ar cuairt L&amp;aacute; an Altaithe, le do thoil. Please come visit on Thanksgiving day . (Please visit the site to view this media) Flashcards</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Lá an Altaithe - Thanksgiving Day</title><link>http://talkirish.com/blogs/wordaday/archive/2016/11/26/irish-word-a-day-l-225-an-altaithe-thanksgiving-day.aspx#4273</link><pubDate>Sat, 28 Nov 2009 08:44:35 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4273</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Thank you Michelle on this Thanksgiving day for being so faithful in helping those of us out here who wish to learn Irish. &amp;nbsp;Your site is so so very helpful to me. &amp;nbsp;I am starting back into my Irish studies next week with a fellow named Jim Brewer. &amp;nbsp;I will give him your site to subscribe.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4273" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Lá an Altaithe - Thanksgiving Day</title><link>http://talkirish.com/blogs/wordaday/archive/2016/11/26/irish-word-a-day-l-225-an-altaithe-thanksgiving-day.aspx#451</link><pubDate>Mon, 01 Dec 2008 14:09:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:451</guid><dc:creator>debra</dc:creator><description>&lt;p&gt;You&amp;#39;ve done it again!! &amp;nbsp;Go raibh míle maith agat!!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=451" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Lá an Altaithe - Thanksgiving Day</title><link>http://talkirish.com/blogs/wordaday/archive/2016/11/26/irish-word-a-day-l-225-an-altaithe-thanksgiving-day.aspx#408</link><pubDate>Thu, 27 Nov 2008 05:26:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:408</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;More useful vocabulary for Thanksgiving!&lt;/p&gt;
&lt;p&gt;thanksgiving - altú	- an t-altú&lt;/p&gt;
&lt;p&gt;pumpkin – puimcín - an puimcín &lt;/p&gt;
&lt;p&gt;turkey – Tuirc - an Tuirc&lt;/p&gt;
&lt;p&gt;harvest – buaint - an bhuaint&lt;/p&gt;
&lt;p&gt;party/Feast – coirm - an choirm&lt;/p&gt;
&lt;p&gt;vegetable – glasra - an glasra&lt;/p&gt;
&lt;p&gt;cranberry – mónóg - an mhónóg&lt;/p&gt;
&lt;p&gt;holiday - saoire - an tsaoire&lt;/p&gt;
&lt;p&gt;celebration – ceiliúradh - an ceiliúradh&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=408" width="1" height="1"&gt;</description></item></channel></rss>