<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - R&amp;#243;s - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx</link><description>r&amp;oacute;s rose (Please visit the site to view this media) With Article (Singular) an r&amp;oacute;s the rose (Please visit the site to view this media) Example Sentence N&amp;iacute;or ordaigh dia r&amp;oacute;s gan dealg. Every rose has thorns. (Please visit the</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4574</link><pubDate>Tue, 09 Feb 2010 08:13:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4574</guid><dc:creator>Doug</dc:creator><description>&lt;p&gt; &amp;nbsp;Tá brón orm ! &amp;nbsp;That will teach me to type and not proof read. &amp;nbsp;It should be:&lt;/p&gt;
&lt;p&gt;Go raibh maith agat&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4574" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4573</link><pubDate>Tue, 09 Feb 2010 08:09:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4573</guid><dc:creator>Doug</dc:creator><description>&lt;p&gt;Déanta go maith ! Perfect in your description. &amp;nbsp;I was thrown off a bit by the &amp;nbsp;&amp;quot;dia&amp;quot;. &amp;nbsp;I read it as being &amp;quot;God&amp;quot; but was unsure because it was all in lower case and thought that it was an alternate deffinition and was unsure as to it&amp;#39;s use and meaning in this sentence. Thank you for clearing it up. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go raiph maith agat.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4573" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4565</link><pubDate>Mon, 08 Feb 2010 11:57:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4565</guid><dc:creator>seano</dc:creator><description>&lt;p&gt;This construction is often found in proverbs, so people who are used to proverbs will find it easier to understand than people who are just used to the conversational language. It literally means &amp;quot;God didn&amp;#39;t order a rose without a thorn&amp;quot;. In other words, God didn&amp;#39;t sanction or create roses which don&amp;#39;t have thorns. So it does imply that all roses have thorns, and not that not all roses do have thorns. If you understand me. And if you don&amp;#39;t, don&amp;#39;t not worry about it ;)&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4565" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4549</link><pubDate>Thu, 04 Feb 2010 17:14:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4549</guid><dc:creator>Doug</dc:creator><description>&lt;p&gt;Let me throw a question out to everyone. I have studied off and on now for about a year and I can peck around a bit and get the general idea of what is being said, but in &amp;nbsp;Todays Word of the Day phrase: &amp;nbsp;&amp;quot;Níor ordaigh dia rós gan dealg&amp;quot;&lt;/p&gt;
&lt;p&gt;has been translated as meaning; &amp;quot;Every rose has thorns.&amp;quot; &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt; Wouldn&amp;#39;t that say something closer to &amp;quot;Not every rose is without thorns&amp;quot; &amp;nbsp;or as might be said here in the &amp;quot;States&amp;quot; as &amp;quot;Not every rose has thorns&amp;quot; ? &amp;nbsp;Just wondering as a new learner I am trying to get it right. &lt;/p&gt;
&lt;p&gt;Thank you for your help.&lt;/p&gt;
&lt;p&gt;Doug&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4549" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4543</link><pubDate>Thu, 04 Feb 2010 07:40:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4543</guid><dc:creator>Maripat</dc:creator><description>&lt;p&gt;Tá sé rós dearg go h-álainn sa mardin.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4543" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4541</link><pubDate>Thu, 04 Feb 2010 05:46:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4541</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Níor ordaigh dia rós gan dath. &amp;nbsp;Every rose has color.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4541" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Rós - Rose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#4539</link><pubDate>Wed, 03 Feb 2010 22:26:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4539</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Tá an rós breá é le gach mna.&lt;/p&gt;
&lt;p&gt;All woman love the rose.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4539" width="1" height="1"&gt;</description></item><item><title>Irish Word a Day - R??s - Rose &amp;laquo; Join Martin</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/03/irish-word-a-day-r-243-s-rose.aspx#1181</link><pubDate>Tue, 03 Feb 2009 07:35:11 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1181</guid><dc:creator>Irish Word a Day - R??s - Rose « Join Martin</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Irish Word a Day - R??s - Rose &amp;laquo; Join Martin&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1181" width="1" height="1"&gt;</description></item></channel></rss>