<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Gr&amp;#225;nna - Ugly</title><link>http://talkirish.com/blogs/wordaday/archive/2016/05/28/irish-word-a-day-gr-225-nna-ugly.aspx</link><description>gr&amp;aacute;nna ugly (Please visit the site to view this media) Exaple Sentence T&amp;aacute; madadh gr&amp;aacute;nna aici. She has an ugly dog. (Please visit the site to view this media) Flashcards</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Gránna - Ugly</title><link>http://talkirish.com/blogs/wordaday/archive/2016/05/28/irish-word-a-day-gr-225-nna-ugly.aspx#2800</link><pubDate>Mon, 01 Jun 2009 04:49:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2800</guid><dc:creator>Gearoid</dc:creator><description>&lt;p&gt;the preposition &amp;#39;ag&amp;#39; does mean &amp;#39;to have&amp;#39;&lt;/p&gt;
&lt;p&gt;agam&lt;/p&gt;
&lt;p&gt;agat&lt;/p&gt;
&lt;p&gt;aige&lt;/p&gt;
&lt;p&gt;aici &lt;/p&gt;
&lt;p&gt;againn&lt;/p&gt;
&lt;p&gt;agaibh&lt;/p&gt;
&lt;p&gt;acu&lt;/p&gt;
&lt;p&gt;Tá punt agam = I have a pound&lt;/p&gt;
&lt;p&gt;agam can also mean you have the ability to do something&lt;/p&gt;
&lt;p&gt;Tá Gaeilge aige = (he has Irish) he can speak irish&lt;/p&gt;
&lt;p&gt;Tá snámh agam = i can swim&lt;/p&gt;
&lt;p&gt;Tá tiomáint agam = i can drive&lt;/p&gt;
&lt;p&gt;Tá ceist agam ort= i have a question (on you) for you&lt;/p&gt;
&lt;p&gt;Tá carr dearg agat = you have a red car&lt;/p&gt;
&lt;p&gt;Gearóid&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2800" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gránna - Ugly</title><link>http://talkirish.com/blogs/wordaday/archive/2016/05/28/irish-word-a-day-gr-225-nna-ugly.aspx#2788</link><pubDate>Fri, 29 May 2009 09:41:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2788</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Rebecca, you are right. &amp;nbsp;There is no &amp;quot;to have&amp;quot; in Irish. &amp;nbsp;You have to say &lt;/p&gt;
&lt;p&gt;&amp;quot;stands ______________ &amp;nbsp;at me/at you/at him/at her/at we/at you pl/at they.&lt;/p&gt;
&lt;p&gt;agam &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;aginn&lt;/p&gt;
&lt;p&gt;agat &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;agibh&lt;/p&gt;
&lt;p&gt;aige/aici &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;acu&lt;/p&gt;
&lt;p&gt;I think,&lt;/p&gt;
&lt;p&gt;FaberM&lt;/p&gt;
&lt;p&gt;Tá madadh gránna agam. &amp;nbsp;( Stands (a) dog ugly at me.)&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2788" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gránna - Ugly</title><link>http://talkirish.com/blogs/wordaday/archive/2016/05/28/irish-word-a-day-gr-225-nna-ugly.aspx#2786</link><pubDate>Fri, 29 May 2009 07:50:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2786</guid><dc:creator>Rebecca</dc:creator><description>&lt;p&gt;Someone please correct me if I&amp;#39;m wrong, but I think:&lt;/p&gt;
&lt;p&gt;aici = at her (preposition &amp;quot;ag&amp;quot; (at) combined with personal pronoun)&lt;/p&gt;
&lt;p&gt;To say &amp;quot;have&amp;quot; in Irish, don&amp;#39;t you have to say that an object is &amp;quot;at&amp;quot; someone?&lt;/p&gt;
&lt;p&gt;(Literally translated, the sentence would read: &amp;quot;An ugly dog is at her.&amp;quot;)&lt;/p&gt;
&lt;p&gt;Is this correct?? &lt;/p&gt;
&lt;p&gt;Just busy trying to learn this rule at the mo!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2786" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gránna - Ugly</title><link>http://talkirish.com/blogs/wordaday/archive/2016/05/28/irish-word-a-day-gr-225-nna-ugly.aspx#2782</link><pubDate>Thu, 28 May 2009 11:43:37 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2782</guid><dc:creator>pjterrylaw</dc:creator><description>&lt;p&gt;aici - what does that mean?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2782" width="1" height="1"&gt;</description></item></channel></rss>