<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Focal an Lae - Irish Word a Day - All Comments</title><link>http://talkirish.com/blogs/wordaday/default.aspx</link><description /><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Milis - Sweet</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/13/irish-word-a-day-milis-sweet.aspx#17581</link><pubDate>Wed, 09 Jan 2019 20:40:04 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17581</guid><dc:creator>alanmstrong@hotmail.com</dc:creator><description>&lt;p&gt;I think it would be - Tá tú milis.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=17581" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Searbh - Bitter</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/14/irish-word-a-day-searbh-bitter.aspx#16899</link><pubDate>Sat, 17 Mar 2018 22:50:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16899</guid><dc:creator>lsm3456</dc:creator><description>&lt;p&gt;what is this anyway?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16899" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Searbh - Bitter</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/14/irish-word-a-day-searbh-bitter.aspx#16560</link><pubDate>Mon, 13 Nov 2017 18:34:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16560</guid><dc:creator>emerson</dc:creator><description>&lt;p&gt;Is maith liom liomoide search&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16560" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Madadh - Dog</title><link>http://talkirish.com/blogs/wordaday/archive/2017/04/22/irish-word-a-day-madra-dog.aspx#16513</link><pubDate>Thu, 12 Oct 2017 11:29:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16513</guid><dc:creator>Tommylamb</dc:creator><description>&lt;p&gt;Sorry....just saw the explanation above.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16513" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Madadh - Dog</title><link>http://talkirish.com/blogs/wordaday/archive/2017/04/22/irish-word-a-day-madra-dog.aspx#16512</link><pubDate>Thu, 12 Oct 2017 11:28:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16512</guid><dc:creator>Tommylamb</dc:creator><description>&lt;p&gt;Why do some use madadh and others madra. Is it a regional variation?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16512" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Madadh - Dog</title><link>http://talkirish.com/blogs/wordaday/archive/2017/04/22/irish-word-a-day-madra-dog.aspx#16511</link><pubDate>Thu, 12 Oct 2017 11:28:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16511</guid><dc:creator>Tommylamb</dc:creator><description>&lt;p&gt;Why do some use madadh and others madra. Is it a regional variation?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=16511" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Bríste Géine - Jeans</title><link>http://talkirish.com/blogs/wordaday/archive/2017/04/02/irish-word-a-day-br-237-ste-g-233-ine-jeans.aspx#15745</link><pubDate>Mon, 03 Apr 2017 00:05:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15745</guid><dc:creator>joe f</dc:creator><description>&lt;p&gt;ok&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=15745" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Aintín - Aunt</title><link>http://talkirish.com/blogs/wordaday/archive/2017/01/15/irish-word-a-day-aint-237-n-aunt.aspx#12199</link><pubDate>Fri, 15 Jan 2016 14:46:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12199</guid><dc:creator>elspeth</dc:creator><description>&lt;p&gt;Nach bhfuil m’aintín ag teacht go dtí an siopa?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=12199" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Iníon - Daughter</title><link>http://talkirish.com/blogs/wordaday/archive/2017/01/13/irish-word-a-day-in-237-on-daughter.aspx#12184</link><pubDate>Thu, 14 Jan 2016 14:02:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12184</guid><dc:creator>elspeth</dc:creator><description>&lt;p&gt;Tá do iníon ag an doras. &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=12184" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Mac - Son</title><link>http://talkirish.com/blogs/wordaday/archive/2017/01/14/irish-word-a-day-mac-son.aspx#12183</link><pubDate>Thu, 14 Jan 2016 13:56:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12183</guid><dc:creator>elspeth</dc:creator><description>&lt;p&gt;Nach raibh thusa agus a mac ag damhsa?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=12183" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Máthair - Mother</title><link>http://talkirish.com/blogs/wordaday/archive/2017/01/09/irish-word-a-day-m-225-thair-mother.aspx#12160</link><pubDate>Sat, 09 Jan 2016 13:21:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12160</guid><dc:creator>elspeth</dc:creator><description>&lt;p&gt;Chuir an máthair an gúna nua ar an leaba.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=12160" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Cócaireán - Cooker</title><link>http://talkirish.com/blogs/wordaday/archive/2015/11/06/irish-word-a-day-c-243-caire-225-n.aspx#11543</link><pubDate>Thu, 06 Nov 2014 21:17:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11543</guid><dc:creator>tranadams</dc:creator><description>&lt;p&gt;Thanks! I don&amp;#39;t think we use the word cooker here in Canada. Is that referring to the oven ...or the stove top? I thought I had seen a different word for oven ...&amp;quot;oigheann.&amp;quot; &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=11543" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Bus - Bus</title><link>http://talkirish.com/blogs/wordaday/archive/2017/04/14/irish-word-a-day-bus-bus.aspx#9971</link><pubDate>Mon, 14 Apr 2014 19:16:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9971</guid><dc:creator>seano</dc:creator><description>&lt;p&gt;We have had a query from a member who says that they were told at school that mall is slow, while déanach is late. Unfortunately, not everything you are taught in school is 100% accurate! If you look at Ó Dónaill&amp;#39;s dictionary, you will find that mall is somewhere between slow and late in meaning. Late potatoes are prátaí malla and a clock can be mall if it&amp;#39;s running late! &amp;nbsp;If you think about it, they are very closely related concepts. In the north, mall usually means late, while fadálach is more likely to mean slow. Déanach hardly exists at all in the north, apart from in phrases like an Ola Dhéanach (Extreme Unction). In other words, it&amp;#39;s partly a dialect thing, and partly that Irish doesn&amp;#39;t parcel up the meanings exactly the same (random) way that English does. It parcels them up in its own random and mysterious ways!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=9971" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Lámh - Hand</title><link>http://talkirish.com/blogs/wordaday/archive/2017/02/05/irish-word-a-day-l-225-mh-hand.aspx#9667</link><pubDate>Wed, 05 Feb 2014 17:41:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9667</guid><dc:creator>Caoladóir</dc:creator><description>&lt;p&gt;A bhecky3086,&lt;/p&gt;
&lt;p&gt;I might be able to help you, although, with that, the caveat that I am neither a language teacher nor fluent in Irish.&lt;/p&gt;
&lt;p&gt;The sound which you are finding difficult to reproduce is one which is familiar to native speakers of English as well as Irish from Ulster: the &amp;quot;ow&amp;quot; sound.&lt;/p&gt;
&lt;p&gt;While most of the English speakers of the world pronounce the &amp;quot;ow&amp;quot; in &amp;quot;how now brown cow?&amp;quot; as o followed (naturally, you might think) by a w; in Ulster it is o followed by a y. &lt;/p&gt;
&lt;p&gt;As a result when somebody from Ulster says &amp;quot;now&amp;quot; it sounds more like &amp;quot;nigh&amp;quot;, as in &amp;quot;the end is nigh&amp;quot;. &lt;/p&gt;
&lt;p&gt;If you take this and apply it to the rest of the words in the above phrase, you get &amp;quot;high nigh brine kigh&amp;quot;.&lt;/p&gt;
&lt;p&gt;Now try again but, in place of the vowel sound ih which comes after the initial consonant and before the final y, use uh, i.e. &amp;quot;h-uh-y&amp;quot; instead of &amp;quot;h-ih-y&amp;quot;&lt;/p&gt;
&lt;p&gt;And finally, make the same sound but preceded by an l.&lt;/p&gt;
&lt;p&gt;I hope that works for you.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=9667" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Láidir - Strong</title><link>http://talkirish.com/blogs/wordaday/archive/2017/01/24/irish-word-a-day-l-225-idir-strong.aspx#9656</link><pubDate>Sat, 25 Jan 2014 14:56:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9656</guid><dc:creator>fiach.dubh</dc:creator><description>&lt;p&gt;Tá mé láidir.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=9656" width="1" height="1"&gt;</description></item></channel></rss>