<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx</link><description>airgead silver (Please visit the site to view this media) With Article (Singular) an t-airgead the silver (Please visit the site to view this media) Example Sentence T&amp;aacute; an tr&amp;aacute;idire airgid sin deas. That&amp;#39;s a nice silver tray. (Please</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#6652</link><pubDate>Tue, 31 May 2011 06:06:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6652</guid><dc:creator>handmade jewelry</dc:creator><description>&lt;p&gt;I visited Dublin and I loved every minute of it...&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6652" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#6651</link><pubDate>Tue, 31 May 2011 06:03:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6651</guid><dc:creator>daisyjrt</dc:creator><description>&lt;p&gt;UNESCO should be protecting Irish language if it is not already. Just like any other language,&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6651" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#6165</link><pubDate>Tue, 05 Oct 2010 06:09:02 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6165</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Visit &lt;a rel="nofollow" target="_new" href="http://talkirish.com/blogs/wordaday/archive/2009/12/26/irish-word-a-day-211-r-gold.aspx"&gt;talkirish.com/.../irish-word-a-day-211-r-gold.aspx&lt;/a&gt;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6165" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#6160</link><pubDate>Mon, 04 Oct 2010 10:37:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6160</guid><dc:creator>sterling silver charms</dc:creator><description>&lt;p&gt;@michelle, thanks for the explanation. Now how do we say gold? &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6160" width="1" height="1"&gt;</description></item><item><title>Twitter Trackbacks for                 Irish Word a Day - Airgead - Silver - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#4354</link><pubDate>Sat, 26 Dec 2009 15:57:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4354</guid><dc:creator>Twitter Trackbacks for                 Irish Word a Day - Airgead - Silver - Focal an Lae - Irish Word a Day - Talk Irish         [talkirish.com]        on Topsy.com</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Twitter Trackbacks for &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Irish Word a Day - Airgead - Silver - Focal an Lae - Irish Word a Day - Talk Irish &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [talkirish.com] &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;on Topsy.com&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4354" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#778</link><pubDate>Sat, 27 Dec 2008 15:21:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:778</guid><dc:creator>Frankie</dc:creator><description>&lt;p&gt;Tá tuirse orm fosta.&lt;/p&gt;
&lt;p&gt;Your doing a great job Michelle, thank you very much for your explanation. Very rich in history is the Irish language, and that is one of the things that I like about it.&lt;/p&gt;
&lt;p&gt;All the work and partying with the festive season leaves us a little worn out, but bring on the new year!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=778" width="1" height="1"&gt;</description></item><item><title>Irish Word a Day - Airgead - Silver &amp;laquo; Join Martin</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#777</link><pubDate>Sat, 27 Dec 2008 08:10:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:777</guid><dc:creator>Irish Word a Day - Airgead - Silver « Join Martin</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Irish Word a Day - Airgead - Silver &amp;laquo; Join Martin&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=777" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#776</link><pubDate>Sat, 27 Dec 2008 04:46:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:776</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Tuigim! Tá mé iontach tuirseach inniu, so I will explain what I know as bearla...&lt;/p&gt;
&lt;p&gt;Airgead means both Silver and Money in Irish, just as Argent means both Silver and Money in French. Both come from the Latin word for silver, which is &amp;#39;argentum&amp;#39;.&lt;/p&gt;
&lt;p&gt;Argentum is where the chemical symbol Ag derives. Argentum comes from the Indo-European root *arg- &amp;#39;To shine; white; the shining or white metal, silver&amp;#39;.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=776" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Airgead - Silver</title><link>http://talkirish.com/blogs/wordaday/archive/2016/12/26/irish-word-a-day-airgead-silver.aspx#775</link><pubDate>Fri, 26 Dec 2008 18:54:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:775</guid><dc:creator>Frankie</dc:creator><description>&lt;p&gt;Cén Gaelige atá air &amp;quot;Money&amp;quot;?&lt;/p&gt;
&lt;p&gt;Tá sé airgead fosta?&lt;/p&gt;
&lt;p&gt;An bhfuil sin ceart?&lt;/p&gt;
&lt;p&gt;Ta bron orm, mo Gaeilge bhriste.&lt;/p&gt;
&lt;p&gt;Thought I&amp;#39;d try to ask my question in Irish, I just kind of made it up from what I know, so I hope it makes sense.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=775" width="1" height="1"&gt;</description></item></channel></rss>