<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Or&amp;#225;iste - Orange (colour)</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx</link><description>or&amp;aacute;iste orange (Please visit the site to view this media) Example Sentence T&amp;aacute; mo charr or&amp;aacute;iste. My car is orange. (Please visit the site to view this media) Flashcards</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Oráiste - Orange (colour)</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#8245</link><pubDate>Tue, 07 May 2013 22:14:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8245</guid><dc:creator>Fraukje</dc:creator><description>&lt;p&gt;Níl mo bhaile oráiste ach buí&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=8245" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Oráiste - Orange (colour)</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#5406</link><pubDate>Sun, 09 May 2010 17:57:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5406</guid><dc:creator>BridMhor</dc:creator><description>&lt;p&gt;Tá geansaí oráiste agam.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5406" width="1" height="1"&gt;</description></item><item><title>Irish Word a Day - Or??iste - Orange (colour) - Focal an Lae &amp;#8230; Staff</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#5396</link><pubDate>Sat, 08 May 2010 10:06:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5396</guid><dc:creator>Irish Word a Day - Or??iste - Orange (colour) - Focal an Lae … Staff</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Irish Word a Day - Or??iste - Orange (colour) - Focal an Lae &amp;#8230; Staff&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5396" width="1" height="1"&gt;</description></item><item><title>Twitter Trackbacks for                 Irish Word a Day - Or??iste - Orange - T?? mo charr or??iste - get the free audio and flashcards  #gaeilge #gael         [talkirish.com]        on Topsy.com</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#5381</link><pubDate>Fri, 07 May 2010 08:16:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5381</guid><dc:creator>Twitter Trackbacks for                 Irish Word a Day - Or??iste - Orange - T?? mo charr or??iste - get the free audio and flashcards  #gaeilge #gael         [talkirish.com]        on Topsy.com</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Twitter Trackbacks for &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Irish Word a Day - Or??iste - Orange - T?? mo charr or??iste - get the free audio and flashcards &amp;nbsp;#gaeilge #gael &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; [talkirish.com] &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;on Topsy.com&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5381" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Oráiste - Orange (colour)</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#5380</link><pubDate>Fri, 07 May 2010 07:49:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5380</guid><dc:creator>faberm</dc:creator><description>&lt;p&gt;Is é ár gcarr oráiste fosta. &amp;nbsp;(Our car is orange as well.)&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5380" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Oráiste - Orange (colour)</title><link>http://talkirish.com/blogs/wordaday/archive/2017/05/07/irish-word-a-day-or-225-iste-orange-colour.aspx#3326</link><pubDate>Thu, 18 Jun 2009 11:02:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3326</guid><dc:creator>Gearoid</dc:creator><description>&lt;p&gt;In English the word orange refers to the fruit and to the colour. In Irish however, there is a difference, strictly speaking,&lt;/p&gt;
&lt;p&gt;Flannbhuí - refers to the colour.&lt;/p&gt;
&lt;p&gt;Oráiste -refers to the fruit.&lt;/p&gt;
&lt;p&gt;Having said this, &amp;#39;Oráiste&amp;#39; is often used to refer to both fruit and colour by many people.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=3326" width="1" height="1"&gt;</description></item></channel></rss>