<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish Word a Day - Gaos&amp;#225;n - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx</link><description>gaos&amp;aacute;n nose (Please visit the site to view this media) With Article (Singular) an gaos&amp;aacute;n the nose (Please visit the site to view this media) Example Sentence Bhuail s&amp;eacute; ar an ghaos&amp;aacute;n &amp;eacute;. He punched him on the nose. (Please</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#6621</link><pubDate>Wed, 27 Apr 2011 21:21:10 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6621</guid><dc:creator>seano</dc:creator><description>&lt;p&gt;Hi, As Chelle says, there are two commonly used words in Irish for nose. One of them is srón, and the other is gaosán. Talkirish doesn&amp;#39;t have anything against the other dialects (Buntús Cainte is not in Ulster dialect). And most of the words given here are the same or nearly the same in all dialects. School is still scoil, word is still focal, good is still maith in all the dialects. However, sometimes there are differences, like this one. We have gaosán here because this website and the people who put it together and work on it are Ulster speakers. We do not use the word srón in the north. I would understand it but I wouldn&amp;#39;t use it. Ever. And putting lots of alternative forms would end up very cumbersome. Let&amp;#39;s be honest about it. You don&amp;#39;t object to gaosán because it&amp;#39;s &amp;quot;harder&amp;quot;. Are you really saying that one syllable words are fine but two or more scare you? No! The real reason is that srón is the dialect you learned and you want that dialect. You regard it as &amp;quot;right&amp;quot;. I feel the same way about gaosán. &amp;nbsp;And if you are on line, you can access all kinds of learning resources. You aren&amp;#39;t dependent on talkirish to give you the whole truth about the language. It is just one of many resources but it is one with a fairly strong Ulster bias. I hope you will use it and enjoy it, just as we use resources that use bord instead of tábla or madra instead of madadh or féach instead of amharc. Variation is part of the language and needs to be embraced.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6621" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#6615</link><pubDate>Tue, 26 Apr 2011 13:08:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6615</guid><dc:creator>lindylu</dc:creator><description>&lt;p&gt;All my primary school education was in Scoil Lorcain in Dublin, where we learnt all subjects in Irish. The word used for nose is sron( there&amp;#39;s a fada over the &amp;quot;o&amp;quot;) To me it&amp;#39;s an easier word than gaosan( I have no ability to put fadas where they should go) Could I suggest that whoever gives the definition of the words, select more than one dialect in their translation to avoid confusion. Good thing I brought my Irish/English dictionary with me to Cyprus where I now live.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6615" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#4703</link><pubDate>Tue, 02 Mar 2010 07:33:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4703</guid><dc:creator>eman</dc:creator><description>&lt;p&gt;An gasón a bhaint &amp;nbsp;de dhuine, to bite s.o.&amp;#39;s nose off.&lt;/p&gt;
&lt;p&gt;D&amp;#39;ainneoin chnámh a gaosáin, in sheer despite of her.&lt;/p&gt;
&lt;p&gt;D&amp;#39;ainneoin chnámh a ghaosáin, in sheer despite of him.&lt;/p&gt;
&lt;p&gt;&amp;quot;Leathanach: 611. Foclóir Gaeilge-Béarla, Niall Ó Dónaill&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4703" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#1543</link><pubDate>Wed, 11 Mar 2009 11:32:35 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1543</guid><dc:creator>Gearoid</dc:creator><description>&lt;p&gt;&amp;#39;Srón&amp;#39; is fine for &amp;#39;a nose&amp;#39;&lt;/p&gt;
&lt;p&gt;Gaosán is a variant form used in Ulster Irish and would be heard more in Donegal&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1543" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#1519</link><pubDate>Sun, 08 Mar 2009 18:06:33 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1519</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;There are several words for nose in Irish - gaosán is more commonly used in Ulster. Srón is used more often in Connacht and Munster. &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1519" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#1518</link><pubDate>Sun, 08 Mar 2009 17:40:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1518</guid><dc:creator>C Ní Chionnaith</dc:creator><description>&lt;p&gt;When did nose stop being a srón?????&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1518" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#1494</link><pubDate>Sun, 01 Mar 2009 14:15:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1494</guid><dc:creator>Frankie</dc:creator><description>&lt;p&gt;Tá sé cam ghaosán.&lt;/p&gt;
&lt;p&gt;His nose is crooked.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1494" width="1" height="1"&gt;</description></item><item><title>re: Irish Word a Day - Gaosán - Nose</title><link>http://talkirish.com/blogs/wordaday/archive/2017/03/01/irish-word-a-day-gaos-225-n-nose.aspx#1492</link><pubDate>Sun, 01 Mar 2009 05:50:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1492</guid><dc:creator>hallion</dc:creator><description>&lt;p&gt;Bhí fearg uirthi. Bhuail sí ar an ghaosán mé! Anois, tá tinneas ghaosán orm.&lt;/p&gt;
&lt;p&gt;She was angry. She hit me on the nose! Now, I have a aching nose.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1492" width="1" height="1"&gt;</description></item></channel></rss>