<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Talk Irish News : celtic media festival</title><link>http://talkirish.com/blogs/sitenews/archive/tags/celtic+media+festival/default.aspx</link><description>Tags: celtic media festival</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>www.talkirish.com wins award!</title><link>http://talkirish.com/blogs/sitenews/archive/2010/05/05/www-talkirish-com-wins-award.aspx</link><pubDate>Wed, 05 May 2010 07:33:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5367</guid><dc:creator>michelle</dc:creator><slash:comments>1</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=5367</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=5367</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2010/05/05/www-talkirish-com-wins-award.aspx#comments</comments><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:Calibri;"&gt;&lt;span style="font-size:small;"&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/sitenews/celticmediafestival1.gif" alt="" /&gt;Bhain &lt;a href="http://www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt; Duais Chiar&amp;aacute;in U&amp;iacute; Eigeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht ag &lt;a href="http://www.celticmediafestival.co.uk/11,32/the_festival/award_winners/"&gt;F&amp;eacute;ile na Me&amp;aacute;n Ceilteac&lt;/a&gt;h. Tugann an duais seo aitheantas don nu&amp;aacute;la&amp;iacute;ocht, don idirghn&amp;iacute;omha&amp;iacute;ocht agus don chruthaitheacht i su&amp;iacute;omhanna gr&amp;eacute;as&amp;aacute;in agus in inneachar ar l&amp;iacute;ne. Chuaigh s&amp;eacute; i bhfeidhm orm go m&amp;oacute;r go raibh www.talkirish.com ar an ghearrliosta le c&amp;uacute;ig shu&amp;iacute;omh gr&amp;eacute;as&amp;aacute;in de chuid an BBC &amp;ndash; agus d&amp;rsquo;fh&amp;eacute;adfadh ceann ar bith acu sin an duais a bhaint. Caithfidh m&amp;eacute; a admh&amp;aacute;il gur le l&amp;aacute;mh a chroitheadh leis an bhuaiteoir a d&amp;rsquo;fhreastail m&amp;eacute; ar shearmanas na nduaiseanna. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Baineadh stangadh asam nuair a bhain www.talkirish.com agus ar nd&amp;oacute;igh, bh&amp;iacute; r&amp;iacute;m&amp;eacute;ad orm fosta! Luaigh na molt&amp;oacute;ir&amp;iacute; an pobal idirn&amp;aacute;isi&amp;uacute;nta agus dearadh glan an tsu&amp;iacute;mh at&amp;aacute; againn mar dh&amp;aacute; cheann de na c&amp;uacute;iseanna ar roghna&amp;iacute;odh talkirish. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mar sin de, bu&amp;iacute;ochas m&amp;oacute;r agus bu&amp;iacute;ochas &amp;oacute; chro&amp;iacute; le gach aon duine a bh&amp;iacute;onn ag obair go dian i nganfhios don saol le www.talkirish.com a choinne&amp;aacute;il ar obair, agus le gach duine sa phobal s&amp;rsquo;againne a chuidigh linn &amp;aacute;is arbh fhi&amp;uacute; an t-aitheantas seo a dh&amp;eacute;anamh den su&amp;iacute;omh. Coinnig&amp;iacute; oraibh leis an dea-obair!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;a href="http://www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt; won the the Kieran Hegarty Award for Interactivity at the&lt;a href="http://www.celticmediafestival.co.uk/11,32/the_festival/award_winners/"&gt; Celtic Media Festival&lt;/a&gt;. This award recognises innovation, interactivity and creativity in websites and online content. I was hugely impressed that www.talkirish.com was sharing a shortlist with 5 BBC websites - any one of which was a worthy winner. I must admit, I attended the awards ceremony to shake the hand of the winner.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I was shocked - and delighted - that www.talkirish.com was the winner. The judges singled out our international community and clean web design as two of the reasons why we were chosen.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;So a great big huge heartfelt thanks to everyone behind the scenes on www.talkirish.com and everyone in our community for helping to build this into something worthy of such recognition. Keep it going!&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5367" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/celtic+media+festival/default.aspx">celtic media festival</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category></item><item><title>Talk Irish nominated for Celtic Media Award</title><link>http://talkirish.com/blogs/sitenews/archive/2010/03/03/talk-irish-nominated-for-celtic-media-award.aspx</link><pubDate>Wed, 03 Mar 2010 03:38:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4710</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=4710</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=4710</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2010/03/03/talk-irish-nominated-for-celtic-media-award.aspx#comments</comments><description>&lt;p&gt;T&amp;aacute; www.talkirish.com curtha ar an ghearrliosta do Dhuais Chiar&amp;aacute;in U&amp;iacute; &amp;Eacute;igeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht ag F&amp;eacute;ile na Me&amp;aacute;n Ceilteach. Is &amp;eacute; is aidhm le F&amp;eacute;ile na Me&amp;aacute;n Ceilteach n&amp;aacute; teangacha agus cult&amp;uacute;ir na dt&amp;iacute;ortha Ceilteacha a choth&amp;uacute; ar an sc&amp;aacute;ile&amp;aacute;in agus sna me&amp;aacute;in chraolta.
&lt;/p&gt;
&lt;p&gt;Tugann Duais Chiar&amp;aacute;in U&amp;iacute; &amp;Eacute;igeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht aitheantas don nu&amp;aacute;la&amp;iacute;ocht, don idirghn&amp;iacute;omha&amp;iacute;ocht agus don chruthaitheacht i su&amp;iacute;omhanna gr&amp;eacute;as&amp;aacute;in agus in &amp;aacute;bhar ar l&amp;iacute;ne.
Is &amp;eacute; www.talkirish.com an t-aon l&amp;eacute;iri&amp;uacute;ch&amp;aacute;n ar an ghearrliosta nach mbaineann leis an BBC &amp;ndash; is f&amp;eacute;idir na hainmni&amp;uacute;ch&amp;aacute;in uilig a fheice&amp;aacute;il &lt;a href="http://www.celticmediafestival.co.uk/11,29/the_festival/shortlist/"&gt;anseo&lt;/a&gt;. &lt;/p&gt;
&lt;p&gt;T&amp;aacute;imid ag d&amp;uacute;il go m&amp;oacute;r le freastal ar an fh&amp;eacute;ile f&amp;eacute;in. Beidh s&amp;eacute; c&amp;oacute;ngarach go leor do Bheal Feirste in I&amp;uacute;r Cinn Tr&amp;aacute;, ar an 21-23 Aibre&amp;aacute;n. Go n-&amp;eacute;ir&amp;iacute; linn!&lt;/p&gt;
&lt;p&gt;****************&lt;/p&gt;
&lt;p&gt;www.talkirish.com has been shortlisted for the Kieran Hegarty Award for Interactivity at the Celtic Media Festival. The Celtic Media Festival aims to promote the languages and cultures of the Celtic countries on screen and in broadcasting.
&lt;/p&gt;
&lt;p&gt;The Kieran Hegarty Award for Interactivity recognises innovation, interactivity and creativity in websites and online content.
www.talkirish.com is the only non-BBC production on the shortlist - you can see all nominees &lt;a href="http://www.celticmediafestival.co.uk/11,29/the_festival/shortlist/"&gt;here&lt;/a&gt;. &lt;/p&gt;
&lt;p&gt;We&amp;#39;re really looking to attending the festival itself, which is up the road from us, in Newry, on 21-23 April. Wish us luck!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4710" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/celtic+media+festival/default.aspx">celtic media festival</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category></item></channel></rss>