<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Talk Irish News : tg4</title><link>http://talkirish.com/blogs/sitenews/archive/tags/tg4/default.aspx</link><description>Tags: tg4</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Meon na mBan – What Irish Women Want</title><link>http://talkirish.com/blogs/sitenews/archive/2009/04/20/meon-na-mban-what-irish-women-want.aspx</link><pubDate>Mon, 20 Apr 2009 11:20:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2264</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=2264</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=2264</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2009/04/20/meon-na-mban-what-irish-women-want.aspx#comments</comments><description>&lt;p&gt;&lt;b&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;font-weight:bold;"&gt;Meon na mBan &amp;ndash; TG4 &amp;ndash; Monday 20&lt;sup&gt;th&lt;/sup&gt; April
10pm&lt;br /&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/b&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;In this new six part series for TG4, Meon na mBan
takes a look at the subjects close to the heart of every woman and reveals what
women really think.&amp;nbsp; Sex, love, careers and relationships ar just a taste
of the hotbed of subjects laid bare in Meon na mBan. Meon na mBan reveals all....&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align:center;" align="center"&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;i&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;font-style:italic;"&gt;Produced by Waddell Media for TG4
with support from the Irish Language Broacdcast Fund, the first programme of the
series can be seen on 20th April.&amp;nbsp; Tune in to TG4 on Mondays at 10pm.&lt;/span&gt;&lt;/span&gt;&lt;/i&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;font-weight:bold;"&gt;Meon na mBan &amp;ndash; TG4 - D&amp;eacute; Luain 20 Aibre&amp;aacute;n ag 10in&lt;/span&gt;&lt;/span&gt;&lt;/b&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;&lt;br /&gt;&lt;br /&gt;Sa tsraith &amp;uacute;rnua 6 ph&amp;aacute;irt seo, breathna&amp;iacute;onn &lt;i&gt;&lt;span style="font-style:italic;"&gt;Meon na mBan&lt;/span&gt;&lt;/i&gt; &lt;/span&gt;&lt;/span&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;ar cad &amp;eacute;
at&amp;aacute; ag teast&amp;aacute;il &amp;oacute; mhn&amp;aacute; na h&amp;Eacute;ireann san 21&amp;uacute; c&amp;eacute;ad.&amp;nbsp; &lt;/span&gt;&lt;/span&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;"&gt;Nochtar
d&amp;uacute;inn cad at&amp;aacute; taobh thiar de smaointe achan bhean.&amp;nbsp; T&amp;eacute;ann t&amp;eacute;ama&amp;iacute; &amp;eacute;ags&amp;uacute;la
mar shampla an gn&amp;eacute;as, gr&amp;aacute;, airgead, p&amp;oacute;sadh, caidrimh, r&amp;oacute;m&amp;aacute;nsa&amp;iacute;ocht agus sl&amp;aacute;inte
faoin scian sa tsraith shiams&amp;uacute;il seo. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;span style="font-family:Arial;font-size:x-small;"&gt;&lt;span style="font-size:10pt;font-family:Arial;font-style:italic;"&gt;L&amp;eacute;irithe ag
Waddell Media do TG4 le taca&amp;iacute;ocht &amp;oacute;n Chiste Craolt&amp;oacute;ireachta Gaeilge, craolfar
an ch&amp;eacute;ad chl&amp;aacute;r den tsraith ar 20i&amp;uacute; Aibre&amp;aacute;n.&amp;nbsp;&amp;nbsp; Beidh Meon na mBan le
feice&amp;aacute;il ar TG4 ar an Luain ag 10in.&amp;nbsp;&amp;nbsp; &lt;br /&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/i&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=2264" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/tv+series/default.aspx">tv series</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/tg4/default.aspx">tg4</category></item></channel></rss>