<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Talk Irish News - All Comments</title><link>http://talkirish.com/blogs/sitenews/default.aspx</link><description /><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>re: www.talkirish.com wins award!</title><link>http://talkirish.com/blogs/sitenews/archive/2010/05/05/www-talkirish-com-wins-award.aspx#5831</link><pubDate>Sun, 06 Jun 2010 18:27:54 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5831</guid><dc:creator>seanduine</dc:creator><description>&lt;p&gt;Congratulations Michelle. Also saw article on your Gaelghradam Loch Lao Business Award in SAOL (Eanáir 2010).&lt;/p&gt;
&lt;p&gt;At Oideas Gael in early April for another go, then time in Antrim with grandson (and family). Down to Belfast to watch a drubbing of the Saffrons by An Dún in a hurling match.&lt;/p&gt;
&lt;p&gt;Wanted to get back for Belfast Taste and Music Fest, but airfares are about double what they were earlier.&lt;/p&gt;
&lt;p&gt;Keep up the good work. We appreciate it!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5831" width="1" height="1"&gt;</description></item><item><title>re: www.talkirish.com ar an Irish News </title><link>http://talkirish.com/blogs/sitenews/archive/2009/11/16/www-talkirish-com-ar-an-irish-news.aspx#4260</link><pubDate>Wed, 25 Nov 2009 12:13:20 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4260</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;Go raibh míle maith agat!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4260" width="1" height="1"&gt;</description></item><item><title>re: www.talkirish.com ar an Irish News </title><link>http://talkirish.com/blogs/sitenews/archive/2009/11/16/www-talkirish-com-ar-an-irish-news.aspx#4241</link><pubDate>Mon, 23 Nov 2009 15:14:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4241</guid><dc:creator>Damien Eoin</dc:creator><description>&lt;p&gt;Leigh me faoin suiomh san alt seo den chead uair. Comhghairdeas.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4241" width="1" height="1"&gt;</description></item><item><title>Barr 50 Gn?? Le Gaeilge &amp;#8211; Top 50 Business as Gaeilge | SEO Article Expert</title><link>http://talkirish.com/blogs/sitenews/archive/2009/07/09/barr-50-gn-243-le-gaeilge-top-50-business-as-gaeilge.aspx#3382</link><pubDate>Thu, 09 Jul 2009 08:19:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3382</guid><dc:creator>Barr 50 Gn?? Le Gaeilge – Top 50 Business as Gaeilge | SEO Article Expert</dc:creator><description>&lt;p&gt;Pingback from &amp;nbsp;Barr 50 Gn?? Le Gaeilge &amp;#8211; Top 50 Business as Gaeilge | SEO Article Expert&lt;/p&gt;
&lt;img src="http://talkirish.com/aggbug.aspx?PostID=3382" width="1" height="1"&gt;</description></item><item><title>re: Talk Irish Launch</title><link>http://talkirish.com/blogs/sitenews/archive/2009/03/17/talk-irish-launch.aspx#1788</link><pubDate>Tue, 24 Mar 2009 17:25:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1788</guid><dc:creator>Seaghán Ó Murchú</dc:creator><description>&lt;p&gt;Is maith liom &amp;quot;Labhairt Gaeilge&amp;quot;! Scríobh mé inniu faoi an suíomh seo! Chuir mé sé inne. &lt;/p&gt;
&lt;p&gt;Tá mé foghlaimeoir fásta i gCathair na hÁingeal i gCalifoirnea. Feicfidh tú naisc eile agamsa ar mo bhlog &amp;quot;Blogtrotter&amp;quot; go Amazon US: &amp;quot;Listmania: Learning Irish Gaelic.&amp;quot; An féidir leat ag feicéail eolas eile ansiud?&lt;/p&gt;
&lt;p&gt;Go raibh maith agaibh agus ádh mór ort-- a chairde i mBéal Feirste agus ar fud an domhan. &lt;/p&gt;
&lt;p&gt;&lt;a rel="nofollow" target="_new" href="http://fionnchu.blogspot.com/2009/03/talk-irish-labhair-gaeilge.html"&gt;fionnchu.blogspot.com/.../talk-irish-labhair-gaeilge.html&lt;/a&gt;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1788" width="1" height="1"&gt;</description></item><item><title>re: Talk Irish Launch</title><link>http://talkirish.com/blogs/sitenews/archive/2009/03/17/talk-irish-launch.aspx#1768</link><pubDate>Fri, 20 Mar 2009 18:20:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1768</guid><dc:creator>Rory Broughal1</dc:creator><description>&lt;p&gt;Hi Michelle. Can you make things a bit more advanced on the site like putting up simple texts to translate each day getting harder and harder. I&amp;#39;m Irish but I&amp;#39;m terrible at speaking. I can speak basic and the stuff on the site is good but I&amp;#39;d love to get the chance to rehearse a text of medium difficulty each day. Cheers &amp;nbsp;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1768" width="1" height="1"&gt;</description></item><item><title>re: Talk Irish Launch</title><link>http://talkirish.com/blogs/sitenews/archive/2009/03/17/talk-irish-launch.aspx#1740</link><pubDate>Thu, 19 Mar 2009 12:23:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1740</guid><dc:creator>Gearoid Ó Duinn</dc:creator><description>&lt;p&gt;Féach ar www.irishpost.co.uk. &lt;/p&gt;
&lt;p&gt;Léigh mé sa pháipéar é.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1740" width="1" height="1"&gt;</description></item><item><title>re: Talk Irish Launch</title><link>http://talkirish.com/blogs/sitenews/archive/2009/03/17/talk-irish-launch.aspx#1737</link><pubDate>Thu, 19 Mar 2009 09:04:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1737</guid><dc:creator>michelle</dc:creator><description>&lt;p&gt;N&amp;iacute; fhaca m&amp;eacute; &amp;eacute;. An bhfuil s&amp;eacute; ar l&amp;iacute;ne?&lt;/p&gt;
&lt;p&gt;I didn&amp;#39;t see it. Is it online?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1737" width="1" height="1"&gt;</description></item><item><title>re: Talk Irish Launch</title><link>http://talkirish.com/blogs/sitenews/archive/2009/03/17/talk-irish-launch.aspx#1736</link><pubDate>Thu, 19 Mar 2009 08:25:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:1736</guid><dc:creator>Gearoid Ó Duinn</dc:creator><description>&lt;p&gt;Bhí píosa san Irish Post inniu. Maith thú!&lt;/p&gt;
&lt;p&gt;G.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=1736" width="1" height="1"&gt;</description></item></channel></rss>