<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Talk Irish News : awards</title><link>http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx</link><description>Tags: awards</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Buaiteoirí! (Arís!)</title><link>http://talkirish.com/blogs/sitenews/archive/2011/01/19/buaiteoir-237-ar-237-s.aspx</link><pubDate>Wed, 19 Jan 2011 09:09:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6434</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=6434</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=6434</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2011/01/19/buaiteoir-237-ar-237-s.aspx#comments</comments><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/sitenews/LWF.jpg" alt="" /&gt;***English below ***&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;/strong&gt;Ainmn&amp;iacute;odh Michelle Gallen mar Laoch-Nu&amp;aacute;la&amp;iacute; ag duaiseanna Foghlaim gan Teorainneacha ar an 10 Ean&amp;aacute;ir 2010. A bhu&amp;iacute;ochas do gach ball de TalkIrish ar fud an domhain a chaith v&amp;oacute;ta&amp;iacute; SMS d&amp;uacute;inn, t&amp;aacute; talkirish.com i ndiaidh aitheantas a fh&amp;aacute;il i nduaiseanna idirn&amp;aacute;isi&amp;uacute;nta. Bronnadh tr&amp;oacute;fa&amp;iacute; gal&amp;aacute;nta r&amp;eacute;alt-chruthach gloine orainn fosta.&lt;/p&gt;
&lt;p&gt;Leis an duais agus an bhliain bhre&amp;aacute; &amp;uacute;r a cheili&amp;uacute;radh, t&amp;aacute;imid i ndiaidh na 365 focal a eisi&amp;uacute;int in&amp;aacute;r gcluiche Wordflash, saor in aisce! Is f&amp;eacute;idir leat do chuid eolais a th&amp;aacute;st&amp;aacute;il anois maidir le gach Focal an Lae at&amp;aacute; eisithe againn riamh.&lt;/p&gt;
&lt;p&gt;Agus n&amp;aacute; d&amp;eacute;an dearmad - is f&amp;eacute;idir leat an c&amp;uacute;rsa MP3 Bunt&amp;uacute;s Cainte a cheannach do do iPhone, iPod n&amp;oacute; i Pad ionas gur f&amp;eacute;idir leat an Ghaeilge a fhoghlaim agus t&amp;uacute; sa si&amp;uacute;l. N&amp;oacute; is f&amp;eacute;idir leat &amp;aacute;r n-albam &amp;uacute;r de sheanfhocail Ghaeilge a cheannach.&lt;/p&gt;
&lt;p&gt;Ba mhaith linn milli&amp;uacute;n bu&amp;iacute;ochas a ghabh&amp;aacute;il le gach duine a v&amp;oacute;t&amp;aacute;il ar son Talk Irish - agus ar son na taca&amp;iacute;ochta a fuair muid &amp;oacute; gach duine agus an su&amp;iacute;omh iontach seo &amp;aacute; th&amp;oacute;g&amp;aacute;il againn. Gu&amp;iacute;m Bliain &amp;Uacute;r faoi mhaise daoibh go l&amp;eacute;ir!&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Winners! (Again!)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Michelle Gallen was named Hero Innovator at the Learning without Frontiers awards in London on January 10 2010. Thanks to all the SMS votes made by Talk Irish members right across the world, talkirish.com has now been recognised in an international award. We&amp;#39;ve also been given a really pretty glass star trophy.&lt;/p&gt;
&lt;p&gt;To celebrate the award and a shiny new year we&amp;#39;ve released all our 365 words into our Wordflash game, for free! You can now test your knowledge of every Focal an Lae we&amp;#39;ve released.&lt;/p&gt;
&lt;p&gt;And don&amp;#39;t forget - you can purchase Bunt&amp;uacute;s Cainte MP3 course for your iPhone, iPod or iPad so you can learn Irish on the go. Or you can purchase our new Irish proverbs album.&lt;/p&gt;
&lt;p&gt;We want to say thanks a million to everyone who voted for Talk Irish - and for everyone&amp;#39;s support in building up such a great site. I wish you all a Happy New Year!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6434" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/learning+without+frontiers/default.aspx">learning without frontiers</category></item><item><title>Ainmnítear talkirish.com do dhuais eile - another award nomination!</title><link>http://talkirish.com/blogs/sitenews/archive/2010/12/22/ainmn-237-tear-talkirish-com-do-dhuais-eile-another-award-nomination.aspx</link><pubDate>Wed, 22 Dec 2010 04:08:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6380</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=6380</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=6380</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2010/12/22/ainmn-237-tear-talkirish-com-do-dhuais-eile-another-award-nomination.aspx#comments</comments><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/sitenews/LWF.jpg" alt="" /&gt;&lt;b&gt;***English below ***&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; Michelle Gallen, bunaitheoir &lt;a&gt;talkirish.com&lt;/a&gt; curtha ar an ghearrliosta mar Laoch-Nu&amp;aacute;la&amp;iacute; sna&lt;a href="http://www.learningwithoutfrontiers.com/lwf-awards-finalists-2011/#gallen"&gt; Duaiseanna Foghlaim Gan Teorainn&lt;/a&gt;. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Rinne beagnach 200 ainmni&amp;uacute; poibl&amp;iacute;, agus d&amp;#39;aontaigh foireann molt&amp;oacute;ir&amp;iacute; ar ghearrliosta de laoch-nu&amp;aacute;laithe agus de laoch-nu&amp;aacute;la&amp;iacute;ochta&amp;iacute;.&lt;/p&gt;
&lt;p&gt;Anois, n&amp;iacute; m&amp;oacute;r don phobal v&amp;oacute;t&amp;aacute;il ar son an Laoch-Nu&amp;aacute;la&amp;iacute; is rogha leo. Mar sin de, ag cuimhneamh ar an d&amp;oacute;igh iontach ar fhreagraigh sibh an ghairm i nDuaiseanna an Laoich Dhigitigh, a ghn&amp;oacute;thaigh &amp;pound;5,000 do &lt;a&gt;talkirish.com&lt;/a&gt;, t&amp;aacute;imid ag iarraidh oraibh cuidi&amp;uacute; linn ar&amp;iacute;s!&lt;/p&gt;
&lt;p&gt;Is f&amp;eacute;idir v&amp;oacute;t&amp;aacute;il ar son talkirish.com &amp;oacute; ghuth&amp;aacute;n p&amp;oacute;ca. N&amp;iacute; g&amp;aacute; duit ach &lt;strong&gt;GALLEN &lt;/strong&gt;a th&amp;eacute;acs&amp;aacute;il chuig &lt;strong&gt;+44 7950 080 667&lt;/strong&gt;.&lt;/p&gt;
&lt;p&gt;N&amp;iacute; f&amp;eacute;idir v&amp;oacute;t&amp;aacute;il d&amp;uacute;inn ach aon uair amh&amp;aacute;in, ach is fi&amp;uacute; dh&amp;aacute; v&amp;oacute;ta an t-aon v&amp;oacute;ta amh&amp;aacute;in m&amp;aacute; t&amp;aacute; s&amp;eacute; ag teacht &amp;oacute; dhuine taobh amuigh den R&amp;iacute;ocht Aontaithe - nach bre&amp;aacute; an rud &amp;eacute; sin!&amp;nbsp;&lt;/p&gt;
&lt;p&gt;M&amp;aacute;s amhlaidh go bhfuil sibh ag v&amp;oacute;t&amp;aacute;il &amp;oacute; &amp;aacute;it at&amp;aacute; taobh amuigh den R&amp;iacute;ocht Aontaithe, is f&amp;eacute;idir &amp;uacute;s&amp;aacute;id a bhaint as Skype le v&amp;oacute;t&amp;aacute;il - rud a choinneoidh an costas bre&amp;aacute; &amp;iacute;seal!&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Le bhur dtoil, a chairde, b&amp;iacute;g&amp;iacute; ag v&amp;oacute;t&amp;aacute;il d&amp;uacute;inn a luaithe agus is f&amp;eacute;idir, mar is ar an 4&amp;uacute; Ean&amp;aacute;ir a dhruideann an v&amp;oacute;t&amp;aacute;il. Agus coinnig&amp;iacute; bhur m&amp;eacute;ara crosta ar a ch&amp;eacute;ile!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;br /&gt;Another award nomination for talkirish.com&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Michelle Gallen, Founder of&lt;a&gt; talkirish.com&lt;/a&gt; has been shortlisted as a Hero Innovator in the &lt;a href="http://www.learningwithoutfrontiers.com/lwf-awards-finalists-2011/#gallen"&gt;Learning Without Frontiers Awards&lt;/a&gt;.&lt;/p&gt;
&lt;p&gt;Nearly 200 public nominations were made, and a team of judges agreed upon a short list of hero innovators and innovations.&lt;/p&gt;
&lt;p&gt;The public must now vote for their Hero innovator. So following your fantastic response for the Digital Hero Award, which raised &amp;pound;5,000 for talkirish.com, we&amp;#39;re once again we&amp;#39;re asking for your help!&lt;/p&gt;
&lt;p&gt;You can vote for talkirish.com from your mobile phone. Simply text &lt;strong&gt;GALLEN &lt;/strong&gt;to &lt;strong&gt;+44 7950 080 667&lt;/strong&gt;.&lt;/p&gt;
&lt;p&gt;You can only vote for us once, but it&amp;#39;s good to know that if you&amp;#39;re voting from outside the UK, your vote will count twice!&lt;/p&gt;
&lt;p&gt;If you&amp;#39;re voting from outside the UK, you can vote via Skype - this should keep the costs down!&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Please please vote for us as soon as you can as voting closes on January 4th. And keep your fingers crossed!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=6380" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/learning+without+frontiers/default.aspx">learning without frontiers</category></item><item><title>www.talkirish.com wins award!</title><link>http://talkirish.com/blogs/sitenews/archive/2010/05/05/www-talkirish-com-wins-award.aspx</link><pubDate>Wed, 05 May 2010 07:33:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5367</guid><dc:creator>michelle</dc:creator><slash:comments>1</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=5367</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=5367</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2010/05/05/www-talkirish-com-wins-award.aspx#comments</comments><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:Calibri;"&gt;&lt;span style="font-size:small;"&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/sitenews/celticmediafestival1.gif" alt="" /&gt;Bhain &lt;a href="http://www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt; Duais Chiar&amp;aacute;in U&amp;iacute; Eigeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht ag &lt;a href="http://www.celticmediafestival.co.uk/11,32/the_festival/award_winners/"&gt;F&amp;eacute;ile na Me&amp;aacute;n Ceilteac&lt;/a&gt;h. Tugann an duais seo aitheantas don nu&amp;aacute;la&amp;iacute;ocht, don idirghn&amp;iacute;omha&amp;iacute;ocht agus don chruthaitheacht i su&amp;iacute;omhanna gr&amp;eacute;as&amp;aacute;in agus in inneachar ar l&amp;iacute;ne. Chuaigh s&amp;eacute; i bhfeidhm orm go m&amp;oacute;r go raibh www.talkirish.com ar an ghearrliosta le c&amp;uacute;ig shu&amp;iacute;omh gr&amp;eacute;as&amp;aacute;in de chuid an BBC &amp;ndash; agus d&amp;rsquo;fh&amp;eacute;adfadh ceann ar bith acu sin an duais a bhaint. Caithfidh m&amp;eacute; a admh&amp;aacute;il gur le l&amp;aacute;mh a chroitheadh leis an bhuaiteoir a d&amp;rsquo;fhreastail m&amp;eacute; ar shearmanas na nduaiseanna. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Baineadh stangadh asam nuair a bhain www.talkirish.com agus ar nd&amp;oacute;igh, bh&amp;iacute; r&amp;iacute;m&amp;eacute;ad orm fosta! Luaigh na molt&amp;oacute;ir&amp;iacute; an pobal idirn&amp;aacute;isi&amp;uacute;nta agus dearadh glan an tsu&amp;iacute;mh at&amp;aacute; againn mar dh&amp;aacute; cheann de na c&amp;uacute;iseanna ar roghna&amp;iacute;odh talkirish. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mar sin de, bu&amp;iacute;ochas m&amp;oacute;r agus bu&amp;iacute;ochas &amp;oacute; chro&amp;iacute; le gach aon duine a bh&amp;iacute;onn ag obair go dian i nganfhios don saol le www.talkirish.com a choinne&amp;aacute;il ar obair, agus le gach duine sa phobal s&amp;rsquo;againne a chuidigh linn &amp;aacute;is arbh fhi&amp;uacute; an t-aitheantas seo a dh&amp;eacute;anamh den su&amp;iacute;omh. Coinnig&amp;iacute; oraibh leis an dea-obair!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;a href="http://www.talkirish.com"&gt;www.talkirish.com&lt;/a&gt; won the the Kieran Hegarty Award for Interactivity at the&lt;a href="http://www.celticmediafestival.co.uk/11,32/the_festival/award_winners/"&gt; Celtic Media Festival&lt;/a&gt;. This award recognises innovation, interactivity and creativity in websites and online content. I was hugely impressed that www.talkirish.com was sharing a shortlist with 5 BBC websites - any one of which was a worthy winner. I must admit, I attended the awards ceremony to shake the hand of the winner.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I was shocked - and delighted - that www.talkirish.com was the winner. The judges singled out our international community and clean web design as two of the reasons why we were chosen.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;So a great big huge heartfelt thanks to everyone behind the scenes on www.talkirish.com and everyone in our community for helping to build this into something worthy of such recognition. Keep it going!&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=5367" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/celtic+media+festival/default.aspx">celtic media festival</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category></item><item><title>Talk Irish nominated for Celtic Media Award</title><link>http://talkirish.com/blogs/sitenews/archive/2010/03/03/talk-irish-nominated-for-celtic-media-award.aspx</link><pubDate>Wed, 03 Mar 2010 03:38:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4710</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><wfw:commentRss xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/rsscomments.aspx?PostID=4710</wfw:commentRss><wfw:comment xmlns:wfw="http://wellformedweb.org/CommentAPI/">http://talkirish.com/blogs/sitenews/commentapi.aspx?PostID=4710</wfw:comment><comments>http://talkirish.com/blogs/sitenews/archive/2010/03/03/talk-irish-nominated-for-celtic-media-award.aspx#comments</comments><description>&lt;p&gt;T&amp;aacute; www.talkirish.com curtha ar an ghearrliosta do Dhuais Chiar&amp;aacute;in U&amp;iacute; &amp;Eacute;igeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht ag F&amp;eacute;ile na Me&amp;aacute;n Ceilteach. Is &amp;eacute; is aidhm le F&amp;eacute;ile na Me&amp;aacute;n Ceilteach n&amp;aacute; teangacha agus cult&amp;uacute;ir na dt&amp;iacute;ortha Ceilteacha a choth&amp;uacute; ar an sc&amp;aacute;ile&amp;aacute;in agus sna me&amp;aacute;in chraolta.
&lt;/p&gt;
&lt;p&gt;Tugann Duais Chiar&amp;aacute;in U&amp;iacute; &amp;Eacute;igeartaigh don Idirghn&amp;iacute;omha&amp;iacute;ocht aitheantas don nu&amp;aacute;la&amp;iacute;ocht, don idirghn&amp;iacute;omha&amp;iacute;ocht agus don chruthaitheacht i su&amp;iacute;omhanna gr&amp;eacute;as&amp;aacute;in agus in &amp;aacute;bhar ar l&amp;iacute;ne.
Is &amp;eacute; www.talkirish.com an t-aon l&amp;eacute;iri&amp;uacute;ch&amp;aacute;n ar an ghearrliosta nach mbaineann leis an BBC &amp;ndash; is f&amp;eacute;idir na hainmni&amp;uacute;ch&amp;aacute;in uilig a fheice&amp;aacute;il &lt;a href="http://www.celticmediafestival.co.uk/11,29/the_festival/shortlist/"&gt;anseo&lt;/a&gt;. &lt;/p&gt;
&lt;p&gt;T&amp;aacute;imid ag d&amp;uacute;il go m&amp;oacute;r le freastal ar an fh&amp;eacute;ile f&amp;eacute;in. Beidh s&amp;eacute; c&amp;oacute;ngarach go leor do Bheal Feirste in I&amp;uacute;r Cinn Tr&amp;aacute;, ar an 21-23 Aibre&amp;aacute;n. Go n-&amp;eacute;ir&amp;iacute; linn!&lt;/p&gt;
&lt;p&gt;****************&lt;/p&gt;
&lt;p&gt;www.talkirish.com has been shortlisted for the Kieran Hegarty Award for Interactivity at the Celtic Media Festival. The Celtic Media Festival aims to promote the languages and cultures of the Celtic countries on screen and in broadcasting.
&lt;/p&gt;
&lt;p&gt;The Kieran Hegarty Award for Interactivity recognises innovation, interactivity and creativity in websites and online content.
www.talkirish.com is the only non-BBC production on the shortlist - you can see all nominees &lt;a href="http://www.celticmediafestival.co.uk/11,29/the_festival/shortlist/"&gt;here&lt;/a&gt;. &lt;/p&gt;
&lt;p&gt;We&amp;#39;re really looking to attending the festival itself, which is up the road from us, in Newry, on 21-23 April. Wish us luck!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://talkirish.com/aggbug.aspx?PostID=4710" width="1" height="1"&gt;</description><category domain="http://talkirish.com/blogs/sitenews/archive/tags/celtic+media+festival/default.aspx">celtic media festival</category><category domain="http://talkirish.com/blogs/sitenews/archive/tags/awards/default.aspx">awards</category></item></channel></rss>