<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Talk Irish: Unanswered Threads</title><link>http://talkirish.com/forums/TopicsNotAnswered.aspx</link><description>Posts that are unanswered</description><dc:language>en-US</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Pledge of Allegiance</title><link>http://talkirish.com/forums/thread/17711.aspx</link><pubDate>Mon, 19 Aug 2019 16:59:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17711</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17711.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17711</wfw:commentRss><description>&lt;p&gt;I was at a meeting last night in which I was asked to lead the group in reciting the Pledge of Allegiance.&amp;nbsp; Afterwards, I was curious how the pledge would read in Irish.&amp;nbsp; I suspect it has probably been done before, but I thought I would take a crack at it, just for fun.&amp;nbsp; Here&amp;#39;s what I came up with (English version first):&lt;/p&gt;
&lt;p&gt;
I pledge allegiance to the flag of the United States of America, and
to the republic for which it stands, one nation, under God,
indivisible, with liberty and justice for all.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Tugaim gealtanas don
bhratach Na St&amp;aacute;t Aontaithe Mheirice&amp;aacute;, agus is comhartha ar an
Phoblacht, is aon naisi&amp;uacute;n amh&amp;aacute;in &amp;eacute;, faoi Dia, doroinnte, le saoirse
agus ceart ar dhuine ar bith &lt;/p&gt;
&lt;p&gt;Any comments, corrections, questions, discussion is welcome......&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;
&lt;p&gt;
&lt;b&gt;&lt;/b&gt;&lt;i&gt;&lt;/i&gt;&lt;span style="text-decoration:underline;"&gt;&lt;/span&gt;&lt;sub&gt;&lt;/sub&gt;&lt;sup&gt;&lt;/sup&gt;&lt;span style="text-decoration:line-through;"&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Motherfoclóir: Dispatches from a Not So Dead Language by Darach Ó Séaghdha</title><link>http://talkirish.com/forums/thread/17710.aspx</link><pubDate>Fri, 16 Aug 2019 02:07:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17710</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17710.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=17710</wfw:commentRss><description>&lt;p&gt;Anyone read this? I am reading it now.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Thainig mé...</title><link>http://talkirish.com/forums/thread/17047.aspx</link><pubDate>Fri, 29 Jun 2018 07:03:37 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17047</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17047.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17047</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&amp;quot;Thainig m&amp;eacute;, chonaic m&amp;eacute;, bhuair m&amp;eacute;.&amp;quot;&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;J. Caesar&lt;/p&gt;
&lt;p&gt;Nota, le do thoil: bh&amp;iacute; an pr&amp;iacute;omha as Laidin:&amp;nbsp; &amp;quot;Veni, Vidi, Vici.&amp;quot;&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>To Whom It May Concern-Deleted Account</title><link>http://talkirish.com/forums/thread/17046.aspx</link><pubDate>Sat, 23 Jun 2018 16:40:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17046</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17046.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17046</wfw:commentRss><description>&lt;p&gt;To the person/persons posting content on this site that &lt;i&gt;appears&lt;/i&gt;&amp;nbsp;to have a valid question but uses very poor grammar and embeds a completely off-topic link in their post:&lt;/p&gt;
&lt;p&gt;Your posts and/or attempted posts have been deleted.&amp;nbsp; They will continue to be deleted as soon as I see them.&amp;nbsp; Your account will also be deleted as a SPAM offender.&lt;/p&gt;
&lt;p&gt;The same applies to those persons posting items for business concerns in China, or who are advertising for the sale of fake documents, watches, clothing, anything else.&lt;/p&gt;
&lt;p&gt;Your account is deleted &lt;i&gt;immediately &lt;/i&gt;because you are attempting to SPAM our group.&amp;nbsp; Such is considered an ILLIGITIMATE USE OF THIS SITE!&lt;/p&gt;
&lt;p&gt;So just stop already.&amp;nbsp; &lt;/p&gt;
&lt;p&gt;I can delete them as fast as you post or attempt to post them.&amp;nbsp; When you create a new member account, your posts begin by going into the Moderated Posts file, where I see them before anyone else.&amp;nbsp; When that happens, they never see the light of day.&lt;/p&gt;
&lt;p&gt;Please leave us alone.&amp;nbsp; Your traffic is not wanted and will continue to be DELETED immediately, along with user accounts of offenders.&lt;/p&gt;
&lt;p&gt;Good-bye.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>hallo from Italy!!!</title><link>http://talkirish.com/forums/thread/16948.aspx</link><pubDate>Thu, 19 Apr 2018 15:21:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16948</guid><dc:creator>sbieca</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16948.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16948</wfw:commentRss><description>&lt;p&gt;Hallo everyone!&lt;/p&gt;
&lt;p&gt;I&amp;#39;m Simona, from Italy!&lt;/p&gt;
&lt;p&gt;I&amp;#39;m looking for translations for my tattoo projects!&lt;/p&gt;
&lt;p&gt;Thank you in advance for your patience!!!!&lt;/p&gt;
&lt;p&gt;Ciao!&lt;/p&gt;
&lt;p&gt;Simona&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>tattoo translations: 2 stand-by projects </title><link>http://talkirish.com/forums/thread/16947.aspx</link><pubDate>Thu, 19 Apr 2018 15:17:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16947</guid><dc:creator>sbieca</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16947.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16947</wfw:commentRss><description>&lt;p&gt;Hallo everyone!&lt;/p&gt;
&lt;p&gt;I&amp;#39;m looking around for translations for two phrases:&lt;/p&gt;
&lt;p&gt;1)&amp;nbsp; &amp;nbsp;&amp;quot;No judgement, no blame, no expectation&amp;quot;&lt;/p&gt;
&lt;p&gt;2)&amp;nbsp; &amp;nbsp; &amp;quot;How do you run from what&amp;#39;s inside your head???&amp;quot;&lt;/p&gt;
&lt;p&gt;The original projects are in English, but after my first celtic tattoo ( &amp;quot;T&amp;aacute; rogha agam&amp;quot;) my mind is always tuned on Gaelic.&lt;/p&gt;
&lt;p&gt;I collect translations from online resources, but I&amp;#39;m not so sure about them... Please could you help me???&lt;/p&gt;
&lt;p&gt;Do I have to write down them??? do I have to open a single post for each phrase??? I don&amp;#39;t want to make mistakes....&lt;/p&gt;
&lt;p&gt;Thank you so much !!!!&lt;/p&gt;
&lt;p&gt;Simona&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Ok I'm back</title><link>http://talkirish.com/forums/thread/16896.aspx</link><pubDate>Thu, 15 Mar 2018 00:12:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16896</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16896.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16896</wfw:commentRss><description>&lt;p&gt;Ok, Fearghal Mag Uiginn does the Giota Beag / Giota Beag Eile and&lt;/p&gt;
&lt;p&gt;the Giota N&amp;iacute;os M&amp;oacute; Ulster language learning series. Which is what I use. Along with this site and the Focl&amp;oacute;ir.ie ( New English to Irish dictionary). Which brings me to my point&lt;/p&gt;
&lt;p&gt;Mr. Mag Uiginn says : Ch&amp;iacute;fidh m&amp;eacute; th&amp;uacute; - I&amp;#39;ll see you.&lt;/p&gt;
&lt;p&gt;However, in the Focl&amp;oacute;ir.ie dictionary, it has..&lt;/p&gt;
&lt;p&gt;Feicfidh m&amp;eacute; th&amp;uacute;... for I&amp;#39;ll see you for the Ulster.&lt;/p&gt;
&lt;p&gt;Soooo, I&amp;#39;m thinking that even in an Irish community where Ulster is&lt;/p&gt;
&lt;p&gt;spoken, there&amp;#39;s more than one way to say the same thing. 😁&lt;/p&gt;
&lt;p&gt;At least I hope that&amp;#39;s right 😱😱😱😱&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Little survey </title><link>http://talkirish.com/forums/thread/16823.aspx</link><pubDate>Sun, 18 Feb 2018 16:35:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16823</guid><dc:creator>Fedepassw</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16823.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16823</wfw:commentRss><description>&lt;p&gt;Good afternoon to everybody! First of all, I introduce myself. My name is Federica, I&amp;#39;m 23 and I come from Italy. I would like to thank all the people here for the attention given. I am at the last year of my university (I study foreign languages and English as well) and I&amp;#39;m doing my final thesis. The subject of my thesis is Ireland, its history, society, language and how some traditions have survived and spread around the world. I am very curious a&lt;span class="text_exposed_show"&gt;bout this argument and I really would like to have a &amp;quot;closer&amp;quot; contact directly with Irish people. Would you help me?&amp;nbsp;&lt;span class="_47e3 _5mfr"&gt;&lt;img width="16" src="https://static.xx.fbcdn.net/images/emoji.php/v9/fa5/1.5/16/1f642.png" height="16" class="img" alt="" /&gt;&lt;span class="_7oe"&gt;:)&lt;/span&gt;&lt;/span&gt;&amp;nbsp;I will post some few questions and you will answer. Thank you a lot!&lt;/span&gt;&lt;/p&gt;
&lt;div class="text_exposed_show"&gt;
&lt;p&gt;1. Name, age, home town and town where you actually live in.&lt;/p&gt;
&lt;p&gt;2. How do you perceive the influence of the British culture on Irish culture and its traditions?&lt;/p&gt;
&lt;p&gt;3. What is left, in your opinion, of the Irishness today? Do you speak Irish? How do you perceive bilingualism? Do you feel you belong to both cultures or do you relate to one more than the other?&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Great new album inspired by Ireland</title><link>http://talkirish.com/forums/thread/16764.aspx</link><pubDate>Thu, 21 Dec 2017 16:46:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16764</guid><dc:creator>SweetJesus</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16764.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=16764</wfw:commentRss><description>&lt;p&gt;The album is called &amp;quot;The Right People&amp;quot; by Fine by Me. You can find it on Spotify&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I met this kid in Chicago who claimed to be a former banjo player, and he asked me to listen to his album. At first I was skeptical, because it seemed pretty bogus. Turns out, not only is the album pretty good, but it has everything to do with Ireland. Underglow on a Pontoon is about a day spent in Ireland, and the whole album seems heavily inspired by the town of Slane.&lt;/p&gt;
&lt;p&gt;Solid 7/10 overall, I wouldn&amp;#39;t pay for it but luckily enough it was free. Check it out&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Irish Firefighter in need of help</title><link>http://talkirish.com/forums/thread/16763.aspx</link><pubDate>Tue, 19 Dec 2017 13:08:13 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16763</guid><dc:creator>cavani12</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16763.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16763</wfw:commentRss><description>&lt;p class="MsoNormal"&gt;&lt;span&gt;I am an Irish firefighter in need of help.&amp;nbsp;&amp;nbsp;Wishing to honor those who have, do, and will serve their communities, I need the Irish Gaelic translation for the English phrase: &amp;ldquo;Everyone Goes Home.&amp;rdquo;&amp;nbsp;&amp;nbsp;This will be used in a tattoo, so accuracy is needed.&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;Thanks for all help.&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Deletion</title><link>http://talkirish.com/forums/thread/16746.aspx</link><pubDate>Sat, 09 Dec 2017 14:38:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16746</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16746.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16746</wfw:commentRss><description>&lt;p&gt;F&amp;oacute;gra:&lt;/p&gt;
&lt;p&gt;Bain amach m&amp;eacute; &amp;uacute;s&amp;aacute;ideoirainm &amp;quot;RyanCaleb&amp;quot; &amp;oacute;n ait seo.&lt;/p&gt;
&lt;p&gt;I have deleted all posts I could find. &amp;nbsp;If you find any remaining, let me know so I can remove them. &amp;nbsp;Thanks!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Hello everybody</title><link>http://talkirish.com/forums/thread/16697.aspx</link><pubDate>Sun, 26 Nov 2017 07:56:11 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16697</guid><dc:creator>dimaria</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16697.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16697</wfw:commentRss><description>&lt;p style="text-align:center;"&gt;&lt;strong&gt;Dự&lt;/strong&gt;&lt;strong&gt; đo&amp;aacute;n xsmb - Dự đo&amp;aacute;n xsmb ch&amp;iacute;nh x&amp;aacute;c nhất - Dự đo&amp;aacute;n xsmb h&amp;ocirc;m nay ng&amp;agrave;y 9/2/2018&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Khi chơi xổ số th&amp;igrave; những người chơi cũng cần phải c&amp;oacute; những kỹ năng ri&amp;ecirc;ng trong việc dự đo&amp;aacute;n xsmb ch&amp;iacute;nh x&amp;aacute;c 100% v&amp;igrave; nếu l&amp;agrave;m được việc dự đo&amp;aacute;n xsmb h&amp;ocirc;m nay th&amp;igrave; những người chơi đ&amp;atilde; c&amp;oacute; được 50% cơ hội đem những giải thưởng về cho m&amp;igrave;nh. Mặt kh&amp;aacute;c, khi du doan xsmb hom nay th&amp;igrave; những người chơi c&amp;ograve;n biết được c&amp;aacute;c th&amp;ocirc;ng tin về c&amp;aacute;c con số để chơi được một c&amp;aacute;ch dễ d&amp;agrave;ng trong những ng&amp;agrave;y tiếp theo.&lt;/p&gt;
&lt;p&gt;Để du doan xsmb chinh xac 100% l&amp;agrave; một việc l&amp;agrave;m cần thiết v&amp;agrave; kh&amp;aacute; kh&amp;oacute; khăn. C&amp;oacute; những phương ph&amp;aacute;p dự đo&amp;aacute;n xsmb miễn ph&amp;iacute; mang t&amp;iacute;nh phức tạp nhưng khi đ&amp;atilde; hiểu được quy luật chơi của ch&amp;uacute;ng th&amp;igrave; việc dự đo&amp;aacute;n xsmb của những con số l&amp;agrave; v&amp;ocirc; c&amp;ugrave;ng dễ d&amp;agrave;ng v&amp;agrave; người chơi sẽ cảm thấy th&amp;iacute;ch th&amp;uacute; từ việc du doan xsmb mien phi n&amp;agrave;y.&lt;/p&gt;
&lt;p&gt;C&amp;aacute;c phương ph&amp;aacute;p dự đo&amp;aacute;n xsmb h&amp;ocirc;m nay ch&amp;iacute;nh x&amp;aacute;c nhất lu&amp;ocirc;n được t&amp;igrave;m kiếm bởi những người chơi xổ số bởi họ biết rằng những c&amp;aacute;ch du doan xsmb n&amp;agrave;y c&amp;oacute; thể đem lại cho họ những điều may mắn.&lt;/p&gt;
&lt;p&gt;C&amp;aacute;c bạn c&amp;oacute; thể theo d&amp;otilde;i những th&amp;ocirc;ng tin mới nhất về xổ số 3 miền h&amp;ocirc;m nay tại &lt;strong&gt;&lt;a href="https://ok.ru/ketquakqxsmnminhngochomnay" rel="nofollow"&gt;XSMN Minh Ngoc hom nay&lt;/a&gt;&lt;/strong&gt;.&lt;/p&gt;
&lt;p&gt;Khi c&amp;oacute; được những con số chuẩn x&amp;aacute;c từ việc du doan xsmb hom nay chinh xac nhat th&amp;igrave; những người chơi sẽ c&amp;agrave;ng đam m&amp;ecirc; v&amp;agrave; hứng khởi hơn. Họ mong muốn v&amp;agrave; chờ đợi đến giờ quay số để biết được m&amp;igrave;nh c&amp;oacute; phải l&amp;agrave; người may mắn tr&amp;uacute;ng giải hay kh&amp;ocirc;ng.&lt;/p&gt;
&lt;p&gt;C&amp;aacute;c phương ph&amp;aacute;p hay lu&amp;ocirc;n được nhiều người t&amp;igrave;m kiếm, tuy nhi&amp;ecirc;n, sẽ c&amp;oacute; những phương ph&amp;aacute;p v&amp;ocirc; c&amp;ugrave;ng đơn giản c&amp;oacute; thể bị bỏ qu&amp;ecirc;n bởi một số người.&lt;/p&gt;
&lt;p&gt;Trong b&amp;agrave;i viết dưới đ&amp;acirc;y, ch&amp;uacute;ng t&amp;ocirc;i sẽ chia sẻ cho c&amp;aacute;c bạn c&amp;aacute;c phương ph&amp;aacute;p hay, bạn c&amp;oacute; thể t&amp;iacute;ch lũy những kinh nghiệm n&amp;agrave;y cho m&amp;igrave;nh để c&amp;oacute; được nhiều phương ph&amp;aacute;p hơn trong việc chơi xổ số v&amp;agrave; c&amp;oacute; thể những cơ hội v&amp;agrave;ng của bạn sẽ được tăng l&amp;ecirc;n đ&amp;aacute;ng kể.&lt;/p&gt;
&lt;p&gt;* &lt;strong&gt;C&amp;aacute;ch bắt l&amp;ocirc; chạm 2 nh&amp;aacute;y bạch thủ ph&amp;aacute;t t&amp;agrave;i, &lt;/strong&gt;&lt;strong&gt;du doan xsmb chinh xac nhat&lt;/strong&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Phương ph&amp;aacute;p bắt l&amp;ocirc; chạm 2 nh&amp;aacute;y bạch thủ&lt;/strong&gt; n&amp;agrave;y kh&amp;ocirc;ng phải l&amp;agrave; một phương ph&amp;aacute;p qu&amp;aacute; kh&amp;oacute; khăn hay n&amp;oacute; cũng hề cầu kỳ như nhiều người vẫn nghĩ, người chơi xổ số chỉ cần để &amp;yacute; kết quả của ng&amp;agrave;y h&amp;ocirc;m trước xem c&amp;oacute; cặp n&amp;agrave;o về 2 nh&amp;aacute;y th&amp;igrave; h&amp;ocirc;m sau đ&amp;aacute;nh chặn đầu v&amp;agrave; chặn đu&amp;ocirc;i của cặp đ&amp;oacute;, chắc chắn bạn sẽ bất ngờ về c&amp;aacute;ch đ&amp;aacute;nh đơn giản n&amp;agrave;y.&lt;/p&gt;
&lt;p&gt;VD: H&amp;ocirc;m trước c&amp;oacute; l&amp;ocirc; 46 ra 2 nh&amp;aacute;y th&amp;igrave; h&amp;ocirc;m sau bạn n&amp;ecirc;n đ&amp;aacute;nh l&amp;ocirc; 45 v&amp;agrave; 47. C&amp;aacute;ch n&amp;agrave;y kh&amp;aacute; đơn giản nhưng cũng mang lại hiệu quả cao.&lt;/p&gt;
&lt;p&gt;C&amp;ugrave;ng tham gia dự đo&amp;aacute;n kết quả xổ số với c&amp;aacute;c chuy&amp;ecirc;n gia xổ số tại &lt;strong&gt;&lt;a href="https://ok.ru/dudoankqxsmnthantaihomnay" rel="nofollow"&gt;Dự đoán XSMN Th&amp;acirc;̀n Tài&lt;/a&gt;&lt;/strong&gt;.&lt;/p&gt;
&lt;p&gt;&lt;img style="display:block;margin-left:auto;margin-right:auto;" src="https://i.pinimg.com/564x/8c/4e/6b/8c4e6bb9d36802d6abf817b140e5a4bd.jpg" width="480" height="392" alt="" /&gt;&lt;/p&gt;
&lt;p style="text-align:center;"&gt;&lt;em&gt;Dự&lt;/em&gt;&lt;em&gt; đo&amp;aacute;n xsmb ch&amp;iacute;nh x&amp;aacute;c&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;* C&amp;aacute;ch soi cầu l&amp;ocirc; k&amp;eacute;p dựa v&amp;agrave;o đu&amp;ocirc;i l&amp;ocirc; c&amp;acirc;m, &lt;/strong&gt;&lt;strong&gt;dự đo&amp;aacute;n xsmb ch&amp;iacute;nh x&amp;aacute;c nhất&lt;/strong&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Người chơi c&amp;oacute; thể xem x&amp;eacute;t xem kết quả xổ số trong ng&amp;agrave;y h&amp;ocirc;m nay c&amp;oacute; đu&amp;ocirc;i l&amp;ocirc; n&amp;agrave;o c&amp;acirc;m kh&amp;ocirc;ng v&amp;agrave; sẽ tiếp tục đợi trong c&amp;aacute;c ng&amp;agrave;y tiếp theo xem con k&amp;eacute;p của đầu c&amp;acirc;m đ&amp;oacute; c&amp;oacute; xuất hiện tr&amp;ecirc;n bảng kết quả hay kh&amp;ocirc;ng. Nếu n&amp;oacute; kh&amp;ocirc;ng ra m&amp;agrave; c&amp;oacute; 1 ng&amp;agrave;y đầu con k&amp;eacute;p đ&amp;oacute; cũng c&amp;acirc;m th&amp;igrave; tốt nhất l&amp;agrave; bạn n&amp;ecirc;n bắt đầu nu&amp;ocirc;i con bạch thủ l&amp;ocirc; k&amp;eacute;p đ&amp;oacute; trong v&amp;ograve;ng 4 ng&amp;agrave;y tiếp theo.&lt;/p&gt;
&lt;p&gt;&lt;em&gt;VD:&lt;/em&gt;&amp;nbsp;Kết quả xổ số ng&amp;agrave;y 1/10/2013 c&amp;oacute; đu&amp;ocirc;i 3 c&amp;acirc;m, người chơi cần để &amp;yacute; đến ng&amp;agrave;y 2/10 v&amp;agrave; ng&amp;agrave;y 3/10 l&amp;ocirc; k&amp;eacute;p 33 đều kh&amp;ocirc;ng ra. Đến ng&amp;agrave;y 4/10 đầu l&amp;ocirc; 3 lại tiếp tục c&amp;acirc;m. Vậy th&amp;igrave; bắt đầu từ ng&amp;agrave;y 5/10, người chơi bắt đầu nu&amp;ocirc;i l&amp;ocirc; bạch thủ k&amp;eacute;p 33 v&amp;agrave; nu&amp;ocirc;i tối đa l&amp;agrave; 4 ng&amp;agrave;y (th&amp;ocirc;ng thường người chơi chỉ cần nu&amp;ocirc;i trong 2 ng&amp;agrave;y đầu l&amp;agrave; l&amp;ocirc; k&amp;eacute;p sẽ ra). Kết quả l&amp;agrave; đến ng&amp;agrave;y 5/10 l&amp;ocirc; k&amp;eacute;p 33 đ&amp;atilde; ra ngay từ ng&amp;agrave;y đầu bắt đầu nu&amp;ocirc;i.&lt;/p&gt;
&lt;p&gt;Ch&amp;uacute; &amp;yacute;: Trong khi chơi th&amp;igrave; người chơi cũng cần thống k&amp;ecirc; lại những con đang c&amp;acirc;m, nếu rơi v&amp;agrave;o những con đang c&amp;acirc;m cả đầu v&amp;agrave; đu&amp;ocirc;i dưới 55 ng&amp;agrave;y th&amp;igrave; tốt nhất l&amp;agrave; kh&amp;ocirc;ng n&amp;ecirc;n d&amp;iacute;nh v&amp;agrave;o, c&amp;ograve;n nếu tr&amp;ecirc;n 55 ng&amp;agrave;y th&amp;igrave; c&amp;oacute; thể v&amp;agrave;o tiền nu&amp;ocirc;i l&amp;ocirc; v&amp;igrave; theo c&amp;aacute;c con số thống k&amp;ecirc; th&amp;igrave; tr&amp;ecirc;n 90% c&amp;aacute;c trường hợp l&amp;ocirc; c&amp;acirc;m sẽ c&amp;acirc;m kh&amp;ocirc;ng qu&amp;aacute; 65 ng&amp;agrave;y. Nếu người chơi n&amp;agrave;o đ&amp;oacute; rơi v&amp;agrave;o 10% c&amp;ograve;n lại th&amp;igrave; người đ&amp;oacute; l&amp;agrave; người chưa được may mắn.&lt;/p&gt;
&lt;p&gt;H&amp;atilde;y c&amp;ugrave;ng dự đo&amp;aacute;n xổ số h&amp;ocirc;m nay chuẩn nhất tại &lt;strong&gt;&lt;a href="https://plus.google.com/communities/115093898201610412286" rel="nofollow"&gt;DD XSMN - Dự đo&amp;aacute;n kết quả xổ số Miền Nam Minh Ngọc h&amp;ocirc;m nay&lt;/a&gt;&lt;/strong&gt;.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;* Hướng dẫn soi cầu l&amp;ocirc; đề theo b&amp;oacute;ng &amp;acirc;m dương:&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Soi cầu l&amp;ocirc; đề theo b&amp;oacute;ng &amp;acirc;m dương l&amp;agrave; một trong những c&amp;aacute;ch t&amp;iacute;nh c&amp;oacute; tỷ lệ tr&amp;uacute;ng rất cao. Người chơi n&amp;ecirc;n dựa v&amp;agrave;o phương ph&amp;aacute;p soi cầu n&amp;agrave;y để tăng độ tin tưởng cho những con l&amp;ocirc; m&amp;agrave; họ đ&amp;atilde; chọn.&lt;/p&gt;
&lt;p&gt;VD:&amp;nbsp;Nếu bạn muốn đ&amp;aacute;nh con l&amp;ocirc; 47 th&amp;igrave; bạn phải t&amp;iacute;nh ra 3 d&amp;ograve;ng số b&amp;oacute;ng theo ngũ h&amp;agrave;nh, b&amp;oacute;ng dương b&amp;oacute;ng &amp;acirc;m v&amp;agrave; thứ tự sẽ l&amp;agrave;: 20, 92, 10. Tiếp theo, bạn h&amp;atilde;y đối chiếu với kết quả xổ số miền Bắc của ng&amp;agrave;y h&amp;ocirc;m trước xem c&amp;oacute; xuất hiện con l&amp;ocirc; n&amp;agrave;o trong 3 con l&amp;ocirc; đ&amp;oacute; kh&amp;ocirc;ng.&lt;/p&gt;
&lt;p&gt;&lt;img style="display:block;margin-left:auto;margin-right:auto;" src="https://i.pinimg.com/564x/56/79/0f/56790ff29561805312c0fbbc0fed3dea.jpg" width="480" height="392" alt="" /&gt;&lt;/p&gt;
&lt;p style="text-align:center;"&gt;&lt;em&gt;Dự&lt;/em&gt;&lt;em&gt; đo&amp;aacute;n xsmb h&amp;ocirc;m nay ng&amp;agrave;y 9/2/2018&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;Nếu như trong bảng kết quả của ng&amp;agrave;y h&amp;ocirc;m trước xuất hiện cả 3 con l&amp;ocirc; tr&amp;ecirc;n th&amp;igrave; tỷ lệ tr&amp;uacute;ng l&amp;ocirc; 47 chỉ c&amp;ograve;n 8%, v&amp;igrave; vậy bạn n&amp;ecirc;n tr&amp;aacute;nh đ&amp;aacute;nh con l&amp;ocirc; n&amp;agrave;y nh&amp;eacute;.&lt;/p&gt;
&lt;p&gt;C&amp;ograve;n nếu bạn thấy c&amp;oacute; xuất hiện 2 con l&amp;ocirc; th&amp;igrave; tỷ lệ tr&amp;uacute;ng l&amp;ocirc; 47 sẽ v&amp;agrave;o khoảng 25% theo c&amp;aacute;ch thức b&amp;oacute;ng &amp;acirc;m dương l&amp;ocirc; đề n&amp;agrave;y, do đ&amp;oacute;, bạn c&amp;oacute; thể nu&amp;ocirc;i v&amp;agrave; đ&amp;aacute;nh con l&amp;ocirc; n&amp;agrave;y.&lt;/p&gt;
&lt;p&gt;Nếu&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;bạn theo d&amp;otilde;i v&amp;agrave; thấy 1 con l&amp;ocirc; xuất hiện th&amp;igrave; tỷ lệ tr&amp;uacute;ng l&amp;ocirc; 47 l&amp;agrave; từ 30-60%,&amp;nbsp;nếu con l&amp;ocirc; xuất hiện l&amp;agrave; b&amp;oacute;ng &amp;acirc;m th&amp;igrave; tỷ lệ tr&amp;uacute;ng sẽ l&amp;agrave; 30%, c&amp;ograve;n nếu như con l&amp;ocirc; xuất hiện l&amp;agrave; b&amp;oacute;ng dương th&amp;igrave; tỷ lệ tr&amp;uacute;ng sẽ rơi v&amp;agrave;o khoảng 45% .&lt;/p&gt;
&lt;p&gt;Nếu bạn thấy xuất hiện b&amp;oacute;ng ngũ h&amp;agrave;nh th&amp;igrave; tỷ lệ khoảng 60%. C&amp;aacute;c bạn n&amp;ecirc;n kết hợp với những c&amp;aacute;ch đ&amp;aacute;nh kh&amp;aacute;c để đ&amp;aacute;nh l&amp;ocirc; 47 nh&amp;eacute;. C&amp;ograve;n nếu như bạn kh&amp;ocirc;ng thấy xuất hiện con l&amp;ocirc; n&amp;agrave;o th&amp;igrave; bạn n&amp;ecirc;n đ&amp;aacute;nh l&amp;ocirc; 47 v&amp;igrave; l&amp;uacute;c n&amp;agrave;y tỷ lệ tr&amp;uacute;ng đ&amp;atilde; l&amp;ecirc;n tới 75% cơ hội, bạn c&amp;oacute; thể sẽ l&amp;agrave; người may mắn đấy.&lt;/p&gt;
&lt;p&gt;Nếu c&amp;aacute;c bạn muốn đạt tới 100% hiệu quả theo c&amp;aacute;ch t&amp;iacute;nh b&amp;oacute;ng &amp;acirc;m dương l&amp;ocirc; đề ngũ h&amp;agrave;nh n&amp;agrave;y th&amp;igrave; c&amp;aacute;c bạn n&amp;ecirc;n t&amp;igrave;m hiểu th&amp;ecirc;m c&amp;aacute;c y&amp;ecirc;u tố như: Tần xuất, bi&amp;ecirc;n độ, bạc nhớ v&amp;agrave; n&amp;oacute; c&amp;ograve;n phụ thuộc v&amp;agrave;o sự may mắn của ch&amp;iacute;nh bạn trong tr&amp;ograve; chơi xổ số nữa.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>So let me see...</title><link>http://talkirish.com/forums/thread/16486.aspx</link><pubDate>Tue, 26 Sep 2017 10:47:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16486</guid><dc:creator>maxbale</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16486.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16486</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Trong cuộc sống n&amp;agrave;y vẫn lu&amp;ocirc;n c&amp;oacute; những điều tr&amp;ugrave;ng hợp bất ngờ m&amp;agrave; kh&amp;ocirc;ng ai c&amp;oacute; thể đo&amp;aacute;n trước được, đặt biệt l&amp;agrave; đối với những sự may mắn trong tr&amp;ograve; chơi x&amp;aacute;c suất như xổ số th&amp;igrave; c&amp;agrave;ng nhiều bất ngờ như thế.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mới đ&amp;acirc;y, một người đ&amp;agrave;n &amp;ocirc;ng đ&amp;atilde; may mắn c&amp;oacute; được vận may mắn như th&amp;ecirc;, do đồng nghiệp của &amp;ocirc;ng nhờ cậy n&amp;ecirc;n &amp;ocirc;ng đ&amp;atilde; đi mua v&amp;eacute; số &lt;b&gt;&lt;a href="https://ok.ru/soicaurongbachkim" target="_blank" title="https://ok.ru/soicaurongbachkim"&gt;soi cầu Rồng Bạch Kim 888 h&amp;ocirc;m nay&lt;/a&gt;&lt;/b&gt;, mặc d&amp;ugrave; l&amp;uacute;c đầu kh&amp;ocirc;ng c&amp;oacute; &amp;yacute; định mua v&amp;eacute;, nhưng l&amp;uacute;c đ&amp;oacute; &amp;ocirc;ng lại quyết định mua th&amp;ecirc;m v&amp;eacute; số m&amp;igrave;nh, v&amp;agrave; quyết định đ&amp;oacute; khiến cho người đ&amp;agrave;n &amp;ocirc;ng đ&amp;atilde; tr&amp;uacute;ng được giải thưởng lớn.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Người may mắn đ&amp;oacute; l&amp;agrave; &amp;ocirc;ng Ravuth Chhim, sống tại Manassas Park, Virginia, Hoa Kỳ. Ng&amp;agrave;y h&amp;ocirc;m đ&amp;oacute;, &amp;ocirc;ng được một nh&amp;oacute;m đồng nghiệp trong c&amp;ocirc;ng ty m&amp;igrave;nh nhờ đi mua hộ v&amp;eacute; số Mega Millions trong đợt quay số mở thưởng tiếp theo.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;Ocirc;ng Chhim đ&amp;atilde; đến cửa h&amp;agrave;ng 9103 Mathis Avenue, Manassas để mua v&amp;eacute; số, tại đ&amp;acirc;y &amp;ocirc;ng quyết định mua cho m&amp;igrave;nh một v&amp;eacute; số c&amp;agrave;o thuộc loại In The Money do cơ quan xổ số Virginia Lottery ph&amp;aacute;t h&amp;agrave;nh.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;V&amp;agrave; thật v&amp;ocirc; c&amp;ugrave;ng may mắn, tấm v&amp;eacute; số đ&amp;oacute; đ&amp;atilde; đem về cho &amp;ocirc;ng giải thưởng xổ số trị gi&amp;aacute; 225.000 USD (tương đương hơn 5,1 tỷ đồng). &amp;Ocirc;ng Chhim chia sẻ: &amp;ldquo;T&amp;ocirc;i đ&amp;atilde; c&amp;agrave;o n&amp;oacute; v&amp;agrave; khi biết m&amp;igrave;nh tr&amp;uacute;ng giải, t&amp;ocirc;i thực sự sốc&amp;rdquo;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img src="https://i.pinimg.com/564x/86/a0/28/86a0285d5fd3d7a1cf1a8d421de2294e.jpg" border="0" /&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Ravuth Chhim tr&amp;uacute;ng số 250.000 đ&amp;ocirc; la khi mua gi&amp;ugrave;m v&amp;eacute; cho đồng nghiệp&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Được biết, để tr&amp;uacute;ng giải h&amp;agrave;ng đầu của tr&amp;ograve; chơi In The Money của xổ số Virginia l&amp;agrave; 1 trong 1.060.800 v&amp;eacute; số, ngo&amp;agrave;i tấm v&amp;eacute; thắng của &amp;ocirc;ng Chhim th&amp;igrave; tr&amp;ograve; chơi n&amp;agrave;y vẫn c&amp;ograve;n một giải nhất nữa chưa c&amp;oacute; người tr&amp;uacute;ng thưởng.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Chiến thắng của Chhim l&amp;agrave; một điều bất ngờ tr&amp;ugrave;ng hợp, nhưng so với người đ&amp;agrave;n &amp;ocirc;ng trong c&amp;acirc;u chuyện dưới đ&amp;acirc;y th&amp;igrave; c&amp;oacute; lẽ khiến bạn cảm thấy bất ngờ hơn khi chỉ trong v&amp;ograve;ng 1 th&amp;aacute;ng, người n&amp;agrave;y đ&amp;atilde; ẵm về cho m&amp;igrave;nh 2 giải thưởng h&amp;agrave;ng đầu của xổ số Virginia.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Người chiến thắng đ&amp;oacute; l&amp;agrave; Hussein Haj-Assaad, sống tại Annandale thuộc Fairfax County, tiểu bang Virginia, Hoa Kỳ. Được biết, v&amp;agrave;o th&amp;aacute;ng 9 năm 2017, Haj-Assaad &amp;nbsp;đ&amp;atilde; mua v&amp;eacute; số trong một tr&amp;ograve; chơi xổ số &lt;b&gt;&lt;a href="https://www.facebook.com/soicauxsmbmienbac24hhomnaychinhxacnhat/" target="_blank" title="https://www.facebook.com/soicauxsmbmienbac24hhomnaychinhxacnhat/"&gt;soi cau MB&lt;/a&gt;&lt;/b&gt; do cơ quan xổ số Virginia Lottery ph&amp;aacute;t h&amp;agrave;nh.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;V&amp;eacute; số may mắn đ&amp;atilde; được Haj-Assaad mua tại cửa h&amp;agrave;ng E &amp;amp; C VA, Đường 2919 Gallows ở Falls Church. Tấm v&amp;eacute; số n&amp;agrave;y đ&amp;atilde; mang về cho anh giải thưởng xổ số trị gi&amp;aacute; 200.000 đ&amp;ocirc; la (tương đương với khoảng 4,4 tỷ đồng tiền Việt).&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Haj-Assaad d&amp;ugrave; chiến thắng lớn nhưng vẫn kh&amp;ocirc;ng từ bỏ th&amp;oacute;i quen chơi xổ số của m&amp;igrave;nh, anh vẫn chăm chỉ mua v&amp;eacute; số với hi vọng may mắn lần tiếp theo. Một th&amp;aacute;ng sau, Haj-Assaad cũng mua v&amp;eacute; số tham dự tr&amp;ograve; chơi Money Mania cũng tại cửa h&amp;agrave;ng E &amp;amp; C VA.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thật kh&amp;ocirc;ng ngờ, may mắn lần thứ 2 đ&amp;atilde; g&amp;otilde; cửa nh&amp;agrave; Haj-Assaad, v&amp;agrave; lần nay, anh cũng gi&amp;agrave;nh được giải nhất của tr&amp;ograve; chơi n&amp;agrave;y với chiến thắng giải thưởng trị gi&amp;aacute; 250.000 đ&amp;ocirc; la. Tức l&amp;agrave; chỉ trong v&amp;ograve;ng một th&amp;aacute;ng, người đ&amp;agrave;n &amp;ocirc;ng đ&amp;atilde; mang về cho m&amp;igrave;nh 2 giải thưởng h&amp;agrave;ng đầu, v&amp;agrave; thực tế đ&amp;acirc;y l&amp;agrave; sự may mắn v&amp;ocirc; c&amp;ugrave;ng hiếm c&amp;oacute;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img src="https://i.pinimg.com/564x/16/17/0a/16170a168e7897dd13fbfd94c8f2e080.jpg" border="0" /&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Hussein Haj-Assaad tr&amp;uacute;ng số 2 lần chỉ trong v&amp;ograve;ng 1 th&amp;aacute;ng&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;V&amp;agrave;o ng&amp;agrave;y 13 th&amp;aacute;ng 10 vừa qua, Haj-Assaad đ&amp;atilde; đến trụ sở xổ số Virginia Lottery để nhận phần thưởng của m&amp;igrave;nh, khi chia sẻ m&amp;igrave;nh gi&amp;agrave;nh được giải thưởng n&amp;agrave;y lần thứ 2, anh đ&amp;atilde; khiến rất nhiều người phải bất ngờ.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Được biết, trong lần chiến thắng đầu ti&amp;ecirc;n, Haj-Assaad cho biết số tiền thắng giải được m&amp;igrave;nh sử dụng để để đầu tư v&amp;agrave;o một cửa h&amp;agrave;ng tại Falls Church m&amp;agrave; anh sở hữu. V&amp;agrave; chiến thắng thứ hai n&amp;agrave;y sẽ gi&amp;uacute;p anh c&amp;oacute; điều kiện để đầu tư v&amp;agrave;o một cửa h&amp;agrave;ng thứ hai.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Được biết, tr&amp;ograve; chơi Money Mania trị gi&amp;aacute; 250.000 đ&amp;ocirc; la l&amp;agrave; một trong nhiều giải thưởng xổ số c&amp;agrave;o biết kết quả ngay do cơ quan Xổ số Virginia ph&amp;aacute;t h&amp;agrave;nh. Money Mania c&amp;oacute; c&amp;aacute;c giải thưởng kh&amp;aacute;c nhau, với giải thưởng nhỏ nhất trị gi&amp;aacute; 20 đ&amp;ocirc; la v&amp;agrave; lớn nhất l&amp;ecirc;n đến 250,000 đ&amp;ocirc; la.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Tỷ lệ thắng giải cao nhất của Money Mania l&amp;agrave; 1 trong 367.200. Tỷ lệ chiến thắng bất kỳ giải thưởng trong tr&amp;ograve; chơi n&amp;agrave;y l&amp;agrave; 1 trong 3,0. Haj-Assaad l&amp;agrave; người đầu ti&amp;ecirc;n nhận giải thưởng h&amp;agrave;ng đầu của tr&amp;ograve; chơi n&amp;agrave;y, tr&amp;ograve; chơi n&amp;agrave;y c&amp;oacute; tất cả 10 giải h&amp;agrave;ng đầu, như vậy c&amp;oacute; nghĩa l&amp;agrave; c&amp;ograve;n 9 v&amp;eacute; &lt;b&gt;&lt;a href="https://flipboard.com/@soicaulode" target="_blank" title="https://flipboard.com/@soicaulode"&gt;cầu l&amp;ocirc; bạch thủ h&amp;ocirc;m nay&lt;/a&gt;&lt;/b&gt; chưa c&amp;oacute; người gi&amp;agrave;nh được chiến thắng .&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Virginia Lottery l&amp;agrave; một trong những cơ quan xổ số của tiểu bang c&amp;oacute; hoạt động xổ số t&amp;iacute;ch cực nhất hiện nay của Hoa Kỳ, h&amp;agrave;ng ng&amp;agrave;y c&amp;oacute; h&amp;agrave;ng chục giải thưởng được tổ chức với gi&amp;aacute; trị từ thấp đến cao, thu h&amp;uacute;t đ&amp;ocirc;ng đảo người chơi tham gia.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Cơ quan xổ số Virginia Lottery lu&amp;ocirc;n t&amp;iacute;ch cực đổi mới c&amp;aacute;c tr&amp;ograve; chơi c&amp;oacute; thưởng để thu h&amp;uacute;t người tham gia v&amp;agrave; đạt được nhiều th&amp;agrave;nh quả đ&amp;aacute;ng mong đợi, h&amp;agrave;ng th&amp;aacute;ng tr&amp;ecirc;n website của c&amp;ocirc;ng ty c&amp;oacute; th&amp;ocirc;ng tin h&amp;agrave;ng chục những người may mắn gi&amp;agrave;nh được giải thưởng h&amp;agrave;ng đầu.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Doanh thu từ Virginia Lottery sẽ được sử dụng để đầu tư cho gi&amp;aacute;o dục của tiểu bang. C&amp;aacute;c th&amp;agrave;nh phố, quận của Virginia dều được ph&amp;acirc;n phối một khoản tiền h&amp;agrave;ng năm để phục vụ cho điều n&amp;agrave;y. Falls Church trong năm qua đ&amp;atilde; được nhận 169.000 đ&amp;ocirc; la từ quỹ xổ số để đầu tư gi&amp;aacute;o dục cho c&amp;aacute;c trường c&amp;ocirc;ng lập K-12.&lt;/p&gt;
&lt;table cellspacing="0" cellpadding="0"&gt;

&lt;tr&gt;
&lt;td class="ForumPostContentArea"&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;/tr&gt;

&lt;/table&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Poll</title><link>http://talkirish.com/forums/thread/16325.aspx</link><pubDate>Mon, 28 Aug 2017 13:43:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16325</guid><dc:creator>Amiga Ireland</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16325.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16325</wfw:commentRss><description>&lt;p&gt;Dia daoibh,&lt;/p&gt;
&lt;p&gt;There&amp;#39;s an interesting poll taking place.&lt;/p&gt;
&lt;p&gt;Vote Gaeilge! :) &lt;a title="http://www.thejournal.ie/poll-irish-language-3-3567933-Aug2017" href="http://www.thejournal.ie/poll-irish-language-3-3567933-Aug2017"&gt;http://www.thejournal.ie/poll-irish-language-3-3567933-Aug2017&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;GMA,&lt;/p&gt;
&lt;p&gt;Iarla&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Is Saol Taibhreamh.</title><link>http://talkirish.com/forums/thread/16193.aspx</link><pubDate>Fri, 21 Jul 2017 04:10:11 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16193</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16193.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16193</wfw:commentRss><description>&lt;p&gt;Bh&amp;iacute; taibhreamh agam ar&amp;eacute;ir go bhuail m&amp;eacute; le fear c&amp;eacute; bh&amp;iacute; Gaeilge aige.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;D&amp;uacute;irt s&amp;eacute; a l&amp;aacute;n de na ruda&amp;iacute; dom i nGaeilge, ach n&amp;iacute; thuig m&amp;eacute; focal amh&amp;aacute;in.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Seanfhocal an Lae</title><link>http://talkirish.com/forums/thread/16104.aspx</link><pubDate>Sat, 24 Jun 2017 13:19:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16104</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16104.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16104</wfw:commentRss><description>&lt;p&gt;N&amp;aacute; b&amp;iacute;odh do theanga faoi do chrios.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Bheith mé ag déanamh iontais</title><link>http://talkirish.com/forums/thread/15995.aspx</link><pubDate>Sun, 04 Jun 2017 10:28:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15995</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15995.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15995</wfw:commentRss><description>&lt;p&gt;Conas a oibr&amp;iacute;onn an c&amp;oacute;ras pointe a oibri&amp;uacute;? &lt;img src="http://talkirish.com/emoticons/emotion-18.gif" alt="Huh?" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Focal an Lae - Comhluadar</title><link>http://talkirish.com/forums/thread/15991.aspx</link><pubDate>Sat, 03 Jun 2017 12:54:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15991</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15991.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15991</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;T&amp;aacute; &amp;aacute;thas orm go bhfuil sibh anseo. &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;Labhair linn.&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Sínise</title><link>http://talkirish.com/forums/thread/15884.aspx</link><pubDate>Wed, 17 May 2017 17:27:51 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15884</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15884.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15884</wfw:commentRss><description>&lt;p class="MsoNormal"&gt;&lt;span&gt;T&amp;aacute; br&amp;oacute;n orm.&amp;nbsp; N&amp;iacute;l S&amp;iacute;nise ach c&amp;uacute;pla f&amp;oacute;cal agam.&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>So let me see...</title><link>http://talkirish.com/forums/thread/15877.aspx</link><pubDate>Mon, 15 May 2017 23:42:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15877</guid><dc:creator>DnK</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15877.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15877</wfw:commentRss><description>&lt;p&gt;Been having tests done so haven&amp;#39;t been around for a day or ten 😷&lt;/p&gt;
&lt;p&gt;Wonder what I missed while I&amp;#39;ve been away.&lt;/p&gt;
&lt;p&gt;Off to read posts..😁. Sl&amp;aacute;n&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Irish acoustic duo</title><link>http://talkirish.com/forums/thread/15869.aspx</link><pubDate>Sat, 13 May 2017 23:50:04 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15869</guid><dc:creator>Scenes_Band</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15869.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15869</wfw:commentRss><description>&lt;p&gt;Hi guys,&amp;nbsp;&lt;/p&gt;
&lt;p&gt;myself and my friend (both from Dublin) &amp;nbsp;decided to set up a YouTube channel and post a few acoustic covers of some songs but as you can see our views and subscribers are quite low :( so we thought we&amp;#39;d put our channel up on this forum to try to get a little bit more support from the good people of Ireland and abroad (hopefully). I&amp;#39;ve posted the link to our channel here so please give us a listen and let us know what you think. If you&amp;#39;re feeling kind, subscribe and maybe even share us on Twitter, Facebook, wherever really!! More tunes in the way soon. Lots of love, Scenes&lt;/p&gt;
&lt;p&gt;https://m.youtube.com/channel/UCJpm28g4SqFvZ25aVrGN08A&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title> tá brón orm </title><link>http://talkirish.com/forums/thread/15835.aspx</link><pubDate>Mon, 08 May 2017 01:10:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15835</guid><dc:creator>DnK</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15835.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15835</wfw:commentRss><description>&lt;p&gt;I should have said. ..ar an TBh and not ..air an TBh.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Dia daoibh !</title><link>http://talkirish.com/forums/thread/15756.aspx</link><pubDate>Sat, 15 Apr 2017 03:04:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15756</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15756.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15756</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;&lt;span&gt;Beidh an Ch&amp;aacute;isc ann roimh i bhfad.&lt;/span&gt;&lt;/strong&gt;&lt;br /&gt;&lt;span&gt;It&amp;nbsp;will soon be Easter 😁&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Take part in an Irish study</title><link>http://talkirish.com/forums/thread/15483.aspx</link><pubDate>Sun, 19 Feb 2017 17:38:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15483</guid><dc:creator>ethankeeney</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15483.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15483</wfw:commentRss><description>&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;http://www.surveygizmo.com/s3/3311292/English-Irish-Mixed-Assessment&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Liberation Serif&amp;#39;, serif;"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;&lt;span&gt;Dia
Duit. T&amp;aacute;imid ag d&amp;eacute;anamh taighde ar conas is f&amp;eacute;idir foghlaim dh&amp;aacute;
theanga &amp;eacute;ifeacht ar dhaoine aonair fadhb cumais r&amp;eacute;iteach. Is &amp;eacute;ard
at&amp;aacute; sa staid&amp;eacute;ar ar roinnt teasers inchinn agus tomhaiseanna a
thomhas gn&amp;eacute;ithe de r&amp;eacute;iteach fadhbanna agus fola&amp;iacute;onn s&amp;eacute; freisin
teanga agus eolas ginear&amp;aacute;lta ceistneoir c&amp;uacute;lra. Chun &amp;aacute;r staid&amp;eacute;ar,
a cheangal againn rannph&amp;aacute;irtithe nach labhra&amp;iacute;onn ach B&amp;eacute;arla chomh
maith leo si&amp;uacute;d a bhfuil Gaeilge agus i mB&amp;eacute;arla. T&amp;aacute; an staid&amp;eacute;ar ar
fad ar l&amp;iacute;ne agus t&amp;oacute;gann n&amp;iacute;os l&amp;uacute; n&amp;aacute; 45 n&amp;oacute;im&amp;eacute;ad. P&amp;aacute;irt a
ghlacadh sa staid&amp;eacute;ar Cuid&amp;iacute;onn tairbhe &amp;aacute;r dtuiscint ar conas
foghlaim F&amp;eacute;adfaidh Ghaeilge &amp;eacute;ifeacht &amp;aacute;r fhadhb cumais r&amp;eacute;iteach
agus freisin d&amp;#39;fh&amp;eacute;adfadh a dh&amp;eacute;anann t&amp;uacute; n&amp;iacute;os an eolas faoi do
chumas an duine aonair agus ina dhiaidh sin iad a fheabhs&amp;uacute;. Ba
mhaith liom bu&amp;iacute;och go m&amp;oacute;r do chuid rannph&amp;aacute;irt&amp;iacute;ochta!&lt;br /&gt;
&lt;br /&gt;
M&amp;aacute;
t&amp;aacute; aon cheist agat maidir leis an staid&amp;eacute;ar a dh&amp;eacute;anamh t&amp;uacute;
f&amp;eacute;adfaidh t&amp;uacute; dul i dteagmh&amp;aacute;il leis seo a leanas:&lt;br /&gt;
Taighdeoir
Mac L&amp;eacute;inn Baitsil&amp;eacute;ir: Ethan Keeney;&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;span&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;&lt;span&gt;&lt;a href="mailto:e.keeney2@nuigalway.ie"&gt;e.keeney2@nuigalway.ie&lt;br /&gt;&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;Maoirseoir:
Dr. Mark Elliott; &lt;/span&gt;&lt;a style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;" href="mailto:mark.elliott@nuigalway.ie"&gt;mark.elliott@nuigalway.ie&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;Hi
there. We are conducting research on how learning two languages may
effect an individuals problem solving ability. The study consists of
a number of brain
teasers and riddles which measure aspects
of problem solving and also includes a language and general knowledge
background questionnaire. For our study, we require participants who
speak only English as well as those who speak both Irish and English.
The study is all online and takes less than 45 minutes. Taking part
in this study helps benefit our understanding of how learning Irish
may effect our problem solving capabilities and also may make you
more aware of your individual abilities and in turn improve them. I
would greatly appreciate your participation!&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;If
you have any questions about the study you may contact the following:&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Liberation Serif&amp;#39;, serif;"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;Bachelor
Student Researcher: Ethan Keeney; &lt;a href="mailto:e.keeney2@nuigalway.ie"&gt;e.keeney2@nuigalway.ie&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span style="color:#000000;"&gt;&lt;span style="font-family:&amp;#39;Liberation Serif&amp;#39;, serif;"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;Times New Roman&amp;#39;, serif;"&gt;&lt;span&gt;Supervisor:
Dr Mark Elliott, &lt;a href="mailto:mark.elliott@nuigalway.ie"&gt;mark.elliott@nuigalway.ie&lt;/a&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Ogham translation of deartháir</title><link>http://talkirish.com/forums/thread/14844.aspx</link><pubDate>Tue, 13 Dec 2016 15:22:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14844</guid><dc:creator>lukegiblin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14844.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=14844</wfw:commentRss><description>&lt;p&gt;Hi All&lt;/p&gt;
&lt;p&gt;I&amp;#39;m looking for the ogham translation of the word&amp;nbsp;&lt;i&gt;dearth&amp;aacute;ir please. Any help would be greatly appreciated, even if you dont know the answer but can point me in the right direction I would love the help. I have seen some online translation which look innacurate so I am looking for someone that legitimatly knows the correct spelling.&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;Thanks in advance!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>