<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: The verb "Feic"</title><link>http://talkirish.com/forums/thread/14292.aspx</link><pubDate>Sun, 10 Apr 2016 00:47:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14292</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14292.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14292</wfw:commentRss><description>&lt;p&gt;If you&amp;#39;re messaging somebody there&amp;#39;s an icon at the top of the tab that says &amp;quot;Add friend&amp;quot; &amp;nbsp;as in &amp;quot;Add friend to the conversation&amp;quot;, just click that and type in any friend&amp;#39;s name and hit enter and it&amp;#39;ll start a new conversation with you, the person you were originally talking too and the person whom you&amp;#39;ve just added.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;And mine is&amp;nbsp;https://www.facebook.com/ryan.bossler&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: The verb "Feic"</title><link>http://talkirish.com/forums/thread/14291.aspx</link><pubDate>Sat, 09 Apr 2016 20:52:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14291</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14291.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14291</wfw:commentRss><description>&lt;p&gt;Ryan, what is your name on Facebook?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: The verb "Feic"</title><link>http://talkirish.com/forums/thread/14289.aspx</link><pubDate>Sat, 09 Apr 2016 16:04:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14289</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14289.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14289</wfw:commentRss><description>&lt;p&gt;Well, as to &amp;quot;gerund&amp;quot; I went to grammar school a long time ago...maybe they don&amp;#39;t use or teach that term anymore?&lt;/p&gt;
&lt;p&gt;Just curious, how do you get into the &amp;quot;chat groups&amp;quot; on Facebook?&amp;quot; &amp;nbsp;I am a member of IRISH FOR BEGINNERS and IRISH LEARNERS BOOK CLUB but my participation in those groups have been hampered by other things. &amp;nbsp;It would be interesting to see if I could survive long in a chat group, though....&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: The verb "Feic"</title><link>http://talkirish.com/forums/thread/14286.aspx</link><pubDate>Tue, 05 Apr 2016 23:11:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14286</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14286.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14286</wfw:commentRss><description>&lt;p&gt;Greatly appreciated! &amp;nbsp;I definitely understand now, and as for my example; In a facebook chat or group chat in English when somebody opens it up it a little note at the bottom will read &amp;quot;Seen by Ryan&amp;quot; or &amp;quot;Seen by Kyle&amp;quot; or whoever it may be. &amp;nbsp;So facebook&amp;#39;s translation into Irish in these group chats are &amp;quot;Feicthe ag Ryan&amp;quot; and &amp;quot;Feicthe ag Kyle&amp;quot; and in bigger group chats &amp;quot;Feicthe ag Ryan, Kyle, Caleb, 4 eile&amp;quot;. &amp;nbsp;Hope that clears it up some!&lt;/p&gt;
&lt;p&gt;Also thanks for the proper names! &amp;nbsp;I would&amp;#39;ve never in my life guessed what &amp;quot;Gerund&amp;quot; could&amp;#39;ve meant! &amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: The verb "Feic"</title><link>http://talkirish.com/forums/thread/14282.aspx</link><pubDate>Tue, 05 Apr 2016 17:06:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14282</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14282.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14282</wfw:commentRss><description>&lt;p&gt;Haigh, Ryan.&lt;/p&gt;
&lt;p&gt;The &amp;quot;present participle&amp;quot; is known as the &amp;quot;verbal noun&amp;quot; in Irish, and is equivalent to adding &amp;quot;-ing&amp;quot; to a verb in English, what we call the &amp;quot;Gerund&amp;quot; form of the verb. &amp;nbsp;So with &amp;quot;feic&amp;quot; the verbal noun is &amp;quot;feice&amp;aacute;il&amp;quot; and would be rendered as &amp;quot;seeing&amp;quot;.&lt;/p&gt;
&lt;p&gt;The &amp;quot;past participle&amp;quot; is known as the &amp;quot;verbal adjective&amp;quot; in Irish, and is equivalent to adding &amp;quot;-en&amp;quot; or &amp;quot;ed&amp;quot; to a verb in English. &amp;nbsp;So with &amp;quot;feic,&amp;quot; the verbal adjective is &amp;quot;feicthe&amp;quot; and would be rendered as &amp;quot;seen&amp;quot;.&lt;/p&gt;
&lt;p&gt;These definitely differentiate from the &amp;quot;past tense&amp;quot; of the verb, which mutates into &amp;quot;chonaic&amp;quot;; &amp;quot;chonaic m&amp;eacute;, chonaic t&amp;uacute;,&amp;quot; etc.&lt;/p&gt;
&lt;p&gt;A second meaning for &amp;quot;feic&amp;quot; is given of being something&amp;#39;s appearance, so &amp;quot;feicthe&amp;quot; could also be rendered possibly as &amp;quot;appeared&amp;quot;.&lt;/p&gt;
&lt;p&gt;The past participle, or verbal adjective, may seem to be &amp;quot;past tense&amp;quot; but it is really a descriptor of something that happened.&lt;/p&gt;
&lt;p&gt;&amp;quot;He was seen in Dublin.&amp;quot; &amp;nbsp;&lt;i&gt;Bh&amp;iacute; s&amp;eacute; ag feicthe i mBaile &amp;Aacute;tha Cliath.&amp;quot;&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;It may also be a descriptor the condition of something in the present: &amp;nbsp;&amp;quot;It is broken&amp;quot; is &lt;i&gt;T&amp;aacute; s&amp;eacute; br&amp;iacute;ste. &amp;nbsp;&lt;/i&gt;However, there is some confusion for me over the correct use of &amp;quot;feicthe&amp;quot; vs. &amp;quot;feice&amp;aacute;il&amp;quot;, as many of the sample sentences in the dictionary are rendered into English as &amp;quot;seen&amp;quot; when using &amp;quot;feice&amp;aacute;il&amp;quot;. &amp;nbsp;I think that is more a peculiarity of Irish construction and idioms, though. &amp;nbsp;For example, &lt;i&gt;T&amp;aacute; s&amp;eacute; le feice&amp;aacute;il ag saol go...&lt;/i&gt;&amp;nbsp;is rendered into English as &amp;quot;It can easily by seen that...&amp;quot;&lt;/p&gt;
&lt;p&gt;I was a bit unclear as to what is being said in the example you gave in your opening query. &amp;nbsp;I assume it may mean &amp;quot;I have seen (Name)&amp;quot; but do you know if that is the intent? &amp;nbsp;I was not able to find any sample sentences using &amp;quot;feicthe&amp;quot;, but several with &amp;quot;feice&amp;aacute;il&amp;quot; as noted, so I don&amp;#39;t know if I can be of more help, but I would like to clarify that if possible....&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>The verb "Feic"</title><link>http://talkirish.com/forums/thread/14279.aspx</link><pubDate>Mon, 04 Apr 2016 07:40:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14279</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14279.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14279</wfw:commentRss><description>&lt;p&gt;Hello all again,&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;ve taken the liberty to changing the language setting in my phone and, probably the biggest help, Facebook into Irish as to help me by using the words on a daily basis and if I find any that I find &amp;quot;more important&amp;quot; than other phrases I look them up and decipher them. &amp;nbsp;What I&amp;#39;m having trouble with is &amp;quot;feic&amp;quot; as in &amp;quot;feicthe ag (Name)&amp;quot; in our group chat. &amp;nbsp;I&amp;#39;ve gotten to this point in breaking down: &amp;nbsp;Feic is translated to &lt;span style="text-decoration:underline;"&gt;to see&lt;/span&gt;&amp;nbsp;and is conjugated to &lt;i&gt;feicthe&lt;/i&gt;&amp;nbsp;in this sense because it falls under the category Past Participle. &amp;nbsp;Okay, that&amp;#39;s all good and gravy. &amp;nbsp;Now, not being in English in 5 years and having the last time I&amp;#39;ve had to define words such as this being even longer, I had to snoop around a little further. &amp;nbsp;Here&amp;#39;s where my confusion sets in.&lt;/p&gt;
&lt;p&gt;*Wiki definition* &amp;nbsp;Participle:&amp;nbsp;&lt;span&gt;A form of a verb&amp;nbsp;&lt;/span&gt;&lt;span&gt;that may function as an adjective&lt;/span&gt;&lt;span&gt;&amp;nbsp;or noun&lt;/span&gt;&lt;span&gt;. English&lt;/span&gt;&lt;span&gt;&amp;nbsp;has two types of participles: the present&amp;nbsp;&lt;/span&gt;&lt;span&gt;participle and the past&lt;/span&gt;&lt;span&gt;&amp;nbsp;participle.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;This is clearly in the &amp;quot;past&amp;quot; tense, also shown by the conjugation tab in&amp;nbsp;https://en.wiktionary.org/wiki/feic#Irish&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;What I&amp;#39;m having trouble on is figuring out if &lt;span style="text-decoration:underline;"&gt;feicthe&lt;/span&gt;&amp;nbsp;falls under the category of a verb that acts as an adjective or a verb that acts as a noun. &amp;nbsp;In my head, I don&amp;#39;t understand it falling under either category. &amp;nbsp;I simply see it as a verb in the past tense and that&amp;#39;s it. &amp;nbsp;Not a verbal noun, or a verbal adjective. &amp;nbsp;Just a past tense verb. &amp;nbsp;Of course, I would consider that to be true in the English language. &amp;nbsp;As far as Irish goes, the rules may change a bit. &amp;nbsp;If anyone could break this down for me and possibly give me other examples that would be so very helpful. &amp;nbsp;Thanks in advance!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Ryan&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>