<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Buntús Cainte learners</title><link>http://talkirish.com/forums/41.aspx</link><description>Are you using Buntús Cainte to learn Irish? Check out this forum where you can practice what you've learned in Buntús Cainte, ask for help or share tips on learning!</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6286.aspx</link><pubDate>Thu, 18 Nov 2010 09:13:10 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6286</guid><dc:creator>fatherandrew</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6286.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6286</wfw:commentRss><description>&lt;p&gt;Michelle,&lt;/p&gt;
&lt;p&gt;Thanks very much for your reply. &amp;nbsp;I downloaded book one but did not receive the lyrics. &amp;nbsp;Did I miss something in the download?&lt;/p&gt;
&lt;p&gt;Fr. Andrew&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6276.aspx</link><pubDate>Tue, 16 Nov 2010 12:37:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6276</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6276.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6276</wfw:commentRss><description>&lt;p&gt;Sorry for the delay in picking this up!&lt;/p&gt;
&lt;p&gt;You can purchase and download the Bunt&amp;uacute;s Cainte Vol 1 MP3 course for iPhone, iPod and iPad. It contains both the sound files and the lyrics in Irish and English, so you can learn on the go. Learn more here:&lt;/p&gt;
&lt;p&gt;&lt;a href="http://talkirish.com/irishcourse/"&gt;http://talkirish.com/irishcourse/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Download lesson 1 - a free trial - here:&lt;/p&gt;
&lt;p&gt;&lt;a href="http://talkirish.bandcamp.com/album/bunt-s-cainte-book-1"&gt;http://talkirish.bandcamp.com/album/bunt-s-cainte-book-1&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;We&amp;#39;re currently hard at work creating an MP3 course for Volumes 2 and 3, which will include the audio for download, along with the lyrics for the Irish and English text.&lt;/p&gt;
&lt;p&gt;We&amp;#39;re also creating a full online course, with new graphics, grammar tips and more. You can try the first lesson out for free here:&lt;/p&gt;
&lt;p&gt;&lt;a href="http://talkirish.com/online_irish_course/"&gt;http://talkirish.com/online_irish_course/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Beir bua,&lt;br /&gt;Michelle&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6231.aspx</link><pubDate>Thu, 04 Nov 2010 14:26:56 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6231</guid><dc:creator>fatherandrew</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6231.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6231</wfw:commentRss><description>&lt;p&gt;I have Buntus Cainte volumes 2 and 3 and would like:&lt;/p&gt;
&lt;p&gt;1. &amp;nbsp;To get a copy of BC Vol 1.&lt;/p&gt;
&lt;p&gt;2. Download the audio to 2 and 3.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Is this possible yet?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Fr. Andrew&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6162.aspx</link><pubDate>Mon, 04 Oct 2010 15:00:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6162</guid><dc:creator>Frankie</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6162.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6162</wfw:commentRss><description>&lt;p&gt;Dia duit a Michelle, been a long time since I have been around. O, t&amp;aacute; m&amp;eacute; go maith go raibh maith agat.&lt;br /&gt;Ach ... I haven&amp;#39;t had any chance to speak Irish, but always got to have your dreams, right? Lol, so I will so get a handle of it &amp;quot;one day&amp;quot;.&lt;br /&gt;&lt;br /&gt;So yeah, hope things are going well for you too Michelle. I shall visit here more often.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6154.aspx</link><pubDate>Sat, 02 Oct 2010 10:47:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6154</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6154.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6154</wfw:commentRss><description>&lt;p&gt;Go h-iontach, Frankie. T&amp;aacute; suil agam go bhfuil t&amp;uacute; go maith! &lt;/p&gt;
&lt;p&gt;Bain sult as Bunt&amp;uacute;s Cainte &lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6153.aspx</link><pubDate>Fri, 01 Oct 2010 20:20:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6153</guid><dc:creator>Frankie</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6153.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6153</wfw:commentRss><description>&lt;p&gt;This looks awesome Michelle! Thanks.&lt;br /&gt;I&amp;#39;m going to purchase it and give it a go!&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Is Buntús Cainte MP3 course available for download from the iTunes Store?</title><link>http://talkirish.com/forums/thread/6142.aspx</link><pubDate>Thu, 30 Sep 2010 10:19:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6142</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6142.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6142</wfw:commentRss><description>&lt;p&gt;&lt;span&gt;Unfortunately,
Apple&amp;#39;s restrictions on the iTunes store prevent us from offering this course
directly from iTunes. Apple doesn&amp;#39;t allow small publishers like us to publish
directly to the iTunes store. We have to go through a third-party publishing
company. And none of the third-party publishing companies we could find
supported embedding lyrics in MP3 files. So instead, you can buy and download this
course &lt;/span&gt;&lt;span&gt;&lt;a href="http://talkirish.com/irishcourse/"&gt;directly from us&lt;/a&gt;&lt;/span&gt;&lt;span&gt;!&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>