<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5865.aspx</link><pubDate>Sun, 20 Jun 2010 15:12:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5865</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5865.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5865</wfw:commentRss><description>&lt;p&gt;We have the MP3s ready to go. But we have to wait until our contracts are signed before we can release them - it&amp;#39;s a bit frustrating! But could be sorted by the end of next week *holding breath*&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Yes - pinch the banner by all means &lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5861.aspx</link><pubDate>Fri, 18 Jun 2010 12:47:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5861</guid><dc:creator>Armaghgeddon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5861.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5861</wfw:commentRss><description>&lt;p&gt;Keep forgetting to come here. Can I pinch the banner and put it on my website and so that others can come here?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Have you created the MP3? =]&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5084.aspx</link><pubDate>Wed, 14 Apr 2010 04:58:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5084</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5084.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5084</wfw:commentRss><description>&lt;p&gt;Ar fheabhas - we&amp;#39;re releasing our first mp3 Irish language course in about a month or two - can you wait? I highly recommend it &lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5083.aspx</link><pubDate>Tue, 13 Apr 2010 20:38:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5083</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5083.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5083</wfw:commentRss><description>&lt;p&gt;T&amp;aacute; m&amp;eacute; go maith.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5082.aspx</link><pubDate>Tue, 13 Apr 2010 20:36:05 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5082</guid><dc:creator>Armaghgeddon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5082.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5082</wfw:commentRss><description>&lt;p&gt;Dia dhuit Cianaigh,&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thanks for that. I found the Liam &amp;Oacute; Maonla&amp;iacute; one earlier. Its helping. Its just remembering the fadas for the words.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Conas t&amp;aacute; t&amp;uacute;?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5081.aspx</link><pubDate>Tue, 13 Apr 2010 20:32:54 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5081</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5081.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5081</wfw:commentRss><description>&lt;p&gt;You&amp;nbsp;could try &lt;a target="_blank" href="http://www.byki.com/fls/free-irish-software-download.html?l=irish"&gt;BKYI &lt;/a&gt;for some basic words both free and paid versions are&amp;nbsp;available.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;
&lt;p&gt;From the links page on this site. The BBC:&amp;nbsp;&lt;a target="_blank" href="http://www.bbc.co.uk/northernireland/irish/blas/learners/beag1/lesson1.shtml"&gt;Giota Beag&lt;/a&gt;&amp;nbsp;(&amp;#39;a wee bit&amp;#39;) is a free audio course for Irish language beginners. Then try&amp;nbsp;&lt;a target="_blank" href="http://www.bbc.co.uk/northernireland/irish/blas/learners/beag2/lesson1.shtml"&gt;Beag Eile&lt;/a&gt;&amp;nbsp;- &amp;#39;another wee bit&amp;#39;. Check out&amp;nbsp;&lt;a target="_blank" href="http://www.bbc.co.uk/northernireland/schools/gcsebitesize/irish"&gt;Bitesize Irish&lt;/a&gt;&amp;nbsp;for resources that support the GCSE curriculum. Visit&amp;nbsp;&lt;a target="_blank" href="http://www.bbc.co.uk/northernireland/colinandcumberland"&gt;Colin and Cumberland&lt;/a&gt;&amp;nbsp;for adult learner resources.&lt;/p&gt;
&lt;p&gt;Download a&amp;nbsp;&lt;a target="_blank" href="http://www.independent.ie/education/features/learn-irish-with-liam-o-maonlai-692551.html"&gt;free Irish language audio course&lt;/a&gt;&amp;nbsp;with PDF support, narrated by Liam &amp;Oacute; Maonla&amp;iacute;.&lt;/p&gt;
&lt;/p&gt;
&lt;td&gt;&lt;br /&gt;&lt;/td&gt;
&lt;td&gt;&lt;br /&gt;&lt;/td&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5078.aspx</link><pubDate>Tue, 13 Apr 2010 10:14:33 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5078</guid><dc:creator>Armaghgeddon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5078.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5078</wfw:commentRss><description>&lt;p&gt;Possibly something I can put on MP3 player =]&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Back again.</title><link>http://talkirish.com/forums/thread/5076.aspx</link><pubDate>Tue, 13 Apr 2010 06:23:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5076</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5076.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5076</wfw:commentRss><description>&lt;p&gt;What do you want? Face to face? Online? Mobile? Printed? &lt;/p&gt;
&lt;p&gt;Got an iPhone? Try http://talkirish.com/forums/p/3155/5047.aspx#5047 - basic but good for getting your ear around the (southern) accent.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Back again.</title><link>http://talkirish.com/forums/thread/5074.aspx</link><pubDate>Mon, 12 Apr 2010 17:13:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5074</guid><dc:creator>Armaghgeddon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5074.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5074</wfw:commentRss><description>&lt;p&gt;Hello everyone, how are you all.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Decided that now summer is around the corner and having a 16 week summer break from university, Ive decided to try and learn Irish again.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Any programs that would be useful?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>