<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Buntús Cainte learners</title><link>http://talkirish.com/forums/41.aspx</link><description>Are you using Buntús Cainte to learn Irish? Check out this forum where you can practice what you've learned in Buntús Cainte, ask for help or share tips on learning!</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/9517.aspx</link><pubDate>Tue, 24 Sep 2013 02:36:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9517</guid><dc:creator>tanyacoleman</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9517.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=9517</wfw:commentRss><description>&lt;p&gt;I guess it is okay to use with certain Android devices.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/8126.aspx</link><pubDate>Tue, 05 Mar 2013 22:28:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8126</guid><dc:creator>JennyL</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8126.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=8126</wfw:commentRss><description>&lt;p&gt;Hi&lt;/p&gt;
&lt;p&gt;RE:&amp;nbsp; Android Device:&amp;nbsp; NEXUS 7 Google &amp;#39;mini&amp;#39; pad &lt;/p&gt;
&lt;p&gt;As mentioned, using the JukeBox app, the Nexus 7 Google mini Android pad has a specific music player called N7 player which you can download and then display the lyrics.&amp;nbsp; When you are &amp;#39;playing&amp;#39; a lesson, just press down for a few seconds over the lesson and a &amp;#39;show lyrics&amp;#39; option will appear.&amp;nbsp; There is a free test app to download for two weeks and then it only costs a few dollars from the Google Play store.&amp;nbsp; I didn&amp;#39;t use JukeBox as it didn&amp;#39;t list my device.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/6155.aspx</link><pubDate>Sat, 02 Oct 2010 16:28:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6155</guid><dc:creator>mehdi</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6155.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6155</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;Using the&amp;nbsp;Bunt&amp;uacute;s Cainte MP3 Course on a Nokia smartphone (e.g. Nokia 5800 or Nokia N97)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;As Michelle mentioned above, the built-in MP3 player on Nokia smartphone can&amp;#39;t display the lyrics embedded in MP3 files. This means that you won&amp;#39;t be able to read the Irish and English translations while listening to the audio course.&lt;/p&gt;
&lt;p&gt;Fortunately, there is a third-party MP3 player you can install on your phone that will let you do that. It&amp;#39;s called LCG Jukebox and you can get it here:&amp;nbsp;&lt;a href="http://www.lonelycatgames.com/?app=lcgjukebox"&gt;http://www.lonelycatgames.com/?app=lcgjukebox&lt;/a&gt;&amp;nbsp;(use the Symbian download link on the left-hand side to download the trial version).&lt;/p&gt;
&lt;p&gt;I&amp;#39;ve tried it on my Nokia 5800 and it works fine. Once a&amp;nbsp;Bunt&amp;uacute;s Cainte lesson is playing, tap the small pen icon to display the Irish and English translation. The pen icon is really tiny so you might need to use the stylus to get to it but once the lyrics are displayed, you can scroll easily with your finger. Here are a couple of screenshots:&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;img src="http://talkirish.com/resized-image.ashx/__size/180x320/__key/CommunityServer.Components.UserFiles/00.00.00.21.08/Scr000002.jpg" alt="" /&gt;&amp;nbsp;&lt;img src="http://talkirish.com/resized-image.ashx/__size/180x320/__key/CommunityServer.Components.UserFiles/00.00.00.21.08/Scr000003.jpg" alt="" /&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;It&amp;#39;s not the prettiest application ever but it does the job. Note that it&amp;#39;s not free - it costs $19.50. There&amp;#39;s a free trial however.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;LCG also have an Android and a Windows Mobile version of this MP3 player. So if you have an Android or Windows Mobile smartphone, you could give it a try to get&amp;nbsp;Bunt&amp;uacute;s Cainte working on your phone.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/6151.aspx</link><pubDate>Fri, 01 Oct 2010 10:54:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6151</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6151.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6151</wfw:commentRss><description>&lt;p&gt;Zeldor, a chara,&lt;/p&gt;
&lt;p&gt;Go raibh maith agat as an t-eolas! I&amp;#39;ll pass this information on to the Android owners who&amp;#39;ve been emailing me.&lt;/p&gt;
&lt;p&gt;You&amp;#39;re right - you have to manually scroll to the lyrics on the iPhone, iPad or iPod.&lt;/p&gt;
&lt;p&gt;Hope a few other Android owners will download this and let us know how they get on.&lt;/p&gt;
&lt;p&gt;Sl&amp;aacute;n anois,&lt;/p&gt;
&lt;p&gt;Michelle&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/6150.aspx</link><pubDate>Fri, 01 Oct 2010 09:39:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6150</guid><dc:creator>zeldor</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6150.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6150</wfw:commentRss><description>&lt;p&gt;the astro player mp3 player shows lyrics on the android phone.&lt;/p&gt;
&lt;p&gt;It doesnt &amp;quot;follow along&amp;quot; as the music plays, but then Im not sure your&lt;/p&gt;
&lt;p&gt;iphone app does either but at least the words are there to scroll&lt;/p&gt;
&lt;p&gt;through as it plays.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Does our new Buntús Cainte course work on MP3 players and smartphones other than Apple's, such as Android or Nokia?</title><link>http://talkirish.com/forums/thread/6143.aspx</link><pubDate>Thu, 30 Sep 2010 10:22:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6143</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6143.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=6143</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;As long as your MP3 player or smartphone can display lyrics embedded in
MP3 files while playing the audio (this is how you can read the Irish and
English translation while listening to the audio course), our Bunt&amp;uacute;s Cainte
course will work. &lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;Unfortunately, the built-in MP3 players in Android and Nokia
smartphones don&amp;#39;t support embedded lyrics. There might be third-party MP3
players you can install on your phone that have this functionality. We&amp;#39;ll start checking these out when we get a moment, and we&amp;#39;ll post our findings here.&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;If you&amp;#39;re unsure whether your MP3 player or smartphone can display
lyrics embedded in MP3 files, you can &lt;a href="http://talkirish.bandcamp.com/"&gt;download the first lesson of our course *FOR FREE* from our bandcamp page&lt;/a&gt; and try it out. &lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;strong&gt;Let other learners know if it works on your device by posting a message
in this thread!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>