<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Filíocht</title><link>http://talkirish.com/forums/thread/17618.aspx</link><pubDate>Mon, 25 Feb 2019 19:01:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17618</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17618.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17618</wfw:commentRss><description>&lt;p&gt;Tuigim.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Filíocht</title><link>http://talkirish.com/forums/thread/17617.aspx</link><pubDate>Mon, 25 Feb 2019 03:23:13 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17617</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17617.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17617</wfw:commentRss><description>&lt;p&gt;A Laura,&lt;/p&gt;
&lt;p&gt;Is fior &amp;eacute; seo, is docha,&lt;/p&gt;
&lt;p&gt;Deir mise, iarraim ag feice&amp;aacute;il na focail&amp;iacute; i fhocl&amp;oacute;ir ar line.&lt;/p&gt;
&lt;p&gt;T&amp;aacute;im ag foghlaim focail eile leis an Duolingo, agus l&amp;eacute;im mo leabhar as Gaeilge nuair is f&amp;eacute;idir m&amp;eacute;....&lt;/p&gt;
&lt;p&gt;T&amp;aacute; tr&amp;iacute; leabhair as Gaeilge agam, n&amp;oacute; ceathair, le mBunreacht na h&amp;Eacute;ireann, ach t&amp;aacute; s&amp;eacute; l&amp;eacute;amh tirim.&lt;/p&gt;
&lt;p&gt;Na leabhair at&amp;aacute; agam:&lt;/p&gt;
&lt;p&gt;Tora&amp;iacute;ocht Diarmaid agus Grainne&lt;/p&gt;
&lt;p&gt;An Gr&amp;aacute; agus an Ghruaim&lt;/p&gt;
&lt;p&gt;An Prionsa Beag&lt;/p&gt;
&lt;p&gt;Is maith liom An Prionsa Beag mar n&amp;iacute;l s&amp;eacute; deacair.&amp;nbsp; T&amp;aacute; na &amp;eacute;ile aimhr&amp;eacute;iteach.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; suil agam go thuigeann t&amp;uacute; mo scr&amp;iacute;obh seo.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Filíocht</title><link>http://talkirish.com/forums/thread/17615.aspx</link><pubDate>Sat, 23 Feb 2019 13:55:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17615</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17615.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17615</wfw:commentRss><description>&lt;p&gt;N&amp;iacute; scr&amp;iacute;obhann duine ar bith i nGaeilge&lt;/p&gt;
&lt;p&gt;Ar an cl&amp;aacute;r teachtaireachta&amp;iacute; ar l&amp;iacute;ne seo&lt;/p&gt;
&lt;p&gt;N&amp;iacute; thuigeann aon duine an teanga&lt;/p&gt;
&lt;p&gt;C&amp;eacute; is moite d&amp;#39;&amp;Aacute;r Tiarna.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>