<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Gearrscannán as Gaeilge</title><link>http://talkirish.com/forums/thread/3358.aspx</link><pubDate>Thu, 02 Jul 2009 05:34:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3358</guid><dc:creator>Caomhánach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/3358.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=3358</wfw:commentRss><description>&lt;p&gt;Br&amp;oacute;n orm faoi mo nasc briste agus go raibh maith agat Cianaigh a chara. The one I was trying to link to was Fluent dysphasia &lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Gearrscannán as Gaeilge</title><link>http://talkirish.com/forums/thread/3357.aspx</link><pubDate>Wed, 01 Jul 2009 20:21:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3357</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/3357.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=3357</wfw:commentRss><description>&lt;p&gt;Tried to follow the link and got this:&lt;/p&gt;
&lt;div id="content"&gt;
&lt;h2&gt;Sorry, there was a problem with your last request!&lt;/h2&gt;
&lt;p&gt;Either the site is offline or an unhandled error occurred. We
apologize and have logged the error. Please try your request again or
if you know who your site administrator is let them know too.&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;But by going to youtube.com and searching for Gearrscann&amp;aacute;n as Gaeilge I came up with four hits here are three of them&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;ol&gt;
&lt;li&gt;&lt;a target="_blank" title="Fluent dysphasia" href="http://www.youtube.com/watch?v=zNI9eBGYpvw"&gt;Fluent dysphasia&amp;nbsp;&amp;nbsp; http://www.youtube.com/watch?v=zNI9eBGYpvw&lt;br /&gt;&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a target="_blank" title="Fluent dysphasia part 2" href="http://www.youtube.com/watch?v=_OlrG9WF2dU"&gt;Fluent dysphasia part 2&amp;nbsp;&amp;nbsp; http://www.youtube.com/watch?v=_OlrG9WF2dU&lt;br /&gt;&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a target="_blank" title="T&amp;iacute;r Gan Teanga" href="http://www.youtube.com/watch?v=b2WpwsgURf4"&gt;T&amp;iacute;r Gan Teanga&lt;/a&gt;&amp;nbsp;&amp;nbsp; &lt;a target="_blank" href="http://www.youtube.com/watch?v=b2WpwsgURf4"&gt;http://www.youtube.com/watch?v=b2WpwsgURf4&lt;/a&gt;&lt;/li&gt;
&lt;/ol&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Gearrscannán as Gaeilge</title><link>http://talkirish.com/forums/thread/3356.aspx</link><pubDate>Wed, 01 Jul 2009 07:12:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3356</guid><dc:creator>Caomhánach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/3356.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=3356</wfw:commentRss><description>&lt;p&gt;&lt;a target="_self" href="http://talkirish.com/forums/EditPost.aspx/"&gt;http://www.youtube.com/watch?v=zNI9eBGYpvw&amp;amp;feature=related&lt;/a&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>