<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: De and na</title><link>http://talkirish.com/forums/thread/17708.aspx</link><pubDate>Tue, 06 Aug 2019 16:42:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17708</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17708.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17708</wfw:commentRss><description>&lt;p&gt;Hi Charlotte,&lt;/p&gt;
&lt;p&gt;Firstly, this is more of a learner&amp;#39;s site and less of a translation service, but where we know what we&amp;#39;re talking about, we&amp;#39;re happy to help.&lt;/p&gt;
&lt;p&gt;Next, the phrase you are using incorporates what is known as the &amp;quot;genetive&amp;quot; case of the noun &amp;quot;freedom&amp;quot;, and the genetive case, in turn, generally incorporates the term &amp;quot;of&amp;quot; into the noun itself.&amp;nbsp; The literal translation of &amp;quot;saol na saoirse&amp;quot; is &amp;quot;the life of freedom&amp;quot;; &amp;quot;na&amp;quot; being the genetive form of the definite article, and when used in this way it goes between the terms being connected.&amp;nbsp; The genetive case denotes a form of possession, expressed by &amp;quot;of&amp;quot; and combines the two words into a single one.&amp;nbsp; It is, as I understand it, correct Irish phraseology to write it this way, even if the phrase you want in English would not use the definite article. so whether you mean to say &amp;quot;the life of freedom&amp;quot; or &amp;quot;a life of freedom&amp;quot; or &amp;quot;life of freedom&amp;quot; it would all be the same, at least I think so.&lt;/p&gt;
&lt;p&gt;If you want a more definitive take on this, you could try going to the Irish Language Forum&amp;nbsp;http://irishlanguageforum.com/.&amp;nbsp; There you will find people much more conversant in the language, and their responses would be much more reliable.&amp;nbsp; Be sure to specify whether you mean to say &amp;quot;life of freedom&amp;quot;, &amp;quot;a life of freedom&amp;quot; or &amp;quot;the life of freedom&amp;quot;, or ask if there would be any differentiation in how any of those would be constructed.&lt;/p&gt;
&lt;p&gt;Good luck!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>De and na</title><link>http://talkirish.com/forums/thread/17707.aspx</link><pubDate>Mon, 05 Aug 2019 16:22:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17707</guid><dc:creator>Charlotte66</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17707.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17707</wfw:commentRss><description>&lt;p&gt;Hi I&amp;rsquo;m trying to write a short story in Irish and have found a difficulty understanding where and when de and na are used.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I specifically incorporated the phrase life of freedom into my story and can&amp;rsquo;t establish whether it&amp;rsquo;s saol na saoirse or saol de saoirse, and how that works&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thanks.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Charlotte&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>