<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Seanfhocail Inquiry: Facta, non verba</title><link>http://talkirish.com/forums/thread/7173.aspx</link><pubDate>Mon, 13 Feb 2012 15:12:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7173</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7173.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=7173</wfw:commentRss><description>&lt;p&gt;Christin,&lt;/p&gt;
&lt;p&gt;When writing the seanfhocal an lae posts I tried really hard to group them, but it proved nightmarish, so I&amp;#39;m afraid I gave up. I found that I started with broad categorisation like Love, Money, Health, but that these soon disintegrated, and often depended on interpretation too. Be great if you could share some of your research findings with us here on the site in due course.&lt;/p&gt;
&lt;p&gt;&amp;Aacute;dh m&amp;oacute;r ort,&lt;br /&gt;Michelle&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Seanfhocail Inquiry: Facta, non verba</title><link>http://talkirish.com/forums/thread/7152.aspx</link><pubDate>Sun, 05 Feb 2012 19:41:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7152</guid><dc:creator>cmulliga</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7152.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=7152</wfw:commentRss><description>&lt;p&gt;GRMMA, Seano. &amp;nbsp;&lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;CM&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Seanfhocail Inquiry: Facta, non verba</title><link>http://talkirish.com/forums/thread/7150.aspx</link><pubDate>Sun, 05 Feb 2012 12:26:06 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7150</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7150.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=7150</wfw:commentRss><description>&lt;p&gt;Hi Christin, Sorry, I can&amp;#39;t really help with the search terms for proverbs but I can certainly help you with facta non verba - n&amp;iacute; briathar a dhearbha&amp;iacute;os ach beart. (Not a word which proves but an action)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Seanfhocail Inquiry: Facta, non verba</title><link>http://talkirish.com/forums/thread/7147.aspx</link><pubDate>Sat, 04 Feb 2012 12:14:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7147</guid><dc:creator>cmulliga</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7147.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=7147</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;blockquote&gt;Hi, I&amp;#39;m new to your site, and I&amp;#39;m doing some research on oral/internet transmission Irish proverbs for a chapter of my dissertation/thesis. &amp;nbsp;First of all, I was wondering if there was any way I could view seanfhocal-an-lae posts by topic/hash tag re: subject/meaning as opposed to date, and second of all, I was wondering if there were any good Irish equivalents to Facta, non verba---deeds, not words. &lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/blockquote&gt;
&lt;blockquote&gt;GRMMA,&lt;/blockquote&gt;
&lt;blockquote&gt;Christin Mulligan&lt;/blockquote&gt;
&lt;blockquote&gt;Ph.D Candidate/Teaching Fellow&lt;/blockquote&gt;
&lt;blockquote&gt;UNC-Chapel Hill&lt;/blockquote&gt;
&lt;blockquote&gt;&lt;br /&gt;&lt;/blockquote&gt;
&lt;blockquote&gt;&lt;br /&gt;&lt;/blockquote&gt;
&lt;div&gt;&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>