<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Series of 5 fantastic Irish Language Video shorts in our Video Gallery!</title><link>http://talkirish.com/forums/thread/7271.aspx</link><pubDate>Thu, 15 Mar 2012 00:44:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7271</guid><dc:creator>inahbeeler</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7271.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7271</wfw:commentRss><description>&lt;p&gt;Thank You for Sharing this one!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Series of 5 fantastic Irish Language Video shorts in our Video Gallery!</title><link>http://talkirish.com/forums/thread/7088.aspx</link><pubDate>Wed, 18 Jan 2012 02:18:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7088</guid><dc:creator>oneoneeight</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7088.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7088</wfw:commentRss><description>&lt;p&gt;That&amp;#39;s fantastic, thanks a lot for that.&lt;/p&gt;
&lt;p&gt;sl&amp;aacute;inte&lt;span&gt;!&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;__________________________________________________________________&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Series of 5 fantastic Irish Language Video shorts in our Video Gallery!</title><link>http://talkirish.com/forums/thread/6779.aspx</link><pubDate>Wed, 17 Aug 2011 11:26:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6779</guid><dc:creator>Halbarad</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6779.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6779</wfw:commentRss><description>&lt;p&gt;Thanks so much! Will have a look at it!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Series of 5 fantastic Irish Language Video shorts in our Video Gallery!</title><link>http://talkirish.com/forums/thread/6777.aspx</link><pubDate>Tue, 16 Aug 2011 10:29:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6777</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6777.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6777</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;Check out the series of 5 fantastic video interviews with local Irish talent in our video gallery! Interviews include:&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;The talented &amp;Eacute;amonn &amp;Oacute; Cath&amp;aacute;in (@culabula)
answering &lt;b&gt;Na Ceithre Ceist&lt;/b&gt; - Four Questions &lt;br /&gt;&lt;a href="http://talkirish.com/media/p/6711.aspx"&gt;&lt;span&gt;http://talkirish.com/media/p/6711.aspx&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;Seacht Actor Neasa N&amp;iacute; Chunaigh describing &lt;b&gt;Saol an Aisteora&lt;/b&gt; - An
Actor&amp;#39;s Life&lt;br /&gt;&lt;a href="http://talkirish.com/media/p/6710.aspx"&gt;&lt;span&gt;http://talkirish.com/media/p/6710.aspx&lt;/span&gt;&lt;/a&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;&lt;span&gt;Presenter, actor and editor D&amp;oacute;nall Mac Giolla Ch&amp;oacute;ill discussing &lt;b&gt;T&amp;aacute;bhacht Na Gaeilge&lt;/b&gt; - The Importance of Irish&lt;br /&gt;&lt;/span&gt;&lt;a href="http://talkirish.com/media/p/6709.aspx"&gt;&lt;span&gt;http://talkirish.com/media/p/6709.aspx&lt;/span&gt;&lt;/a&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;Poet and academic Se&amp;aacute;n &amp;Oacute; D&amp;uacute;rois talking about &lt;b&gt;M&amp;eacute; f&amp;eacute;in, an
Ghaeilge agus an fhil&amp;iacute;ocht&lt;/b&gt; &amp;ndash; himself, the Irish language and poetry. &lt;br /&gt;&lt;a href="http://talkirish.com/media/p/6521.aspx"&gt;&lt;span&gt;http://talkirish.com/media/p/6521.aspx&lt;/span&gt;&lt;/a&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;Irish language teacher Elaine N&amp;iacute; Bhraon&amp;aacute;in describes her life in&lt;b&gt; Nua
Eabhrac, Nua Eabhrac&lt;/b&gt; &lt;br /&gt;&lt;a href="http://talkirish.com/media/p/6239.aspx"&gt;&lt;span&gt;http://talkirish.com/media/p/6239.aspx&lt;/span&gt;&lt;/a&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNoSpacing"&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>