<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Galway Bay - cannot translate some words</title><link>http://talkirish.com/forums/thread/16485.aspx</link><pubDate>Tue, 26 Sep 2017 02:44:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16485</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16485.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16485</wfw:commentRss><description>&lt;p&gt;Gars&amp;uacute;n means boy. Then what Dale said about the praties. O&amp;#39;re would be over, yes.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Galway Bay - cannot translate some words</title><link>http://talkirish.com/forums/thread/16484.aspx</link><pubDate>Sat, 23 Sep 2017 16:39:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16484</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16484.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16484</wfw:commentRss><description>&lt;p&gt;Hello, amia.&lt;/p&gt;
&lt;p&gt;The translations you are requesting are not Irish per se, but more Hyberno-English (English as spoken by an Irish person).&lt;/p&gt;
&lt;p&gt;&amp;quot;praties&amp;quot; is probably a reference to potatoes, which are &amp;quot;prata&amp;quot; in the Irish language, and the plural is &amp;quot;prata&amp;iacute;&amp;quot; pronounced &amp;quot; praw-tee&amp;quot; so the hyberno-English would add an &amp;quot;s&amp;quot; to it to make it agree with English grammar.&lt;/p&gt;
&lt;p&gt;I am unsure about &amp;quot;gossoms&amp;quot;.&lt;/p&gt;
&lt;p&gt;The contraction &amp;quot;o&amp;#39;er&amp;quot; is a standard poetic contraction for &amp;quot;over&amp;quot; and is not Hiberno-English, but a common form used by English poets for hundreds of years.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I hope that helps you a little.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Galway Bay - cannot translate some words</title><link>http://talkirish.com/forums/thread/16483.aspx</link><pubDate>Sat, 23 Sep 2017 14:30:35 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16483</guid><dc:creator>amia</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16483.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16483</wfw:commentRss><description>&lt;p&gt;Hello,&lt;/p&gt;
&lt;p&gt;I&amp;#39;m going to learn a traditionnal song from Dr. Arthur Colahan : Galway Bay.&lt;/p&gt;
&lt;p&gt;There some words I cannot translate. Can you help me ?&lt;/p&gt;
&lt;p&gt;upland diggin&amp;#39; praties. I cannot translate &amp;quot;praties&amp;quot; ?&lt;/p&gt;
&lt;p&gt;barefoot gossoms. Is it like &amp;quot;children&amp;quot; ?&lt;/p&gt;
&lt;p&gt;breezes blowing o&amp;#39;re the sea of Ireland. Is o&amp;#39;re = over ?&lt;/p&gt;
&lt;p&gt;Thanks in advance !&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>