<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Need Help.  How would you say a Courageous Dancing Fox?</title><link>http://talkirish.com/forums/thread/14331.aspx</link><pubDate>Fri, 10 Jun 2016 16:47:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14331</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14331.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14331</wfw:commentRss><description>&lt;p&gt;F&amp;aacute;ilte romhat, a Natasha!&lt;/p&gt;
&lt;p&gt;The only place I had seen &amp;quot;madra rua&amp;quot; employed, in my limited experience, was in the book &amp;quot;An Prionsa Beag&amp;quot; (The Little Prince), translated by Breand&amp;aacute;n &amp;Oacute; Doibhlin. &amp;nbsp;The &amp;quot;fox&amp;quot; is a pivotal character in that story, and I had seen the term previously. &amp;nbsp;I was not aware of the alternative term &amp;quot;sionnach&amp;quot; until your inquiry, so we have both learned from each other! &amp;nbsp;Of course, that&amp;#39;s what this forum is all about....&lt;/p&gt;
&lt;p&gt;Sl&amp;aacute;n!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Need Help.  How would you say a Courageous Dancing Fox?</title><link>http://talkirish.com/forums/thread/14330.aspx</link><pubDate>Fri, 10 Jun 2016 12:29:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14330</guid><dc:creator>thedancingirish</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14330.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14330</wfw:commentRss><description>&lt;p id="docs-internal-guid-5e9d86c8-3a46-86d9-a0e5-c4c0dc36c308" dir="ltr"&gt;&lt;span&gt;Thank you so much that is very helpful. I am excited to include language in my school, but it will be a long journey as I still need to grow myself.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p dir="ltr"&gt;&lt;span&gt;I had seen the &amp;quot;madra rua&amp;quot; &amp;nbsp;and I love the symbology of a red fox. I wasn&amp;#39;t sure it would be a good version of fox to use since I see it associated with pubs and a news journal.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p dir="ltr"&gt;&lt;span&gt;Go raibh maith agat,&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Natasha H&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Need Help.  How would you say a Courageous Dancing Fox?</title><link>http://talkirish.com/forums/thread/14328.aspx</link><pubDate>Fri, 10 Jun 2016 08:59:35 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14328</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14328.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14328</wfw:commentRss><description>&lt;p&gt;Haigh, thedancingirish.&lt;/p&gt;
&lt;p&gt;Misneach = courage, which is a noun; what you want is the adjective form &amp;quot;courageous&amp;quot; which is &amp;quot;misni&amp;uacute;il&amp;quot;.&lt;/p&gt;
&lt;p&gt;In Irish, adjectives generally follow the noun they modify, so &amp;quot;Sionnach Misni&amp;uacute;il&amp;quot; would be &amp;quot;a courageous fox.&lt;/p&gt;
&lt;p&gt;So I would tentatively render it &amp;quot;An Sionnach Misni&amp;uacute;il Damhsa&amp;quot; &lt;i&gt;The Courageous Dancing Fox&lt;/i&gt;.&lt;/p&gt;
&lt;p&gt;There is another term for &amp;quot;fox&amp;quot; -- &amp;quot;madra rua&amp;quot;, literally &amp;quot;red-haired dog&amp;quot; but it is a term used in literature for fox. &amp;nbsp;It might be a bit more cumbersome to use in this case, and you may not have in mind a red-haired fox, but rather a grey fox or whatever other variety, but just in case you are interested....&lt;/p&gt;
&lt;p&gt;Disclaimer: &amp;nbsp;I am not a native Irish speaker, and consider myself a learner, so I may be mistaken. &amp;nbsp;I would advise you to wait a bit and see if anyone else confirms my construct before using it for an official licensing purchase.&lt;/p&gt;
&lt;p&gt;Sl&amp;aacute;n!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Need Help.  How would you say a Courageous Dancing Fox?</title><link>http://talkirish.com/forums/thread/14327.aspx</link><pubDate>Thu, 09 Jun 2016 17:42:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14327</guid><dc:creator>thedancingirish</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14327.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14327</wfw:commentRss><description>&lt;p&gt;I have reciently received my Irish Dance Certification and would like to have a creative name for my school. There are schools with the name &lt;span id="docs-internal-guid-cd782c9f-3639-acbc-bd56-4fee534cf186" style="font-size:13.333333333333332px;font-family:Arial;color:#212121;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;"&gt;an sionnach. I was thinking something like Misneach Sionnach Damhsa. I don&amp;#39;t know anything about gramer and wanted some advice before purchasing licensing. Let me know your thoughs?&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>