<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>A quotation from an Irish poem for a headstone</title><link>http://talkirish.com/forums/thread/11245.aspx</link><pubDate>Fri, 30 May 2014 10:02:43 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11245</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11245.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11245</wfw:commentRss><description>&lt;p&gt;&lt;span&gt;We recently received a request for information on a poem about Timoleague in West Cork (Tig Molaige in Irish) for a headstone carving.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;I think this is the poem. It was written in the early 19th century by Se&amp;aacute;n &amp;Oacute; Coile&amp;aacute;in and it&amp;rsquo;s called Machnamh an Duine Dhoil&amp;iacute;osaigh (the Contemplation of the Sorrowful Man). It is subtitled a lament on the Friary of Timoleague.&lt;/p&gt;
&lt;p&gt;&lt;b&gt;MACHNAMH AN DUINE DHOIL&amp;Iacute;OSAIGH&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;(CAOINEADH AR MHAINISTIR THlGH MOLAIGE)&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;le Se&amp;aacute;n &amp;Oacute; Coile&amp;aacute;in&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;O&amp;iacute;che dhom go doiligh, dubhach&lt;/p&gt;
&lt;p&gt;Cois fharraige na dtonn dtr&amp;eacute;an&lt;/p&gt;
&lt;p&gt;Ag l&amp;eacute;ir-smaoineadh is ag lua&lt;/p&gt;
&lt;p&gt;Ar chora chrua an tsaoil&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; an r&amp;eacute; is na r&amp;eacute;alta suas,&lt;/p&gt;
&lt;p&gt;N&amp;iacute;or chlos fuaim toinne n&amp;aacute; tr&amp;aacute;,&lt;/p&gt;
&lt;p&gt;Is n&amp;iacute; raibh gal ann den ghaoth&lt;/p&gt;
&lt;p&gt;Do chroithfeadh barr crainn n&amp;aacute; blath.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Do ghluaiseas ag machnamh im aon&lt;/p&gt;
&lt;p&gt;Gan aire ar raon mo shi&amp;uacute;il,&lt;/p&gt;
&lt;p&gt;Doras cille gur dhearc m&amp;eacute;&lt;/p&gt;
&lt;p&gt;&amp;#39;San gconair r&amp;eacute;idh ar mo chionn.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Do stad m&amp;eacute; sa doras sean&lt;/p&gt;
&lt;p&gt;&amp;#39;Nar ghn&amp;aacute;th almsana is aos&lt;/p&gt;
&lt;p&gt;D&amp;aacute; nd&amp;aacute;il don lobhar is don lag&lt;/p&gt;
&lt;p&gt;An tr&amp;aacute;th do mhair lucht an t&amp;iacute;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; foradh fiar ar a thaobh,&lt;/p&gt;
&lt;p&gt;Is cian &amp;oacute; cuireadh a chl&amp;oacute; -&lt;/p&gt;
&lt;p&gt;Ar a suiodh saoithe is cliar&lt;/p&gt;
&lt;p&gt;Is taisteala&amp;iacute; thriallta an r&amp;oacute;id.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Sonn do bh&amp;iacute;odh cloig agus cliar,&lt;/p&gt;
&lt;p&gt;Dr&amp;eacute;achta is diagacht d&amp;aacute; l&amp;eacute;amh,&lt;/p&gt;
&lt;p&gt;C&amp;oacute;ra&amp;iacute;ceatal agus ceol&lt;/p&gt;
&lt;p&gt;Ag moladh m&amp;oacute;rgacht D&amp;eacute;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Do bh&amp;iacute;os-sa f&amp;eacute;in sona seal,&lt;/p&gt;
&lt;p&gt;Faraoir! Do chlaochlaigh mo chl&amp;oacute;;&lt;/p&gt;
&lt;p&gt;Th&amp;aacute;inig t&amp;oacute;ir an tsaoil i m&amp;rsquo;aghaidh&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l feidhm orm ach br&amp;oacute;n.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;It is a nice little poem, though rather bleak and sad. It has been compared to Grey&amp;rsquo;s Elegy, which was probably an influence on the poet. There are several translations of it in English by people like Furlong and James Clarence Mangan, though none of them is very close or accurate. Three of them are available on an online corpus called CELT. I don&amp;rsquo;t know if much of this poem would be suitable for an epitaph, except the last verse, which is striking in the original (my translation doesn&amp;rsquo;t do it justice, I&amp;rsquo;m afraid):&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Do bh&amp;iacute;os-sa f&amp;eacute;in sona seal,&lt;/p&gt;
&lt;p&gt;Faraoir! Do chlaochlaigh mo chl&amp;oacute;;&lt;/p&gt;
&lt;p&gt;Th&amp;aacute;inig t&amp;oacute;ir an tsaoil i m&amp;rsquo;aghaidh&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l feidhm orm ach br&amp;oacute;n.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I myself was once happy a while&lt;/p&gt;
&lt;p&gt;Alas, but I have changed.&lt;/p&gt;
&lt;p&gt;The world&amp;rsquo;s chase has turned against me,&lt;/p&gt;
&lt;p&gt;All I can do is lament.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I hope that this is a help to you. My commiserations to you on behalf of all of us on TalkIrish. N&amp;iacute; maith linn bhur mbris.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>