<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Is anyone else tired of typing sl(alt+130)n go fo(alt+161)ll instead of slán go foíll?</title><link>http://talkirish.com/forums/thread/7713.aspx</link><pubDate>Thu, 06 Sep 2012 11:29:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7713</guid><dc:creator>Sinéad6</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7713.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7713</wfw:commentRss><description>&lt;p&gt;I just hold ALT GR key and letter at the same time.&amp;aacute;,&amp;eacute;,&amp;iacute;,&amp;oacute;,&amp;uacute;.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is anyone else tired of typing sl(alt+130)n go fo(alt+161)ll instead of slán go foíll?</title><link>http://talkirish.com/forums/thread/7710.aspx</link><pubDate>Fri, 31 Aug 2012 00:42:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7710</guid><dc:creator>caseydillon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7710.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7710</wfw:commentRss><description>&lt;p&gt;Also, maybe you type full words out but I tend to type with a lot of abbreviations. Partially to save time and partially to confuse Google Translaters.&lt;/p&gt;
&lt;p&gt;So using your method I couldn&amp;#39;t easily write, for example, &amp;quot;M&amp;#39;athair&amp;quot; because it would be rendered (somewhat confusingly) &amp;quot;M&amp;aacute;thair&amp;quot;.&lt;/p&gt;
&lt;p&gt;Obviously if that doesn&amp;#39;t bother you, it&amp;#39;s not a problem but it may be a problem for some!&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is anyone else tired of typing sl(alt+130)n go fo(alt+161)ll instead of slán go foíll?</title><link>http://talkirish.com/forums/thread/7709.aspx</link><pubDate>Fri, 31 Aug 2012 00:33:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7709</guid><dc:creator>caseydillon</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7709.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7709</wfw:commentRss><description>&lt;p&gt;If Michelle&amp;#39;s advice doesn&amp;#39;t help, try fiddling with the language your keyboard is set to.&lt;br /&gt;Mine is set to Irish and the only difference between that setting and the British English setting is that fadas are alt+[vowel required] in Irish. &amp;nbsp;Whether it&amp;#39;s very different to American English keyboards I couldn&amp;#39;t say though.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Is anyone else tired of typing sl(alt+130)n go fo(alt+161)ll instead of slán go foíll?</title><link>http://talkirish.com/forums/thread/7708.aspx</link><pubDate>Thu, 30 Aug 2012 22:00:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7708</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7708.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7708</wfw:commentRss><description>&lt;p&gt;Just a really quick reply - does your PC have an Alt Gr key? It&amp;#39;s usually near the spacebar. If you hold it down and type an vowel, you&amp;#39;ll get a fada! Try that and let me know how you go.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Is anyone else tired of typing sl(alt+130)n go fo(alt+161)ll instead of slán go foíll?</title><link>http://talkirish.com/forums/thread/7685.aspx</link><pubDate>Wed, 22 Aug 2012 20:24:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7685</guid><dc:creator>Maxtro</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7685.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7685</wfw:commentRss><description>&lt;p&gt;I know this has come up in discussion before and I realize there are multiple solutions to this.&amp;nbsp; This seems to be the easiest fix I&amp;#39;ve found for fadas on a PC computer.&lt;/p&gt;
&lt;p&gt;&amp;lt;DISCLAIMER&amp;gt;:&amp;nbsp; I don&amp;#39;t know if this works the same way for all computers worldwide.&amp;nbsp; I live in the U.S. and verified these methods on U.S. computers using U.S. versions of the operating system.&lt;/p&gt;
&lt;p&gt;I came across a link yesterday when I hit my rope&amp;#39;s end while trying to type fadas using alt and the number pad i.e.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;alt+130=&amp;eacute; &lt;/p&gt;
&lt;p&gt;alt+160=&amp;aacute;&lt;/p&gt;
&lt;p&gt;alt+161=&amp;iacute;&lt;/p&gt;
&lt;p&gt;alt+162=&amp;oacute;&lt;/p&gt;
&lt;p&gt;alt+163=&amp;uacute;&lt;/p&gt;
&lt;p&gt;alt+144=&amp;Eacute;&lt;/p&gt;
&lt;p&gt;alt+0201=&amp;Eacute;&lt;/p&gt;
&lt;p&gt;alt+0193=&amp;Aacute;&lt;/p&gt;
&lt;p&gt;alt+0205=&amp;Iacute;&lt;/p&gt;
&lt;p&gt;alt+0211=&amp;Oacute;&lt;/p&gt;
&lt;p&gt;alt+0218=&amp;Uacute;&lt;/p&gt;
&lt;p&gt;I know.&amp;nbsp; Talk about a pain in the th&amp;oacute;in.&amp;nbsp; Anyway, yesterday I cam across this link:&lt;/p&gt;
&lt;p style="margin:0in 0in 10pt;" class="MsoNormal"&gt;&lt;a href="http://support.microsoft.com/kb/306560"&gt;&lt;span style="font-size:small;font-family:Calibri;"&gt;http://support.microsoft.com/kb/306560&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;It gives the step by step directions for windows users to change their keyboard setting to an international keyboard.&amp;nbsp; What this does is allow you to type fada letters with just 2 keystrokes (3 if capital).&amp;nbsp; For example now when I want to type &amp;aacute;, I just type an apostrophe followed by the letter. If I need &amp;Aacute;, I&amp;#39;ll type the apostrophe followed by shift+a.&amp;nbsp; Nice and easy.&lt;/p&gt;
&lt;p&gt;There are different methods if you&amp;#39;re a mac user (I go back and forth bewteen the two systems).&amp;nbsp; The mac methods can be seen here:&lt;/p&gt;
&lt;p style="margin:0in 0in 10pt;" class="MsoNormal"&gt;&lt;a href="http://talkirish.com/forums/t/26.aspx"&gt;&lt;span style="font-size:small;color:#800080;font-family:Calibri;"&gt;http://talkirish.com/forums/t/26.aspx&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p style="margin:0in 0in 10pt;" class="MsoNormal"&gt;&amp;nbsp;&lt;/p&gt;
&lt;p style="margin:0in 0in 10pt;" class="MsoNormal"&gt;On another side note:&amp;nbsp; I have found that if you are an iPhone user, if you go to your settings, general, international, and change your region format to Ireland (Irish), not only does it change you calendar to Irish but as you text in Irish your phone will be begin to recognize and eventually auto-correct Irish.&amp;nbsp; I haven&amp;#39;t researched this in depth but I recently notice that while I was texting I typed &amp;quot;slan&amp;quot; and my phone corrected the word to &amp;quot;sl&amp;aacute;n&amp;quot; when I hit the space button afterwards.&amp;nbsp; Granted, this didn&amp;#39;t happen for probably the first 5 times I typed the word after switching my region format to Irish, but it does now.&amp;nbsp; Another thing to keep in mind (at least my iPhone 4S does this) is that once your phone starts auto-correcting properly in Irish, the words will still have that red dotted underline singnaling a misspelling, so you have be attentive to what your typing.&amp;nbsp; If anyone has any questions regarding Irish on the iPhone I&amp;#39;ll be happy to answer them to the best of my knowlege.&amp;nbsp; I&amp;#39;m a bit of a tech geek and I tend to discover things like this by accident.&lt;/p&gt;
&lt;p style="margin:0in 0in 10pt;" class="MsoNormal"&gt;Hope this helps.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>