<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Fiche Ceis</title><link>http://talkirish.com/forums/thread/11877.aspx</link><pubDate>Sun, 14 Jun 2015 14:58:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11877</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11877.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11877</wfw:commentRss><description>&lt;p&gt;Cinnte, t&amp;aacute; a fhios agat. Fiche &lt;i&gt;Ceist&lt;/i&gt;, cialla&amp;iacute;onn s&amp;iacute;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Iarr ar fiche ceist chun iarracht a buille faoi thuairim c&amp;eacute;annacht duine, &amp;aacute;it, n&amp;oacute; rud.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;https://en.wikibooks.org/wiki/Irish/Basic_Sentence_Structure#Fiche_Ceist_.28Twenty_Questions.29&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;1.&amp;nbsp;&lt;span&gt;An ainmh&amp;iacute; &amp;eacute;?&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fiche Ceis</title><link>http://talkirish.com/forums/thread/11875.aspx</link><pubDate>Mon, 08 Jun 2015 08:41:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11875</guid><dc:creator>Aine B</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11875.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11875</wfw:commentRss><description>&lt;p&gt;Is maith liom a sugradh leat ach nil fhios agam cad e an cluiche seo ?????&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Fiche Ceis</title><link>http://talkirish.com/forums/thread/11833.aspx</link><pubDate>Wed, 22 Apr 2015 21:23:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11833</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11833.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11833</wfw:commentRss><description>&lt;p&gt;T&amp;aacute; m&amp;eacute; ag s&amp;uacute;gradh cluiche &amp;#39;Fiche Ceis&amp;#39; le mo mhac annois.&amp;nbsp;&lt;span&gt;Ba mhaith liom a s&amp;uacute;gradh le&amp;nbsp;&lt;/span&gt;daoine f&amp;aacute;sta. (N&amp;iacute;l s&amp;eacute; an rud salach!)&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;An bhfuil aon&amp;nbsp;&lt;span&gt;duine eile ann? Ba mhaith leat a s&amp;uacute;gradh liom?&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;div id="tw-target-text-container" class="tw-ta-container tw-nfl"&gt;
&lt;pre class="tw-data-text vk_txt tw-ta tw-text-medium"&gt;&lt;/pre&gt;
&lt;/div&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>