<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/17668.aspx</link><pubDate>Tue, 07 May 2019 18:19:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17668</guid><dc:creator>O Ceadfhada</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17668.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17668</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span style="font-family:Calibri;font-size:small;"&gt;N&amp;iacute; raibh m&amp;eacute; riamh &lt;/span&gt;&lt;/span&gt;&lt;span&gt;&lt;span style="color:#515358;font-family:Arial;font-size:x-small;"&gt;Seachtaine Gaeilge. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span style="font-family:Calibri;font-size:small;"&gt;N&amp;iacute; raibh a fhios agam faoi sin I gCol&amp;aacute;iste Coe. &amp;nbsp;Go bhfuil s&amp;eacute; suimi&amp;uacute;il.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span style="font-family:Calibri;font-size:small;"&gt;Go raibh maith agat.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;b&gt;&lt;/b&gt;&lt;i&gt;&lt;/i&gt;&lt;span style="text-decoration:underline;"&gt;&lt;/span&gt;&lt;sub&gt;&lt;/sub&gt;&lt;sup&gt;&lt;/sup&gt;&lt;span style="text-decoration:line-through;"&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/17663.aspx</link><pubDate>Fri, 03 May 2019 00:12:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17663</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17663.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17663</wfw:commentRss><description>&lt;p&gt;Chuaigh m&amp;eacute;, cinnte.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; s&amp;eacute; ceart go leor.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;An dt&amp;eacute;ann tusa riamh?&amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; ceann ag Col&amp;aacute;iste Coe i Cedar Rapids i m&amp;iacute; an Mheithimh.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/17662.aspx</link><pubDate>Thu, 02 May 2019 16:52:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17662</guid><dc:creator>O Ceadfhada</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17662.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17662</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span style="font-size:x-small;"&gt;Dia duit, is mise Bill. Ta m&amp;eacute; i mo ch&amp;oacute;nai in
Iowa. Conas a bhi Seachtaine Gaeilge? An ndeachaigh t&amp;uacute; i mbliana?&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/17616.aspx</link><pubDate>Sat, 23 Feb 2019 13:58:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17616</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17616.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17616</wfw:commentRss><description>&lt;p&gt;N&amp;iacute;l ach dh&amp;aacute; mh&amp;iacute; go dt&amp;iacute; go dt&amp;oacute;gfaidh m&amp;eacute; mo chuid droch Gaeilge ar ais go dt&amp;iacute; Bloomington.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/17578.aspx</link><pubDate>Thu, 03 Jan 2019 04:50:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17578</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17578.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17578</wfw:commentRss><description>&lt;p&gt;Rachaidh m&amp;eacute; ar&amp;iacute;s an bhliain seo chugainn freis&amp;iacute;n. &lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16946.aspx</link><pubDate>Wed, 18 Apr 2018 03:13:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16946</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16946.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16946</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;D&amp;#39;fhreastail
m&amp;eacute; ar Dheireadh Seachtaine Gaeilge i Bloomington, Indiana an deireadh
seachtaine seo caite &amp;oacute; o&amp;iacute;che D&amp;eacute; hAoine, 13 Aibre&amp;aacute;n 2018 tr&amp;iacute; mhaidin D&amp;eacute;
Domhnaigh, 15 Aibre&amp;aacute;n 2018.&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; &amp;eacute; cl&amp;aacute;r&amp;uacute; an ch&amp;eacute;ad rud ar an gcl&amp;aacute;r oibre. I lounge na
comhdh&amp;aacute;la, buna&amp;iacute;odh &amp;aacute;r ngr&amp;uacute;pa chun na daoine a d&amp;#39;fhreastail orthu a chl&amp;aacute;r&amp;uacute; agus
clibeanna ainmneacha, fillte&amp;aacute;in, peann agus p&amp;aacute;ip&amp;eacute;ar a thabhairt d&amp;oacute;ibh.&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; cruinni&amp;uacute; gearr ag a s&amp;eacute; a chlog
chun na m&amp;uacute;inteoir&amp;iacute; a thabhairt isteach, athbhreithni&amp;uacute; a dh&amp;eacute;anamh ar sceideal an
chl&amp;aacute;ir, agus gach duine a roinnt sna ranganna. Bh&amp;iacute; ceithre leibh&amp;eacute;al againn:
bunleibh&amp;eacute;al / leibh&amp;eacute;al amh&amp;aacute;in, idirmhe&amp;aacute;nacha neamh-l&amp;iacute;ofa / leibh&amp;eacute;al dh&amp;aacute;,
idirmhe&amp;aacute;nacha l&amp;iacute;ofa / leibh&amp;eacute;al tr&amp;iacute;, agus daoine a bh&amp;iacute; l&amp;iacute;ofa / leibh&amp;eacute;al ceithre.
&lt;/p&gt;
&lt;p&gt;Chuir na
m&amp;uacute;inteoir&amp;iacute; roinnt ceisteanna le daoine a roinnt i ngr&amp;uacute;pa&amp;iacute;. Cad is ainm duit?
Mura bhfuil a fhios agat an freagra, leibh&amp;eacute;al amh&amp;aacute;in. M&amp;aacute;s f&amp;eacute;idir leat d&amp;#39;ainm a
thabhairt, agus c&amp;eacute;n &amp;aacute;it a bhfuil t&amp;uacute;, leibh&amp;eacute;al a d&amp;oacute;. M&amp;aacute;s f&amp;eacute;idir leat comhr&amp;aacute; a
dh&amp;eacute;anamh, leibh&amp;eacute;il tr&amp;iacute; agus ceithre. (T&amp;aacute; daoine saor in aisce leibh&amp;eacute;il a athr&amp;uacute;
le linn an deireadh seachtaine m&amp;aacute; bh&amp;iacute;onn siad sa rang m&amp;iacute;cheart.) &lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; m&amp;eacute; i
leibh&amp;eacute;al a d&amp;oacute;. N&amp;iacute;l aon iontas ann. T&amp;aacute; s&amp;eacute; n&amp;iacute;os deacra ag labhairt n&amp;aacute; cl&amp;oacute;scr&amp;iacute;obh
le n&amp;oacute;ta&amp;iacute; oscailte agus ar an idirl&amp;iacute;on. &lt;/p&gt;
&lt;p&gt;D&amp;#39;oibr&amp;iacute;omar
ar aidiachtacha sa ch&amp;eacute;ad rang an tr&amp;aacute;thn&amp;oacute;na sin.&lt;/p&gt;
&lt;p&gt;An ch&amp;eacute;ad
o&amp;iacute;che chuaigh muid go dt&amp;iacute; an teach t&amp;aacute;bhairne Creole do c&amp;eacute;ili. D&amp;#39;fhreastail
freastala&amp;iacute; uaf&amp;aacute;sach d&amp;uacute;inn cat mara. N&amp;iacute;or rince m&amp;eacute;.&lt;/p&gt;
&lt;p&gt;Ar an dara
l&amp;aacute; bh&amp;iacute; ranganna maidin agus tr&amp;aacute;thn&amp;oacute;na (1&amp;uacute; briathra comhghabh&amp;aacute;la), le
&amp;quot;ceardlanna&amp;quot; idir. Rinne m&amp;eacute; l&amp;oacute;n le bean &amp;aacute;iti&amp;uacute;il ag Bialann Leon &amp;Eacute;ireannach, ach n&amp;iacute; fhaca m&amp;eacute; an taibhse.
Chumhdaigh na ceardlanna ruda&amp;iacute; mar theicst&amp;iacute;l&amp;iacute; &amp;Eacute;ireannacha, iom&amp;aacute;na&amp;iacute;ocht, agus
damhsa sean-nos. N&amp;iacute;or damhsa n&amp;aacute; n&amp;iacute;or chaith amach m&amp;eacute;. &lt;/p&gt;
&lt;p&gt;Th&amp;aacute;inig na
ranganna go l&amp;eacute;ir le ch&amp;eacute;ile ag deireadh an ranga tr&amp;aacute;thn&amp;oacute;na chun f&amp;eacute;achaint ar
scann&amp;aacute;n gearr ar ainmneacha logainmneacha &amp;Eacute;ireannacha. Bh&amp;iacute; an scann&amp;aacute;n i
nGaeilge le fotheidil B&amp;eacute;arla. &lt;/p&gt;
&lt;p&gt;Ansin
d&amp;iacute;oladh roinnt ruda&amp;iacute; ag ceant. Bh&amp;iacute; tairiscint&amp;iacute; dian &amp;oacute; am go ham.&lt;/p&gt;
&lt;p&gt;An dara
o&amp;iacute;che chuaigh muid chuig bialann &amp;eacute;ags&amp;uacute;il (an Sp&amp;uacute;n&amp;oacute;g) le haghaidh seisi&amp;uacute;n ceoil
traidisi&amp;uacute;nta. Bh&amp;iacute; m&amp;uacute;inteoir an-dath&amp;uacute;il ag seinm na bosca ceol. Chan m&amp;eacute; amhr&amp;aacute;n i nGaeilge.&lt;/p&gt;
&lt;p&gt;Chr&amp;iacute;ochnaigh
seisi&amp;uacute;n ranga deiridh ar maidin D&amp;eacute; Domhnaigh na f&amp;eacute;ilte, agus cuireadh cruinni&amp;uacute;
gairid ar f&amp;aacute;il ionas go mbeadh a fhios ag gach duine cathain agus i gc&amp;aacute;s ina
mbeidh sceidealta breise seachtaine Gaeilge ann.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;uacute;il agam
gur f&amp;eacute;idir liom dul ar ais an bhliain seo chugainn!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16856.aspx</link><pubDate>Sun, 11 Mar 2018 20:38:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16856</guid><dc:creator>Siobhanabc</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16856.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16856</wfw:commentRss><description>&lt;p&gt;Is deas &amp;eacute; n&amp;iacute;os m&amp;oacute; gaeilge a fheice&amp;aacute;il anseo.&amp;nbsp; Maith sibh!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16850.aspx</link><pubDate>Sat, 10 Mar 2018 16:21:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16850</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16850.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16850</wfw:commentRss><description>&lt;p&gt;Yep, t&amp;aacute; me go maith ach t&amp;aacute; m&amp;eacute; chomh leisci&amp;uacute;il ar maidin. ☕😴&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16849.aspx</link><pubDate>Sat, 10 Mar 2018 13:08:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16849</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16849.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16849</wfw:commentRss><description>&lt;p&gt;Ag cur isteach n&amp;oacute; ag tabhairt amach? &lt;img src="http://talkirish.com/emoticons/emotion-4.gif" alt="Stick out tongue" /&gt;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; an-mhaith, agus t&amp;aacute; suil agam gur t&amp;aacute; t&amp;uacute; fosta. Nach bhfuil t&amp;uacute;?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16848.aspx</link><pubDate>Sat, 10 Mar 2018 02:11:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16848</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16848.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16848</wfw:commentRss><description>&lt;p&gt;Dia duit, a Laura!&amp;nbsp;&lt;span&gt;Cad &amp;eacute; mar at&amp;aacute; t&amp;uacute; ag cur isteach?&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16846.aspx</link><pubDate>Sat, 10 Mar 2018 01:23:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16846</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16846.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16846</wfw:commentRss><description>&lt;p&gt;Go hiontach. Anois, cuir Gaeilge air. &lt;img src="http://talkirish.com/emoticons/emotion-5.gif" alt="Wink" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16845.aspx</link><pubDate>Fri, 09 Mar 2018 18:12:02 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16845</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16845.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16845</wfw:commentRss><description>&lt;p&gt;P.S. I know I&amp;#39;ve said this before, but now that I know that I have a place to speak what I learn, I&amp;#39;m more determined than ever to learn !!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16844.aspx</link><pubDate>Fri, 09 Mar 2018 18:07:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16844</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16844.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16844</wfw:commentRss><description>&lt;p&gt;Dia duit, a Dale ! Grma for the translation.&amp;nbsp; Did you know that we have a Irish Society here where I live ?? Neither did I until the other day !!&lt;/p&gt;
&lt;p&gt;And to think, I could have been speaking my wee bit of Irish right here in my own home town all this time 😱&lt;/p&gt;
&lt;p&gt;Now here&amp;#39;s my new plan.... I know this site isn&amp;#39;t very active, tho I wish with all my heart that it was, but I am going to be as active on here as I possibly can. Even if I&amp;#39;m the only one speaking the Ulster 👍😁.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;And I&amp;#39;m asking all members to please do the same. I&amp;#39;m speaking to the newbies. Don&amp;#39;t be afraid of making mistakes or feel too shy to give it a go because we have fluent speakers here or speakers who are well advanced.&amp;nbsp; The fluent and the advanced speakers are a blessing because they can help us learn.&lt;/p&gt;
&lt;p&gt;Now I&amp;#39;m off to download my Giota Beag , Giota Beag Eile, Colin and Cumberland Northern Ireland and any other site I can find to help me. Oh yeah, the ever so helpful English to Irish dictionary with audio 😁😁😁😁&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16841.aspx</link><pubDate>Fri, 02 Mar 2018 11:38:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16841</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16841.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16841</wfw:commentRss><description>&lt;p&gt;You will attend an Irish weekend in Bloomington Indiana the end of this Spring. &amp;nbsp;Sounds like fun. &amp;nbsp;Wish I could join you, but Bloomington is a ways off the beaten path for me.....&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Deireadh Seachtaine Gaeilge</title><link>http://talkirish.com/forums/thread/16840.aspx</link><pubDate>Wed, 28 Feb 2018 11:43:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16840</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16840.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=16840</wfw:commentRss><description>&lt;p&gt;Beidh m&amp;eacute; ag freastal ar Dheireadh Seachtaine Gaeilge i Bloomington, Indiana an t-Earraigh seo chugainn. An bhfuil aon leideanna agaibh?&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>