<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish books, cds, posters, etc</title><link>http://talkirish.com/forums/32.aspx</link><description>Place to discuss what you've bought, where you bought it and what you think of it.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/15887.aspx</link><pubDate>Thu, 18 May 2017 02:10:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15887</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15887.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=15887</wfw:commentRss><description>&lt;p&gt;&amp;Eacute;isteacht le Pimsleur dh&amp;eacute;anann d&amp;Uacute;sachtach dom.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;quot;An dtuigeann t&amp;uacute; Gaelainn?&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;quot;Tuigim.&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;quot;N&amp;iacute; thuigim&amp;quot;&lt;/p&gt;
&lt;p&gt;Ar&amp;iacute;s agus ar&amp;iacute;s gan deireadh.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/3172.aspx</link><pubDate>Sun, 14 Jun 2009 19:51:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:3172</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/3172.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=3172</wfw:commentRss><description>&lt;p&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&amp;nbsp;The Pimsleur&amp;nbsp; package arrived and I&amp;#39;ve been listening to it for the past few days, yes you can learn from it fairly easily, though I did find it a bit boring in that I already knew quite a few of the words and phases covered it the course. I picked up bout a dozen words that I had not used before.&lt;br /&gt;Is it worth the price I paid for it? Almost.&lt;br /&gt;&lt;br /&gt;&amp;nbsp;It does teach you some basic language skills, but what I found most annoying was not being able to see the words (they suggest that you not even try to look up the words).&lt;br /&gt;&lt;br /&gt;&amp;nbsp;I think that the BC (&lt;a target="_blank" title="Bunt&amp;uacute;s Cainte Seit ioml&amp;aacute;n 1,2,3 agus CDs, &amp;euro;25.00 + shipping" href="http://www.litriocht.com/shop/product_info.php?manufacturers_id=&amp;amp;products_id=3158"&gt;Bunt&amp;uacute;s Cainte Seit ioml&amp;aacute;n 1,2,3 agus CDs, &amp;euro;25.00 + shipping&lt;/a&gt;) course was a better investment, though if you buy the books &amp;amp; CD&amp;rsquo;s from Amazon you pay more for them if you can find all 3 of them that is, the last time I found book one on Amazon it listed for over $20.00 US and I have never see all three books sold as a set from them. Then if you buy them from Litriocht and this even includes paying the additional shipping charge.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;And since I&amp;#39;m on the subject &lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;div class="newPrice"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;a target="_blank" href="http://www.amazon.com/Progress-Irish-Graded-Beginners-Revision/dp/0861671597/ref=sr_1_1?ie=UTF8&amp;amp;s=books&amp;amp;qid=1245022616&amp;amp;sr=1-1"&gt; Progress in Irish: A Graded Course for Beginners and Revision&lt;/a&gt; &lt;span class="ptBrand"&gt;by Mairead Ni Ghrada&lt;/span&gt;&lt;span class="binding"&gt; (&lt;span class="format"&gt;Paperback&lt;/span&gt; - Feb 2, 1980)&lt;/span&gt; &lt;span&gt;$32.49&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div class="newPrice"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div class="newPrice"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;As compaired to Litriocht&lt;/span&gt;&lt;/div&gt;
&lt;div class="newPrice"&gt;
&lt;h1&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;a target="_blank" title="Progress in Irish" href="http://www.litriocht.com/shop/product_info.php?products_id=4613"&gt;Progress in Irish&amp;nbsp;&lt;/a&gt;&lt;span&gt;Bog / Paperback&lt;/span&gt;&lt;/span&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt; &amp;euro;9.95 + shipping&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;If anyone is interested the rate of exchange at the time this was written is as follows:&lt;/span&gt;&lt;/p&gt;
&lt;table class="XEtbl_sub" align="center" cellpadding="1" cellspacing="0"&gt;

&lt;tr&gt;
&lt;td colspan="3" class="XEenlarge" align="center"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;span class="XEsmall"&gt;Live rates at 2009.06.14 23:45:54 UTC&lt;/span&gt;&lt;/span&gt;
      &lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class="XEenlarge" align="right"&gt;
&lt;h2 class="XE"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;9.95 EUR&lt;/span&gt;&lt;/h2&gt;
&lt;/td&gt;
&lt;td class="XEenlarge" align="center"&gt;
&lt;h2 class="XE"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;=&lt;/span&gt;&lt;/h2&gt;
&lt;/td&gt;
&lt;td class="XEenlarge" align="left"&gt;
&lt;h2 class="XE"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;13.9160 USD&lt;/span&gt;&lt;/h2&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class="XEenlarge" align="right"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;Euro
            &lt;/span&gt;&lt;/td&gt;
&lt;td class="XEenlarge" align="center"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&amp;nbsp;&lt;/span&gt;&lt;/td&gt;
&lt;td class="XEenlarge" align="left"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;United States Dollars
            &lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class="XEenlarge" align="right"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;span class="XEsmall"&gt;1 EUR = 1.39859 USD&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td class="XEenlarge" align="center"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&amp;nbsp;&lt;/span&gt;&lt;/td&gt;
&lt;td class="XEenlarge" align="left"&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;span class="XEsmall"&gt;1 USD = 0.715004 EUR&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;

&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt;&lt;span style="font-size:medium;font-family:book antiqua,palatino;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2778.aspx</link><pubDate>Wed, 27 May 2009 16:23:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2778</guid><dc:creator>seanduine</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2778.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2778</wfw:commentRss><description>&lt;p&gt;Dia daoibh a chairde -&lt;/p&gt;
&lt;p&gt;A note of caution here with the Pimsleur offer. If you do order, make sure that you &lt;span style="text-decoration:underline;"&gt;uncheck&lt;/span&gt; the box below the Submit button. Else, you will automatically receive, otherwise unsolicited, the first chunk of an expanded course at a cost of hundreds of dollars. I learned the hard way - cost me about $20 to return an unwanted course. &lt;/p&gt;
&lt;p&gt;I&amp;#39;m not sure what you would get as a follow-on &amp;nbsp;with Irish - maybe nothing (don&amp;#39;t think they have the usual 45 hours of instruction for Irish). I have the old 4 CD set. I really like the Pimsleur method (used it for other languages) - but you have to adjust for Munster dialect (not just pronunciation, but many words different from what your&amp;nbsp;Ulster Irish experience would be). One other thing - there is a transcript of the CDs on the internet (Pimsleur uses little or no&amp;nbsp;printed material in their method.&lt;/p&gt;
&lt;p&gt;There is quite a bit of Pimsleur Irish on YouTube - so you could check it out before buying.&lt;/p&gt;
&lt;p&gt;T&amp;oacute;g go bog &amp;eacute;,&lt;/p&gt;
&lt;p&gt;Seanduine&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2765.aspx</link><pubDate>Tue, 26 May 2009 18:27:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2765</guid><dc:creator>Brendan</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2765.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2765</wfw:commentRss><description>&lt;p&gt;The pimsleur Irish is very good for a beginer. It&amp;nbsp;get&amp;#39;s the ear and tongue familiar with Gaeilge.&amp;nbsp;If you use a particular dialect it could become confusing as&amp;nbsp;this course uses the new standardized Irish. It&amp;#39;s an excellent&amp;nbsp;deal.&lt;/p&gt;
&lt;p&gt;Bruce&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2764.aspx</link><pubDate>Tue, 26 May 2009 06:11:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2764</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2764.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2764</wfw:commentRss><description>&lt;p&gt;Be good if you could review the package here on the site...I have bought a few things like this but haven&amp;#39;t found them much use - but then different materials suit different people.&lt;/p&gt;
&lt;p&gt;Go raibh maith agaibh,&lt;/p&gt;
&lt;p&gt;Michelle&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2759.aspx</link><pubDate>Mon, 25 May 2009 00:03:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2759</guid><dc:creator>Frankie</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2759.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2759</wfw:commentRss><description>&lt;p&gt;Oh cool I see what it is, that&amp;#39;s pretty cool Domhnall, ya just never know with these things. Always worth a try if it don&amp;#39;t break your bank account, lol.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2757.aspx</link><pubDate>Sun, 24 May 2009 19:54:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2757</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2757.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2757</wfw:commentRss><description>&lt;p&gt;Dia duit a Frankie,&lt;/p&gt;
&lt;p&gt;You&amp;#39;re right the link is broken.&lt;/p&gt;
&lt;p&gt;I found the offer by clicking on the Irish Gaelic link in the Ads by Google that appear on these pages.&lt;/p&gt;
&lt;p&gt;The full link appears below, you may have to cut and paste it into your address bar.&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="https://ww5.pimsleurapproach.com/include/lp/LanguageList_v2e/QS995_v2c.asp?sid=0020contentLSK_ggl&amp;amp;Network=Content&amp;amp;kw=irish%20gaelic%20language&amp;amp;ad=3884695625&amp;amp;SiteTarget=talkirish.com&amp;amp;9gtype=content&amp;amp;9gkw=irish%20gaelic%20language&amp;amp;9gad=3884695625&amp;amp;9gag=1255433735&amp;amp;s_kwcid=ContentNetwork|3884695625&amp;amp;gclid=CITrq5SS1poCFRMUagodAHZK2g"&gt;https://ww5.pimsleurapproach.com/include/lp/LanguageList_v2e/QS995_v2c.asp?sid=0020contentLSK_ggl&amp;amp;Network=Content&amp;amp;kw=irish%20gaelic%20language&amp;amp;ad=3884695625&amp;amp;SiteTarget=talkirish.com&amp;amp;9gtype=content&amp;amp;9gkw=irish%20gaelic%20language&amp;amp;9gad=3884695625&amp;amp;9gag=1255433735&amp;amp;s_kwcid=ContentNetwork|3884695625&amp;amp;gclid=CITrq5SS1poCFRMUagodAHZK2g&lt;/a&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: If anyone might be interested</title><link>http://talkirish.com/forums/thread/2756.aspx</link><pubDate>Sun, 24 May 2009 19:15:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2756</guid><dc:creator>Frankie</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2756.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2756</wfw:commentRss><description>&lt;p&gt;Dia duit a Cianaigh, t&amp;aacute; br&amp;oacute;n orm, ach do &amp;quot;link&amp;quot; t&amp;aacute; s&amp;eacute; br&amp;iacute;ste ... Is d&amp;oacute;igh liom &amp;eacute;? ...&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Pimsleur Course</title><link>http://talkirish.com/forums/thread/2755.aspx</link><pubDate>Sun, 24 May 2009 18:51:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:2755</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/2755.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=2755</wfw:commentRss><description>&lt;div class="al1"&gt;&lt;span class="adt"&gt;Pimsleur $9.95 + Free S&amp;amp;H&lt;/span&gt;&lt;/div&gt;
&lt;p&gt;Best Pimsleur offer ever! Offer ends soon. Act now.&lt;br /&gt;&lt;span class="adu"&gt;PimsleurApproach.com&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;I don&amp;#39;t know how good this is but the price isn&amp;#39;t bad.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>