<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6139.aspx</link><pubDate>Tue, 28 Sep 2010 09:20:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6139</guid><dc:creator>back2ct</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6139.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6139</wfw:commentRss><description>&lt;p&gt;I want to put the phrase on a football jacket for my son. I want it to have the town, the logo and&amp;nbsp;&lt;b&gt;N&amp;aacute; g&amp;eacute;ill cho&amp;iacute;che.&lt;/b&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;It will look something like this, (where you see the word logo there will be a tiger paw logo).&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; MADISON&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; (LOGO)&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;
&lt;p class="MsoNormal"&gt;&lt;i&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp; N&amp;aacute; g&amp;eacute;ill cho&amp;iacute;che&lt;/i&gt;&lt;span&gt;&lt;/span&gt;&lt;/p&gt;


&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Would this be correct?&lt;/p&gt;
&lt;p&gt;Thanks,&lt;/p&gt;
&lt;p&gt;David&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6138.aspx</link><pubDate>Mon, 27 Sep 2010 18:20:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6138</guid><dc:creator>ÉamonnÓCatháin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6138.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6138</wfw:commentRss><description>&lt;p&gt;I&amp;#39;d need a bit more context than that: I don&amp;#39;t understand what you mean in English and the Irish means nothing at all. Can you explain what its is you mean or in what situation you are using this phrase?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6137.aspx</link><pubDate>Mon, 27 Sep 2010 15:01:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6137</guid><dc:creator>gerbil</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6137.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6137</wfw:commentRss><description>&lt;p&gt;
&lt;p&gt;A&amp;nbsp;Chara &amp;nbsp;(re-posting of how to hear proper pronunciation)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go to:&amp;nbsp;&lt;a href="http://www.abair.tcd.ie/index.php"&gt;http://www.abair.tcd.ie/index.php&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Type&amp;nbsp;&lt;b&gt;N&amp;aacute; g&amp;eacute;ill cho&amp;iacute;che&amp;nbsp;&lt;/b&gt;in the text box&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Click on button below which says&amp;nbsp;&lt;b&gt;Synthesise&amp;nbsp;&lt;/b&gt;or&amp;nbsp;&lt;b&gt;Dean Sinteis&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;A sound file is produced so click play mp3 to hear&amp;nbsp;pronunciation using an Ulster dialect [N&amp;aacute; g&amp;eacute;ill cho&amp;iacute;che&amp;nbsp;sounds like &amp;quot;na gale heecha&amp;quot; &amp;nbsp; - don&amp;#39;t rely on this tho - the way we read such things vary!!]&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Adh mor&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;K&lt;/p&gt;
&lt;div&gt;&lt;/div&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6135.aspx</link><pubDate>Mon, 27 Sep 2010 13:43:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6135</guid><dc:creator>irishglr66</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6135.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6135</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;Can u help me? I need to know if ...&lt;/strong&gt; &lt;strong&gt;with love forever Sisters is translated to &lt;span style="background-color:#e6ecf9;color:#000;"&gt;Le Gr&amp;aacute; Deo Si&amp;uacute;racha.. and does anyone know how to say that?&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;Thank you,&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;D&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6136.aspx</link><pubDate>Mon, 27 Sep 2010 13:43:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6136</guid><dc:creator>irishglr66</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6136.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6136</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;Can u help me? I need to know if ...&lt;/strong&gt; &lt;strong&gt;with love forever Sisters is translated to &lt;span style="background-color:#e6ecf9;color:#000;"&gt;Le Gr&amp;aacute; Deo Si&amp;uacute;racha.. and does anyone know how to say that?&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;Thank you,&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="background-color:#e6ecf9;color:#000;"&gt;D&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6131.aspx</link><pubDate>Mon, 27 Sep 2010 10:50:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6131</guid><dc:creator>ÉamonnÓCatháin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6131.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6131</wfw:commentRss><description>&lt;p&gt;Oh....here we go:(Please visit the site to view this media)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Help</title><link>http://talkirish.com/forums/thread/6130.aspx</link><pubDate>Mon, 27 Sep 2010 10:47:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6130</guid><dc:creator>ÉamonnÓCatháin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6130.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6130</wfw:commentRss><description>&lt;p&gt;I have recorded it for you, but apparently cannot upload that kind of file.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Help</title><link>http://talkirish.com/forums/thread/6126.aspx</link><pubDate>Sun, 26 Sep 2010 08:43:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6126</guid><dc:creator>back2ct</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6126.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6126</wfw:commentRss><description>&lt;p&gt;Can anyone help me to pronounce the following by sending an audio file or posting it on here?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;b&gt;N&amp;aacute; g&amp;eacute;ill
cho&amp;iacute;che&lt;/b&gt;&lt;/span&gt;

&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>