<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: I need help with a tattoo ASAP!</title><link>http://talkirish.com/forums/thread/16002.aspx</link><pubDate>Sun, 04 Jun 2017 11:59:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16002</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16002.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16002</wfw:commentRss><description>&lt;p&gt;N&amp;aacute;
d&amp;eacute;an dearmad ar an s&amp;iacute;neadh fada.&lt;/p&gt;
&lt;p&gt;i =
in&amp;nbsp; agus &amp;iacute; = she&lt;/p&gt;
&lt;p&gt;&amp;nbsp; &amp;nbsp;Is &amp;iacute;
Christine cuisle mo chroi.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>I need help with a tattoo ASAP!</title><link>http://talkirish.com/forums/thread/12424.aspx</link><pubDate>Thu, 28 Jan 2016 15:09:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12424</guid><dc:creator>chefheff</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/12424.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=12424</wfw:commentRss><description>&lt;p&gt;Hi,&lt;/p&gt;
&lt;p&gt;I requested help with a translation months ago, and thought I was good to go...scheduled an appointment with a tattoo artist for TOMORROW NIGHT....just went online this morning for a final confirmation, and now I&amp;#39;m getting some different answers....&lt;/p&gt;
&lt;p&gt;I want to say &amp;quot;Christine is the pulse of my heart&amp;quot;. I was originally told that the correct translation is &amp;quot;Is i Christine cuisle mo chroi&amp;quot;, but now I&amp;#39;m seeing that this Gaelic phrase actually means &amp;quot;Christine is in my heart pulse&amp;quot;. Today I&amp;#39;m being told that the correct phrase should be &amp;quot;Is Christine an chuisle mo chroi&amp;quot;.&lt;/p&gt;
&lt;p&gt;Can somebody please tell me ASAP which is the correct translation of &amp;quot;Christine is the pulse of my heart&amp;quot;? If I can&amp;#39;t get this confirmed my tomorrow, I will have to cancel my appointment, because I don&amp;#39;t want to have a mistake permanently inked on my body...&lt;/p&gt;
&lt;p&gt;Sean&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>