<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Names for Grandma</title><link>http://talkirish.com/forums/thread/15784.aspx</link><pubDate>Fri, 28 Apr 2017 02:32:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15784</guid><dc:creator>NewGram</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15784.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=15784</wfw:commentRss><description>&lt;p&gt;Thank you so much for taking the time to explain this! &amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Names for Grandma</title><link>http://talkirish.com/forums/thread/15780.aspx</link><pubDate>Tue, 25 Apr 2017 11:02:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15780</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15780.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=15780</wfw:commentRss><description>&lt;p&gt;Hi NewGram,&lt;/p&gt;
&lt;p&gt;The formal Irish words for &lt;i&gt;grandmother&lt;/i&gt; are&amp;nbsp;&lt;i&gt;seanmh&amp;aacute;thair&lt;/i&gt;,&amp;nbsp;&lt;i&gt;m&amp;aacute;thair mh&amp;oacute;r&lt;/i&gt;&amp;nbsp;or &lt;i&gt;m&amp;aacute;thair chr&amp;iacute;onna&lt;/i&gt;.&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;/i&gt;But Irish speaking children would usually use&amp;nbsp;&lt;i&gt;mam&amp;oacute;&lt;/i&gt;&amp;nbsp;as an informal and affectionate way of referring to their grandmothers.&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;i&gt;Mam&amp;oacute;&lt;/i&gt; would be along the same lines as &lt;i&gt;granny&lt;/i&gt; in English.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;If directly addressing their grandmother, they&amp;#39;d say&amp;nbsp;&lt;i&gt;a mham&amp;oacute;&lt;/i&gt;.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;The reason for this is when we address someone in Irish, words change slightly. For example, a boy named &lt;i&gt;Se&amp;aacute;n&lt;/i&gt; would be addressed as &lt;i&gt;a She&amp;aacute;in&lt;/i&gt;, or a girl named &lt;i&gt;Br&amp;iacute;d&lt;/i&gt; would be addressed as &lt;i&gt;a Bhr&amp;iacute;d&lt;/i&gt;. So when talking &lt;span style="text-decoration:underline;"&gt;to&lt;/span&gt; your granny, you&amp;#39;d use&amp;nbsp;&lt;i&gt;a Mham&amp;oacute;&lt;/i&gt;. When talking &lt;span style="text-decoration:underline;"&gt;about&lt;/span&gt; her, you&amp;#39;d use &lt;i&gt;Mam&amp;oacute;&lt;/i&gt;.&lt;/p&gt;
&lt;p&gt;But maybe I&amp;#39;m overly complicating things. As your future grandchild won&amp;#39;t be speaking to you in Irish, he or she could probably just address you as&amp;nbsp;&lt;i&gt;mam&amp;oacute;&lt;/i&gt;&amp;nbsp;and keep it simple... :)&lt;/p&gt;
&lt;p&gt;You can hear the pronounciation for &lt;i&gt;mam&amp;oacute;&lt;/i&gt;&amp;nbsp;here...&amp;nbsp;&lt;a href="http://www.teanglann.ie/en/fuaim/mam%C3%B3"&gt;http://www.teanglann.ie/en/fuaim/mam%C3%B3&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;(For the pronounciation of &lt;i&gt;a&amp;nbsp;mham&amp;oacute;&lt;/i&gt;, the &lt;i&gt;a&lt;/i&gt; sound is a bit like &lt;i&gt;uh&lt;/i&gt; and the&amp;nbsp;&lt;i&gt;mh&lt;/i&gt;&amp;nbsp;sounds like a &lt;i&gt;w&lt;/i&gt;.&lt;i&gt;&amp;nbsp;&lt;/i&gt;So you have something&amp;nbsp;like&amp;nbsp;&lt;span&gt;&lt;i&gt;uh wahm-OH).&lt;/i&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;English speaking Irish kids usually use &lt;i&gt;Nana&lt;/i&gt; when referring to their grandmother.&lt;/p&gt;
&lt;p&gt;These terms of affection,&amp;nbsp;&lt;i&gt;Mam&amp;oacute;&lt;/i&gt; and &lt;i&gt;Nana,&lt;/i&gt;&amp;nbsp;are not just for kids though. Many Irish adults continue to refer to their grandparents as &lt;i&gt;Mam&amp;oacute;&lt;/i&gt; or &lt;i&gt;Nana&lt;/i&gt;.&lt;/p&gt;
&lt;p&gt;Hope this helps.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Names for Grandma</title><link>http://talkirish.com/forums/thread/15776.aspx</link><pubDate>Sun, 23 Apr 2017 13:15:42 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15776</guid><dc:creator>NewGram</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15776.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=15776</wfw:commentRss><description>&lt;p&gt;I will soon be a new first-time grandmother and my daughter has asked me to decide what I want the baby to call me. &amp;nbsp;He/She already has 2 &amp;quot;Grandma&amp;#39;s&amp;quot; and 1 &amp;quot;Grammie&amp;quot; (paternal grandmother and 2 great-grandmothers). &amp;nbsp;Nana and MeMe seem to be very popular right now in the US, but I was hoping to find something unique. &amp;nbsp;My father was Irish and my mother is French/English/Scottish so I&amp;#39;ve been looking for ideas from those nationalities. &amp;nbsp; I&amp;#39;d be interested to know what Irish and Scottish children call their grandmothers. &amp;nbsp;I also welcome any input and ideas. &amp;nbsp;Thank you.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>