<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/6244.aspx</link><pubDate>Tue, 09 Nov 2010 13:09:13 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6244</guid><dc:creator>hallion</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6244.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6244</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;rum&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;rum&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;D&amp;oacute;l m&amp;eacute; gloine rum!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;I drank a glass of rum! &lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span&gt;Beidh an litir eile a &amp;quot;M&lt;/span&gt;&lt;/span&gt;&lt;span&gt;&lt;span&gt;&amp;quot;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/5992.aspx</link><pubDate>Thu, 05 Aug 2010 12:34:25 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5992</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5992.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=5992</wfw:commentRss><description>&lt;p&gt;

&lt;table cellpadding="0" cellspacing="0"&gt;

&lt;tr&gt;
&lt;td&gt;
&lt;div&gt;This is an interesting question. Basically, the two constructions are slightly different in meaning. If you say, &amp;quot;Bh&amp;iacute; seachtar ann&amp;quot;, it just means &amp;quot;there were seven people there&amp;quot; (or seven objects - you can often use the personal numbers for things). If you say, &amp;quot;Bh&amp;iacute; siad seachtar ann&amp;quot;, that means that they were seven in number. You could use it to refer to a family, a group of children etc.. It emphasises that they are a group and that there are seven in the group, while &amp;quot;Bh&amp;iacute; seachtar ann&amp;quot; just means that there were seven people (or objects) somewhere but they might just be there through random chance.&amp;nbsp;&amp;quot;Bh&amp;iacute; seachtar ann&amp;quot;&amp;nbsp;would answer the question &amp;quot;How many people were in the park?&amp;quot;, for example. If somebody asked you how many people went to a restaurant with you, you would probably say &amp;quot;Bh&amp;iacute; muid seachtar ann!&amp;quot;&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;You could also say &amp;quot;Bh&amp;iacute; seachtar againn ann&amp;quot; but &amp;quot;Bh&amp;iacute;&amp;nbsp;muid seachtar ann&amp;quot; seems more natural to me, especially because &amp;quot;Bh&amp;iacute; seachtar againn ann&amp;quot; implies that we weren&amp;#39;t all there - there were seven of us but there were other members of our group who couldn&amp;#39;t or didn&amp;#39;t make it.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;Hope this clarifies things!&amp;nbsp;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;

&lt;/table&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/5990.aspx</link><pubDate>Thu, 05 Aug 2010 04:03:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5990</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5990.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=5990</wfw:commentRss><description>&lt;p&gt;

&lt;b&gt;&lt;span&gt;rothar&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;bicycle&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;&lt;span&gt;Ghlac s&amp;eacute; a rothar suas staighre.&lt;/span&gt;&lt;/b&gt;&lt;br /&gt;&lt;span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;He took his bicycle upstairs.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;See word a day for flashcard and audio support:&lt;/p&gt;
&lt;p&gt;&lt;a target="_self" href="http://talkirish.com/blogs/wordaday/archive/2010/04/07/irish-word-a-day-rothar-bicycle.aspx"&gt;http://talkirish.com/blogs/wordaday/archive/2010/04/07/irish-word-a-day-rothar-bicycle.aspx&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;

&lt;span&gt;&lt;span&gt;Beidh an litir eile a &amp;quot;&lt;/span&gt;&lt;b&gt;R&lt;/b&gt;&lt;/span&gt;&lt;span&gt;&lt;span&gt;&amp;quot;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/5944.aspx</link><pubDate>Fri, 23 Jul 2010 22:05:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5944</guid><dc:creator>germantiger</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5944.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=5944</wfw:commentRss><description>&lt;p&gt;nuacht&amp;aacute;n - newspaper&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;L&amp;eacute;im an nhuacht&amp;aacute;n ga l&amp;aacute;ch.&lt;/p&gt;
&lt;p&gt;I read the newspaper every day.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4611.aspx</link><pubDate>Thu, 18 Feb 2010 20:18:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4611</guid><dc:creator>lanstad</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4611.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4611</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;bh&amp;iacute;&amp;nbsp; siad seachtar ami.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Domhnall, what is that word&amp;nbsp;&lt;strong&gt;ami ..&lt;/strong&gt;&amp;nbsp;I haven&amp;#39;t seen it before.&lt;/p&gt;
&lt;p&gt;I would have thought it would be &lt;strong&gt;bh&amp;iacute;&amp;nbsp; seachtar ann.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;I hope to be corrected if I&amp;#39;m wrong.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Can anyone help?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4492.aspx</link><pubDate>Sat, 23 Jan 2010 13:49:32 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4492</guid><dc:creator>Russell</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4492.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4492</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;Donn&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Brown&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;T&amp;aacute; s&amp;uacute;ile gal&amp;aacute;nta donna aici.&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;She has beautiful brown eyes.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Next letter is &amp;quot;N&amp;quot;.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4488.aspx</link><pubDate>Fri, 22 Jan 2010 22:59:03 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4488</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4488.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4488</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;nead&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;nest&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Bh&amp;iacute; an nead an-mh&amp;oacute;r.&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;The nest was very large.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Beidh an litir eile a &amp;quot;&lt;/span&gt;&lt;/span&gt;&lt;strong&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;D&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&amp;quot;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Tabhair faoi deara go bhfuil liosta de na focail a bh&amp;iacute; in &amp;uacute;s&amp;aacute;id cheana i gcluiche seo ag &lt;/span&gt;&lt;a href="http://talkirish.com/forums/t/2621.aspx" target="_blank"&gt;&lt;span style="font-size:medium;"&gt;http://talkirish.com/forums/t/2621.aspx&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:arial, helvetica, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Please note there is a list of the words that have already been used in this game at &lt;a href="http://talkirish.com/forums/t/2621.aspx" target="_blank"&gt;http://talkirish.com/forums/t/2621.aspx&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4487.aspx</link><pubDate>Fri, 22 Jan 2010 14:17:05 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4487</guid><dc:creator>kerrid</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4487.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4487</wfw:commentRss><description>&lt;p&gt;&lt;strong&gt;Neipti&amp;uacute;n&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Neptune&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;T&amp;aacute; Neipti&amp;uacute;n pl&amp;aacute;in&amp;eacute;ad t-ocht&amp;uacute;.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Neptune is the eighth planet.&lt;/p&gt;
&lt;p&gt;Hope I translated correctly. I am very much a beginner. Started learning only a couple months ago.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Next letter is &amp;quot;n&amp;quot; again&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4486.aspx</link><pubDate>Fri, 22 Jan 2010 02:25:37 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4486</guid><dc:creator>Russell</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4486.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4486</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;Sean&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;Old&lt;/p&gt;
&lt;p&gt;&lt;b&gt;&lt;br /&gt;&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;T&amp;aacute; an seanduine ar an st&amp;oacute;l.&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;The old man is on the stool.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Next letter is N.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4477.aspx</link><pubDate>Sun, 17 Jan 2010 17:38:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4477</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4477.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4477</wfw:commentRss><description>&lt;p&gt;&lt;span style="font-size:medium;"&gt;&lt;strong&gt;r&amp;aacute;s&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;race&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;&lt;strong&gt;Na r&amp;aacute;sa&amp;iacute; capall spraoi a bh&amp;iacute; iontach chun faire.&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;The horse races were great fun to watch.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;Beidh an litir eile a &amp;quot;&lt;strong&gt;S&lt;/strong&gt;&amp;quot;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-size:medium;"&gt;Tabhair faoi deara go bhfuil liosta de na focail a bh&amp;iacute; in &amp;uacute;s&amp;aacute;id cheana i gcluiche seo ag &lt;a target="_blank" href="http://talkirish.com/forums/t/2621.aspx"&gt;http://talkirish.com/forums/t/2621.aspx&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;Please note there is a list of the words that have already been used in this game at &lt;a target="_blank" href="http://talkirish.com/forums/t/2621.aspx"&gt;http://talkirish.com/forums/t/2621.aspx&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4471.aspx</link><pubDate>Sun, 17 Jan 2010 08:29:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4471</guid><dc:creator>Caomhánach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4471.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4471</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;M&amp;aacute;istir &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;master &lt;/p&gt;
&lt;p&gt;&lt;b&gt;T&amp;aacute; s&amp;eacute; ina mh&amp;aacute;istir ar a ghn&amp;oacute;tha&amp;iacute; f&amp;eacute;in &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;He is master of his own affairs &lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Litir &amp;quot;R&amp;quot; anois&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4464.aspx</link><pubDate>Thu, 14 Jan 2010 20:28:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4464</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4464.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4464</wfw:commentRss><description>&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;b&gt;Naoimh&amp;nbsp;&lt;/b&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Saint(s)&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;b&gt;Naoimh Peadar agus P&amp;oacute;l.&lt;/b&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Saints Peter and Paul.&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;span class="short_text" id="result_box"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Litir Aghaidh &amp;quot;&lt;b&gt;M &lt;/b&gt;n&amp;oacute; &lt;b&gt;H&lt;/b&gt;&amp;quot;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4459.aspx</link><pubDate>Wed, 13 Jan 2010 06:14:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4459</guid><dc:creator>Caomhánach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4459.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4459</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;Lean &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;follow &lt;/p&gt;
&lt;p&gt;&lt;b&gt;C&amp;eacute;n uimhir a lean ann a s&amp;eacute; ?&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;What number comes after six?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Litir &amp;quot;N&amp;quot; anois&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4444.aspx</link><pubDate>Sat, 09 Jan 2010 19:11:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4444</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4444.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4444</wfw:commentRss><description>&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;b&gt;&lt;span style="font-size:medium;"&gt;Dh&amp;uacute;n na nGall&lt;/span&gt;&lt;/b&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;Donegal&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;td id="gap"&gt;&lt;/td&gt;
&lt;td&gt;
&lt;div class="almost_half_cell"&gt;
&lt;div&gt;
&lt;div id="tts_button"&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;&lt;span class="short_text" id="result_box"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;b&gt;&lt;span style="font-size:medium;"&gt;Bhog s&amp;eacute; go baile Dh&amp;uacute;n na nGall.&lt;/span&gt;&lt;/b&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;He moved to Donegal town.&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;/div&gt;
&lt;div&gt;&lt;span class="short_text" id="result_box"&gt;&lt;span&gt;&lt;span style="font-family:&amp;#39;comic sans ms&amp;#39;, sans-serif;"&gt;&lt;span style="font-size:medium;"&gt;T&amp;aacute; ch&amp;eacute;ad litir &amp;quot;&lt;b&gt;L&lt;/b&gt;&amp;quot; ar&amp;iacute;s&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How about a word game?</title><link>http://talkirish.com/forums/thread/4419.aspx</link><pubDate>Wed, 06 Jan 2010 05:45:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:4419</guid><dc:creator>Caomhánach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/4419.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=4419</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;l&amp;oacute;ic&amp;eacute;ad &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;load/large quantity &lt;/p&gt;
&lt;p&gt;&lt;b&gt;T&amp;aacute; l&amp;oacute;ic&amp;eacute;ad bre&amp;aacute; leat &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;You have a fine haul (of goods)&lt;b&gt; &lt;/b&gt;there &lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;litir &amp;quot;D&amp;quot; anois&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>