<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Bible in Irish now available on the internet free of charge</title><link>http://talkirish.com/forums/thread/6196.aspx</link><pubDate>Fri, 15 Oct 2010 10:21:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6196</guid><dc:creator>tc0081</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6196.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6196</wfw:commentRss><description>&lt;p&gt;Yes that is great news Michelle !&lt;/p&gt;
&lt;p&gt;I commend it to everyone - I am working my way through the gospels studying the grammar and vocab. I have an English Bible to hand for when I am stuck. Then once I have a passage sussed I sit back and read it to myself and think on what it means.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Bible in Irish now available on the internet free of charge</title><link>http://talkirish.com/forums/thread/6123.aspx</link><pubDate>Fri, 24 Sep 2010 06:51:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6123</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6123.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=6123</wfw:commentRss><description>&lt;p&gt;I got sent this press release - perhaps of interest to TC0081?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;The Bible in Irish, &amp;lsquo;An B&amp;iacute;obla Naofa,&amp;rsquo; is now available on the internet.&lt;/strong&gt;&amp;nbsp; It can be downloaded to a computer for use with dedicated Bible software, viewed online in pdf format, or even downloaded for viewing on a mobile phone, at &lt;a href="http://www.anbioblanaofa.org"&gt;www.anbioblanaofa.org&lt;/a&gt; .&lt;/p&gt;
&lt;p&gt;There are several advantages to viewing &amp;lsquo;An B&amp;iacute;obla Naofa&amp;rsquo; with free Bible software, e-Sword.&amp;nbsp; For example, viewing verses in Irish and English at the same time can be a great aid in learning Irish.&amp;nbsp;&amp;nbsp; Alternatively, having the whole Bible on a mobile phone means that it can be read anywhere, anytime.&amp;nbsp; Both programs can also be used in the medium of Irish.&lt;/p&gt;
&lt;p&gt;With a desire to see the Bible in Irish used more widely, and with the publisher&amp;rsquo;s (Mons. P&amp;aacute;draig &amp;Oacute; Fiannachta, &amp;lsquo;An Sagart&amp;rsquo;) similar generosity in allowing it to be free of charge, Colin Glen Christian Fellowship has converted the existing CD-ROM contents into Bible software formats. &lt;/p&gt;
&lt;p&gt;&amp;ldquo;The Bible has been a source of inspiration and faith in Ireland from the era of Celtic Christianity up to the present day.&amp;nbsp; While it has only been available in print in the Irish language in recent centuries, the release of &amp;lsquo;An B&amp;iacute;obla Naofa&amp;rsquo; on the internet is a significant step forward in making God&amp;rsquo;s Word more widely accessible in the Irish language,&amp;rdquo; says project leader John Duffy. Whether it is for Bible reading, or just finding a favourite Bible verse in Irish, visit &lt;a href="http://www.anbioblanaofa.org"&gt;www.anbioblanaofa.org&lt;/a&gt; .&lt;/p&gt;
&lt;p&gt;Contact:&lt;br /&gt;John Duffy (Colin Glen Christian Fellowship): 028 90600323 or 07977132383, &lt;a href="mailto:johnduffy@cgcf.net"&gt;johnduffy@cgcf.net&lt;/a&gt; (project leader for resource conversion and website creation, although not a fluent Irish speaker)&lt;/p&gt;
&lt;p&gt;Mons. P&amp;aacute;draig &amp;Oacute; Fiannachta (An Sagart): +353 66 9150000, &lt;a href="mailto:pof@ansagart.ie"&gt;pof@ansagart.ie&lt;/a&gt; (Publisher and main Bible translator)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>