<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Let's see if I have this right....</title><link>http://talkirish.com/forums/thread/6675.aspx</link><pubDate>Wed, 22 Jun 2011 04:25:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6675</guid><dc:creator>Debe</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6675.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6675</wfw:commentRss><description>&lt;p&gt;Go raibh maith agat mo chara!&amp;nbsp; &lt;br /&gt;Also, it&amp;#39;s good to see that I&amp;#39;m not the only in this group..lol&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Let's see if I have this right....</title><link>http://talkirish.com/forums/thread/6674.aspx</link><pubDate>Wed, 22 Jun 2011 02:28:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6674</guid><dc:creator>ricaluanna</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6674.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6674</wfw:commentRss><description>&lt;p&gt;I think you have it right.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Let's see if I have this right....</title><link>http://talkirish.com/forums/thread/6667.aspx</link><pubDate>Fri, 10 Jun 2011 13:45:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6667</guid><dc:creator>Debe</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6667.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6667</wfw:commentRss><description>&lt;p&gt;Go raibh maith agat mo chara!&lt;/p&gt;
&lt;p&gt;And I thought Cherokee was a hard language to learn!&amp;nbsp; lol&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Let's see if I have this right....</title><link>http://talkirish.com/forums/thread/6662.aspx</link><pubDate>Fri, 10 Jun 2011 01:04:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6662</guid><dc:creator>BridMhor</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6662.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6662</wfw:commentRss><description>&lt;p&gt;&amp;quot;Connacht throws uses a pronoun along with now..... T&amp;aacute; N&amp;oacute;ra anseo &amp;iacute;.&amp;quot; &lt;/p&gt;
&lt;p&gt;No, that is wrong.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Let's see if I have this right....</title><link>http://talkirish.com/forums/thread/6648.aspx</link><pubDate>Tue, 24 May 2011 16:04:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6648</guid><dc:creator>Debe</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6648.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6648</wfw:commentRss><description>&lt;p&gt;Here are some of the differences between Connermara and Ulster&lt;/p&gt;
&lt;p&gt;Ulster =&amp;nbsp; Cad&amp;eacute;&amp;nbsp; What?&lt;/p&gt;
&lt;p&gt;Connacht =&amp;nbsp; C&amp;eacute;ard&amp;nbsp; What?&lt;/p&gt;
&lt;p&gt;Connacht throws uses a pronoun along with now..... T&amp;aacute; N&amp;oacute;ra anseo &amp;iacute;. &lt;/p&gt;
&lt;p&gt;Ulster =&amp;nbsp; T&amp;aacute; N&amp;oacute;ra anseo.&lt;/p&gt;
&lt;p&gt;I&amp;#39;m sure there are many other differences but give a girl a star for trying, right ? &lt;img src="http://talkirish.com/emoticons/emotion-30.gif" alt="Star" /&gt; lol&lt;/p&gt;
&lt;p&gt;Oh and there are the differences between the the d sounds when next to an i or e.&lt;/p&gt;
&lt;p&gt;Well, how am I doing so far????&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>