<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11944.aspx</link><pubDate>Fri, 04 Sep 2015 00:41:47 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11944</guid><dc:creator>MacStibhin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11944.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11944</wfw:commentRss><description>&lt;p&gt;Lann Abhaigh is Glenavy in English. It&amp;#39;s in County Antrim. &amp;nbsp;It&amp;#39;s a small village just outside of Belfast.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11943.aspx</link><pubDate>Thu, 03 Sep 2015 20:14:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11943</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11943.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11943</wfw:commentRss><description>&lt;p&gt;F&amp;aacute;ilte romhat, a Dhaith&amp;iacute;!&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; fiosrach...agus n&amp;iacute; maith liom at&amp;aacute; amharc agam ar mo l&amp;eacute;arsc&amp;aacute;il &amp;Eacute;ireann. &amp;nbsp;Cad &amp;eacute; an &amp;quot;Lann Abhaigh&amp;quot; as B&amp;eacute;arla? &amp;nbsp;C&amp;eacute; &amp;eacute; an chontae? &amp;nbsp;C&amp;eacute;n &amp;aacute;it an bhfuil suite?&lt;/p&gt;
&lt;p&gt;Is mise Dale. &amp;nbsp;T&amp;aacute; m&amp;eacute; i mo gcona&amp;iacute; i Woodland, California sna St&amp;aacute;it Aontaithe. &amp;nbsp;T&amp;aacute; beirt dearth&amp;aacute;ireacha agus cuigear deirfi&amp;uacute;racha agam. &amp;nbsp;T&amp;aacute; beirt mac agus in&amp;iacute;on againn, ach t&amp;aacute; gach tri&amp;uacute;r duine f&amp;aacute;sta iad. &amp;nbsp;Bh&amp;iacute; m&amp;eacute; in &amp;Eacute;ire dh&amp;aacute; bliana i 1973-75, agus bh&amp;iacute; m&amp;eacute; i mB&amp;eacute;al Feirste, Lios na gCearrbhach, An Baile Me&amp;aacute;nach, Carraig Fhearghais, Baile &amp;Aacute;tha Cliath, Port L&amp;aacute;irge, agus Corcaigh.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; ag foghlaim Gaeilge f&amp;oacute;s.&lt;/p&gt;
&lt;p&gt;Keep working at it.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11942.aspx</link><pubDate>Thu, 03 Sep 2015 19:01:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11942</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11942.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11942</wfw:commentRss><description>&lt;p&gt;F&amp;aacute;ilte isteach, a Dhaith&amp;iacute;! Thuig m&amp;eacute; gach aon rud. Ma&amp;iacute;th th&amp;uacute;. B&amp;iacute; c&amp;uacute;ramach leis an strucht&amp;uacute;r at&amp;aacute; mar an gc&amp;eacute;anna le &amp;#39;have&amp;#39; i mB&amp;eacute;arla. T&amp;aacute; beirt in&amp;iacute;onacha agam, Caitl&amp;iacute;n agus Aoife an leagan ceart. D&amp;#39;&amp;uacute;s&amp;aacute;id t&amp;uacute; sin le Gaeilge - t&amp;aacute; Gaeilge agam. T&amp;aacute; s&amp;uacute;il agam go mbainfidh t&amp;uacute; sult as an tsu&amp;iacute;omh seo! Beir bua, Se&amp;aacute;no.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11941.aspx</link><pubDate>Thu, 03 Sep 2015 11:51:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11941</guid><dc:creator>MacStibhin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11941.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11941</wfw:commentRss><description>&lt;p&gt;Dia daoibh a chairde,&lt;/p&gt;
&lt;p&gt;is mise Daith&amp;iacute; MacStibhin. Is as B&amp;eacute;al Feirste m&amp;eacute; ach t&amp;aacute; m&amp;eacute; &amp;iacute; mo ch&amp;oacute;nai &amp;iacute; Lann Abhaigh. T&amp;aacute; gaelige agam beag ach t&amp;aacute; m&amp;eacute; ag foghlaim. &amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; beirt in&amp;iacute;on, Caitlin agus Aoife.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Hopefully that makes sense and if there are any issues, feedback is always welcome.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go raibh mile maith agaibh&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Daith&amp;iacute;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11657.aspx</link><pubDate>Tue, 10 Feb 2015 01:22:24 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11657</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11657.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11657</wfw:commentRss><description>&lt;p&gt;Is &amp;iacute; sin.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11656.aspx</link><pubDate>Sun, 08 Feb 2015 18:27:42 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11656</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11656.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11656</wfw:commentRss><description>&lt;p&gt;F&amp;aacute;ilte isteach, a Laura! T&amp;aacute; &amp;aacute;thas orainne go bhfuil t&amp;uacute; ag foghlaim Gaeilge fosta. Is bre&amp;aacute; an teanga &amp;iacute;! :-)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/11655.aspx</link><pubDate>Sun, 08 Feb 2015 15:42:05 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11655</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11655.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11655</wfw:commentRss><description>&lt;p&gt;Dia Daoibh.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Is mise Laura. T&amp;aacute; &amp;aacute;thas orm go bhfuil m&amp;eacute; ag foghlaim Gaeilge. &lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/10075.aspx</link><pubDate>Mon, 12 May 2014 11:23:27 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:10075</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/10075.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=10075</wfw:commentRss><description>&lt;p&gt;Haigh, Saralyn.&lt;/p&gt;
&lt;p&gt;Failte romhat ar fh&amp;oacute;ram!&lt;/p&gt;
&lt;p&gt;Although it is not a &amp;quot;beginner&amp;quot; book necessarily, I do recommend &lt;i&gt;An Prionsa Beag&lt;/i&gt;, which I have 
purchased, and it is a lot of fun to read.&amp;nbsp; In general it follows the 
English translation fairly closely, but the Irish idioms are faithfully 
executed.&amp;nbsp; You would have to purchase the English version, &lt;i&gt;The Little Prince&lt;/i&gt;, separately, but it should still be available.
&lt;/p&gt;
&lt;p&gt;As to other possibilities, might I recommend that you look around on &lt;a href="http://www.leabhar.com"&gt;www.leabhar.com&lt;/a&gt;
 as they feature a number of books for different levels of Irish 
learners.&amp;nbsp; They also include some comic books!&amp;nbsp; One that looks 
intriguing is called &lt;i&gt;An T&amp;oacute;ra&amp;iacute;ocht&lt;/i&gt; which is a comic-book retelling of &lt;i&gt;T&amp;oacute;ra&amp;iacute;ocht Diarmad agus Grainne&lt;/i&gt;.&amp;nbsp;
 I have a published version of the story that a friend gave me when I 
was in Ireland in the &amp;#39;70s, and it is a challenge to read.&amp;nbsp; The comic 
version, based on the panels they show on their website, looks much 
simplified as a lot of the actions are visualized so you&amp;#39;re mostly 
reading just dialog.&amp;nbsp; Anyway, when you go to their &lt;i&gt;Siopa&lt;/i&gt;/Shop 
link, they break down all their available offerings into categories, 
such as Children and Beginners, Teens and Adults, Comics, etc.&amp;nbsp; I 
suspect you can probably find something of interest that would be 
useful, although I don&amp;#39;t know that they have anything with both English and Irish together, if that&amp;#39;s of concern to you.&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Disclaimer:&lt;/b&gt;&amp;nbsp; I am not in any way affiliated with &lt;a href="http://www.leabhar.com"&gt;www.leabhar.com&lt;/a&gt; or &lt;i&gt;Cl&amp;oacute; Mhaigh Eo&lt;/i&gt;
 so I cannot vouch for them, and on the other hand I&amp;#39;m not remunerated 
in any way either.&amp;nbsp; It does appear to me to be a good resource for 
getting Irish literature in appropriate levels.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/9981.aspx</link><pubDate>Tue, 22 Apr 2014 06:35:06 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9981</guid><dc:creator>Saralyn</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9981.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=9981</wfw:commentRss><description>&lt;p&gt;I just finished online lesson 28 and there are sticky notes all over my house now. &amp;nbsp;I have not got up the nerve to post on Facebook yet, but I am beginning to find myself thinking of ways to incorporate words into the sentences that are in the lessons.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;d like to find some simple books (children&amp;#39;s books would do) to practice on ... especially if they have English and Irish together. &amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/9673.aspx</link><pubDate>Tue, 11 Feb 2014 02:58:10 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9673</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9673.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=9673</wfw:commentRss><description>&lt;p&gt;Hi Kay. ......Oh f&amp;eacute;ach! T&amp;aacute; s&amp;eacute; ag cur sneachta! &amp;nbsp;Oh look! It&amp;#39;s snowing! :-)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/9672.aspx</link><pubDate>Mon, 10 Feb 2014 20:12:15 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9672</guid><dc:creator>kay1966</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9672.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=9672</wfw:commentRss><description>&lt;p&gt;i think this is me also.&amp;nbsp; So far I have sticky notes on my bottle of white wine and whiskey.&amp;nbsp; It&amp;#39;s snowing outside so my facebook says &amp;#39;oh look, sneachta&amp;#39;&amp;nbsp; but i don&amp;#39;t know how to say Oh look! in Irish.&amp;nbsp; &lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/9670.aspx</link><pubDate>Fri, 07 Feb 2014 15:59:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9670</guid><dc:creator>ponipelangi</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9670.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=9670</wfw:commentRss><description>&lt;p&gt;dia daoibh... im panji from indonesia.. : ) &lt;span id="result_box"&gt;&lt;span class="hps"&gt;only&lt;/span&gt; &lt;span class="hps"&gt;English and&lt;/span&gt; &lt;span class="hps"&gt;bahasa&lt;/span&gt; &lt;span class="hps"&gt;who&lt;/span&gt; &lt;span class="hps"&gt;studied&lt;/span&gt; &lt;span class="hps"&gt;in&lt;/span&gt; &lt;span class="hps"&gt;my&lt;/span&gt; &lt;span class="hps"&gt;country and irish language isn&amp;#39;t popular&lt;/span&gt; &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;today, im trying to learn irish language and one day i had to go to ireland:)&lt;/p&gt;
&lt;p&gt;go raibh maith agat ( terimakasih )&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/8466.aspx</link><pubDate>Wed, 17 Jul 2013 01:24:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8466</guid><dc:creator>thunderhead</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8466.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8466</wfw:commentRss><description>&lt;p&gt;Hi there.&amp;nbsp; I&amp;#39;m a definite newby, as in I only have a few words in Irish.&amp;nbsp; I decided to learn the language because I&amp;#39;ve gotten into Celtic music really hard core, and I&amp;#39;d like to be able to sing along.&amp;nbsp; Also, I&amp;#39;ve gotten hooked on listening to Radio na Gaeltachta and it would be nice to understand what the DJ&amp;#39;s are saying.&amp;nbsp; I&amp;#39;m from the U.S. and don&amp;#39;t have any Irish heritage that I know of, but I&amp;#39;m just in love with the language, so I&amp;#39;m trying to learn it.&amp;nbsp; I literally just started by going on Youtube and trying to learn from some vids people upload, but that&amp;#39;s a bit tricky, so I discovered this site.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/7213.aspx</link><pubDate>Sat, 03 Mar 2012 01:31:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7213</guid><dc:creator>cailingaelach</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7213.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7213</wfw:commentRss><description>&lt;p&gt;Dia dhiabh! :)&lt;/p&gt;
&lt;p&gt;S&amp;eacute; sin mo ch&amp;eacute;ad uair p&amp;aacute;irt a glacadh le su&amp;iacute;omh tr&amp;iacute; mhean na gaeilge, ach ceap m&amp;eacute; go mbeadh s&amp;eacute; suimi&amp;uacute;il go leor. &amp;nbsp;B&amp;iacute;onn s&amp;eacute; i gcona&amp;iacute; iontach chun labhairt le daoine le gaeilge n&amp;oacute; daoine at&amp;aacute; ag iarriadh an teanga &amp;aacute;lainn seo a fhoglaim. :)&lt;br /&gt;&lt;br /&gt;Hey everyone! This is my first time taking part in an online site through the irish language, but I thought it would be quite interesting as it&amp;#39;s always great to talk to people with the language or people that want to learn it. &amp;nbsp;I&amp;#39;m in my final year of college studying the irish langauge, and will hopefully go on next year to do some sort of a masters in it.&lt;br /&gt;&lt;br /&gt;Ag tnuth go m&amp;oacute;r le p&amp;aacute;irt a glacadh! :)&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Fáilte/Welcome</title><link>http://talkirish.com/forums/thread/7200.aspx</link><pubDate>Sun, 26 Feb 2012 23:20:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7200</guid><dc:creator>Keegah</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7200.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7200</wfw:commentRss><description>&lt;p&gt;Hey guys. Absolute, 100% beginner to the language. I&amp;#39;m of half Irish descent (English on the other side), and have been trying to get more in touch with that side of my heritage for awhile now. So, here I am, trying to learn the Irish language. It&amp;#39;s going pretty slowly, but I guess it always does when you&amp;#39;re first trying to learn a&amp;nbsp;language. Still, the lessons seems to be put together very intuitively, and I&amp;#39;m feeling optimistic. I&amp;#39;m confident I&amp;#39;ll achieve fluency eventually. &lt;/p&gt;
&lt;p&gt;I will say this though - Irish pronounciation. Wow, is it difficult to get a handle on. Is &amp;quot;bh&amp;quot; a v or a w sound?&amp;nbsp;Why does it seem like it&amp;#39;s silent sometimes?&amp;nbsp;I have no&amp;nbsp;idea. I&amp;#39;m sure I&amp;#39;ll get used to it eventually.&lt;/p&gt;
&lt;p&gt;Anyway, thank you for having me, and I look forward to learning Irish with all of you fine people.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>