<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Tips</title><link>http://talkirish.com/forums/thread/5821.aspx</link><pubDate>Fri, 04 Jun 2010 19:16:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5821</guid><dc:creator>Russell</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5821.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5821</wfw:commentRss><description>&lt;p&gt;I&amp;#39;ve been using &lt;a title="Byki" href="http://www.byki.com/"&gt;Byki&lt;/a&gt; and &lt;a title="Transparent Language" href="http://www.transparent.com/learn-irish/"&gt;Transparent Irish&lt;/a&gt;. Both programs are made by the same people. They have been very helpful and really speed up the learning process, not to mention they&amp;#39;re pretty fun. I tried Rosetta Stone for Japanese and I wouldn&amp;#39;t buy it for Irish. It didn&amp;#39;t work very well for me and I found it kinda boring. Byki is a virtual flashcard program and Transparent Irish is a series of immersion environments. It really helps to be immersed and forces me to learn more quickly than I would otherwise. While it may sound difficult to be immersed in Irish for a beginner, it&amp;#39;s actually very easy since there are textual and audio translations for all of the words. The translations can be displayed or hidden. &lt;/p&gt;
&lt;p&gt;From Transparent Irish, I&amp;#39;ve printed some of the lessons and have begun to copy them word for word onto paper. Since everything is in Irish, it&amp;#39;s useful, and I find that writing Irish does me a lot of good for remembering it. It&amp;#39;s also got some good instructions on Irish grammar in English that I&amp;#39;ve printed as well. Byki has an option for printing flashcards, but I haven&amp;#39;t been able to get it to work with my printer yet.&lt;/p&gt;
&lt;p&gt;I&amp;#39;ve also been listening to &lt;a href="http://www.rte.ie/rnag/"&gt;RT&amp;Eacute; Raidi&amp;oacute; Na Gaeltachta&lt;/a&gt; and watching &lt;a href="http://www.tg4.ie/bearla/index.asp"&gt;TG4&lt;/a&gt;, an Irish television station streamed online. Both have been helpful, especially TG4, which has English subtitles for most of its programs.&lt;/p&gt;
&lt;p&gt;Another thing I&amp;#39;ve been doing is using &lt;a title="Google Translate" href="http://translate.google.com/"&gt;Google Translate&lt;/a&gt; to translate Irish webpages into English and then hovering over the translations to see the original text. It works pretty well, I think, though, Google Translate doesn&amp;#39;t always work very well. However, it does give me a basic idea of what&amp;#39;s being said and I can figure stuff out from that. What I don&amp;#39;t understand I look up in a dictionary, either an online one or this paperback I have here called &lt;a href="http://www.collinslanguage.com/"&gt;Collins&lt;/a&gt; easy learning Irish Dictionary. I think a good way to study conversational Irish is to translate a forum where the users talk in Irish. Articles are also good for learning, but there&amp;#39;s not that conversational flow that you find in forums. Blogs can be useful too.&amp;nbsp; &lt;/p&gt;
&lt;p&gt;I have a novel that&amp;#39;s written in Irish called &lt;i&gt;An Fear agus an Luch&lt;/i&gt;, but I&amp;#39;m still slowly working my way through it. I&amp;#39;ve been writing translations for the pages on paper that I keep in a binder, so that I don&amp;#39;t forget what I&amp;#39;ve already translated. Since it takes a while to translate things, I find that the Irish words get stuck in my head and I can read translated sections without checking my notes.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;An idea might be to start a journal in Irish. I created an online blog where I write about my studies and some posts are entirely in Irish. You can just write about your day or anything that comes to mind, and many blog sites allow you to set your blog as private, in case you don&amp;#39;t feel comfortable with other people reading your journal.&lt;/p&gt;
&lt;p&gt;I tried the post-it note thing when I started, but I never got around to
 sticking the entire house yet. I guess I need to take up the task again. Haha.&lt;/p&gt;
&lt;p&gt;Some useful websites:&lt;/p&gt;
&lt;p&gt;http://www.fluentin3months.com/ - This is a blog written by a man who makes it his mission to learn languages quickly. He has a lot of good advice to share for learning any language. He also just happens to be Irish, lives in Ireland, and can speak Irish. He also has a &lt;a href="http://www.irishpolyglot.com/ga"&gt;video blog&lt;/a&gt; that he updates in Irish. &lt;/p&gt;
&lt;p&gt;http://www.nualeargais.ie/gnag/gram.htm - This is a website on Irish grammar that was suggested by the man who made the website above. I have not looked much into it yet, but it seems helpful. &lt;/p&gt;
&lt;p&gt;http://www.transparent.com/irish/ - This is Transparent Language&amp;#39;s blog on Irish. Again, I&amp;#39;ve not read a whole lot of it, but it seems to teach about different words and verbs and such.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Tips</title><link>http://talkirish.com/forums/thread/5723.aspx</link><pubDate>Sat, 29 May 2010 11:02:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5723</guid><dc:creator>beanrua</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5723.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5723</wfw:commentRss><description>&lt;p&gt;agus mar a d&amp;uacute;irt Brandon cheana f&amp;eacute;in,&amp;nbsp; post-it notes are very handy.&amp;nbsp;I used them all over the house e.g mind the step, would you like a bite to eat, shower, bath, soap, etc etc, very useful and they were up so long&amp;nbsp;I forgot they were all over the house until other people pointed them out to me, or they fluttered to the floor.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Tips</title><link>http://talkirish.com/forums/thread/5722.aspx</link><pubDate>Fri, 28 May 2010 16:20:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5722</guid><dc:creator>beanrua</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5722.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5722</wfw:commentRss><description>&lt;p&gt;Just thought&amp;nbsp;I would share some tips that I found and still find useful for learning Irish. Mostly told to me by other learners or gained through painful experience. You may find them useful or perhaps not.&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;If you know the Irish word for something use it - ie if you know that door is doras then start by saying close the doras or open the doras until you learn the verbs. &lt;/li&gt;
&lt;li&gt;Learn a useful phrase everyday, one that you will use. I remember learning to say,I woke at 8 o&amp;#39;clock, I got out of bed, I combed my hair -&amp;nbsp;in Irish but to tell the truth I rarely used these phrases in English never mind Irish.&lt;/li&gt;
&lt;li&gt;I used to read children&amp;#39;s books in Irish, mostly stories that&amp;nbsp;I knew, eg Cinderella, The three little pigs etc etc, knowing the story helped in the understanding of the irish.&lt;/li&gt;
&lt;li&gt;I used to listen to RnaG every day and between 4-5pm (I think) there were adverts for things for sale eg van for sale, year, make, price, tel. no etc - the constant repition every day was helpful.&lt;/li&gt;
&lt;li&gt;If you are serious about learning Irish you must spend at least 30mins practising it each day.&lt;/li&gt;
&lt;li&gt;Conversation can be difficult so I started with simple but useful phrases - phrases&amp;nbsp;I would commonly use in English.&lt;/li&gt;
&lt;li&gt;N&amp;iacute; thuigim - I don&amp;#39;t understand - was probably my most used phrase at a time.&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;If anyone out there has other tips or strategies that&amp;nbsp;they have found useful I would love to hear them.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>