<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Talk Irish video series - First release!</title><link>http://talkirish.com/forums/thread/6262.aspx</link><pubDate>Sat, 13 Nov 2010 14:46:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6262</guid><dc:creator>mary Dugan</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6262.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6262</wfw:commentRss><description>&lt;p&gt;T&amp;aacute; me ag foghlaimn Gaeilge. T&amp;aacute; m&amp;eacute; i mo ch&amp;oacute;na&amp;iacute; i suas Nua Eabharc. Glad to become acquainted with the Activism in the Big Apple. &amp;nbsp; I appreciate how the web videos connect enthusiastic learners with each other. Especially as I am teaching myself, which would be impossible without the audio available on the web. &amp;nbsp;A google search for prayers in Irish was a great start for me. &amp;nbsp;I&amp;#39;m so glad to have found Talk Irish! Look forward to much and I&amp;#39;m spreading the word to many, especially my cousins in E&amp;iacute;re. Hope they&amp;#39;ll all be putting in their votes for you&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mary&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Talk Irish video series - First release!</title><link>http://talkirish.com/forums/thread/6259.aspx</link><pubDate>Fri, 12 Nov 2010 18:29:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6259</guid><dc:creator>gerbil</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6259.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6259</wfw:commentRss><description>&lt;p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;Agallamh go hiontach ar fad . . .&amp;nbsp;&lt;/span&gt;&lt;span&gt;Bhain m&amp;eacute; sult as&amp;nbsp;glan ioml&amp;aacute;n&lt;span&gt;!! &lt;/span&gt;&lt;span&gt;Is &amp;iacute; mo bhar&amp;uacute;il f&amp;eacute;in&lt;b&gt; &lt;/b&gt;&lt;/span&gt;&lt;span&gt;go bhfuil &lt;/span&gt;&lt;span&gt;f&amp;iacute;se&amp;aacute;n i bhfad n&amp;iacute;os cumhachta&amp;iacute; n&amp;aacute; na focail scr&amp;iacute;ofa.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;Comhghairdeas
libh go l&amp;eacute;ir!!! &lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;/Wonderful interview . . . I enjoyed it totally. In my opinion videos are much better than any form of written words!! [excuse errors as always!!]&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&amp;nbsp;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;Ken&lt;/p&gt;


&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Talk Irish video series - First release!</title><link>http://talkirish.com/forums/thread/6257.aspx</link><pubDate>Fri, 12 Nov 2010 10:17:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6257</guid><dc:creator>hallion</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6257.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6257</wfw:commentRss><description>&lt;p&gt;Is maith liom &amp;eacute;. T&amp;aacute; s&amp;eacute; an-suimi&amp;uacute;il. Ba mhaith liom dul go dt&amp;iacute; Nua Eabharc - an t-&amp;uacute;ll mh&amp;oacute;r!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Talk Irish video series - First release!</title><link>http://talkirish.com/forums/thread/6240.aspx</link><pubDate>Tue, 09 Nov 2010 10:23:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6240</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6240.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6240</wfw:commentRss><description>&lt;p&gt;We&amp;#39;ve just launched the first video in our new video gallery. Check out the great video interview with&amp;nbsp;Elaine N&amp;iacute; Bhraon&amp;aacute;in who&amp;#39;s based in Nua Eabhrac as an Irish language teacher and activist. It&amp;#39;s in our new video gallery here&amp;nbsp;&lt;a href="http://talkirish.com/media/p/6239.aspx"&gt;http://talkirish.com/media/p/6239.aspx&lt;/a&gt;&amp;nbsp;or you can view the embedded video below.&lt;/p&gt;
&lt;p&gt;We&amp;#39;ve 4 more fantastic videos in the pipeline. Let us know what you think of this!&lt;/p&gt;
&lt;p&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>