<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Translation help pleass</title><link>http://talkirish.com/forums/thread/11956.aspx</link><pubDate>Wed, 30 Sep 2015 15:59:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11956</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11956.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11956</wfw:commentRss><description>&lt;p&gt;T&amp;aacute; m&amp;eacute; ag dul a lu&amp;iacute; (literally, I&amp;#39;m going to lie)&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; ag dul a chodladh (literally, I&amp;#39;m going to sleep)&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; ag dul don leaba (literally, I&amp;#39;m going to the bed)&lt;/p&gt;
&lt;p&gt;&lt;span class="diclick"&gt;T&amp;aacute; m&amp;eacute; ag dul&lt;/span&gt;&lt;span&gt;&amp;nbsp;&lt;/span&gt;&lt;span class="diclick"&gt;chun&lt;/span&gt;&lt;span&gt;&amp;nbsp;&lt;/span&gt;&lt;span class="diclick"&gt;soip (&amp;#39;sop&amp;#39; is a bed made of straw...like the English phrase &amp;#39;hitting the hay&amp;#39;)&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Translation help pleass</title><link>http://talkirish.com/forums/thread/11951.aspx</link><pubDate>Tue, 29 Sep 2015 22:11:18 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11951</guid><dc:creator>evnmrphy</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11951.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11951</wfw:commentRss><description>&lt;p&gt;In Irish we generally say &amp;#39;I&amp;#39;m going to sleep&amp;#39; rather than &amp;#39;...to bed&amp;#39;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; ag dul a choladh.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;quot;T&amp;aacute; m&amp;eacute;&amp;quot; can become &amp;quot;T&amp;aacute;im&amp;quot; for greater fluency.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute;im ag dul a choladh.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Translation help pleass</title><link>http://talkirish.com/forums/thread/11949.aspx</link><pubDate>Mon, 28 Sep 2015 06:09:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11949</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11949.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11949</wfw:commentRss><description>&lt;p&gt;Haigh, Bama!&lt;/p&gt;
&lt;p&gt;You could say, &amp;quot;T&amp;aacute; m&amp;eacute; ag dul a leaba&amp;quot; &lt;i&gt;I&amp;#39;m going to my bed&lt;/i&gt;, but it appears the Irish idiom leans more toward saying, &amp;quot;T&amp;aacute; m&amp;eacute; ag dul a lu&amp;iacute;&amp;quot; &lt;i&gt;I am going to lay down. &amp;nbsp;&lt;/i&gt;The latter phrase is active rather than passive, which may be why it&amp;#39;s preferred, but the English phrase &amp;quot;I&amp;#39;m going to bed&amp;quot; does literally mean &amp;quot;I&amp;#39;m going to get in bed.&amp;quot; &amp;nbsp;The phrase &amp;quot;T&amp;aacute; m&amp;eacute; ag dul a leaba&amp;quot; could be translated simply as, &lt;i&gt;I&amp;#39;m going to my bed&lt;/i&gt;&amp;nbsp;but would not necessarily indicate that you intended to lay down on it....&lt;/p&gt;
&lt;p&gt;Of course, if I&amp;#39;m off base here, hopefully someone will chime in to correct me!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Translation help pleass</title><link>http://talkirish.com/forums/thread/11948.aspx</link><pubDate>Sun, 27 Sep 2015 22:15:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11948</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11948.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11948</wfw:commentRss><description>&lt;p&gt;Can someone please tell me how to say....I&amp;#39;m going to bed.&lt;/p&gt;
&lt;p&gt;Grma :-)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>