<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Translation - Please help</title><link>http://talkirish.com/forums/thread/17681.aspx</link><pubDate>Thu, 30 May 2019 11:14:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17681</guid><dc:creator>Breandán</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17681.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17681</wfw:commentRss><description>&lt;p&gt;&lt;b&gt;Misneach&lt;/b&gt; &amp;quot;Courage&amp;quot;&lt;br /&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Dul ar Aghaidh&lt;/b&gt; &amp;quot;Moving Forward&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;&lt;span class="fgb title"&gt;diongbh&amp;aacute;ilteacht agus &lt;/span&gt;&lt;span class="superentry"&gt;&lt;span class="sense"&gt;&lt;span class="cit_translation"&gt;&lt;span class="quote"&gt;buanseasmhacht&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/b&gt; &amp;quot;toughness and perseverence&amp;quot;&lt;/p&gt;
&lt;p&gt;Something having to do with pushing forward despite what life has thrown at you:&lt;br /&gt;&lt;b&gt;&lt;br /&gt;Coinnigh do mhisneach!&amp;nbsp; &lt;/b&gt;&amp;quot;Keep up your courage!&amp;quot;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Translation - Please help</title><link>http://talkirish.com/forums/thread/17666.aspx</link><pubDate>Mon, 06 May 2019 18:28:20 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17666</guid><dc:creator>Kristenalissa</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17666.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17666</wfw:commentRss><description>&lt;p&gt;I am looking to make a sign with a word or phrase to describe the following.... translated to irish / Gaelic.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;- Courage&lt;/p&gt;
&lt;p&gt;- Moving Forward&lt;/p&gt;
&lt;p&gt;- toughness and perseverence&amp;nbsp;&lt;/p&gt;
&lt;p&gt;- Something having to do with pushing forward despite what life has thrown at you.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I am not sure what direction I want to go in with the sign whether it is a translation to the above phrases or topics.. or if there is an irish saying that I can incorporate that means something similar. &lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thank you for your help!&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>