<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Dia Daoibh</title><link>http://talkirish.com/forums/thread/17733.aspx</link><pubDate>Tue, 17 Sep 2019 06:42:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17733</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17733.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17733</wfw:commentRss><description>&lt;p&gt;Haigh, Laura.&lt;/p&gt;
&lt;p&gt;Conas at&amp;aacute; t&amp;uacute;?&lt;/p&gt;
&lt;p&gt;Conas at&amp;aacute; do Ghaeilge?&amp;nbsp; An gcuimhn&amp;iacute;onn t&amp;uacute; l&amp;iacute;ofa teanga as Gaeilge?&amp;nbsp; C&amp;eacute; acu can&amp;uacute;int an bhfuil t&amp;uacute; ag foghlaim?&lt;/p&gt;
&lt;p&gt;D&amp;#39;fhoghlaim m&amp;eacute; mor&amp;aacute;n focail ach n&amp;iacute; mheabhra&amp;iacute;m iad nuair an bhfuil uaim iad.&amp;nbsp; D&amp;eacute;anaim na cheactanna as Bunt&amp;uacute;s Cainte agus Duolingo, agus d&amp;eacute;anaim na scr&amp;uacute;daithe iontu, ach n&amp;iacute;lim cleachtadh go leor agam.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; i mo gc&amp;oacute;na&amp;iacute; i Woodland, California.&amp;nbsp; Bh&amp;iacute; m&amp;eacute; i mo gc&amp;oacute;na&amp;iacute; anseo fiche bl&amp;iacute;ainta.&amp;nbsp; T&amp;aacute; an aimsir go deas anseo,&amp;nbsp; T&amp;aacute; m&amp;oacute;r&amp;aacute;n feirm in aice &amp;aacute;r mbaile.&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; madra againn, ach bh&amp;iacute; s&amp;eacute; b&amp;aacute;s dh&amp;aacute; bhl&amp;iacute;ain go haim seo.&amp;nbsp; T&amp;aacute; madra eile &amp;oacute; mo bhean ch&amp;eacute;ile, ach n&amp;iacute;lim ceann uaim f&amp;oacute;s,&amp;nbsp; T&amp;aacute; ail&amp;eacute;irg&amp;iacute; ag mo bhean ch&amp;eacute;ile, mar sin t&amp;aacute; p&amp;oacute;rtha &amp;aacute;irithe is f&amp;eacute;idir linn againn.&lt;/p&gt;
&lt;p&gt;(not sure you&amp;#39;ll be able to follow all that...but all we can do is try!)&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Dia Daoibh</title><link>http://talkirish.com/forums/thread/17727.aspx</link><pubDate>Sat, 07 Sep 2019 00:28:39 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17727</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17727.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17727</wfw:commentRss><description>&lt;p&gt;T&amp;aacute;, cinnte:&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;br /&gt;&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;span&gt;Laura is the face in the misty light&lt;/span&gt;&lt;br /&gt;&lt;span&gt;Footsteps that you hear down the hall&lt;/span&gt;&lt;br /&gt;&lt;span&gt;The laugh that floats on a summer night&lt;/span&gt;&lt;br /&gt;&lt;span&gt;That you can never quite recall&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span&gt;And you see Laura on a train that is passing through&lt;/span&gt;&lt;br /&gt;&lt;span&gt;Those eyes how familiar they seem&lt;/span&gt;&lt;br /&gt;&lt;span&gt;She gave your very first kiss to you&lt;/span&gt;&lt;br /&gt;&lt;span&gt;That was Laura but she&amp;#39;s only a dream&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span&gt;She gave your very first kiss to you&lt;/span&gt;&lt;br /&gt;&lt;span&gt;That was Laura but she&amp;#39;s only a dream&lt;/span&gt;&lt;/i&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Dia Daoibh</title><link>http://talkirish.com/forums/thread/17726.aspx</link><pubDate>Fri, 06 Sep 2019 22:27:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17726</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17726.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17726</wfw:commentRss><description>&lt;p&gt;In case you are interested: &amp;nbsp;https://www.youtube.com/results?search_query=laura+spike+jones&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Dia Daoibh</title><link>http://talkirish.com/forums/thread/17721.aspx</link><pubDate>Fri, 06 Sep 2019 05:16:27 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17721</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17721.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17721</wfw:commentRss><description>&lt;p&gt;Haigh, Laura.&lt;/p&gt;
&lt;p&gt;An bhfuil rud ar bith go maith leat a labhairt?&lt;/p&gt;
&lt;p&gt;Is maith liom an picti&amp;uacute;r ar do phr&amp;oacute;if&amp;iacute;l den scann&amp;aacute;n &amp;quot;Laura&amp;quot;.&amp;nbsp; Is &amp;eacute; scann&amp;aacute;n go maith, agus is maith liom an t&amp;eacute;amamhr&amp;aacute;n.&amp;nbsp; N&amp;iacute; raibh fh&amp;iacute;os agam go bhfuil focail ar an t&amp;eacute;amamhr&amp;aacute;n.&amp;nbsp; An bhfuil fh&amp;iacute;os agat na focail?&amp;nbsp; Chuala m&amp;eacute; na focail ar thaifead&amp;aacute;n le &amp;quot;Spike Jones and the City Slickers&amp;quot;.&amp;nbsp; Bh&amp;iacute; siad gr&amp;uacute;pa ceolt&amp;oacute;ir&amp;iacute; i mbliana 1940s-1950s, cos&amp;uacute;il le &amp;quot;Weird Al Yankovich&amp;quot;.&amp;nbsp; Rinne siad taifead&amp;aacute;n go maith agus aon greannmhar....&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Dia Daoibh</title><link>http://talkirish.com/forums/thread/17720.aspx</link><pubDate>Wed, 04 Sep 2019 17:32:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17720</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17720.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17720</wfw:commentRss><description>&lt;p&gt;
&lt;p class="MsoNormal"&gt;&lt;span class="quote"&gt;&lt;span&gt;N&amp;iacute; m&amp;oacute;r dom
tabhairt go d&amp;aacute;ir&amp;iacute;re faoin foghlaim.&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class="MsoNormal"&gt;&lt;span&gt;Labhair liom.&amp;nbsp;&lt;/span&gt;&lt;span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>