<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Prayer Translation to Irish</title><link>http://talkirish.com/forums/thread/15453.aspx</link><pubDate>Tue, 14 Feb 2017 13:00:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15453</guid><dc:creator>ohara2017</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15453.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15453</wfw:commentRss><description>&lt;p&gt;I have, just not at this point in time. I definitely hope to learn it some day!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Prayer Translation to Irish</title><link>http://talkirish.com/forums/thread/15452.aspx</link><pubDate>Tue, 14 Feb 2017 03:09:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15452</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15452.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15452</wfw:commentRss><description>&lt;p&gt;Not a problem at all. &amp;nbsp;Have you considered learning Irish? &amp;nbsp;There&amp;#39;s plenty of resources out there to get you started and the other members have much more information on the matter as well.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Prayer Translation to Irish</title><link>http://talkirish.com/forums/thread/15451.aspx</link><pubDate>Tue, 14 Feb 2017 03:05:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15451</guid><dc:creator>ohara2017</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15451.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15451</wfw:commentRss><description>&lt;p&gt;Hi Ryan,&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Yes this is for a tattoo so i definitely want to make sure it&amp;#39;s translated properly.&lt;/p&gt;
&lt;p&gt;Thanks for the insight!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Prayer Translation to Irish</title><link>http://talkirish.com/forums/thread/15450.aspx</link><pubDate>Tue, 14 Feb 2017 03:00:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15450</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15450.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15450</wfw:commentRss><description>&lt;p&gt;Dia dhuit, a ohara!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;It&amp;#39;s a good thing you chose not to trust google translate. &amp;nbsp;It&amp;#39;s good for simple translations but full sentences are more than not incorrect. &amp;nbsp;I&amp;#39;m far from fluent but I can offer my advice; this translation definitely isn&amp;#39;t correct. &amp;nbsp;All I can offer is to confirm your suspisions of GT and tell you that &amp;quot;Bealtaine&amp;quot; refers to the month May. &amp;nbsp;I assume that this is for a tattoo?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;-Ryan&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Prayer Translation to Irish</title><link>http://talkirish.com/forums/thread/15449.aspx</link><pubDate>Mon, 13 Feb 2017 15:22:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15449</guid><dc:creator>ohara2017</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15449.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=15449</wfw:commentRss><description>&lt;p&gt;Hi there,&lt;/p&gt;
&lt;p&gt;I&amp;#39;d like to get a short prayer translated, but I don&amp;#39;t trust Google translator. Hoping to get clarification for an accurate translation!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;quot;May my thoughts be Thy thoughts&lt;/p&gt;
&lt;p&gt;May my words be Thy words&lt;/p&gt;
&lt;p&gt;May my desires be Thy desires&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;This is the google translation - I substituted &amp;#39;your&amp;#39; instead of &amp;#39;Thy&amp;#39; I don&amp;#39;t know if there is a proper translation for that.&lt;/p&gt;
&lt;p&gt;&amp;quot;Bealtaine mo chuid smaointe a bheith do chuid smaointe&lt;/p&gt;
&lt;p&gt;Bealtaine mo focail a bheith do chuid focal&lt;/p&gt;
&lt;p&gt;Bealtaine mo mian le do mian&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Any and all feedback would be much appreciated!!&lt;/p&gt;
&lt;p&gt;Thanks a million&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>