<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/17734.aspx</link><pubDate>Wed, 18 Sep 2019 06:33:04 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17734</guid><dc:creator>Brodiese</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17734.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=17734</wfw:commentRss><description>&lt;p&gt;yes you &lt;a href="https://www.stlcurioshoppe.com/v-tight-gel-review/" target="_blank" title="https://www.stlcurioshoppe.com/v-tight-gel-review/"&gt;v tight gel&lt;/a&gt; are right :)&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11958.aspx</link><pubDate>Thu, 01 Oct 2015 00:15:02 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11958</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11958.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11958</wfw:commentRss><description>&lt;p&gt;As to dictionaries, I really like www.irishdictionary.ie, not only because it&amp;#39;s a really good online dictionary, but because it also includes sample uses for many words, and many of the samples provide idiomatic examples of their usage or the ideographic constructs needed to say the similar thing in English. &amp;nbsp;I find it very valuable at times.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11957.aspx</link><pubDate>Thu, 01 Oct 2015 00:11:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11957</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11957.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11957</wfw:commentRss><description>&lt;p&gt;Whoa!&lt;/p&gt;
&lt;p&gt;&amp;quot;Everyone knows&amp;quot; -- &lt;i&gt;T&amp;aacute; a fhios ag madra&amp;iacute; na sr&amp;aacute;ide&amp;quot;&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;This seems to be an expression said more in exaggeration, if not in outright contempt. &amp;nbsp;I would give the literal translations as, &amp;quot;Even the dogs on the street know ... &amp;quot; &amp;nbsp;Not exactly complementary. &amp;nbsp;I&amp;#39;m sure you could also say, &lt;i&gt;T&amp;aacute; a fhios ag gach duine.&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11955.aspx</link><pubDate>Tue, 29 Sep 2015 22:52:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11955</guid><dc:creator>evnmrphy</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11955.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11955</wfw:commentRss><description>&lt;p&gt;Ceapaim - I think&lt;/p&gt;
&lt;p&gt;I mo thuairim - in my opinion&lt;/p&gt;
&lt;p&gt;I mo bhar&amp;uacute;il - in my opinion&lt;/p&gt;
&lt;p&gt;Ach - but&lt;/p&gt;
&lt;p&gt;Agus - and&lt;/p&gt;
&lt;p&gt;&amp;Aacute;fach - however&lt;/p&gt;
&lt;p&gt;Feictear domsa - it seems to me&lt;/p&gt;
&lt;p&gt;T&amp;aacute; a fhios ag madra&amp;iacute; na sr&amp;aacute;ide &amp;nbsp;- everyone knows&lt;/p&gt;
&lt;p&gt;Ar nd&amp;oacute;igh - of course&lt;/p&gt;
&lt;p&gt;Measaim - I think&lt;/p&gt;
&lt;p&gt;S&amp;iacute;lim - I think&lt;/p&gt;
&lt;p&gt;Mar - because&lt;/p&gt;
&lt;p&gt;Mar gheall ar - as a result of&lt;/p&gt;
&lt;p&gt;Chomh maith leis sin - as well as that&lt;/p&gt;
&lt;p&gt;Ina theannta sin - on top of that&lt;/p&gt;
&lt;p&gt;Nuair - while/when&lt;/p&gt;
&lt;p&gt;Le linn/i rith - during&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11846.aspx</link><pubDate>Wed, 29 Apr 2015 16:16:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11846</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11846.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11846</wfw:commentRss><description>&lt;p&gt;Mary, a chara.&lt;/p&gt;
&lt;p&gt;Seo cupla nasc dhuit. T&amp;aacute; s&amp;uacute;il a&amp;#39;m go mbeidh siad ina gcuidi&amp;uacute; leat.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Cora Cainte (Idioms)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.scoilgaeilge.org/lessons/GLee.htm" target="_blank"&gt;http://www.scoilgaeilge.org/lessons/GLee.htm&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;C&amp;oacute;naisc (Conjunctions)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://nualeargais.ie/gnag/conaisc.htm" target="_blank"&gt;http://nualeargais.ie/gnag/conaisc.htm&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://nualeargais.ie/gnag/gram.htm" target="_self"&gt;http://nualeargais.ie/gnag/gram.htm&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Focl&amp;oacute;ir&amp;iacute; (Dictionaries)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/en/" target="_blank"&gt;http://www.focloir.ie/en/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.teanglann.ie/en/" target="_blank"&gt;http://www.teanglann.ie/en/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight:bold;"&gt;I think...&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/en/search/ei/adv?q=i+think&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=" target="_blank"&gt;http://www.focloir.ie/en/search/ei/adv?q=i+think&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;I find...&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/en/search/ei/adv?q=i+find&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=" target="_blank"&gt;http://www.focloir.ie/en/search/ei/adv?q=i+find&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;In my opinion...&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/en/search/ei/adv?q=in+my+opinion&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=" target="_self"&gt;http://www.focloir.ie/en/search/ei/adv?q=in+my+opinion&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;I forget...&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/en/search/ei/adv?q=i+forget&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=" target="_self"&gt;http://www.focloir.ie/en/search/ei/adv?q=i+forget&amp;amp;inlanguage=en&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Agus tuilleadh de mhaoil mo mhainge fh&amp;eacute;in...&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;De mhaoil mo mhainge fh&amp;eacute;in / off the top of my head, off my own back, on my own initiative&lt;/p&gt;
&lt;p&gt;Chomh fada le mo bhar&amp;uacute;il fh&amp;eacute;in / In my opinion, as far as I know, as far as I&amp;#39;m concerned etc.&lt;/p&gt;
&lt;p&gt;Chomh fada le me bhar&amp;uacute;ilse&amp;nbsp;/ In my opinion, as far as I know, as far as I&amp;#39;m concerned etc.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;span class="eid trg clickable"&gt;A&lt;span class="diclick"&gt;r&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;feadh&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;mo&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;bhar&amp;uacute;la / In my opinion&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l tuairim na ngr&amp;aacute;st agam / I haven&amp;#39;t a notion, haven&amp;#39;t a clue etc.&lt;/p&gt;
&lt;p&gt;Ar na bac&amp;aacute;in / On the cards, in the pipeline, on the horizon&lt;/p&gt;
&lt;p&gt;Sin a chloch is l&amp;uacute; ar mo phaidr&amp;iacute;n / That&amp;#39;s the least fo my concerns, least of my worries&lt;/p&gt;
&lt;p&gt;Sin a chloch is m&amp;oacute; ar mo phaidr&amp;iacute;n / That&amp;#39;s my main concern&lt;/p&gt;
&lt;p&gt;T&amp;aacute; mo bholg thiar ar mo dhroim ag an ocras / I&amp;#39;m famished&amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; mo chuid put&amp;oacute;ga&amp;iacute; ag ithe a ch&amp;eacute;ile le hocras / I&amp;#39;m famished&amp;nbsp;&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l m&amp;eacute; basctha anois ar chor ar bith / I&amp;#39;m not bad now at all, I&amp;#39;m grand etc.&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l aon chaill orm / I&amp;#39;m not bad, I&amp;#39;m grand etc.&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; a dh&amp;oacute;thain farraige faoi / He was plenty drunk&lt;/p&gt;
&lt;p&gt;Bh&amp;iacute; s&amp;eacute; ina chaora le &amp;oacute;l / He was very drunk&lt;/p&gt;
&lt;p&gt;D&amp;#39;&amp;oacute;lfadh s&amp;eacute; an Chroch Ch&amp;eacute;asta den asal / He&amp;#39;s well able to drink (He&amp;#39;d drink the the cross (Cross of the Crucifixion) off a donkey&amp;#39;s back)&lt;/p&gt;
&lt;p&gt;Uair sa naoi dtr&amp;aacute;th / Once in a blue moon&lt;/p&gt;
&lt;p&gt;T&amp;aacute; an deabhal (diabhal) d&amp;eacute;anta anois / There&amp;#39;ll be trouble now, the shite has hit the fan etc.&lt;/p&gt;
&lt;p&gt;Thug m&amp;eacute; an deabhal le n-ithe dh&amp;oacute; / I gave him hell, gave him a good talking to etc.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; galra cabach air / He&amp;#39;s loose lipped, can&amp;#39;t keep a secret&lt;/p&gt;
&lt;p&gt;N&amp;iacute; f&amp;eacute;&amp;iacute;dir hata b&amp;aacute;n a r&amp;aacute; leis / He&amp;#39;s awful touchy, can&amp;#39;t say boo to him, can&amp;#39;t say a word to him without him starting an argument&lt;/p&gt;
&lt;p&gt;T&amp;aacute; codladh g&amp;eacute; air / He&amp;#39;s pretending to sleep&lt;/p&gt;
&lt;p&gt;Codladh na headra / Sleep late, lie-in (literally, sleeping until the late-morning milking)&lt;/p&gt;
&lt;p&gt;Ceochodladh / Lightsleep&lt;/p&gt;
&lt;p&gt;T&amp;aacute; mar&amp;uacute; madadh d&amp;#39;airgead aige / He&amp;#39;s loaded (with money)&lt;/p&gt;
&lt;p&gt;T&amp;aacute; l&amp;aacute;n carr asail aige d&amp;#39;airgead / He&amp;#39;s loaded (has an ass cart full of money, or anything else for that matter, to express plenty)&lt;/p&gt;
&lt;p&gt;N&amp;iacute; fi&amp;uacute; tr&amp;aacute;ithn&amp;iacute;n &amp;eacute; / It&amp;#39;s worthless&lt;/p&gt;
&lt;p&gt;Hata b&amp;aacute;n a chur ar dhuine / To impoverish someone, ruin someone&lt;/p&gt;
&lt;p&gt;T&amp;aacute; m&amp;eacute; b&amp;aacute;naithe / I&amp;#39;m cleaned out, broke, no money&lt;/p&gt;
&lt;p&gt;T&amp;aacute; talamh faoi / He has a high opinion of himself&lt;/p&gt;
&lt;p&gt;T&amp;aacute; port na bhfiacal agam (ag an bhfuacht) / My teeth are chattering (from the cold)&amp;nbsp;&lt;/p&gt;
&lt;p&gt;N&amp;aacute; hinis do do l&amp;aacute;imh dheas &amp;eacute; / Keep it to yourself, don&amp;#39;t tell a soul&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;eacute; chomh sleamhain le punt ime / He&amp;#39;s a slippery character, not to be trusted (slippery as a pound of butter)&lt;/p&gt;
&lt;p&gt;Ag cur ime ar a chuid ar&amp;aacute;in fh&amp;eacute;in at&amp;aacute; s&amp;eacute; / He&amp;#39;s looking out for number one (buttering his own bread)&lt;/p&gt;
&lt;p&gt;Eisteacht na heas&amp;oacute;ige a bheith agat / To have sharp hearing&lt;/p&gt;
&lt;p&gt;T&amp;aacute; siad ar aon r&amp;oacute;pa amh&amp;aacute;in / They&amp;#39;re workin g together, pulling together&lt;/p&gt;
&lt;p&gt;T&amp;aacute; an saol ina dheabhal (dhiabhal) / Life&amp;#39;s a *** (an then you die)!&lt;/p&gt;
&lt;p&gt;T&amp;aacute; an saol ina chad&amp;aacute;s / What&amp;#39;s the world coming to, the world is going to hell (in a hand basket), going pear-shaped etc.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; saol na bhfu&amp;iacute;oll agat, sh&amp;iacute;lfe&amp;aacute; / Looks like you have the life, like a pig in clover, living in the lap of luxury etc.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;To say &lt;i&gt;&amp;#39;it was (very) helpful&amp;#39;&lt;/i&gt;,&amp;nbsp;I&amp;#39;d probably say &lt;i&gt;&amp;#39;ba mh&amp;oacute;r an cuid&amp;iacute;u liom &amp;eacute;&amp;#39;&lt;/i&gt; n&amp;oacute;&amp;nbsp;&lt;i&gt;&amp;#39;bh&amp;iacute; s&amp;eacute; ina chuidi&amp;uacute; m&amp;oacute;r liom&amp;#39;&lt;/i&gt;.&lt;/p&gt;
&lt;p&gt;In speech, you might round that off with a &lt;i&gt;bail &amp;oacute; Dhia ort!&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Bhi s&amp;eacute; ina chuidi&amp;uacute; m&amp;oacute;r liom, bail &amp;oacute; Dhia ort!&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go n-&amp;eacute;ir&amp;iacute; leat!&lt;/p&gt;
&lt;p&gt;Barra&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11832.aspx</link><pubDate>Tue, 21 Apr 2015 22:05:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11832</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11832.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11832</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Dale a chara,&lt;/p&gt;
&lt;p&gt;Lorg m&amp;eacute; i an B&amp;iacute;obla chun teacht ar an bhfocal &amp;#39; cabhrach . &amp;quot; ( T&amp;aacute; a fhios agam an leabhar go maith . ) T&amp;aacute; s&amp;eacute; seo &amp;oacute; Philemon , 1.11 - b&amp;#39;fh&amp;eacute;idir go bhfuil an freagra anseo?&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&amp;quot;Ba bheag an &lt;span style="text-decoration:underline;"&gt;&lt;b&gt;chabhair&lt;/b&gt;&lt;/span&gt; duitse tr&amp;aacute;th &amp;eacute; ach is f&amp;oacute;inteach duitse agus domsa anois &amp;eacute;.&amp;quot;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Cad a cheapann t&amp;uacute;? Is &amp;eacute; sin an focal ceart? &lt;b&gt;&lt;span style="text-decoration:underline;"&gt;&amp;#39;chabair&amp;#39;?&amp;nbsp;&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11829.aspx</link><pubDate>Tue, 21 Apr 2015 19:51:54 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11829</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11829.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11829</wfw:commentRss><description>&lt;p&gt;Mary a chara,&lt;/p&gt;
&lt;p&gt;Is maith sin. &amp;nbsp;Lorg m&amp;eacute; san focl&amp;oacute;ir ag an focal &amp;quot;cabhrach&amp;quot;. &amp;nbsp;Ghlac m&amp;eacute; roinnt f&amp;eacute;ach le focl&amp;oacute;ir a faigh do bhr&amp;iacute; mar &amp;quot;helpful&amp;quot;. &amp;nbsp;N&amp;iacute;l a fh&amp;iacute;os agam m&amp;aacute;s at&amp;aacute; sl&amp;iacute; fearr a r&amp;aacute; &amp;quot;It was helpful&amp;quot;.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11827.aspx</link><pubDate>Tue, 21 Apr 2015 14:28:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11827</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11827.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11827</wfw:commentRss><description>&lt;p&gt;Go raibh m&amp;iacute;le maith agat go m&amp;oacute;r. Bh&amp;iacute; s&amp;eacute; &amp;nbsp;cabhrach. (An bhfuil s&amp;eacute; ceart?)&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11826.aspx</link><pubDate>Tue, 21 Apr 2015 07:14:36 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11826</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11826.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11826</wfw:commentRss><description>&lt;p&gt;Hi Mary.&lt;/p&gt;
&lt;p&gt;For &amp;quot;on line&amp;quot; I have always seen &amp;quot;ar line&amp;quot;. &amp;nbsp;The online dictionary gives two versions: &amp;quot;ar line&amp;quot; and &amp;quot;arline&amp;quot; so I assume the words &amp;quot;on line&amp;quot; can be contracted in Irish to form &amp;quot;online&amp;quot; just the same as in English.&lt;/p&gt;
&lt;p&gt;I have seen two ways for saying &amp;quot;I think...&amp;quot; but one way for thinking and the other for an opinion:&lt;/p&gt;
&lt;p&gt;&lt;i&gt;S&amp;iacute;lim&lt;/i&gt;&amp;nbsp;is &amp;quot;I think&amp;quot; as in thinking about something.&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Is d&amp;oacute;igh liom&lt;/i&gt;&amp;nbsp;is &amp;quot;I believe, My opinion is,&amp;quot; and perhaps could include &amp;quot;I find,&amp;quot; if it is more opinion than conclusion, and &amp;quot;In my opinion&amp;quot; would be included.&lt;/p&gt;
&lt;p&gt;My hardcopy dictionary gives &amp;quot;&lt;i&gt;Mo dhearmad!&amp;quot; &lt;/i&gt;for &amp;quot;I forgot!&amp;quot; &amp;nbsp;&amp;quot;...&lt;i&gt;dearmad a dh&amp;eacute;anamh&amp;quot; &lt;/i&gt;is shown as &amp;quot;I forget&amp;quot; something. &amp;nbsp;The word &lt;i&gt;dearmad&lt;/i&gt;&amp;nbsp;is shown as the verb &amp;quot;forget&amp;quot; but is also listed as nouns &amp;quot;lapse, mistake, or oversight&amp;quot;. &amp;nbsp;Sorry that&amp;#39;s not more cut-and-dried....&lt;/p&gt;
&lt;p&gt;Conjunctions:&lt;/p&gt;
&lt;p&gt;&amp;quot;and&amp;quot; = &lt;i&gt;agus&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&amp;quot;but&amp;quot; = &lt;i&gt;ach&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&amp;quot;or&amp;quot; = &lt;i&gt;n&amp;oacute;&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;/i&gt;&amp;quot;Nor&amp;quot; can be &lt;i&gt;n&amp;aacute;&lt;/i&gt;&amp;nbsp;(not or, &amp;quot;or&amp;quot; in the negative&amp;quot;) but is also &amp;quot;than&amp;quot;&lt;/p&gt;
&lt;p&gt;Not positive how to ask the questions you pose, but I hope someone will answer those, as I would like to know those as well....&lt;/p&gt;
&lt;p&gt;Dale d&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11824.aspx</link><pubDate>Mon, 20 Apr 2015 09:17:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11824</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11824.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11824</wfw:commentRss><description>&lt;p&gt;Oh, and how would you say: I posted it online? &amp;#39;&lt;span&gt;Sa phost m&amp;eacute; &amp;eacute; (something instead of &amp;eacute;)&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;And &amp;#39;how do you spell that?&amp;#39;&lt;/p&gt;
&lt;p&gt; &amp;#39;how do you say that?&amp;#39; &lt;/p&gt;
&lt;p&gt;&amp;#39;how do you pronounce that?&amp;#39;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Conjunctions and so on.</title><link>http://talkirish.com/forums/thread/11823.aspx</link><pubDate>Mon, 20 Apr 2015 09:00:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11823</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11823.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11823</wfw:commentRss><description>&lt;p&gt;T&amp;aacute;im ag lorg gramada&amp;iacute; maith ar an idirl&amp;iacute;on. (N&amp;iacute;l an abairt seo ceart.&amp;nbsp;&lt;span&gt;T&amp;aacute; br&amp;oacute;n orm.&lt;/span&gt;)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Also, I am looking for conjunctions, and phrases like:&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I think,&lt;/p&gt;
&lt;p&gt;I find,&lt;/p&gt;
&lt;p&gt;In my opinion&lt;/p&gt;
&lt;p&gt;I forget&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;(ie, words you can use as a hinge to connect sentences.)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Oh - and interesting idioms. But the most important thing at the moment would be to find a comprehensive list of idioms.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>