<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8077.aspx</link><pubDate>Mon, 04 Feb 2013 20:19:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8077</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8077.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8077</wfw:commentRss><description>Fantastic news!! GRMA a Mhichelle!!&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8075.aspx</link><pubDate>Mon, 04 Feb 2013 18:00:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8075</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8075.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8075</wfw:commentRss><description>&lt;p&gt;Hi, Michelle.&lt;/p&gt;
&lt;p&gt;Thanks for letting us know about that, it&amp;#39;s exciting to think of having more than three times the words available!&lt;/p&gt;
&lt;p&gt;I must apologize for my lack of good form in my post, I should have said &amp;quot;a Mhichelle&amp;quot; as Bama did in his post, but I didn&amp;#39;t catch that in time.&amp;nbsp; Sorry!&lt;/p&gt;
&lt;p&gt;Also, I was working on the little on the phrase you have at the bottom of your posts, and just wanted to check my translation:&lt;/p&gt;
&lt;p&gt;&amp;quot;Two languages are better than one.&amp;quot;&amp;nbsp; Is that correct?&lt;/p&gt;
&lt;p&gt;Thanks again!&amp;nbsp; I&amp;#39;m looking forward to the additional words.&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8073.aspx</link><pubDate>Mon, 04 Feb 2013 15:29:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8073</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8073.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8073</wfw:commentRss><description>&lt;p&gt;N&amp;aacute; habair &amp;eacute;! And thanks for your patience...we will be releasing about 1,000 words (including the 365 already there) but we&amp;#39;re trying to figure out the best possible way to do this. &lt;/p&gt;
&lt;p&gt;When we started this website, we had virtually no mobile traffic. Now we have lots of users coming here from hundreds of different devices. So we have to see how we can publish content that&amp;#39;s accessible to the most people on the most popular devices. T&amp;aacute; s&amp;eacute; crua go leor!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8068.aspx</link><pubDate>Sat, 02 Feb 2013 00:00:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8068</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8068.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8068</wfw:commentRss><description>&lt;p&gt;I won&amp;#39;t argue with that for a second!&lt;/p&gt;
&lt;p&gt;Go raibh maith agat, Michelle, agus ag duine eile a beith ag obair lena!&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8067.aspx</link><pubDate>Fri, 01 Feb 2013 22:31:57 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8067</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8067.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8067</wfw:commentRss><description>Is fior sin , Dale :).  I&amp;#39;m like the kid in the candy shop...I want as much as I
can get lol
However, you did have two very good points.
But, since I&amp;#39;m feeling greedy today, I also wish we had a forum for
those of us who are learning Irish from the &amp;quot;Word a Day&amp;quot; so we could
practice what we are learning. ;-) 
The main thing is to thank Michelle and everyone else who works so hard
to give us free access to learn Irish and to keep it up and running.
It can&amp;#39;t be easy. Soooo...GRMA a Mhichelle agus everyone responsible
for TalkIrish!! :)&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8064.aspx</link><pubDate>Thu, 31 Jan 2013 18:28:54 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8064</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8064.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8064</wfw:commentRss><description>&lt;p&gt;I understand what you mean...although, to be fair, there are two alternative considerations.&lt;/p&gt;
&lt;p&gt;One is that the learning process is facilitated through repedition, so repeating them isn&amp;#39;t necessarily a bad thing.&amp;nbsp; Although it does seem to limit us to 365 words.&lt;/p&gt;
&lt;p&gt;Secondarily, when new people join the site, they probably need that initial set of words.&amp;nbsp; I know I haven&amp;#39;t mastered all of them yet.&lt;/p&gt;
&lt;p&gt;So maybe we need a &amp;quot;Set 2&amp;quot; of words that could be selected once you&amp;#39;ve been through the first group?&lt;/p&gt;
&lt;p&gt;Of course, there is the &amp;quot;Seanfhocal&amp;quot; section that provides some significant additions to the vocabulary and grammar, but sometimes idiomatic Irish doesn&amp;#39;t leave you clear as to the meaning of the words within an expression....&lt;/p&gt;
&lt;p&gt;I back your basic premise that it would be great to have more words, but maybe Michelle can look at a way of doing that without losing the first set.&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Word A day?</title><link>http://talkirish.com/forums/thread/8061.aspx</link><pubDate>Thu, 31 Jan 2013 18:16:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8061</guid><dc:creator>jorgea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8061.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=8061</wfw:commentRss><description>&lt;p&gt;I think posting new Irish words for the community to learn is a great idea for http://www.talkirish.com &amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Word A day?</title><link>http://talkirish.com/forums/thread/7958.aspx</link><pubDate>Wed, 02 Jan 2013 21:10:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7958</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7958.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=7958</wfw:commentRss><description>I love the Daily Irish section but I noticed they are repeating
the same words lately. Will new words be added soon?
GRMA&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>