<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: An bhfuil Tuigim i gceart?</title><link>http://talkirish.com/forums/thread/11852.aspx</link><pubDate>Wed, 29 Apr 2015 19:09:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11852</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11852.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11852</wfw:commentRss><description>&lt;p&gt;Thank you again! You&amp;#39;ve been a great help today.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: An bhfuil Tuigim i gceart?</title><link>http://talkirish.com/forums/thread/11848.aspx</link><pubDate>Wed, 29 Apr 2015 18:59:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11848</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11848.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11848</wfw:commentRss><description>&lt;p&gt;leabhar na r&amp;uacute;n / (the) book of secrets&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/r%C3%BAn"&gt;http://www.teanglann.ie/en/gram/r%C3%BAn&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;leabhar na gcrann / (the) book of trees&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/crann"&gt;http://www.teanglann.ie/en/gram/crann&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;leabhar na gaoise (or&amp;nbsp;leabhar&amp;nbsp;na heagna) / (the) book of wisdom&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/gaois"&gt;http://www.teanglann.ie/en/gram/gaois&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/eagna"&gt;http://www.teanglann.ie/en/gram/eagna&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;leabhar an &amp;aacute;thais (or leabhar na l&amp;uacute;ch&amp;aacute;ire) / (the) book of joy&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/%C3%A1thas"&gt;http://www.teanglann.ie/en/gram/%C3%A1thas&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a target="_blank" href="http://www.teanglann.ie/en/gram/l%C3%BAch%C3%A1ir"&gt;http://www.teanglann.ie/en/gram/l%C3%BAch%C3%A1ir&lt;/a&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>An bhfuil Tuigim i gceart?</title><link>http://talkirish.com/forums/thread/11845.aspx</link><pubDate>Wed, 29 Apr 2015 14:49:27 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11845</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11845.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11845</wfw:commentRss><description>&lt;pre id="tw-target-text" class="tw-data-text vk_txt tw-ta tw-text-small"&gt;&lt;b&gt;leabhar na r&amp;uacute;in &lt;/b&gt;- book of secrets
&lt;b&gt;leabhar na gcrann &lt;/b&gt;- book of trees
&lt;b&gt;leabhar de ghaois &lt;/b&gt;- book of wisdom
&lt;b&gt;leabhar an-&amp;aacute;thas &lt;/b&gt;- book of joy&lt;/pre&gt;
&lt;pre id="tw-target-text" class="tw-data-text vk_txt tw-ta tw-text-small"&gt;&lt;/pre&gt;
&lt;pre id="tw-target-text" class="tw-data-text vk_txt tw-ta tw-text-small"&gt;An bhfuil siad ceart? Go raibh maith agat!&lt;/pre&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>