<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: correct spelling</title><link>http://talkirish.com/forums/thread/14751.aspx</link><pubDate>Sat, 29 Oct 2016 14:48:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14751</guid><dc:creator>Safesuli</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14751.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14751</wfw:commentRss><description>&lt;p&gt;hmmm maybe it only shows on my computer because I&amp;#39;ve got the font installed.&lt;/p&gt;
&lt;p&gt;Here&amp;#39;s a link to the font I&amp;#39;m gonna use http://www.gaelchlo.com/bunarsgc.html&lt;/p&gt;
&lt;p&gt;It&amp;#39;s called Bunchl&amp;oacute; &amp;aacute;rsa GC.&lt;/p&gt;
&lt;h1&gt;&lt;/h1&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: correct spelling</title><link>http://talkirish.com/forums/thread/14750.aspx</link><pubDate>Sat, 29 Oct 2016 11:19:02 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14750</guid><dc:creator>Safesuli</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14750.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14750</wfw:commentRss><description>&lt;p&gt;Thank you very much. I totally forgot about that. The font only shows on computer. I&amp;#39;ll take a picture and post it here when I have my computer on.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: correct spelling</title><link>http://talkirish.com/forums/thread/14749.aspx</link><pubDate>Sat, 29 Oct 2016 09:37:16 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14749</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14749.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14749</wfw:commentRss><description>&lt;p&gt;Hi&lt;/p&gt;
&lt;p&gt;Spelling is correct except for missing fadas (accents on characters in &lt;i&gt;&amp;aacute;it&lt;/i&gt;, &lt;i&gt;chro&amp;iacute;&lt;/i&gt; and &lt;i&gt;th&amp;uacute;&lt;/i&gt;). These are essential.&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;i&gt;An &amp;aacute;it a bhfuil do chro&amp;iacute;, is ann a thabharfas do chosa th&amp;uacute;&lt;/i&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The font looks like some standard serif font. Not sure if it&amp;#39;s meant to be a gaelic font, but if so, it&amp;#39;s not displaying.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>correct spelling</title><link>http://talkirish.com/forums/thread/14748.aspx</link><pubDate>Thu, 27 Oct 2016 19:02:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14748</guid><dc:creator>Safesuli</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14748.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14748</wfw:commentRss><description>&lt;p&gt;Hello&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;ve got an Ireland themed tattoo and I want this saying tattooed around it in a half circle. I won&amp;#39;t be back to the place in Ireland where I got the tattoo anytime soon, so I have to get it done here in Germany.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Is spelling and font correct? A tattoo after all are for a life time and mistakes hard to correct.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thank you very much in advance.&lt;/p&gt;
&lt;p&gt;Sarah&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;h1 class="western"&gt;&lt;span style="color:#181818;"&gt;&lt;span style="font-family:IrishUnciAlphabet;"&gt;&lt;span style="font-size:xx-large;"&gt;An
ait a bhfuil do chroi is ann a thabharfas do chosa thu&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>