<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Buntús Cainte learners</title><link>http://talkirish.com/forums/41.aspx</link><description>Are you using Buntús Cainte to learn Irish? Check out this forum where you can practice what you've learned in Buntús Cainte, ask for help or share tips on learning!</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Learning sufficient Gaelige to pass my Scrúduithe na hArdteistiméireachta and to use it in everyday life.</title><link>http://talkirish.com/forums/thread/11978.aspx</link><pubDate>Wed, 04 Nov 2015 17:14:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11978</guid><dc:creator>Phase</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11978.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=11978</wfw:commentRss><description>&lt;p&gt;Hi Dylan!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;so just wondering how things went for you, did you do as well as you&amp;#39;d hoped in your leaving cert, and do you still keep up the Irish in everyday life?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;All the best&lt;/p&gt;
&lt;p&gt;Phaso&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Learning sufficient Gaelige to pass my Scrúduithe na hArdteistiméireachta and to use it in everyday life.</title><link>http://talkirish.com/forums/thread/7913.aspx</link><pubDate>Fri, 07 Dec 2012 09:09:11 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7913</guid><dc:creator>Dylan_64</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7913.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=7913</wfw:commentRss><description>&lt;p&gt;Well I would like a bit of help from you guys, would appreciate it a lot!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Learning sufficient Gaelige to pass my Scrúduithe na hArdteistiméireachta and to use it in everyday life.</title><link>http://talkirish.com/forums/thread/7910.aspx</link><pubDate>Thu, 06 Dec 2012 11:43:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7910</guid><dc:creator>danielm</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7910.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=7910</wfw:commentRss><description>&lt;p&gt;good luck with this!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Google translate is a great tool!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Learning sufficient Gaelige to pass my Scrúduithe na hArdteistiméireachta and to use it in everyday life.</title><link>http://talkirish.com/forums/thread/7905.aspx</link><pubDate>Wed, 05 Dec 2012 02:08:35 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:7905</guid><dc:creator>Dylan_64</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/7905.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=7905</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;div&gt;
&lt;div&gt;Dia duit!&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;I&amp;#39;m Irish just to start off. All I&amp;#39;d like to do is learn enough Irish to pass my Leaving Cert. in 2014. I would like to know how to put sentences together and how to remember how they go together. All I know to date is: T&amp;aacute; = Present tense, Bh&amp;iacute; = Past tense and that a verb is always first in a sentence. An&amp;nbsp;example&amp;nbsp;of a sentence I know is: Bh&amp;iacute; Jimmy go dt&amp;iacute; an teach t&amp;aacute;bhairne gach Aoine, which is: Jimmy went to the pub every Friday and T&amp;aacute; m&amp;eacute;/T&amp;aacute;&amp;iacute;m tuirseach: I&amp;#39;m tired.&lt;/p&gt;
&lt;p&gt;I would like to know enough Irish to be able to talk in a Gaeltacht when I leave school, to be able to have a conversation in irish with my Irish teacher because he&amp;#39;s great craic! Also I&amp;#39;d like to be able to do my Irish oral without saying &amp;quot;eh&amp;quot; all the time through out it all. I currently do Ordinary Level Irish and got a B in my Junior Cert. at Ordinary Level too. I&amp;#39;d like to chance an Honours/Higher Level paper but I&amp;nbsp;&lt;span&gt;doubt very much&lt;/span&gt;&amp;nbsp;I&amp;#39;d be able to pass it. Most of the time I use Google Translate to do my obair bhaile and I know that it&amp;#39;s inaccurate.&lt;/p&gt;
&lt;p&gt;Go raibh m&amp;iacute;le maith agat.&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>