<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Name pronunciation</title><link>http://talkirish.com/forums/thread/8452.aspx</link><pubDate>Thu, 11 Jul 2013 21:59:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8452</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8452.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8452</wfw:commentRss><description>&lt;p&gt;Hi Eirinn, I think Dale&amp;#39;s right, it kind of looks right (apart from the nh, which looks a bit Vietnamese to me) but the poem you mention is about Romans and Celts, and of course the Romans never made it to Ireland, or not in large numbers anyway. It might be some kind of Welsh but it is perhaps just a name invented by the author of the poem. &lt;/p&gt;
&lt;p&gt;It&amp;#39;s certainly an interesting name but I couldn&amp;#39;t vouch for its authenticity. There are lots of nice Irish names and lots of websites. If you have any other names you want to check, post them here and we can advise you on the best spellings and the pronunciation. &lt;/p&gt;
&lt;p&gt;Hope this helps! &lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Name pronunciation</title><link>http://talkirish.com/forums/thread/8433.aspx</link><pubDate>Mon, 08 Jul 2013 16:45:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8433</guid><dc:creator>Eirinn</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8433.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8433</wfw:commentRss><description>&lt;p&gt;Thanks for the suggestion list, Dale. I like how they have the pronunciations already listed.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;From what research I have done, it appears that &amp;quot;Arienh&amp;quot; is a name of Celtic origin, but it could have been altered over time. Because it&amp;#39;s not very well-known or popular, it&amp;#39;s difficult to find much information on it, although I have seen it used in a couple of Irish-themed publications, such as the poem &amp;quot;The Celtic Queen&amp;quot; as seen &lt;a href="http://books.google.com/books?id=uEsipoJ0pFYC&amp;amp;pg=PA13&amp;amp;lpg=PA13&amp;amp;dq=arienh+celtic&amp;amp;source=bl&amp;amp;ots=rBfFEKzmpk&amp;amp;sig=rzy4D5wMHlfw7f1evq2OnGB69xk&amp;amp;hl=en&amp;amp;sa=X&amp;amp;ei=u9zaUeaSMsfj4AOco4CICA&amp;amp;ved=0CGwQ6AEwCzgK#v=onepage&amp;amp;q=arienh%20celtic&amp;amp;f=false"&gt;here&lt;/a&gt;.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Either way, it does seem pretty obscure. If anyone happens to be familiar with it or can attest to its authenticity, I&amp;#39;d appreciate any input. &amp;nbsp;Otherwise I may stick to the more well-founded names.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Name pronunciation</title><link>http://talkirish.com/forums/thread/8432.aspx</link><pubDate>Mon, 08 Jul 2013 16:30:28 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8432</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8432.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8432</wfw:commentRss><description>&lt;p&gt;Hello.&lt;/p&gt;
&lt;p&gt;I have a former work associate who has this name, but spells it quite differently, and pronounces it with your first option.&lt;/p&gt;
&lt;p&gt;But I question whether this is an Irish name, or certainly not the Irish spelling in any case, as it does not follow the broad/slender vowel convention, and also has an &amp;quot;h&amp;quot; after the &amp;quot;n&amp;quot;, and I don&amp;#39;t think that combination occurs in Irish.&amp;nbsp; I could be wrong, but don&amp;#39;t remember seeing it anywhere.&lt;/p&gt;
&lt;p&gt;Conventional vowel construction in Irish is designed to give the consonants their broad or slender quality.&amp;nbsp; The broad vowels are a, o, and u; the slender are e and i.&amp;nbsp; The rule is, when you have a broad vowel on one side of a consonant, you need a broad vowel on the other side to balance it for pronunciation.&amp;nbsp; That is clearly not the case in the spelling you have given.&amp;nbsp; To make it fit the rule, you would have to insert either an e or an i after the initial A, or insert an o, u or a before the i.&amp;nbsp; The first option would be most likely, probably with an i being inserted there.&amp;nbsp; Of course, that would make it conform to the spelling conventions in Irish, but wouldn&amp;#39;t necessarily make it an Irish name!&lt;/p&gt;
&lt;p&gt;A quick search of Yahoo! brings up a number of sites on Irish names.&amp;nbsp; I like this one in particular:&amp;nbsp; &lt;a href="http://www.namenerds.com/irish/lists.html"&gt;http://www.namenerds.com/irish/lists.html&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;If you are looking for a truly Irish name, that might be a good place to start.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Name pronunciation</title><link>http://talkirish.com/forums/thread/8431.aspx</link><pubDate>Mon, 08 Jul 2013 16:16:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8431</guid><dc:creator>Eirinn</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8431.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8431</wfw:commentRss><description>&lt;p&gt;Hello,&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I was wondering if anyone knew the correct pronunciation of the name &amp;quot;Arienh.&amp;quot; &amp;nbsp;I have seen both Ah-ree-en and Ah-reen, and even an Air-ee-ain. I am considering it as a possible name for my baby, but wanted to make sure I was saying it correctly.&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>