<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16553.aspx</link><pubDate>Tue, 07 Nov 2017 17:17:09 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16553</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16553.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16553</wfw:commentRss><description>&lt;p&gt;Oops! &amp;nbsp;Thanks for catching that, Laura. &amp;nbsp;I was typing faster than my brain was thinking. &amp;nbsp;I looked up the right word and got the right translation, but I apparently was thinking of something backwards.....&lt;/p&gt;
&lt;p&gt;Dearthair&amp;iacute;n &amp;oacute; mo chro&amp;iacute; = &amp;quot;Little brother of my heart.&amp;quot;&lt;/p&gt;
&lt;p&gt;Sorry if I confused anyone....&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16552.aspx</link><pubDate>Tue, 07 Nov 2017 08:45:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16552</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16552.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16552</wfw:commentRss><description>&lt;p&gt;Deirfi&amp;uacute;r n&amp;oacute; dearth&amp;aacute;ir, a Dale?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16551.aspx</link><pubDate>Tue, 07 Nov 2017 04:48:05 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16551</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16551.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16551</wfw:commentRss><description>&lt;p&gt;Okay...a bit at a time here.&lt;/p&gt;
&lt;p&gt;&amp;quot;Dearthair&amp;iacute;n &amp;oacute; mo chro&amp;iacute;&amp;quot; is &amp;quot;little sister of my heart.&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;quot;Jemmy mo Veela Store&amp;quot; is an Anglicization of &amp;quot;Jimmy mo mh&amp;iacute;le st&amp;oacute;r&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;quot;Cianach Corrach&amp;quot; means &amp;quot;uneasy melancholy&amp;quot; or something similar.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16550.aspx</link><pubDate>Tue, 07 Nov 2017 01:12:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16550</guid><dc:creator>Bama</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16550.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16550</wfw:commentRss><description>&lt;p&gt;Maith this !!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16549.aspx</link><pubDate>Mon, 06 Nov 2017 20:47:36 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16549</guid><dc:creator>livil.s</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16549.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16549</wfw:commentRss><description>&lt;p&gt;Hello, Dale D,&lt;/p&gt;
&lt;p&gt;Thank you for the corrections and for the meaning of the title :D I&amp;#39;m glad this will help people who have the same issue!&lt;/p&gt;
&lt;p&gt;My priority was to find the title of the song. Once I found it, I started to search for its lyrics, but there are slightly different versions and I&amp;#39;m not able to figure out which is the right one. So I&amp;#39;d be happy if you help me understand but take your time, it&amp;#39;s not essential to me :) I only want to add something I&amp;#39;ve found over the net: the song is also known as &amp;quot;Drahaareen O Mochree&amp;quot; (Dearthair&lt;span&gt;&amp;iacute;&lt;/span&gt;n-&lt;span&gt;&amp;oacute;&lt;/span&gt; Mo Chro&lt;span&gt;&amp;iacute;&lt;/span&gt;) or &amp;quot;Jemmy mo Veela Sthore&amp;quot; and there&amp;#39;s an alternate version called &amp;quot;Cianach Corrach&amp;quot; (correct me if I missed fada marks).&lt;/p&gt;
&lt;p&gt;livil.s&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16534.aspx</link><pubDate>Fri, 03 Nov 2017 16:10:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16534</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16534.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16534</wfw:commentRss><description>&lt;p&gt;Hello, livil.s.&lt;/p&gt;
&lt;p&gt;You are close! &amp;nbsp;But your written translation is missing a couple of fada marks (like accent marks, but they govern the pronunciation of the vowel).&lt;/p&gt;
&lt;p&gt;&amp;quot;Jimmy mo mh&amp;iacute;le st&amp;oacute;r&amp;quot; (with fada marks on the &amp;quot;i&amp;quot; in &amp;quot;mh&amp;iacute;le&amp;quot; and the &amp;quot;o&amp;quot; in &amp;quot;st&amp;oacute;r&amp;quot; means, &amp;quot;Jimmy my dearest love&amp;quot;.&lt;/p&gt;
&lt;p&gt;I am not familiar with the song, so I don&amp;#39;t know how much else I can tell you at the moment. &amp;nbsp;When I have some time I may check out your link and have a listen, but can&amp;#39;t take the time at the moment.....&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Irish song translation</title><link>http://talkirish.com/forums/thread/16532.aspx</link><pubDate>Fri, 03 Nov 2017 12:10:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16532</guid><dc:creator>livil.s</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16532.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16532</wfw:commentRss><description>&lt;p&gt;Guys, I found it! The title is &amp;quot;Jimmy mo mhile stor&amp;quot;, I found it by coincidence :)))&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Irish song translation</title><link>http://talkirish.com/forums/thread/16531.aspx</link><pubDate>Thu, 02 Nov 2017 11:28:17 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:16531</guid><dc:creator>livil.s</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/16531.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=16531</wfw:commentRss><description>&lt;p&gt;Hi everybody,&lt;br /&gt;I have this five-year-old recording 
from an Irish radio and I&amp;#39;ll be immensely grateful to whoever helps me 
understand what the song title is or at least what the speaker and the 
song say. I&amp;#39;ve tried searching for something on youtube and google, but I can&amp;#39;t even define which genre or how old it is.&lt;br /&gt;Here is the link to the file &lt;a target="_blank" href="https://mega.nz/#!KxNjEQZD!j6GNyodi1Tmi3GIIQiG8vMkxNTwMfenmixUTQ5VlmP8"&gt;https://mega.nz/#!KxNjEQZD!j6GNyodi1Tmi3GIIQiG8vMkxNTwMfenmixUTQ5VlmP8&lt;/a&gt;&lt;br /&gt;I&amp;#39;m
 sorry for the low quality. You can listen to the voice of the speaker 
before and after the song (it&amp;#39;s a bit long), I don&amp;#39;t know which is the 
comment to it, maybe neither  &lt;img title="Sad" alt=":(" src="http://www.irishgaelictranslator.com/phpbb/images/smilies/icon_sad.gif" /&gt;&lt;br /&gt;Thank you all in advance, it&amp;#39;s very very important to me!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>