<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6069.aspx</link><pubDate>Wed, 25 Aug 2010 05:31:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6069</guid><dc:creator>ÉamonnÓCatháin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6069.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6069</wfw:commentRss><description>&lt;p&gt;You are correct in that In&amp;iacute;on means a &amp;#39;daughter&amp;#39;.&lt;/p&gt;
&lt;p&gt;But how are you is &amp;quot;Conas at&amp;aacute; t&amp;uacute;&amp;quot;, &amp;quot;C&amp;Eacute;N CHAOI INA BHFUIL T&amp;Uacute;&amp;quot; (your second example is incorrect).&lt;/p&gt;
&lt;p&gt;Neither of these expressions are used in Ulster irish, where we say &amp;quot;Goid&amp;eacute; mar at&amp;aacute; t&amp;uacute;&amp;quot; but the other examples would be understood.&lt;/p&gt;
&lt;p&gt;Congratulations on the youtube clips, excellent work! &lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6068.aspx</link><pubDate>Wed, 25 Aug 2010 05:28:54 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6068</guid><dc:creator>ÉamonnÓCatháin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6068.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6068</wfw:commentRss><description>&lt;p&gt;Deirfi&amp;uacute;r (&amp;lt;deirbh-shi&amp;uacute;r) is the word for &amp;#39;sister&amp;#39; and your phonetic approximation of its pronunciation is spot on.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;The word for a daughter is &amp;quot;in&amp;iacute;on&amp;quot;.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6011.aspx</link><pubDate>Mon, 09 Aug 2010 18:05:50 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6011</guid><dc:creator>Dioluin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6011.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6011</wfw:commentRss><description>&lt;p&gt;Is Deirf&amp;uacute;ir the word your thinking of? That means&amp;nbsp;Sister. In&amp;iacute;on is daughter.&lt;/p&gt;
&lt;p&gt;I&amp;#39;m pretty sure it is anyway. &lt;/p&gt;
&lt;p&gt;&amp;#39;How are you?&amp;#39; can be either - Conas at&amp;aacute; t&amp;uacute;? or C&amp;eacute; ca bhfuil t&amp;uacute;?(K caw vwill to)&lt;/p&gt;
&lt;p&gt;I am fine - T&amp;aacute; m&amp;eacute; ceart go leor. (Taw may keyart guh lor)&lt;/p&gt;
&lt;p&gt;Thank you - Go raibh maith agat (Guh rev mot a-gut)&lt;/p&gt;
&lt;p&gt;Check out my youtube page and Lesson 2. Basic Conversation goes through things like this. :)&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.youtube.com/watch?v=5g-2QCQmdss"&gt;(Please visit the site to view this media)&lt;/a&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6010.aspx</link><pubDate>Mon, 09 Aug 2010 15:22:51 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6010</guid><dc:creator>Tuinean</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6010.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6010</wfw:commentRss><description>&lt;p&gt;Is there any conversational gaelic on this website? I would like to learn how to say the basics such as &amp;#39;Good morning&amp;#39;, &amp;#39;Good Evening&amp;#39;, &amp;#39;How are you&amp;#39;, &amp;#39;I am fine, thank you&amp;#39;, etc.......&lt;/p&gt;
&lt;p&gt;Thanks again all!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Donna&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6009.aspx</link><pubDate>Mon, 09 Aug 2010 15:05:27 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6009</guid><dc:creator>Tuinean</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6009.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6009</wfw:commentRss><description>&lt;p&gt;I like it but it may be a little confusing to people like me with NO gaelic experience. For instance, the word daughter in the lessons on this website is pronounced (as close to english as I can tell) &amp;#39;Jer-eh-fur&amp;#39; but you pronounce it differently. Which is correct? There are other similar examples where the pronounciation is different. &lt;/p&gt;
&lt;p&gt;Any direction and assistance in pronouncing these words would be greatly appreciated!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thanks much!&lt;/p&gt;
&lt;p&gt;Donna&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/6003.aspx</link><pubDate>Sun, 08 Aug 2010 18:07:10 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6003</guid><dc:creator>Kathleen167</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6003.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6003</wfw:commentRss><description>&lt;p&gt;I really like it. keep making these !&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5997.aspx</link><pubDate>Thu, 05 Aug 2010 21:47:49 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5997</guid><dc:creator>Dioluin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5997.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5997</wfw:commentRss><description>&lt;p&gt;Go raibh maith agat Michelle!&lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5996.aspx</link><pubDate>Thu, 05 Aug 2010 21:46:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5996</guid><dc:creator>Dioluin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5996.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5996</wfw:commentRss><description>&lt;p&gt;Lesson 2. Basic Conversation&lt;/p&gt;
&lt;p&gt;(Please visit the site to view this media)&lt;/p&gt;
&lt;p&gt;Lesson 3. Numbers&lt;/p&gt;
&lt;p&gt;&lt;span style="text-decoration:underline;"&gt;&lt;span style="color:#800080;"&gt;&lt;a href="http://www.youtube.com/watch?v=pf3H6SPLqds&amp;amp;feature=related"&gt;(Please visit the site to view this media)&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Lesson 4. The Hotel&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.youtube.com/watch?v=niTyObiKOlw&amp;amp;feature=channel"&gt;(Please visit the site to view this media)&lt;/a&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5988.aspx</link><pubDate>Thu, 05 Aug 2010 03:47:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5988</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5988.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5988</wfw:commentRss><description>&lt;p&gt;Go h-iontach - go raibh maith agat!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5987.aspx</link><pubDate>Wed, 04 Aug 2010 14:05:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5987</guid><dc:creator>CaisleanOir</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5987.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5987</wfw:commentRss><description>&lt;p&gt;Excellent! &lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5982.aspx</link><pubDate>Tue, 03 Aug 2010 09:42:23 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5982</guid><dc:creator>Maripat</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5982.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5982</wfw:commentRss><description>Tá an-mhaith, I love it.  More GRMA!&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Beginers lessons on youtube</title><link>http://talkirish.com/forums/thread/5980.aspx</link><pubDate>Mon, 02 Aug 2010 21:31:03 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:5980</guid><dc:creator>Dioluin</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/5980.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=5980</wfw:commentRss><description>&lt;p&gt;I am putting up a series of video&amp;#39;s with basic phrase&amp;#39;s and vocab that is good for beginners. Check it out. &lt;br /&gt;This is lesson 1. People &lt;br /&gt;(Please visit the site to view this media)&lt;br /&gt;&lt;br /&gt;For more go to: &lt;a target="_blank" href="http://www.youtube.com/Dioluin"&gt;http://www.youtube.com/Dioluin&lt;/a&gt; &lt;br /&gt;&lt;br /&gt;Let me know what you think!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>