<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Need help finding an Irish poem/verse/song</title><link>http://talkirish.com/forums/thread/11844.aspx</link><pubDate>Sat, 25 Apr 2015 05:48:31 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11844</guid><dc:creator>sadams1068</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11844.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11844</wfw:commentRss><description>&lt;p&gt;I am looking for an old poem that my mother used to tell me... It talked about t2o women talking in the back yard and one says to the other, between the heat of the day and the kids to beat and the sweat of the night and my aching feet, the baby on one side wanting to suck and ======== on the other side wanting to ----- or never mind you have problems of your own, &amp;nbsp;Any body heard of it, Please respond to sadams@infowest.com&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Need help finding an Irish poem/verse/song</title><link>http://talkirish.com/forums/thread/9591.aspx</link><pubDate>Sun, 08 Dec 2013 18:24:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9591</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9591.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=9591</wfw:commentRss><description>&lt;p&gt;Great! I hope your grandfather enjoys hearing it again! &lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Need help finding an Irish poem/verse/song</title><link>http://talkirish.com/forums/thread/9590.aspx</link><pubDate>Thu, 05 Dec 2013 15:20:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9590</guid><dc:creator>Priceless668</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9590.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=9590</wfw:commentRss><description>&lt;p&gt;Yes! &amp;nbsp;This is absolutely it. &amp;nbsp;Thank you so much for the hints on how to find an mp3 version of it, I downloaded it from Amazon&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thanks again!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Need help finding an Irish poem/verse/song</title><link>http://talkirish.com/forums/thread/9582.aspx</link><pubDate>Sun, 01 Dec 2013 15:48:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9582</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9582.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=9582</wfw:commentRss><description>&lt;p&gt;Hi, This is the kind of thing that TalkIrish excels at, so I&amp;#39;m glad to say we can help you out here! The song is quite famous. It is called Cill Aod&amp;aacute;in and it was written by Antoine &amp;Oacute; Raifteiri, or Raftery the Poet as he&amp;#39;s sometimes known in English. &lt;/p&gt;
&lt;p&gt;These are the words of Cill Aod&amp;aacute;in:&lt;/p&gt;
&lt;p&gt;Anois teacht an earraigh &lt;/p&gt;
&lt;p&gt;beidh an l&amp;aacute; ag dul chun s&amp;iacute;neadh,&lt;/p&gt;
&lt;p&gt;Is tar &amp;eacute;is na f&amp;eacute;il Br&amp;iacute;de&lt;/p&gt;
&lt;p&gt;ard&amp;oacute;idh m&amp;eacute; mo sheol.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;Oacute; chuir m&amp;eacute; i mo cheann &amp;eacute;&lt;/p&gt;
&lt;p&gt;n&amp;iacute; ch&amp;oacute;n&amp;oacute;idh me cho&amp;iacute;che&lt;/p&gt;
&lt;p&gt;Go seasfaidh m&amp;eacute; s&amp;iacute;os&lt;/p&gt;
&lt;p&gt;i l&amp;aacute;r Chontae Mhaigh Eo.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I gCl&amp;aacute;r Chlainne Mhuiris&lt;/p&gt;
&lt;p&gt;A bheas m&amp;eacute; an ch&amp;eacute;ad o&amp;iacute;che,&lt;/p&gt;
&lt;p&gt;Is i mBalla taobh th&amp;iacute;os de&lt;/p&gt;
&lt;p&gt;A thos&amp;oacute;idh m&amp;eacute; ag &amp;oacute;l.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go Coillte M&amp;aacute;ch rachaidh&lt;/p&gt;
&lt;p&gt;Go nd&amp;eacute;anfadh cuairt mh&amp;iacute;osa ann&lt;/p&gt;
&lt;p&gt;I bhfogas dh&amp;aacute; mh&amp;iacute;le&lt;/p&gt;
&lt;p&gt;Do Bh&amp;eacute;al an &amp;Aacute;tha Mh&amp;oacute;ir&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Here&amp;#39;s a rough English version:&lt;/p&gt;
&lt;p&gt;Now&amp;#39;s the coming of spring &lt;/p&gt;
&lt;p&gt;the day will be lengthening,&lt;/p&gt;
&lt;p&gt;And after St Brigid&amp;#39;s day&lt;/p&gt;
&lt;p&gt;I will raise my sail.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;Since I thought of it&lt;/p&gt;
&lt;p&gt;I will not stop at all&lt;/p&gt;
&lt;p&gt;Until I will stand down&lt;/p&gt;
&lt;p&gt;in the middle of County Mayo.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;In Claremorris&lt;/p&gt;
&lt;p&gt;I will be the first night,&lt;/p&gt;
&lt;p&gt;And in&amp;nbsp;Balla beside it&lt;/p&gt;
&lt;p&gt;I will begin to drink.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;To Kiltimagh I will go&lt;/p&gt;
&lt;p&gt;To stay for a month,&lt;/p&gt;
&lt;p&gt;Near enough two miles&lt;/p&gt;
&lt;p&gt;From Ballinamore.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;This may not be completely accurate but it&amp;#39;s near enough. It&amp;#39;s not exactly the same version on the Wiki article about Raftery but I think it makes more sense. I can&amp;#39;t find a YouTube version (it&amp;#39;s a really nice tune) but you should be able to find a version of it on Amazon - there&amp;#39;s one by Gear&amp;oacute;id&amp;iacute;n Bhreathnach which will cost you about a dollar to download!&lt;/p&gt;
&lt;p&gt;Hope this is what you&amp;#39;re looking for (I think it must be). All the best!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Need help finding an Irish poem/verse/song</title><link>http://talkirish.com/forums/thread/9575.aspx</link><pubDate>Sun, 24 Nov 2013 21:40:51 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:9575</guid><dc:creator>Priceless668</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/9575.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=9575</wfw:commentRss><description>&lt;p&gt;Hello!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;My grandfather speaks Irish and learned it in school. &amp;nbsp;However, he lives far away from me and is getting quite old and his memory is starting to go. &amp;nbsp;He always recited this certain thing to me in Irish every time I see him. &amp;nbsp;I don&amp;#39;t know the Irish words but he told me the English translation:&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;quot;Now comes the Spring. &amp;nbsp;The days are growing longer. &amp;nbsp;And after the feast of St. Bridget, I will raise my sail. &amp;nbsp;And I will put it in my mind that I will not hesitate until I stand in County Mayo.&amp;quot;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I would really appreciate it if anyone could give me any help about where I could find the Irish words to this. &amp;nbsp;He told me he thinks it came from a song, so if you know the title of the song or where I can find that, even better!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Go raibh maith agat!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>