<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11673.aspx</link><pubDate>Sun, 22 Feb 2015 23:13:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11673</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11673.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11673</wfw:commentRss><description>&lt;p&gt;&lt;span&gt;Is
iad na litreacha ORI giorr&amp;uacute;ch&amp;aacute;n ar &amp;#39;original.&amp;#39;&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11668.aspx</link><pubDate>Thu, 19 Feb 2015 05:10:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11668</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11668.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11668</wfw:commentRss><description>&lt;p&gt;Go raibh maith agat.&lt;/p&gt;
&lt;p&gt;Is cuimhin liom an scann&amp;aacute;n seo a fheice&amp;aacute;il fad&amp;oacute;. &amp;nbsp;Bh&amp;iacute; s&amp;eacute; sultmhar.&lt;/p&gt;
&lt;p&gt;Cad &amp;eacute; at&amp;aacute; t&amp;uacute; a r&amp;aacute; lena litriacha &amp;quot;ORI&amp;quot; i ndiaidh do sloinne? &amp;nbsp;An bhfuil siad cuid do sloinne iad?&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11666.aspx</link><pubDate>Thu, 19 Feb 2015 02:50:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11666</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11666.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11666</wfw:commentRss><description>&lt;p&gt;T&amp;aacute;. T&amp;aacute; s&amp;eacute; as scann&amp;aacute;n sin.&amp;nbsp;Ba &amp;eacute; an scann&amp;aacute;n is fearr leis m&amp;#39;athair.&lt;/p&gt;
&lt;p&gt;N&amp;iacute;l. N&amp;iacute;l m&amp;eacute; d&amp;eacute;annamh Skype go f&amp;oacute;ill. B&amp;iacute;onn s&amp;eacute; dom r&amp;oacute;-fhada a chun freagra.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;uacute;il agam labhairt go maith go leor chun Skype go luath.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11665.aspx</link><pubDate>Wed, 18 Feb 2015 05:52:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11665</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11665.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11665</wfw:commentRss><description>&lt;p&gt;An bhfuil an picti&amp;uacute;r i do pr&amp;oacute;if&amp;iacute;l don scann&amp;aacute;n &amp;quot;Laura&amp;quot;?&lt;/p&gt;
&lt;p&gt;An bufuil t&amp;uacute; &amp;quot;Skype&amp;quot; a dh&amp;eacute;anamh?&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11664.aspx</link><pubDate>Sun, 15 Feb 2015 11:40:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11664</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11664.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11664</wfw:commentRss><description>&lt;p&gt;Is scr&amp;iacute;obh rud maith, a Dale. &lt;img src="http://talkirish.com/emoticons/emotion-5.gif" alt="Wink" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11663.aspx</link><pubDate>Fri, 13 Feb 2015 06:39:34 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11663</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11663.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11663</wfw:commentRss><description>&lt;p&gt;F&amp;aacute;ilte romhat, a Laura.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;uacute;il agam go bhfuil a l&amp;aacute;n daoine a labhair leat anseo. &amp;nbsp;T&amp;aacute; gr&amp;uacute;pa agam ar &amp;quot;Facebook&amp;quot; do labhair as Gaeilge ar &amp;quot;Skype&amp;quot;, agus thug m&amp;eacute; &amp;quot;Gaeilge Skypers&amp;quot; air. T&amp;aacute; l&amp;aacute;n daoine anseo freisin, ach le scr&amp;iacute;obh amh&amp;aacute;in.&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;uacute;il agam go bhfaighe t&amp;uacute; gl&amp;eacute;asa&amp;iacute; maith ar foghlaim. &amp;nbsp;Sl&amp;aacute;n agat!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Labhair Gaeilge Liom (le do theil)</title><link>http://talkirish.com/forums/thread/11662.aspx</link><pubDate>Wed, 11 Feb 2015 18:23:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11662</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11662.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11662</wfw:commentRss><description>&lt;p&gt;Dia daoibh, a dhaoine uaisle.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Bionn an aimsir go h-&amp;aacute;lainn.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;T&amp;aacute; s&amp;uacute;il agam go bhfuil sl&amp;aacute;inte agaibh. &lt;img src="http://talkirish.com/emoticons/emotion-1.gif" alt="Smile" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>