<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: can anyone translate 'Níl dé air' for me please.</title><link>http://talkirish.com/forums/thread/12122.aspx</link><pubDate>Wed, 16 Dec 2015 17:18:22 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12122</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/12122.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=12122</wfw:commentRss><description>&lt;p&gt;&lt;span class="quote"&gt;&lt;i&gt;&amp;#39;N&amp;iacute;l d&amp;eacute; air&amp;#39;&lt;/i&gt; means &amp;#39;&lt;/span&gt;&lt;i&gt;there&amp;#39;s not a trace of him (or it)&amp;#39;, &amp;#39;there&amp;#39;s no sign of him (or it)&amp;#39;, &amp;#39;he&amp;#39;s (or it&amp;#39;s) vanished without a trace&amp;#39;, etc.&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;span class="quote"&gt;The word&amp;nbsp;&lt;i&gt;d&amp;eacute; means smoke, puff, breath, glimmer.&lt;/i&gt;&lt;/span&gt;&lt;/p&gt;
&lt;div&gt;You might also come across&amp;nbsp;&lt;i&gt;&amp;#39;&lt;span&gt;n&amp;iacute;l&lt;/span&gt;&lt;span&gt;&amp;nbsp;&lt;/span&gt;&lt;/i&gt;&lt;span&gt;&lt;i&gt;d&amp;eacute; n&amp;aacute; deatach air&amp;#39;&lt;/i&gt;&amp;nbsp;which has the same meaning as above.&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;&lt;/div&gt;
&lt;div&gt;&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;&lt;a href="http://www.focloir.ie/ga/search/ei/adv?q=d%C3%A9+deatach&amp;amp;inlanguage=ga&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style="&gt;http://www.focloir.ie/ga/search/ei/adv?q=d%C3%A9+deatach&amp;amp;inlanguage=ga&amp;amp;searchin=&amp;amp;pos=&amp;amp;subject=&amp;amp;style=&lt;/a&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;See also a similar useage in &lt;a href="http://www.teanglann.ie/en/fgb/"&gt;&amp;Oacute; D&amp;oacute;naill&amp;#39;s Focl&amp;oacute;ir Gaeilge-B&amp;eacute;arla&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;span class="eid example clickable"&gt;&lt;span class="diclick"&gt;&lt;/span&gt;&lt;/span&gt;&lt;span class="eid example clickable"&gt;&lt;strong&gt;&lt;span class="diclick"&gt;n&amp;iacute;&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;fhacas&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;d&amp;eacute;&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;air&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;le&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;blianta, &lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;span class="eid example clickable"&gt;&lt;i&gt;&lt;span class="eid src clickable"&gt;&lt;span class="diclick"&gt;I&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;haven&amp;#39;t&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;set&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;eyes&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;on&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;him&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;for&lt;/span&gt;&amp;nbsp;&lt;span class="diclick"&gt;years&lt;/span&gt;&lt;/span&gt;&lt;/i&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.teanglann.ie/en/eid/d%C3%A9_air"&gt;http://www.teanglann.ie/en/eid/d%C3%A9_air&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Barra&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: can anyone translate 'Níl dé air' for me please.</title><link>http://talkirish.com/forums/thread/12121.aspx</link><pubDate>Sun, 13 Dec 2015 15:01:58 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:12121</guid><dc:creator>LauraHuntORI</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/12121.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=12121</wfw:commentRss><description>&lt;p&gt;Cad &amp;eacute; an comhth&amp;eacute;acs?&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: can anyone translate 'Níl dé air' for me please.</title><link>http://talkirish.com/forums/thread/11998.aspx</link><pubDate>Wed, 18 Nov 2015 01:29:19 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11998</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11998.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11998</wfw:commentRss><description>&lt;p&gt;The literal translation I have come up with is &amp;quot;Smoke is not on him&amp;quot; but I am certain this is an idiomatic construct. &amp;nbsp;&lt;i&gt;D&amp;eacute;&lt;/i&gt;&amp;nbsp;shows as meaning &amp;quot;smoke&amp;quot; but also &amp;quot;breath&amp;quot; or &amp;quot;puff&amp;quot;.&lt;/p&gt;
&lt;p&gt;I suspect it may mean, &amp;quot;He doesn&amp;#39;t smoke&amp;quot; (as in tobacco products) but I could be mistaken.&lt;/p&gt;
&lt;p&gt;Another possibility is, if&amp;nbsp;&lt;i&gt;d&amp;eacute;&lt;/i&gt;&amp;nbsp;is being used to mean &amp;quot;breath&amp;quot; instead of &amp;quot;smoke&amp;quot;, then it might translate as &amp;quot;He is not breathing.&amp;quot;&lt;/p&gt;
&lt;p&gt;The context of the sentence may be the determining factor.&lt;/p&gt;
&lt;p&gt;Anyone else willing to chime in?&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>can anyone translate 'Níl dé air' for me please.</title><link>http://talkirish.com/forums/thread/11997.aspx</link><pubDate>Tue, 17 Nov 2015 17:59:37 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11997</guid><dc:creator>seanjohnson</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11997.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11997</wfw:commentRss><description>&lt;p&gt;can anyone translate &amp;#39;N&amp;iacute;l d&amp;eacute; air&amp;#39; for me please.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;thanks.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>