<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Irish to Japanese translator.</title><link>http://talkirish.com/forums/thread/17627.aspx</link><pubDate>Fri, 08 Mar 2019 17:31:00 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17627</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17627.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17627</wfw:commentRss><description>&lt;p&gt;Hello, Blaise,&lt;/p&gt;
&lt;p&gt;Because you dealt so well with the subject of this forum, I have approved your post, with this caveat:&amp;nbsp; You need to edit your post to remove the &amp;quot;Reference&amp;quot; to &amp;quot;Video production rates&amp;quot;.&amp;nbsp; This is a site for learning Irish, not one for advertising or promoting business, unless that business directly relates to learning Irish.&amp;nbsp; Ordinarily, I would immediately delete a post with a promotional link embedded, but you show some knowledge of Irish and interest in the language.&lt;/p&gt;
&lt;p&gt;I hope you understand my concern.&amp;nbsp; I have to delete literally thousands of post attempts of people trying to promote products and use the site for advertising.&amp;nbsp; I appreciate your understanding, and hope you will enjoy using the site to help in developing your skills with Irish.&lt;/p&gt;
&lt;p&gt;Thank you.&lt;/p&gt;
&lt;p&gt;Dale Dennis&lt;/p&gt;
&lt;p&gt;Moderator&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Irish to Japanese translator.</title><link>http://talkirish.com/forums/thread/17623.aspx</link><pubDate>Thu, 07 Mar 2019 14:28:56 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:17623</guid><dc:creator>blaise84</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/17623.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=17623</wfw:commentRss><description>&lt;p&gt;&lt;span&gt;Dia dhaoibh, t&amp;aacute; &amp;aacute;thas orm bualadh libh. Blaise at&amp;aacute; orm. Is Astr&amp;aacute;lach m&amp;eacute;. T&amp;aacute; m&amp;eacute; ag foghlaim na Gaeilge le c&amp;uacute;ig bliana is fiche anuas agus t&amp;aacute; m&amp;eacute; i gc&amp;oacute;na&amp;iacute; ag foghlaim!&amp;nbsp;&lt;/span&gt;&lt;img title="Dark laugh" alt=":darklaugh:" src="http://www.irishlanguageforum.com/images/smilies/2daarklaaf.gif" /&gt;&lt;span&gt;&amp;nbsp;&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span&gt;(Hi, nice to meet you all. My name is Blaise. I&amp;#39;m Australian. I have been learning Irish for 25 years and I am still learning!&amp;nbsp;&lt;/span&gt;&lt;img title="Dark laugh" alt=":darklaugh:" src="http://www.irishlanguageforum.com/images/smilies/2daarklaaf.gif" /&gt;&lt;span&gt;&amp;nbsp;)&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span&gt;Why Irish? I fell in love with Irish music (Clannad) and then I discovered the language that goes with it. I lived in Tokyo for sixteen years and made five trips to Ireland in all. (At one stage I was teaching Irish to Japanese students at a private language school in Tokyo.) Now I sing songs in Irish and play uilleann pipes here in Oz.&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span&gt;Let us know what sparked _your_ interest in Irish.&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Blaise&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Reference:&lt;/p&gt;
&lt;p&gt;&lt;a href="https://www.izideo.com/blog/ideal-video-production-rates/"&gt;video production rates&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>