<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Buntús Cainte learners</title><link>http://talkirish.com/forums/41.aspx</link><description>Are you using Buntús Cainte to learn Irish? Check out this forum where you can practice what you've learned in Buntús Cainte, ask for help or share tips on learning!</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Learn Irish with Buntús Cainte on your iPad - award-winning new app!</title><link>http://talkirish.com/forums/thread/10031.aspx</link><pubDate>Wed, 07 May 2014 11:41:04 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:10031</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/10031.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=41&amp;PostID=10031</wfw:commentRss><description>&lt;p&gt;Really excited to say we released our &lt;a href="https://itunes.apple.com/us/app/learn-irish-gaelic-buntus/id852572204?mt=8&amp;amp;uo=4"&gt;Bunt&amp;uacute;s Cainte Irish Course for Beginners &lt;/a&gt;last week. Most of you know we&amp;#39;ve been working on this iPad app for over a year. But it&amp;#39;s finally out there!&lt;/p&gt;
&lt;p&gt;On release last week, it hit the number 1 slot in the Irish education category and hit number 20 in the UK Education category. And a few weeks earlier, the app won Best App award at the Celtic Media Festival &lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="https://itunes.apple.com/us/app/learn-irish-gaelic-buntus/id852572204?mt=8&amp;amp;uo=4"&gt;Learn Irish with Bunt&amp;uacute;s Cainte&lt;/a&gt; is the result of a co-production between us and &lt;a href="http://www.mgalba.com"&gt;MG ALBA&lt;/a&gt; (BBC Scotland). We decided to pool our resources to create an app for learners of Irish and Scots Gaelic that is as beautiful, effective and rich as any app produced for major world languages like Spanish or English.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;During the production period, we collaborated with great actors, award-winning illustrator &lt;a href="http://twitter.com/ja_illustrator"&gt;Julie-Anne Graham&lt;/a&gt;, instructional designers and language-learning geeks. The result is our gorgeous and engaging language learning app with 60 lessons, more than 1,000 bespoke illustrations, 1,800 native speaker audio files and 3,000 test questions and learning games that take full advantage of the iPad&amp;rsquo;s touchscreen.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Personally, I&amp;#39;ve been blown away by how much people love our quizzes! We developed five question types that test different aspects of language mastery, and I wrote over 3,000 quiz questions. That was a tonne of work, but the questions are a huge hit with our learners.&lt;/p&gt;
&lt;p&gt;So, are we on Android? Well...not yet! We decided to develop our iPad app first after analysing the traffic on www.talkirish.com &amp;ndash; over 70% of mobile traffic currently comes from iOS devices. However, we&amp;#39;re now hard at work on a HTML5 version of the course for desktop and Android tablets - visit &lt;a href="http://buntuscainte.com"&gt;http://buntuscainte.com&lt;/a&gt; to sign up for a release alert.&amp;nbsp;&lt;/p&gt;
&lt;div&gt;Got an iPad? &lt;a href="https://itunes.apple.com/us/app/learn-irish-gaelic-buntus/id852572204?mt=8&amp;amp;uo=4"&gt;Download the app now &lt;/a&gt;and try the first lesson for free!&lt;/div&gt;
&lt;div&gt;&lt;/div&gt;
&lt;div&gt;&lt;/div&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>