<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: How to pronounce the surname 'Crehan'</title><link>http://talkirish.com/forums/thread/15680.aspx</link><pubDate>Sat, 18 Mar 2017 15:59:14 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:15680</guid><dc:creator>dairire</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/15680.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=15680</wfw:commentRss><description>&lt;p&gt;Hello,&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I was born in Ireland and my last name is Crean, no &amp;#39;H&amp;#39;.&lt;/p&gt;
&lt;p&gt;I can send you the history of your name if you&amp;#39;d like to send me your email address because Crean was the orginal name. The family came down from the Sligo area to fight in the battle of Kinsale and as they went back home again they settled in Kerry, Clare, East Galway, Roscommon, Sligo and a little farther up. The name changed from Crean, to Crehan and Cregan as they settled along that strip from Kerry up to Sligo.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;It&amp;#39;s pronounced Cree-han though Crean is often pronounced &amp;quot;Crane&amp;quot; in the west of Ireland.&lt;/p&gt;
&lt;p&gt;Check out&amp;nbsp;&lt;/p&gt;
&lt;p&gt;https://en.wikipedia.org/wiki/Junior_Crehan&lt;/p&gt;
&lt;p&gt;https://en.wikipedia.org/wiki/Tom_Crean_(explorer)&lt;/p&gt;
&lt;p&gt;Hope this helps.&lt;/p&gt;
&lt;p&gt;Beannachta&amp;iacute;,&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;Eacute;il&amp;iacute;s Crean&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to pronounce the surname 'Crehan'</title><link>http://talkirish.com/forums/thread/8451.aspx</link><pubDate>Thu, 11 Jul 2013 21:44:37 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8451</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8451.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8451</wfw:commentRss><description>&lt;p&gt;Yes, I would agree more or less with Chelle&amp;#39;s pronunciation. Cree-han is the way it would normally be pronounced. There was a well-known fiddler from Clare called Junior Crehan and there&amp;#39;s a tune known as Junior Crehan&amp;#39;s Favourite. You can find a couple of versions on youtube!&lt;/p&gt;
&lt;p&gt;&lt;img src="http://talkirish.com/emoticons/emotion-2.gif" alt="Big Smile" /&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to pronounce the surname 'Crehan'</title><link>http://talkirish.com/forums/thread/8449.aspx</link><pubDate>Wed, 10 Jul 2013 16:34:08 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8449</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8449.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8449</wfw:commentRss><description>&lt;p&gt;If I were to pronounce it, I&amp;#39;d say &amp;#39;Creh-hann&amp;#39;. That&amp;#39;s my Ulster pronunciation of the English. Not sure how other people would do it!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>How to pronounce the surname 'Crehan'</title><link>http://talkirish.com/forums/thread/8435.aspx</link><pubDate>Tue, 09 Jul 2013 04:18:46 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:8435</guid><dc:creator>Crehan</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/8435.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=8435</wfw:commentRss><description>&lt;p&gt;Hello - I had a question about my last name&amp;#39;s pronunciation. I&amp;#39;ve done a little research and have seen that it mainly traces back to Galway, Ireland. Though, I cannot find the correct or even most common pronunciation of it.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;m from the US and have lived here my entire life, and have always pronounced it as &amp;quot;Cran&amp;quot;, but it never sounded right (and it always gets mistaken as Grant). I&amp;#39;ve been told it&amp;#39;s &amp;quot;Cree-han&amp;quot; or &amp;quot;Cree-haan&amp;quot;, but I never actually asked someone from Ireland. So, here&amp;#39;s my attempt at that. Anyone from Ireland, maybe even the Galway area, that could help me out? Thanks!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>