<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Learn and practice Irish (Gaeilge) online on Skype</title><link>http://talkirish.com/forums/thread/11889.aspx</link><pubDate>Thu, 09 Jul 2015 01:52:38 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11889</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11889.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11889</wfw:commentRss><description>&lt;p&gt;D&amp;aacute; d&amp;eacute;an m&amp;eacute; &amp;aacute;irithint, an bhf&amp;eacute;idir leat ag obair le iPad, n&amp;oacute; an bhfuil r&amp;iacute;omhaire uaim? &amp;nbsp;(Le ceamara?) &amp;nbsp;Anois, d&amp;eacute;anaim Skype ar iPad amh&amp;aacute;in. &amp;nbsp;T&amp;aacute; a hocht uair difr&amp;iacute;ocht ama idir m&amp;eacute; agus t&amp;uacute; freisin. &amp;nbsp;T&amp;aacute; m&amp;eacute; i mo ch&amp;oacute;na&amp;iacute; i California sa St&amp;aacute;it Aontaithe.&lt;/p&gt;
&lt;p&gt;M&amp;aacute; ba maith leat ag scr&amp;iacute;obh tr&amp;iacute; riomhphost, abair &amp;eacute;, agus scr&amp;iacute;obh m&amp;eacute; ar do seoladh riomhphost.&lt;/p&gt;
&lt;p&gt;Go raibh maith agat!&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Learn and practice Irish (Gaeilge) online on Skype</title><link>http://talkirish.com/forums/thread/11888.aspx</link><pubDate>Thu, 09 Jul 2015 00:39:40 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11888</guid><dc:creator>siobhan_ni_m</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11888.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11888</wfw:commentRss><description>&lt;p&gt;Dale, a chara,&lt;/p&gt;
&lt;p&gt;Braitheann an costas ar riachtanais an dalta agus ar ch&amp;uacute;iseanna eile. T&amp;aacute; an ch&amp;eacute;ad cheacht saor in aisce agus r&amp;eacute;itim an praghas leis an ndalta ansin. Geallaim dhuit go bhfuil s&amp;eacute; saor go leor.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Siobh&amp;aacute;n&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Learn and practice Irish (Gaeilge) online on Skype</title><link>http://talkirish.com/forums/thread/11887.aspx</link><pubDate>Wed, 08 Jul 2015 22:47:21 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11887</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11887.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11887</wfw:commentRss><description>&lt;p&gt;C&amp;aacute; bh&amp;eacute;ad at&amp;aacute; ar gach cheacht?&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Learn and practice Irish (Gaeilge) online on Skype</title><link>http://talkirish.com/forums/thread/11885.aspx</link><pubDate>Mon, 29 Jun 2015 20:05:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11885</guid><dc:creator>siobhan_ni_m</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11885.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=11885</wfw:commentRss><description>&lt;p&gt;Dia dhaoibh,&lt;/p&gt;
&lt;p&gt;Caith s&amp;uacute;il ar an su&amp;iacute;omh seo, www.irishandenglish.com, d&amp;aacute; mba rud &amp;eacute; gur mhaith leat do chuid Gaeilge a chleachta ar Skype le cainteoir l&amp;iacute;ofa laeth&amp;uacute;il.&lt;/p&gt;
&lt;p&gt;Have a look at this site, www.irishandenglish.com, if you would like to learn and practice Irish on Skype with a fluent daily speaker.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Beir bua agus beannachta&amp;iacute;!&lt;/p&gt;
&lt;p&gt;Siobh&amp;aacute;n N&amp;iacute; Mhaoildhia&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>