<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: What is the correct way?</title><link>http://talkirish.com/forums/thread/107.aspx</link><pubDate>Tue, 05 Aug 2008 10:55:12 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:107</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/107.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=107</wfw:commentRss><description>&lt;p&gt;&amp;nbsp;That will be fine.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;Slán &lt;br /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: What is the correct way?</title><link>http://talkirish.com/forums/thread/106.aspx</link><pubDate>Tue, 05 Aug 2008 10:28:55 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:106</guid><dc:creator>michelle</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/106.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=106</wfw:commentRss><description>&lt;p&gt;Cianaigh,&lt;/p&gt;
&lt;p&gt;Would this work?&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Last modified &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;nbsp; &lt;/i&gt;&lt;b&gt;Mionathraithe go Deireanach &lt;/b&gt;&lt;/p&gt;
&lt;p&gt;I don&amp;#39;t know if you&amp;#39;ve ever heard of the Microsoft Community Glossary, but I use it for techie terms. It&amp;#39;s a Foras na Gaeilge project, sponsored by Microsoft. It&amp;#39;s basically a bit standardised glossary of IT terminology for the Irish language. It&amp;#39;s useful because the terminology here was used in the Gaeilge version of Windows, so it&amp;#39;s a pretty good standard. It also shows the suggestions made before they settled on a term. &lt;/p&gt;
&lt;p&gt;I find it a bit hard to access - it requires a Windows Live ID and the security cert is out of date, so if you can&amp;#39;t get in, you can always email me with other queries! &lt;/p&gt;
&lt;p&gt;Try this url to see if you can get in:&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.microsoft.com/language/wincg/default.aspx"&gt;http://www.microsoft.com/language/wincg/default.aspx&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Sl&amp;aacute;n go f&amp;oacute;il,&lt;/p&gt;
&lt;p&gt;Michelle&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>What is the correct way?</title><link>http://talkirish.com/forums/thread/104.aspx</link><pubDate>Sun, 03 Aug 2008 17:37:48 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:104</guid><dc:creator>Cianaigh</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/104.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=104</wfw:commentRss><description>&lt;p&gt;What would be the proper way to write &amp;quot;last updated on&amp;quot; in Irish for use on a web page?&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>