<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: glas nó uaine</title><link>http://talkirish.com/forums/thread/11850.aspx</link><pubDate>Wed, 29 Apr 2015 19:06:52 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11850</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11850.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11850</wfw:commentRss><description>&lt;p&gt;That is wonderfully comprehensive answer! Thank you so much! It&amp;#39;s fascinating to realise that the perceptions a culture has of nature and colour can affect language in such a way. And I wouldn&amp;#39;t have realised that Irish had such a wide range of subtleties in colour perception - differentiating between natural and unatural for example. Also the shades you describe do blend together on the colour spectrum, so of course there is no reason why the words we ascribe to certain colours have to be directly interchangeable with those of another language.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thank you very much for going into so much detail, and for the links you have provided.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: glas nó uaine</title><link>http://talkirish.com/forums/thread/11847.aspx</link><pubDate>Wed, 29 Apr 2015 17:50:53 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11847</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11847.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11847</wfw:commentRss><description>&lt;p&gt;Hi Mary,&lt;/p&gt;
&lt;p&gt;This is tricky. There&amp;#39;s no definitive answer (that I can give you). In Irish, colours are interpreted differently than they are in English.&lt;/p&gt;
&lt;p&gt;I&amp;#39;ll try and explain it as I understand it.&lt;/p&gt;
&lt;p&gt;In the simplest terms &lt;i&gt;glas&lt;/i&gt; usually applies to natural greens - grass, vegetation etc. and also related eco terms (the Green Party, &lt;i&gt;green&lt;/i&gt; as in eco-friendly etc.), or &lt;i&gt;green&lt;/i&gt; as in inexperienced, young etc. But &lt;i&gt;uaithne&lt;/i&gt; may also be applied to verdure. depending on the shade of green in question.&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Uaithne/Uaine&lt;/i&gt; usually applies to vivid greens, and dyed or artificial greens. But it&amp;#39;s not as straight cut as that as&amp;nbsp;&lt;i&gt;glas&lt;/i&gt; can be and is used in these situations too and some people will just use &lt;i&gt;glas&lt;/i&gt; for all greens. I don&amp;#39;t know how this plays out accross dialects or if it&amp;#39;s just a school thing or what.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Where it can get confusing is&amp;nbsp;&lt;i&gt;glas&lt;/i&gt; very often means&amp;nbsp;&lt;i&gt;grey &lt;/i&gt;(I would assume &lt;i&gt;grey&lt;/i&gt; before &lt;i&gt;green&lt;/i&gt; if I heard &lt;i&gt;glas&lt;/i&gt;)&lt;i&gt; -&lt;/i&gt;&amp;nbsp;&lt;i&gt;cloch glas&lt;/i&gt; is a grey stone, &lt;i&gt;madadh glas&lt;/i&gt; is a grey dog, &lt;i&gt;sp&amp;eacute;ir ghlas&lt;/i&gt; is grey sky, &lt;i&gt;carr glas&lt;/i&gt; is a grey car but&amp;nbsp;&lt;i&gt;cnoc glas&lt;/i&gt; is a green hill and&amp;nbsp;&lt;i&gt;f&amp;eacute;ar glas&lt;/i&gt; is green grass. I&amp;#39;d really only use &lt;i&gt;liath&lt;/i&gt; for grey where it&amp;#39;s a light grey or almost white colour, or a person&amp;#39;s hair for example. Not for a darkish grey, and usually not for greys in the natural world - animals, the sea, the sky and so on. I might also use &lt;i&gt;glas&lt;/i&gt; for dark, dyed greens but &lt;i&gt;uaine&lt;/i&gt; for the green in the Irish flag, for example.&lt;/p&gt;
&lt;p&gt;If I wrote &amp;eacute;&lt;i&gt;adach glas&lt;/i&gt; I&amp;#39;d mean &lt;i&gt;grey&lt;/i&gt; clothes even though&amp;nbsp;some people might understand that to mean&amp;nbsp;&lt;i&gt;green clothes&lt;/i&gt;. If I wanted to say green clothes, I&amp;#39;d use&amp;nbsp;&lt;i&gt;&amp;eacute;adach uaithne. &lt;/i&gt;If the clothes were a very dark green though, I might use &lt;i&gt;eadach glas&lt;/i&gt; and not distinguish between English grey and English green at all. &lt;/p&gt;
&lt;p&gt;So I guess with &lt;i&gt;glas&lt;/i&gt; I think of it as applying mostly to the natural world, shades of green or grey (and sometimes blue) on the darkish end of the spectrum, with shades of English greens and English greys and some English blues being shades of the Irish&amp;nbsp;&lt;i&gt;glas. Uaithne&lt;/i&gt;&amp;nbsp;on the other hand I&amp;#39;d apply where dyed or bright greens, or vivid, lush greens, are in question.&lt;/p&gt;
&lt;p&gt;While looking for a way to explain myself, I found these blog posts on &lt;i&gt;glas&lt;/i&gt; vs &lt;i&gt;uaine.&lt;/i&gt; Hope they help.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://nimill.blogspot.ie/2010/10/gorm-glas-uaine.html" target="_blank"&gt;http://nimill.blogspot.ie/2010/10/gorm-glas-uaine.html&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://blogs.transparent.com/irish/beoir-uaine-no-glas-no-ceachtar-beer-greenuaine-or-greenglas-or-neither/"&gt;http://blogs.transparent.com/irish/beoir-uaine-no-glas-no-ceachtar-beer-greenuaine-or-greenglas-or-neither/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://blogs.transparent.com/irish/beigil-uaine-no-glas-which-type-of-green-for-bagels/" target="_blank"&gt;http://blogs.transparent.com/irish/beigil-uaine-no-glas-which-type-of-green-for-bagels/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://blogs.transparent.com/irish/aibhneacha-glas-no-uaine-rivers-greenglas-or-greenuaine/" target="_blank"&gt;http://blogs.transparent.com/irish/aibhneacha-glas-no-uaine-rivers-greenglas-or-greenuaine/&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&lt;a href="http://blogs.transparent.com/irish/more-green-ideas-mostly-not-colorless-sorry-chomsky/" target="_blank"&gt;http://blogs.transparent.com/irish/more-green-ideas-mostly-not-colorless-sorry-chomsky/&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Dea-ghu&amp;iacute;,&lt;/p&gt;
&lt;p&gt;Barra&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: glas nó uaine</title><link>http://talkirish.com/forums/thread/11831.aspx</link><pubDate>Tue, 21 Apr 2015 20:07:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11831</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11831.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11831</wfw:commentRss><description>&lt;p&gt;Hello again, Mary!&lt;/p&gt;
&lt;p&gt;Well, I did a search on the site here and found the following exchange:&lt;/p&gt;
&lt;p&gt;http://talkirish.com/forums/p/4269/9983.aspx#9983&lt;/p&gt;
&lt;p&gt;I know it doesn&amp;#39;t elucidate a great deal, but it may help you a bit, and it does teach the proper word for &amp;quot;greenhouse&amp;quot; in Irish, which is &lt;i&gt;not&lt;/i&gt;&amp;nbsp;a direct translation. &amp;nbsp;I can always count on seano to help out with things like that.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: glas nó uaine</title><link>http://talkirish.com/forums/thread/11830.aspx</link><pubDate>Tue, 21 Apr 2015 20:02:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11830</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11830.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11830</wfw:commentRss><description>&lt;p&gt;Hi, Mary.&lt;/p&gt;
&lt;p&gt;Sorry, this response will have to be &lt;i&gt;as B&amp;eacute;arla.&lt;/i&gt;&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Glas&lt;/i&gt;&amp;nbsp;means &amp;quot;green&amp;quot;.&lt;/p&gt;
&lt;p&gt;&lt;i&gt;Uaine&lt;/i&gt;&amp;nbsp;means &amp;quot;vivid green&amp;quot; or &amp;quot;verdure&amp;quot;.&lt;/p&gt;
&lt;p&gt;I remember going through the differences between these a long time ago, and I&amp;#39;m afraid I don&amp;#39;t remember the specifics of the difference in usage, but I think that &amp;quot;uaine&amp;quot; may also be used to refer to a green pasture, or a golf green and the like, but I&amp;#39;m not certain of that.&lt;/p&gt;
&lt;p&gt;If I can run across where I encountered those previously, I&amp;#39;ll get back to you.&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>glas nó uaine</title><link>http://talkirish.com/forums/thread/11828.aspx</link><pubDate>Tue, 21 Apr 2015 14:57:44 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11828</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11828.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=11828</wfw:commentRss><description>&lt;pre&gt;&amp;#39;glas&amp;#39; agus &amp;#39;uaine.&amp;#39; c&amp;eacute;n f&amp;aacute;th &amp;eacute; an difr&amp;iacute;ocht?&lt;/pre&gt;
&lt;pre&gt;&lt;/pre&gt;
&lt;pre&gt;&lt;/pre&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>