<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Irish books, cds, posters, etc</title><link>http://talkirish.com/forums/32.aspx</link><description>Place to discuss what you've bought, where you bought it and what you think of it.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: Teach Yourself Irish by Myles Dillon</title><link>http://talkirish.com/forums/thread/11858.aspx</link><pubDate>Thu, 14 May 2015 18:39:01 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11858</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11858.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=11858</wfw:commentRss><description>&lt;p&gt;Hi, Mary.&lt;/p&gt;
&lt;p&gt;Someone just e-mailed me with the sound files (and a pdf file of the book) for Teach Yourself Irish, and I downloaded them in a zip file. &amp;nbsp;Did they e-mail you as well? &amp;nbsp;If not, I can forward you the link.&lt;/p&gt;
&lt;p&gt;Dale&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: Teach Yourself Irish by Myles Dillon</title><link>http://talkirish.com/forums/thread/11854.aspx</link><pubDate>Thu, 30 Apr 2015 19:34:30 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11854</guid><dc:creator>Dale D</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11854.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=11854</wfw:commentRss><description>&lt;p&gt;Hi, Mary.&lt;/p&gt;
&lt;p&gt;i actually own a (paperback) copy of that book, but it did not include any LPs, cassettes, or other sound file sources. &amp;nbsp;If you do find them, I would appreciate knowing about them!&lt;/p&gt;
&lt;p&gt;it is heavy on grammar, but teaches some essential background items and a very comprehensive, if somewhat mind-boggling list of rules for lenition (which he calls aspiration) and eclipsis. &amp;nbsp;This was the book I bought in a bookstore in Cork, and a friend came up to me and said, &amp;quot;You&amp;#39;ll never learn Irish reading that!&amp;quot; &amp;nbsp;She proceeded to give me her copies of Bunt&amp;uacute;s Cainte, but the books only. &amp;nbsp;I later bought my own copy with the cassette tapes. &amp;nbsp;I do still open up my Teach Yourself book from time to time. &amp;nbsp;It has a very good section on proper names, and possessive constructs, along with other idioms. &amp;nbsp;He also includes a glossary at the end, but it is Irish to English only, and contains only the vocabulary included in the lessons. &amp;nbsp;Also, you should be aware that the older Irish spellings are used, so hopefully that does not introduce many issues.&lt;/p&gt;
&lt;p&gt;Good luck! &amp;nbsp;Let me know if you find the sound files!&lt;/p&gt;
&lt;p&gt;Dale D&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Teach Yourself Irish by Myles Dillon</title><link>http://talkirish.com/forums/thread/11853.aspx</link><pubDate>Wed, 29 Apr 2015 19:13:16 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:11853</guid><dc:creator>Mary Lea</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/11853.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=32&amp;PostID=11853</wfw:commentRss><description>&lt;p&gt;Hi there - I&amp;#39;ve just found an original copy of this book for a pound, and it will be turning up in the next few days. My Dad tells me that it used to come with LPs for the (Munster) pronunciation. (He&amp;#39;s also warned me what to expect - grammar and lots of it, though he assures me it is very practical.)&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Anyway - I have heard it said that, in some mystical internet land, there are mp3s of the original LPs. Which would obviously help pronunciation if it were true.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Does anyone know where I can find sound files? Or if worst comes to worst, where I can find LPs that aren&amp;#39;t scratched to ribbons?&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thank you!&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>