<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>The Irish Language - Grammar, Pronunciation, Games, Myths, Poetry and more</title><link>http://talkirish.com/forums/40.aspx</link><description>A great place to discuss Irish grammar, pronunciation, and vocabulary.  You'll also find lots of help and information on Irish translations, Irish myths and legends, and Irish poetry. And here's where we have some Irish word games and lots of useful tips on language learning.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: How to translate a phrase for a tattoo idea</title><link>http://talkirish.com/forums/thread/14397.aspx</link><pubDate>Fri, 01 Jul 2016 16:31:56 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14397</guid><dc:creator>otuathail</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14397.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14397</wfw:commentRss><description>&lt;p&gt;Hi Anueye&lt;/p&gt;
&lt;p&gt;&lt;b&gt;&lt;i&gt;Until we meet again&lt;/i&gt;&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;Go dt&amp;iacute; go gcasfar ar a ch&amp;eacute;ile ar&amp;iacute;s sinn&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;OR&lt;/p&gt;
&lt;p&gt;&lt;span&gt;Go dt&amp;iacute; go gcasfar ar a ch&amp;eacute;ile ar&amp;iacute;s muid&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to translate a phrase for a tattoo idea</title><link>http://talkirish.com/forums/thread/14396.aspx</link><pubDate>Thu, 30 Jun 2016 06:40:41 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14396</guid><dc:creator>Ryboss47</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14396.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14396</wfw:commentRss><description>&lt;p&gt;Haigh Anueye!&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;d like to be the first to say welcome to the community and I hope you stick with us for a while! &amp;nbsp;Some great helpful members here. &amp;nbsp;I don&amp;#39;t know much so I can&amp;#39;t help, but I promise others will!&lt;/p&gt;
&lt;p&gt;Are you learning Irish as well as the rest of us? &amp;nbsp;I have a slight feeling you may be brand new to the language &lt;img src="http://talkirish.com/emoticons/emotion-5.gif" alt="Wink" /&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>How to translate a phrase for a tattoo idea</title><link>http://talkirish.com/forums/thread/14395.aspx</link><pubDate>Thu, 30 Jun 2016 00:35:07 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:14395</guid><dc:creator>Anueye</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/14395.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=40&amp;PostID=14395</wfw:commentRss><description>&lt;p&gt;Hello, I&amp;#39;ve been working on a memorial tattoo for all my lost loved ones. I was thinking a Gaelic phrase. Something along the lines of &amp;quot;Until we meet again.&amp;quot;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Any suggestions or ideas let me know as well! Thank you!&amp;nbsp;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>