<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://talkirish.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>General</title><link>http://talkirish.com/forums/7.aspx</link><description>This is where general discussions about Ireland and the Irish language take place. Also, if you would like to introduce yourself, please feel free to do that here. We may post announcements about the website in this board from time to time.</description><dc:language>en</dc:language><generator>CommunityServer 2008 SP1 (Build: 30619.63)</generator><item><title>Re: How to pronounce Irish names</title><link>http://talkirish.com/forums/thread/6190.aspx</link><pubDate>Wed, 13 Oct 2010 09:23:29 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6190</guid><dc:creator>caubeen</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6190.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6190</wfw:commentRss><description>&lt;p&gt;Seano,&lt;/p&gt;
&lt;p&gt;Thanks very much for the quick response.&amp;nbsp; I too favor the Ulster sound, but that is probably because that is what my ear was accustomed to in English.&amp;nbsp; However, most of the teaching materials over here in the US are either in standard (&amp;quot;Dublin&amp;quot;) Irish, or else Connacht or Munster.&amp;nbsp; I guess that makes sense, as most of the family connections would have been to the South, but it makes it a bit harder for one to learn the Uladh dialect.&amp;nbsp; I cannot see (hear?) myself sounding like a Galway man, for example, although I do want to be able to understand what he says.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to pronounce Irish names</title><link>http://talkirish.com/forums/thread/6188.aspx</link><pubDate>Wed, 13 Oct 2010 06:57:45 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6188</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6188.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6188</wfw:commentRss><description>&lt;p&gt;&lt;span class="Apple-style-span" style="widows:2;text-transform:none;text-indent:0px;border-collapse:separate;font:medium &amp;#39;Times New Roman&amp;#39;;white-space:normal;orphans:2;letter-spacing:normal;color:#000000;word-spacing:0px;-webkit-border-horizontal-spacing:0px;-webkit-border-vertical-spacing:0px;-webkit-text-decorations-in-effect:none;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;"&gt;
&lt;div style="background-color:#ffffff;margin:8px;font-family:Verdana, Arial, Helvetica, sans-serif;color:#000000;font-size:10px;background-origin:initial;background-clip:initial;"&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Hi Caubeen, &lt;/p&gt;
&lt;p&gt;Sorry to confuse you with my Ulsterisms! You are absolutely right, in Ulster Irish both a dh and an mh (and a bh on occasion, in words like banbh, garbh, tarbh which are pronounced bannoo, garroo, tarroo) are pronounced as an -oo-. So the Ulster Irish for think is smaoin(t)eamh, which is pronounced smween(ch)oo. A hair cut is a bearradh gruaige which is barroo groo-igya. D&amp;eacute;anamh (to do or make) is pronounced jannoo in Ulster. &lt;/p&gt;
&lt;p&gt;So Seosamh is pronounced &amp;quot;Shaw-soo&amp;quot; and in the genitive (in phrases like Joseph&amp;#39;s car - carr Sheosaimh) &amp;nbsp;it is Sheosaimh (hyaw-siv), with the v sound pronounced. &lt;/p&gt;
&lt;p&gt;Speakers of other dialects tend to find Ulster Irish too soft, with too much oo-ing, and rather flat in intonation, but to us many speakers of southern dialects sound very up and down in intonation and very harsh in the way sounds are pronounced &amp;nbsp;- like a Dalek singing. (No offence, guys!)&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;So to recap, Solamh is solloo in the north, solluv in the south . In general I am not fond of Biblical names, but Solamh is one I like.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/span&gt;&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to pronounce Irish names</title><link>http://talkirish.com/forums/thread/6185.aspx</link><pubDate>Tue, 12 Oct 2010 14:21:06 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6185</guid><dc:creator>caubeen</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6185.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6185</wfw:commentRss><description>&lt;p&gt;Seano,&lt;/p&gt;
&lt;p&gt;I read your response about pronouncing Solamh, and wondered if I&amp;nbsp;am understanding the&amp;nbsp;Ulster pronounciation correctly.&amp;nbsp; I am familiar with the word &amp;quot;madadh&amp;quot;, which I pronounce as &amp;quot;madoo&amp;quot; (the &amp;quot;adh&amp;quot; giving an &amp;quot;oo&amp;quot; sound).&amp;nbsp; However, you gave the pronunciation of the name &amp;quot;Solamh&amp;quot; as having the &amp;quot;oo&amp;quot; ending also, even thought the spelling is &amp;quot;a&lt;span style="text-decoration:underline;"&gt;m&lt;/span&gt;h&amp;quot;.&amp;nbsp; This is where I am confused.&amp;nbsp; Can you clarify?&amp;nbsp; Also, my first name is Seosamh.&amp;nbsp; Would this be pronounced in Ulster as &amp;quot;show soo&amp;quot;?&amp;nbsp; I have always thought it should be pronounced &amp;quot;show siv&amp;quot;.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>Re: How to pronounce Irish names</title><link>http://talkirish.com/forums/thread/6184.aspx</link><pubDate>Mon, 11 Oct 2010 16:57:26 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6184</guid><dc:creator>seano</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6184.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6184</wfw:commentRss><description>&lt;p&gt;

Hi - Names like this are a bit artificial, in that they are versions of Hebrew names - Just as in English it would be hard to argue for an absolutely correct &amp;quot;English&amp;quot; version of the pronunciation of Zerubabbel or Uriah. (i.e. is it Ooria, or Yooria, or You-raya; Zeruhbabbel or Zeeroobabbel?)&amp;nbsp;I usually pronounce names like I&amp;oacute;sua with a y at the start - yoh-soo-ah, and I would put the stress on the first syllable (YOH-soo-ah) but that is probably just because I&amp;#39;m an Ulster speaker. A Kerryman might pronounce it&amp;nbsp;yaw-SOO-ah. As for Solamh, I pronounce it&amp;nbsp;SOLLoo, but a southern speaker would pronounce the&amp;nbsp;-amh as an&amp;nbsp;uv, so they would say solluv. Hope this helps! Let us know if there&amp;#39;s anything else you need help with.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item><item><title>How to pronounce Irish names</title><link>http://talkirish.com/forums/thread/6179.aspx</link><pubDate>Sun, 10 Oct 2010 03:22:59 GMT</pubDate><guid isPermaLink="false">0644754f-ff87-49dd-b5e3-0e104f790f4a:6179</guid><dc:creator>FoSho</dc:creator><slash:comments>0</slash:comments><comments>http://talkirish.com/forums/thread/6179.aspx</comments><wfw:commentRss>http://talkirish.com/forums/commentrss.aspx?SectionID=7&amp;PostID=6179</wfw:commentRss><description>&lt;p&gt;How do I pronounce these two names in Irish Iosua (biblical version of Joshua) and Solamh (biblical version of Solomon). &amp;nbsp;&lt;/p&gt;
&lt;p&gt;I&amp;#39;ve read some differences but I&amp;#39;m not sure Iosua (ee-oh-sue-ah or yoe-sue-ah) and Solamh (soe-lahv or sue-lev).&lt;/p&gt;
&lt;p&gt;I have no idea which pronunciation is correct or if either is right. &amp;nbsp;I tried looking for sermons online in gaelic to see if I could hear how it truly sounds but came up empty.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;PS I&amp;#39;m american so any help for how we say it here in the states vs. an English accent would be very helpful.&lt;/p&gt;&lt;div style="clear:both;"&gt;&lt;/div&gt;</description></item></channel></rss>